//
// NOTE: This is a generated file! Don't edit it directly.
// Eventually community translation will be set up on some translation platform.
// 
// Generated with: npm run update-localization
//
loaded_localizations("sv", {
	"Attributes": "Inställningar",
	"&Width:": "&Bredd:",
	"Width:": "Bredd:",
	"&Height:": "&Höjd:",
	"Height:": "Höjd:",
	"Units": "Enhet",
	"&Inches": "&tum",
	"Inches": "tum",
	"C&m": "&cm",
	"Cm": "cm",
	"&Pixels": "b&ildpunkter",
	"Pixels": "bildpunkter",
	"Colors": "Färger",
	"&Black and white": "Svart&vit",
	"Black and white": "Svartvit",
	"Co&lors": "&Färger",
	"Transparency": "Transparens",
	"Use &Transparent background color": "&Använd transparent bakgrundsfärg",
	"Use Transparent background color": "Använd transparent bakgrundsfärg",
	"Select &Color": "Välj f&ärg",
	"Select Color": "Välj färg",
	"Cancel": "Avbryt",
	"&Default": "&Standard",
	"Default": "Standard",
	"Custom Zoom": "Anpassad zoomning",
	"Current zoom:": "Aktuell zoomning:",
	"Zoom to": "Zooma till",
	"&100%": "&100 %",
	"100%": "100 %",
	"&200%": "&200 %",
	"200%": "200 %",
	"&400%": "&400 %",
	"400%": "400 %",
	"&600%": "&600 %",
	"600%": "600 %",
	"&800%": "&800 %",
	"800%": "800 %",
	"Flip and Rotate": "Vänd och rotera",
	"Flip or rotate": "Vänd eller rotera",
	"&Flip horizontal": "Vänd &horisontellt",
	"Flip horizontal": "Vänd horisontellt",
	"Flip &vertical": "Vänd &vertikalt",
	"Flip vertical": "Vänd vertikalt",
	"&Rotate by angle": "&Rotera med vinkeln",
	"Rotate by angle": "Rotera med vinkeln",
	"Stretch and Skew": "Ändra storlek och snedställ",
	"Stretch": "Ändra storlek",
	"&Horizontal:": "&Vågrätt:",
	"Horizontal:": "Vågrätt:",
	"&Vertical:": "&Lodrätt:",
	"Vertical:": "Lodrätt:",
	"Skew": "Snedställ",
	"H&orizontal:": "V&ågrätt:",
	"Degrees": "grader",
	"V&ertical:": "Lo&drätt:",
	"Color Table": "Färgtabell",
	"New": "Ny",
	"&New ": "&Ny(tt)",
	"New ": "Ny(tt)",
	"&Help": "&Hjälp",
	"Help": "Hjälp",
	"Printing": "Skriver ut",
	"on the": "på",
	"&Print": "&Skriv ut",
	"Print": "Skriv ut",
	"&Next Page": "&Nästa sida",
	"Next Page": "Nästa sida",
	"Pre&v Page": "&Föreg sida",
	"Prev Page": "Föreg sida",
	"Zoom &In": "Zooma &in",
	"Zoom In": "Zooma in",
	"Zoom &Out": "Zooma &ut",
	"Zoom Out": "Zooma ut",
	"&Close": "St&äng",
	"Close": "Stäng",
	"Grid Settings": "Inställningar för rutnät",
	"&Pixel Grid": "&Punktrutnät",
	"Pixel Grid": "Punktrutnät",
	"&Tile Grid": "&Vanligt rutnät",
	"Tile Grid": "Vanligt rutnät",
	"pixels": "bildpunkter",
	"H&eight:": "&Höjd:",
	"Undo": "Ångra",
	"Cut": "Klipp ut",
	"Copy": "Kopiera",
	"Paste": "Klistra in",
	"Clear Selection": "Radera markering",
	"Select All": "Markera allt",
	"Text Toolbar": "Verktygsfältet Formatera",
	"Selection": "Markering",
	"Cu&t": "&Klipp ut",
	"&Copy": "K&opiera",
	"&Paste": "K&listra in",
	"C&lear Selection": "&Radera markering",
	"Select &All": "&Markera allt",
	"C&opy To": "Kopiera &till",
	"Copy To": "Kopiera till",
	"Paste &From": "Klistra in &från",
	"Paste From": "Klistra in från",
	"Flip/&Rotate": "&Vänd/Rotera",
	"Flip/Rotate": "Vänd/Rotera",
	"&Stretch/Skew": "&Ändra storlek/Snedställ",
	"Stretch/Skew": "Ändra storlek/Snedställ",
	"&Invert Colors": "&Invertera färger",
	"Invert Colors": "Invertera färger",
	"Thumbnail": "Miniatyr",
	"&File": "&Arkiv",
	"File": "Arkiv",
	"&New": "&Nytt",
	"&Open": "&Öppna",
	"Open": "Öppna",
	"&Save": "&Spara",
	"Save": "Spara",
	"Save &As": "Spara so&m",
	"Save As": "Spara som",
	"Print Pre&view": "För&handsgranska",
	"Print Preview": "Förhandsgranska",
	"Page Se&tup": "Utskri&ftsformat",
	"Page Setup": "Utskriftsformat",
	"S&end": "S&kicka",
	"Send": "Skicka",
	"Set As &Wallpaper (Tiled)": "Använd som skrivbordsunderlägg (s&ida vid sida)",
	"Set As Wallpaper (Tiled)": "Använd som skrivbordsunderlägg (sida vid sida)",
	"Set As Wa&llpaper (Centered)": "Använd som skrivbordsunderlägg (&centrerad)",
	"Set As Wallpaper (Centered)": "Använd som skrivbordsunderlägg (centrerad)",
	"Recent File": "Senaste fil",
	"E&xit": "&Avsluta",
	"Exit": "Avsluta",
	"&Edit": "&Redigera",
	"Edit": "Redigera",
	"&Undo": "&Ångra",
	"&Repeat": "&Upprepa",
	"Repeat": "Upprepa",
	"Ctrl+A": "Ctrl+L",
	"&View": "Vi&sa",
	"View": "Visa",
	"&Tool Box": "&Verktygslåda",
	"Tool Box": "Verktygslåda",
	"&Color Box": "&Färglåda",
	"Color Box": "Färglåda",
	"Ctrl+L": "Ctrl+A",
	"&Status Bar": "&Statusfält",
	"Status Bar": "Statusfält",
	"T&ext Toolbar": "Verktygsfältet F&ormatera",
	"&Zoom": "&Zooma",
	"Zoom": "Zooma",
	"&Normal Size": "&Normal storlek",
	"Normal Size": "Normal storlek",
	"&Large Size": "&Förstoring",
	"Large Size": "Förstoring",
	"C&ustom": "&Egen zoomning",
	"Custom": "Egen zoomning",
	"Show &Grid": "Visa &rutnät",
	"Show Grid": "Visa rutnät",
	"Show T&humbnail": "Visa &miniatyr",
	"Show Thumbnail": "Visa miniatyr",
	"&View Bitmap": "Visa &bitmapp",
	"View Bitmap": "Visa bitmapp",
	"&Image": "&Bild",
	"Image": "Bild",
	"&Flip/Rotate": "&Vänd/Rotera",
	"&Attributes": "&Inställningar",
	"&Clear Image": "&Radera bild",
	"Clear Image": "Radera bild",
	"Ctrl+Shft+N": "Ctrl+Skift+N",
	"&Draw Opaque": "Ri&ta heltäckande objekt",
	"Draw Opaque": "Rita heltäckande objekt",
	"&Colors": "&Färger",
	"&Edit Colors": "&Redigera färger",
	"Edit Colors": "Redigera färger",
	"&Help Topics": "&Hjälpavsnitt",
	"Help Topics": "Hjälpavsnitt",
	"&About Paint": "&Om Paint",
	"About Paint": "Om Paint",
	"&Update": "Upp&datera",
	"Update": "Uppdatera",
	"Save Copy &As": "&Spara kopia som",
	"Save Copy As": "Spara kopia som",
	"untitled": "namnlös",
	"Bitmap Image": "Bitmappsbild",
	"Bitmap Files (*.bmp)": "Bitmappsfiler (*.BMP)",
	"PCX Files": "PCX-fil",
	"Icon Files": "Ikon-filer",
	"Monochrome Bitmap (*.bmp;*.dib)": "Monokrom bitmapp (*.BMP;*.DIB)",
	"16 Color Bitmap (*.bmp;*.dib)": "16-färgers bitmapp (*.BMP;*.DIB)",
	"256 Color Bitmap (*.bmp;*.dib)": "256-färgers bitmapp (*.BMP;*.DIB)",
	"Paint cannot open this file.": "Det går inte att öppna filen.",
	"Paint cannot read this file.": "Ett läsfel inträffade när filen laddades.",
	"This file is read-only.": "Filen är skrivskyddad.",
	"To save your changes, use a different filename.": "Använd ett annat filnamn.",
	"This file is already open.": "Filen är redan öppen.",
	"This is not a valid .PCS file.": "Det här är inte en giltig PCS-fil.",
	"This file is open for editing and cannot be overwritten.": "Filen är öppen för redigering och kan inte skrivas över.",
	"Use a different filename to save your changes.": "Använd ett annat filnamn.",
	"This is not a valid bitmap file, or its format is not currently supported.": "Ogiltig bitmappsbild eller format som inte stöds.",
	"This is not a valid icon.": "Detta är inte en giltig ikon.",
	"This is not a valid cursor.": "Detta är inte giltig markör.",
	"Save was interrupted, so your file has not been saved.": "Kommandot avbröts. Filen sparades inte.",
	"You cannot save to a read-only file.": "Du kan inte spara en skrivskyddad fil.",
	"Use a different file name.": "Använd ett annat filnamn.",
	"This file is already in use.": "Filen används redan.",
	"Close the program, and then try again.": "Stäng programmet och försök igen.",
	"Paint cannot save this file.": "Det går inte att spara filen.",
	"Paint cannot save to the same filename with a different file type.": "Det går inte att spara filen med samma namn i ett annat filformat.",
	"The grid spacing must be an integer between %d and %d.": "Värdet för mellanrum i rutnätet måste vara ett heltal mellan %d och %d.",
	"There is not enough memory or resources to complete operation.": "Det finns inte tillräckligt med ledigt minne för att slutföra åtgärden.",
	"Close some programs, and then try again.": "Stäng några program och försök igen.",
	"Low on memory or resources.": "Det finns inte tillräckligt med ledigt minne.",
	"Group error.": "Gruppfel",
	"Paint was unable to print your document. Please make sure you have sufficient disk space and that your printer is working correctly.": "Paint kunde inte skriva ut dokumentet. Kontrollera att det finns tillräckligt med ledigt minne och att skrivaren fungerar korrekt.",
	"Saving into this format may cause some loss of color information.": "Om du sparar i detta format kan du förlora färginformation.",
	"Do you want to continue?": "Vill du fortsätta?",
	"Converting to black and white cannot be undone.  This action affects the current file and may cause some loss of color information.": "Det går inte att ångra konvertering till svartvitt. Det här kommandot påverkar den aktiva filen så att du kan förlora färginformation.",
	"Bitmaps must be greater than one pixel on a side.": "Sidan på en bitmapp måste vara större än en bildpunkt.",
	"Generic error.": "Allmänt fel.",
	"File not found.": "Det gick inte att hitta filen.",
	"Bad path.": "Felaktig sökväg.",
	"Too many open files.": "För många öppna filer.",
	"Access denied.": "Åtkomst nekad.",
	"Invalid file.": "Ogiltig fil.",
	"Remove current folder.": "Ta bort aktuell mapp.",
	"Folder full.": "Mappen är full.",
	"Bad seek.": "Felaktig sökning.",
	"Hard IO error.": "Maskinvaru-I/O-fel.",
	"Sharing violation.": "Fildelningsfel.",
	"Lock violation.": "Fillåsningsfel",
	"Disk full.": "Disken är full.",
	"End of file.": "Slutet på filen.",
	"Error getting the Clipboard Data!": "Det gick inte att hämta information från Urklipp!",
	"No Printer Found @ page setup": "Hittade ingen skrivare @ Utskriftsformat",
	"24-bit Bitmap (*.bmp;*.dib)": "24-bitars bitmapp (*.BMP;*.DIB)",
	"All Files": "Alla filer",
	"Palette|*.pal|": "Palett|*.pal|",
	"OLE 2.0 was unable to start.": "Det gick inte att starta OLE 2.0.",
	"Make sure that you are using the correct version of the OLE libraries.": "Kontrollera att du använder rätt version av OLE-biblioteket.",
	"Resets the text be without any attributes.": "Återställer texten så att alla formateringar försvinner.",
	"Sets or clears the text bold attribute.": "Formaterar med fet stil eller tar bort fet stil.",
	"Sets or clears the text italic attribute.": "Formaterar med kursiv stil eller tar bort kursiv stil.",
	"Selects the font used by the text.": "Väljer teckensnitt.",
	"Selects the point size of the text.": "Väljer teckenstorlek.",
	"Sets or clears the text underline attribute.": "Stryker under text eller ta bort understrykning.",
	"Shows or hides the tooltips.": "Visar/döljer knappbeskrivning.",
	"Show Paint Help.": "Visa Hjälpen.",
	"Sends a picture by using mail or fax.": "Skickar en bild via Mail eller fax.",
	"Copies the selection to a file.": "Kopierar markerat område till en fil.",
	"Pastes a file into the selection.": "Klistrar in en fil i markeringen.",
	"Zooms the picture to 100%.": "Zoomar 100 %.",
	"Zooms the picture to 400%.": "Zoomar 400 %.",
	"Zooms the picture.": "Zoomar.",
	"Displays the entire picture.": "Visar hela bilden.",
	"Shows or hides the thumbnail view of the picture.": "Visar/döljer miniatyr.",
	"Shows or hides the grid.": "Visar/döljer rutnät.",
	"Shows or hides the text toolbar.": "Visar/döljer verktygsfältet Formatera.",
	"Flips or rotates the picture or a selection.": "Vänder eller roterar en bild eller markering.",
	"Stretches or skews the picture or a selection.": "Ändrar storlek på eller snedställer bilden eller markeringen.",
	"Inverts the colors of the picture or a selection.": "Inverterar färgerna på bilden eller markeringen.",
	"Changes the attributes of the picture.": "Ändrar bildinställningar.",
	"Clears the picture or selection.": "Rensar bilden eller markeringen.",
	"The font size must be a numeric value.": "Teckenstorlek måste vara ett numeriskt värde.",
	"Contains commands for working with the selected item(s).": "Innehåller kommandon för att arbeta med markerade objekt.",
	"Contains commands for selecting and transferring items.": "Innehåller kommandon för att markera och flytta objekt.",
	"Contains commands for customizing this window.": "Innehåller kommandon för att anpassa fönstret.",
	"Contains commands for manipulating pictures and setting attributes.": "Innehåller kommandon för att ändra bilder och sätta attribut.",
	"Contains commands for using custom colors and drawing options.": "Innehåller kommandon för att använda anpassade färger.",
	"Contains commands for displaying Help for and information about Paint.": "Innehåller kommandon för att visa Hjälp och information om Paint.",
	"Cannot save file.": "Det går inte att spara filen.",
	"Error removing temporary file.": "Ett fel inträffade när en temporär fil togs bort.",
	"Get Colors": "Hämta färger",
	"Save Colors": "Spara färger",
	"File last saved:": "Senast sparad:",
	"Not Available": "Ej tillgängligt",
	"Size on disk:": "Storlek på disk:",
	"%s bytes": "%s byte",
	"Painting": "Målning",
	"Fonts": "Formatera",
	"Tools": "Verktyg",
	"All Picture Files": "Alla bildfiler",
	"For Help, click Help Topics on the Help Menu.": "Välj Hjälpavsnitt på Hjälp-menyn om du vill ha hjälp.",
	"Select an area on which to get Help.": "Välj det område du vill söka hjälp om.",
	"%1 in %2": "%1 i %2",
	"Creates a new document.": "Skapar ett nytt dokument.",
	"Opens an existing document.": "Öppnar ett befintligt dokument.",
	"Closes the active document.": "Stänger det aktiva dokumentet.",
	"Saves the active document.": "Sparar det aktiva dokumentet.",
	"Saves the active document with a new name.": "Sparar det aktiva dokumentet med ett nytt namn.",
	"Changes the page layout.": "Ändrar utskriftsformat.",
	"Specifies the default printer setup.": "Anger standardinställning för skrivaren.",
	"Prints the active document and sets printing options.": "Skriver ut aktivt dokument och ställer in utskriftsalternativ.",
	"Displays full pages.": "Visar hela sidor.",
	"Opens this document.": "Öppnar dokumentet.",
	"Deletes the selection.": "Raderar markeringen.",
	"Erases everything.": "Raderar allt.",
	"Copies the selection and puts it on the Clipboard.": "Kopierar markeringen och lägger den i Urklipp.",
	"Cuts the selection and puts it on the Clipboard.": "Klipper ut markeringen och lägger den i Urklipp.",
	"Finds the specified text.": "Söker efter angiven text.",
	"Inserts the contents of the Clipboard.": "Infogar innehållet i Urklipp.",
	"Repeats the last action.": "Gör om senaste kommando.",
	"Replaces specific text with different text.": "Ersätter angiven text med annan text.",
	"Selects everything.": "Markerar allt.",
	"Undoes the last action.": "Ångrar senaste kommando.",
	"Redoes the previously undone action.": "Gör om senast ångrade åtgärd.",
	"Displays program information, version number, and copyright.": "Visar programinformation, versionsnummer och copyright.",
	"Quits Paint.": "Avslutar Paint",
	"Opens Paint Help.": "Öppnar Hjälp.",
	"Displays instructions about how to use Help.": "Visar hur du använder Hjälp.",
	"Displays Help for areas you click on.": "Visar Hjälp för de områden du markerar.",
	"Displays Help for the current task or command.": "Visar Hjälp för aktuell uppgift eller kommando.",
	"Centers this bitmap as the desktop wallpaper.": "Centrerar bitmappen som skrivbordsunderlägg.",
	"Tiles this bitmap as the desktop wallpaper.": "Lägger bitmappen sida vid sida som skrivbordsunderlägg.",
	"Sends the selection using mail or fax.": "Skickar markeringen via Mail eller fax.",
	"Prints the selection.": "Skriver ut markeringen.",
	"Shows or hides the thumbnail.": "Visar/döljer miniatyr.",
	"Shows Paint Help.": "Visar Hjälpen.",
	"Shows or hides the status bar.": "Visar/döljer statusfält.",
	"Shows or hides the tool box.": "Visar/döljer verktygslådan.",
	"Shows or hides the color box.": "Visar/döljer färglådan.",
	"Only a Far East font can be used for vertical editing.": "Endast en Fjärran östern-teckensnitt kan redigeras vertikalt.",
	"Changes the window size.": "Ändrar fönstrets storlek.",
	"Changes the window position.": "Ändrar fönstrets läge på skärmen.",
	"Reduces the window to an icon.": "Förminskar fönstret till en ikon.",
	"Enlarges the window to full size.": "Maximerar fönstret till full storlek.",
	"Switches to the next document window.": "Växlar till nästa dokumentfönster.",
	"Switches to the previous document window.": "Växlar till föregående dokumentfönster.",
	"Closes the active window and asks if you want to save changes.": "Stänger aktivt fönster och frågar om du vill spara ändringar.",
	"Restores the window to normal size.": "Återställer fönstret till normal storlek.",
	"Activates the task list.": "Visar aktiva program.",
	"All Files (*.*)": "Alla filer (*.*)",
	"Untitled": "Namnlös",
	"an unnamed file": "en namnlös fil",
	"&Hide": "&Dölj",
	"Hide": "Dölj",
	"No error message is available.": "Inget felmeddelande finns tillgängligt.",
	"An unsupported operation was attempted.": "Det har gjorts ett försök att utföra en åtgärd som inte stöds.",
	"A required resource was unavailable.": "En resurs som krävs var inte tillgänglig.",
	"Out of memory.": "Otillräckligt minne.",
	"An unknown error has occurred.": "Ett okänt fel har uppstått.",
	"on %1": "på %1",
	"&One Page": "&En sida",
	"One Page": "En sida",
	"&Two Page": "&Två sidor",
	"Two Page": "Två sidor",
	"Page %u": "Sidan %u",
	"Pages %u-%u": "Sidorna %u-%u",
	"Printer Files (*.prn)|*.prn|All Files (*.*)|*.*||": "Skrivarfiler (*.prn)|*.prn|Alla filer (*.*)|*.*||",
	"Print to File": "Skriv ut till fil",
	"to %1": "till %1",
	"&Update %1": "&Uppdatera %1",
	"Update %1": "Uppdatera %1",
	"E&xit && Return to %1": "A&vsluta och återvänd till %1",
	"Exit && Return to %1": "Avsluta och återvänd till %1",
	"Linked %s": "Länkad %s",
	"Unknown Type": "Okänd typ",
	"Invalid filename.": "Ogiltigt filnamn.",
	"Failed to open document.": "Det gick inte att öppna dokumentet.",
	"Failed to save document.": "Det gick inte att spara dokumentet.",
	"Save changes to %1?": "Vill du spara ändringar till %1?",
	"Failed to create empty document.": "Det gick inte att skapa ett tomt dokument.",
	"The file is too large to open.": "Filen är för stor för att kunna öppnas.",
	"Could not start print job.": "Det gick inte att starta utskriften.",
	"Failed to launch help.": "Det gick inte att starta hjälpen.",
	"Internal application error.": "Internt programfel.",
	"Command failed.": "Kommandot misslyckades.",
	"Insufficient memory to perform operation.": "Det finns inte tillräckligt med minne för att utföra åtgärden.",
	"System registry entries have been removed and the INI file (if any) was deleted.": "INI-filen och systemets registervärden har tagits bort.",
	"Not all of the system registry entries (or INI file) were removed.": "Inte alla registervärden (eller INI-filen) har tagits bort.",
	"This program requires the file %s, which was not found on this system.": "Detta program kräver filen %s,Som inte kunde hittas i det här systemet.",
	"This program is linked to the missing export %s in the file %s. This machine may have an incompatible version of %s.": "Detta program är länkat till den saknade exporten %s i filen %s. Den här datorn har eventuellt en inkompatibel version av %s.",
	"Please enter an integer.": "Ange ett heltal.",
	"Please enter a number.": "Ange ett tal.",
	"Please enter an integer between %1 and %2.": "Ange ett heltal mellan %1 och %2.",
	"Please enter a number between %1 and %2.": "Ange ett tal mellan %1 och %2.",
	"Please enter no more than %1 characters.": "Ange högst %1 tecken.",
	"Please select a button.": "Välj en knapp.",
	"Please enter an integer between 0 and 255.": "Ange ett heltal mellan 0 och 255.",
	"Please enter a positive integer.": "Du måste ange ett positivt heltal.",
	"Please enter a date and/or time.": "Skriv ett datum och/eller tid.",
	"Please enter a currency.": "Skriv en valuta.",
	"Unexpected file format.": "Oväntat filformat.",
	"Cannot find this file.": "Det går inte att hitta filen.",
	"Please verify that the correct path and file name are given.": "Kontrollera sökväg och filnamn.",
	"Destination disk drive is full.": "Måldisken är full.",
	"Unable to read from %1, it is opened by someone else.": "Det går inte att läsa från %1, eftersom den är öppnad av en annan användare.",
	"Unable to write to %1, it is read-only or opened by someone else.": "Det går inte att skriva till %1, eftersom den är skrivskyddad eller öppnad av en annan användare.",
	"An unexpected error occurred while reading %1.": "Ett oväntat fel inträffade vid läsning av %1.",
	"An unexpected error occurred while writing %1.": "Ett oväntat fel inträffade vid skrivning till %1.",
	"Unable to register document.": "Det gick inte att öppna registerdokumentet.",
	"The document may already be open.": "Dokumentet kanske redan är öppet.",
	"Update %1 before proceeding?": "Vill du uppdatera %1 innan du fortsätter?",
	"Could not update client.": "Det gick inte att uppdatera klient.",
	"Failed to register. ActiveX features may not work properly.": "Det gick inte att registrera. Det är inte säkert att ActiveX-funktionerna kommer att fungera.",
	"Failed to update the system registry.": "Det gick inte att uppdatera systemregistret.",
	"Please try using REGEDIT.": "Använd REGEDIT.",
	"Unable to read write-only property.": "Det går inte att läsa skrivskyddat material.",
	"Unable to write read-only property.": "Det går inte att skriva till skrivskyddat material.",
	"Unable to load mail system support.": "Det gick inte att ladda stöd för e-postsystemet.",
	"Mail system DLL is invalid.": "E-postsystem-DLL:en är inte giltig.",
	"Send Mail failed to send message.": "Det gick inte att skicka meddelande.",
	"No error occurred.": "Inget fel inträffade.",
	"An unknown error occurred while accessing %1.": "Ett okänt fel inträffade vid åtkomst av %1.",
	"%1 was not found.": "%1 kunde inte hittas.",
	"%1 contains an invalid path.": "%1 innehåller en ogiltig sökväg.",
	"%1 could not be opened because there are too many open files.": "%1 kunde inte öppnas eftersom det finns för många öppnade filer.",
	"Access to %1 was denied.": "Åtkomst till %1 nekades.",
	"An invalid file handle was associated with %1.": "Det finns en ogiltig filreferens i %1.",
	"%1 could not be removed because it is the current directory.": "%1 kunde inte tas bort eftersom det är den aktuella katalogen.",
	"%1 could not be created because the directory is full.": "%1 kunde inte skapas eftersom katalogen är full.",
	"Seek failed on %1": "Sökningen på %1 misslyckades.",
	"A hardware I/O error was reported while accessing %1.": "Hårdvarufel vid åtkomst till %1.",
	"A sharing violation occurred while accessing %1.": "Delningsfel vid åtkomst till %1.",
	"A locking violation occurred while accessing %1.": "Låsningsfel vid åtkomst till %1.",
	"Disk full while accessing %1.": "Diskutrymmet tog slut vid åtkomst till %1.",
	"An attempt was made to access %1 past its end.": "Det gjordes ett försök att nå %1 efter filslut.",
	"An attempt was made to write to the reading %1.": "Det går inte att skriva till %1 medan den läses.",
	"An attempt was made to read from the writing %1.": "Det går inte att läsa från %1 medan den skrivs.",
	"%1 has a bad format.": "%1 har felaktigt format.",
	"%1 contained an unexpected object.": "%1 innehåller ett oväntat objekt.",
	"%1 contains an incorrect schema.": "%1 innehåller ett felaktigt schema.",
	"Selects a rectangular part of the picture to move, copy, or edit.": "Markerar en rektangulär del av bilden för att flytta, kopiera eller redigera.",
	"Select": "Markera",
	"Selects a free-form part of the picture to move, copy, or edit.": "Markerar en del av bilden, med valfri form, för att flytta, kopiera eller redigera.",
	"Free-Form Select": "Markera valfri form",
	"Inserts text into the picture.": "Infogar text i bilden.",
	"Fills an area with the current drawing color.": "Fyller ett område med aktuell färg.",
	"Fill With Color": "Fyll",
	"Draws a straight line with the selected line width.": "Ritar en rät linje med markerad linjebredd.",
	"Line": "Linje",
	"Draws using an airbrush of the selected size.": "Ritar med en retuschspruta med markerad storlek.",
	"Airbrush": "Retuschspruta",
	"Draws a curved line with the selected line width.": "Ritar en kurvlinje med markerad linjebredd.",
	"Curve": "Kurvlinje",
	"Draws a polygon with the selected fill style.": "Ritar en polygon med markerad fyllning.",
	"Draws a rounded rectangle with the selected fill style.": "Ritar en rektangel med runda hörn med markerad fyllning.",
	"Rounded Rectangle": "Rundad rektangel",
	"Draws a free-form line one pixel wide.": "Ritar en frihandslinje med en bildpunkts bredd.",
	"Pencil": "Penna",
	"Erases a portion of the picture, using the selected eraser shape.": "Raderar en del av bilden med markerad form på radergummit.",
	"Eraser/Color Eraser": "Radergummi",
	"Changes the magnification.": "Ändrar förstoringen.",
	"Magnifier": "Förstora",
	"Picks up a color from the picture for drawing.": "Hämtar en färg från bilden för att rita med den.",
	"Pick Color": "Hämta färg",
	"Draws using a brush with the selected shape and size.": "Ritar med en pensel med markerad form och storlek.",
	"Brush": "Pensel",
	"Draws a rectangle with the selected fill style.": "Ritar en rektangel med markerad fyllning.",
	"Rectangle": "Rektangel",
	"Draws a filled rectangle.": "Ritar en fylld rektangel.",
	"Draws an ellipse with the selected fill style.": "Ritar en oval med markerad fyllning.",
	"Ellipse": "Oval",
	"Draws a filled ellipse.": "Ritar en fylld oval.",
	"Makes the current selection either opaque or transparent.": "Gör aktuell markering antingen ogenomskinlig eller genomskinlig.",
	"Creates a new color.": "Skapar en ny färg.",
	"Uses a previously saved palette of colors.": "Använder en tidigare sparat färgpalett.",
	"Saves the current palette of colors to a file.": "Sparar aktuell färgpalett till en fil.",
	"You must save the file before choosing it as Wallpaper.": "Du måste spara filen innan du använder den som skrivbordsunderlägg.",
	"The selection is now larger than the bitmap.": "Markeringen är nu större än bitmappen.",
	"Would you like the bitmap enlarged?": "Vill du förstora bitmappen?",
	"The image in the clipboard is larger than the bitmap.": "Bilden i Urklipp är större än bitmappen.",
	"The file is not in the correct format.": "Filen har ett ogiltigt filformat.",
	"Not enough room to paste text.": "Textområdet är tillräckligt stort för att klistra in texten.",
	"Enlarge the text area and try again.": "Förstora textområdet och försök igen.",
	"Places the text.": "Placerar texten."
});
