//
// NOTE: This is a generated file! Don't edit it directly.
// Eventually community translation will be set up on some translation platform.
// 
// Generated with: npm run update-localization
//
loaded_localizations("tr", {
	"Attributes": "Öznitelikler",
	"&Width:": "&Genişlik:",
	"Width:": "Genişlik:",
	"&Height:": "&Yükseklik:",
	"Height:": "Yükseklik:",
	"Units": "Birimler",
	"&Inches": "İ&nç",
	"Inches": "İnç",
	"C&m": "&Cm",
	"Cm": "Cm",
	"&Pixels": "&Piksel",
	"Pixels": "Piksel",
	"Colors": "Renkler",
	"&Black and white": "&Siyah beyaz",
	"Black and white": "Siyah beyaz",
	"Co&lors": "&Renkli",
	"Transparency": "Saydamlık",
	"Use &Transparent background color": "S&aydam artalan rengi kullan",
	"Use Transparent background color": "Saydam artalan rengi kullan",
	"Select &Color": "Renk S&eç",
	"Select Color": "Renk Seç",
	"OK": "Tamam",
	"Cancel": "İptal",
	"&Default": "&Varsayılan",
	"Default": "Varsayılan",
	"Custom Zoom": "Özel Yakınlaştırma",
	"Current zoom:": "Geçerli yakınlaştırma:",
	"Zoom to": "Yakınlaştır",
	"&100%": "%&100 ",
	"100%": "%100 ",
	"&200%": "%&200 ",
	"200%": "%200 ",
	"&400%": "%&400 ",
	"400%": "%400 ",
	"&600%": "%&600 ",
	"600%": "%600 ",
	"&800%": "%&800 ",
	"800%": "%800 ",
	"Flip and Rotate": "Döndür ve Çevir",
	"MS Shell Dlg": "MS Sans Serif",
	"Flip or rotate": "Döndür veya çevir",
	"&Flip horizontal": "&Yatay çevir",
	"Flip horizontal": "Yatay çevir",
	"Flip &vertical": "&Dikey çevir",
	"Flip vertical": "Dikey çevir",
	"&Rotate by angle": "&Açılı döndür",
	"Rotate by angle": "Açılı döndür",
	"Stretch and Skew": "Uzat ve Eğ",
	"Stretch": "Uzat",
	"&Horizontal:": "Ya&tay:",
	"Horizontal:": "Yatay:",
	"&Vertical:": "&Dikey:",
	"Vertical:": "Dikey:",
	"Skew": "Eğ",
	"H&orizontal:": "Yata&y:",
	"Degrees": "Derece",
	"V&ertical:": "Di&key:",
	"Color Table": "Renk Tablosu",
	"New": "Yeni",
	"&New ": "Y&eni ",
	"New ": "Yeni ",
	"&Help": "&Yardım",
	"Help": "Yardım",
	"Printing": "Yazdırılan",
	"on the": "yazdırıldığı yazıcı",
	"&Print": "&Yazdır",
	"Print": "Yazdır",
	"&Next Page": "&Sonraki Sayfa",
	"Next Page": "Sonraki Sayfa",
	"Pre&v Page": "Ön&ceki Sayfa",
	"Prev Page": "Önceki Sayfa",
	"Zoom &In": "&Büyüt",
	"Zoom In": "Büyüt",
	"Zoom &Out": "Küçü&lt",
	"Zoom Out": "Küçült",
	"&Close": "K&apat",
	"Close": "Kapat",
	"Grid Settings": "Klavuz Ayarları",
	"&Pixel Grid": "&Piksel Klavuzu",
	"Pixel Grid": "Piksel Klavuzu",
	"&Tile Grid": "Klavu&z Döşe",
	"Tile Grid": "Klavuz Döşe",
	"pixels": "piksel",
	"H&eight:": "&Yükseklik:",
	"Text": "Metin",
	"Undo": "Geri Al",
	"Cut": "Kes",
	"Copy": "Kopyala",
	"Paste": "Yapıştır",
	"Clear Selection": "Seçileni Temizle",
	"Select All": "Tümünü Seç",
	"Text Toolbar": "Metin Araç Çubuğu",
	"Selection": "Seçim",
	"Cu&t": "&Kes",
	"&Copy": "K&opyala",
	"&Paste": "&Yapıştır",
	"C&lear Selection": "&Seçileni Temizle",
	"Select &All": "&Tümünü Seç",
	"C&opy To": "&Dosyaya Kopyala",
	"Copy To": "Kopyala",
	"Paste &From": "Dosyada&n Yapıştır",
	"Paste From": "Yapıştır",
	"Flip/&Rotate": "Döndür/Çe&vir",
	"Flip/Rotate": "Döndür/Çevir",
	"&Stretch/Skew": "&Uzat/Eğ",
	"Stretch/Skew": "Uzat/Eğ",
	"&Invert Colors": "R&enkleri Ters Çevir",
	"Invert Colors": "Renkleri Ters Çevir",
	"Thumbnail": "Parçacık",
	"&File": "&Dosya",
	"File": "Dosya",
	"&New": "&Yeni",
	"&Open": "&Aç",
	"Open": "Aç",
	"&Save": "Kayde&t",
	"Save": "Kaydet",
	"Save &As": "&Farklı Kaydet",
	"Save As": "Farklı Kaydet",
	"Print Pre&view": "Baskı Önizl&eme",
	"Print Preview": "Baskı Önizleme",
	"Page Se&tup": "&Sayfa Yapısı",
	"Page Setup": "Sayfa Yapısı",
	"S&end": "&Gönder",
	"Send": "Gönder",
	"Set As &Wallpaper (Tiled)": "Duvar Kağıdı &Olarak Ayarla (Döşeli)",
	"Set As Wallpaper (Tiled)": "Duvar Kağıdı Olarak Ayarla (Döşeli)",
	"Set As Wa&llpaper (Centered)": "D&uvar Kağıdı Olarak Ayarla (Ortalanmış)",
	"Set As Wallpaper (Centered)": "Duvar Kağıdı Olarak Ayarla (Ortalanmış)",
	"Recent File": "Son Dosya",
	"E&xit": "Çı&kış",
	"Exit": "Çıkış",
	"&Edit": "Dü&zen",
	"Edit": "Düzen",
	"&Undo": "&Geri Al",
	"&Repeat": "&Yinele",
	"Repeat": "Yinele",
	"&View": "&Görünüm",
	"View": "Görünüm",
	"&Tool Box": "&Araç Kutusu",
	"Tool Box": "Araç Kutusu",
	"&Color Box": "&Renk Kutusu",
	"Color Box": "Renk Kutusu",
	"&Status Bar": "&Durum Çubuğu",
	"Status Bar": "Durum Çubuğu",
	"T&ext Toolbar": "&Metin Araç Çubuğu",
	"&Zoom": "&Yakınlaştır",
	"Zoom": "Yakınlaştır",
	"&Normal Size": "&Normal Boyut",
	"Normal Size": "Normal Boyut",
	"&Large Size": "&Geniş Boyut",
	"Large Size": "Geniş Boyut",
	"C&ustom": "Ö&zel",
	"Custom": "Özel",
	"Show &Grid": "Klavuzu Gö&ster",
	"Show Grid": "Klavuzu Göster",
	"Show T&humbnail": "&Parçacığı Göster",
	"Show Thumbnail": "Parçacığı Göster",
	"&View Bitmap": "&Bit Eşlem Göster",
	"View Bitmap": "Bit Eşlem Göster",
	"&Image": "&Resim",
	"Image": "Resim",
	"&Flip/Rotate": "&Döndür/Çevir",
	"&Attributes": "Ö&znitelikler",
	"&Clear Image": "Res&mi Temizle",
	"Clear Image": "Resmi Temizle",
	"&Draw Opaque": "D&onuk Çiz",
	"Draw Opaque": "Donuk Çiz",
	"&Colors": "R&enkler",
	"&Edit Colors": "&Renkleri Düzenle",
	"Edit Colors": "Renkleri Düzenle",
	"&Help Topics": "&Yardım Konuları",
	"Help Topics": "Yardım Konuları",
	"&About Paint": "Paint &Hakkında",
	"About Paint": "Paint Hakkında",
	"&Update": "&Güncelleştir",
	"Update": "Güncelleştir",
	"Save Copy &As": "K&opyayı Farklı Kaydet",
	"Save Copy As": "Kopyayı Farklı Kaydet",
	"untitled": "adsız",
	"Bitmap Image": "Bit Eşlem Resmi",
	"Bitmap Files (*.bmp)": "Bit Eşlem Dosyaları",
	"PCX Files": "PCX Dosyaları",
	"Icon Files": "Simge Dosyaları",
	"Monochrome Bitmap (*.bmp;*.dib)": "Tek Renkli Bit Eşlem (*.bmp;*.dib)",
	"16 Color Bitmap (*.bmp;*.dib)": "16 Renkli Bit Eşlem (*.bmp;*.dib)",
	"256 Color Bitmap (*.bmp;*.dib)": "256 Renkli Bit Eşlem (*.bmp;*.dib)",
	"Paint cannot open this file.": "Paint bu dosyayı açamıyor.",
	"Paint cannot read this file.": "Paint bu dosyayı okuyamıyor.",
	"This file is read-only.": "Bu dosya salt okunur.",
	"To save your changes, use a different filename.": "Değişikliklerinizi kaydetmek için, farklı bir dosya adı kullanın.",
	"This file is already open.": "Bu dosya zaten açık.",
	"This is not a valid .PCS file.": "Bu, geçerli bir .PCS dosyası değil.",
	"This file is open for editing and cannot be overwritten.": "Bu dosya düzenleme için açık ve üstüne yazılamaz.",
	"Use a different filename to save your changes.": "Değişikliklerinizi kaydetmek için farklı bir dosya adı kullanın.",
	"This is not a valid bitmap file, or its format is not currently supported.": "Bu, geçerli bir bit eşlem dosyası değil veya bu biçim artık desteklenmiyor.",
	"This is not a valid icon.": "Bu, geçerli bir simge değil.",
	"This is not a valid cursor.": "Bu, geçerli bir imleç değil.",
	"Save was interrupted, so your file has not been saved.": "Kayıt kesildiğinden dosyanız kaydedilemedi.",
	"You cannot save to a read-only file.": "Salt okunur bir dosyayı kaydedemezsiniz.",
	"Use a different file name.": "Farklı bir dosya adı kullanın.",
	"This file is already in use.": "Bu dosya kullanımda.",
	"Close the program, and then try again.": "Programı kapatıp yeniden deneyin.",
	"Paint cannot save this file.": "Paint bu dosyayı kaydedemiyor.",
	"Paint cannot save to the same filename with a different file type.": "Paint, aynı dosya adını farklı bir dosya türüyle kaydedemez.",
	"The grid spacing must be an integer between %d and %d.": "Klavuz aralığı, %d ile %d arasında bir tamsayı olmalıdır.",
	"There is not enough memory or resources to complete operation.": "İşlemi tamamlamak için yeterli bellek veya kaynak yok.",
	"Close some programs, and then try again.": "Bazı programları kapatıp yeniden deneyin.",
	"Low on memory or resources.": "Bellek veya kaynak azlığı.",
	"Group error.": "Grup hatası.",
	"Paint was unable to print your document. Please make sure you have sufficient disk space and that your printer is working correctly.": "Paint belgenizi yazdıramadı. Lütfen yeterli sabit disk alanınız olup olmadığından ve yazıcınızın düzgün çalışıp çalışmadığından emin olun.",
	"Saving into this format may cause some loss of color information.": "Bu biçimde saklamak bazı renk bilgilerinin kaybedilmesine neden olabilir .",
	"Do you want to continue?": "Devam etmek istiyor musunuz?",
	"Converting to black and white cannot be undone.  This action affects the current file and may cause some loss of color information.": "Siyah beyaza dönüştürme işlemi geri alınamaz.  Bu eylem geçerli dosyayı etkiler ve bazı renk bilgilerinin kaybolmasına neden olabilir.",
	"Bitmaps must be greater than one pixel on a side.": "Bit eşlemler bir kenarda bir pikselden büyük olmalıdırlar.",
	"Generic error.": "Soysal hata.",
	"File not found.": "Dosya bulunamadı.",
	"Bad path.": "Hatalı yol.",
	"Too many open files.": "Açık dosya sayısı çok fazla.",
	"Access denied.": "Erişim engellendi.",
	"Invalid file.": "Geçersiz dosya.",
	"Remove current folder.": "Geçerli klasörü kaldırın.",
	"Folder full.": "Klasör dolu.",
	"Bad seek.": "Hatalı arama.",
	"Hard IO error.": "Donanım GÇ hatası.",
	"Sharing violation.": "Paylaşım ihlali.",
	"Lock violation.": "Kilitleme ihlali.",
	"Disk full.": "Disk dolu.",
	"End of file.": "Dosya sonu.",
	"Error getting the Clipboard Data!": "Pano Verisi alınırken hata!",
	"No Printer Found @ page setup": "Yazıcı Bulunamadı @ sayfa yapısı",
	"24-bit Bitmap (*.bmp;*.dib)": "24-bit Bit Eşlem (*.bmp;*.dib)",
	"All Files": "Tüm Dosyalar",
	"Palette|*.pal|": "Palet|*.pal|",
	"untitled.pal": "adsız.pal",
	"OLE 2.0 was unable to start.": "OLE 2.0 başlayamadı.",
	"Make sure that you are using the correct version of the OLE libraries.": "Doğru OLE kitaplığı sürümünü kullandığınızdan emin olun.",
	"Resets the text be without any attributes.": "Metni hiç özniteliği olmayacak şekilde sıfırlar.",
	"Sets or clears the text bold attribute.": "Metnin kalın özniteliğini ayarlar veya temizler.",
	"Sets or clears the text italic attribute.": "Metnin italik özniteliğini ayarlar veya temizler.",
	"Selects the font used by the text.": "Metin tarafından kullanılan yazı tipini seçer.",
	"Selects the point size of the text.": "Metnin nokta boyutunu seçer.",
	"Sets or clears the text underline attribute.": "Metnin altçizgi özniteliğini ayarlar veya temizler.",
	"Shows or hides the tooltips.": "Araç ipuçlarını gösterir veya gizler.",
	"Show Paint Help.": "Paint Yardımını Gösterir.",
	"Sends a picture by using mail or fax.": "Posta veya faks kullanarak resim gönderir.",
	"Copies the selection to a file.": "Seçimi bir dosyaya kopyalar.",
	"Pastes a file into the selection.": "Seçimin içine bir dosya yapıştırır.",
	"Zooms the picture to 100%.": "Resmi %100 boyutuna büyütür.",
	"Zooms the picture to 400%.": "Resmi %400 boyutuna büyütür.",
	"Zooms the picture.": "Resmi büyütür.",
	"Displays the entire picture.": "Tüm resmi gösterir.",
	"Shows or hides the thumbnail view of the picture.": "Resmin parçacık görüntüsünü gösterir veya gizler.",
	"Shows or hides the grid.": "Klavuzu gösterir veya gizler.",
	"Shows or hides the text toolbar.": "Metin araç çubuğunu gösterir veya gizler.",
	"Flips or rotates the picture or a selection.": "Resmi veya bir seçimi döndürür veya çevirir.",
	"Stretches or skews the picture or a selection.": "Resmi veya bir seçimi uzatır veya eğer.",
	"Inverts the colors of the picture or a selection.": "Resmin veya bir seçimin renklerini evirir.",
	"Changes the attributes of the picture.": "Resmin özniteliklerini değiştirir.",
	"Clears the picture or selection.": "Resmi veya seçimi temizler.",
	"The font size must be a numeric value.": "Yazı tipi boyutu sayısal bir değer olmalıdır.",
	"Contains commands for working with the selected item(s).": "Seçili öğelerle çalışmak için komutlar içerir.",
	"Contains commands for selecting and transferring items.": "Öğeleri seçmek ve aktarmak için komutlar içerir.",
	"Contains commands for customizing this window.": "Bu pencereyi özelleştirmek için komutlar içerir.",
	"Contains commands for manipulating pictures and setting attributes.": "Resimleri değiştirmek ve öznitelikleri ayarlamak için kullanılan komutlar içerir.",
	"Contains commands for using custom colors and drawing options.": "İsteğe uyarlanmış renkleri ve çizim nesnelerini kullanmak için komutlar içerir.",
	"Contains commands for displaying Help for and information about Paint.": "Paint hakkında bilgi ve Yardım göstermek için komutlar içerir.",
	"Cannot save file.": "Dosya kaydedilemiyor.",
	"Error removing temporary file.": "Geçici dosyayı kaldırma hatası.",
	"Get Colors": "Renkleri Al",
	"Save Colors": "Renkleri Kaydet",
	"File last saved:": "Son kayıt tarihi:",
	"Not Available": "Kullanım dışı",
	"Size on disk:": "Diskteki boyutu:",
	"%s bytes": "%s bayt",
	"Painting": "Boyama",
	"Fonts": "Yazıtipleri",
	"Tools": "Araçlar",
	"All Picture Files": "Tüm Resim Dosyaları",
	"For Help, click Help Topics on the Help Menu.": "Yardım için Yardım Menüsü'ndeki Yardım Konuları'nı tıklatın.",
	"Select an area on which to get Help.": "Yardım almak istediğiniz alanı seçin.",
	"%1 in %2": "%2 içinde %1",
	"Creates a new document.": "Yeni bir belge oluşturur.",
	"Opens an existing document.": "Varolan bir belgeyi açar.",
	"Closes the active document.": "Etkin belgeyi kapatır.",
	"Saves the active document.": "Etkin belgeyi kaydeder.",
	"Saves the active document with a new name.": "Etkin belgeyi yeni bir adla kaydeder.",
	"Changes the page layout.": "Sayfa düzenini değiştirir.",
	"Specifies the default printer setup.": "Varsayılan yazıcı ayarlarını belirtir.",
	"Prints the active document and sets printing options.": "Etkin belgeyi yazdırır ve yazdırma seçeneklerini ayarlar.",
	"Displays full pages.": "Tam sayfa olarak gösterir.",
	"Opens this document.": "Bu belgeyi açar.",
	"Deletes the selection.": "Seçimi siler.",
	"Erases everything.": "Her şeyi siler.",
	"Copies the selection and puts it on the Clipboard.": "Seçimi kopyalar ve Pano'ya koyar.",
	"Cuts the selection and puts it on the Clipboard.": "Seçimi keser ve Pano'ya koyar.",
	"Finds the specified text.": "Belirtilen metni bulur.",
	"Inserts the contents of the Clipboard.": "Pano içeriğini ekler.",
	"Repeats the last action.": "Son eylemi yineler.",
	"Replaces specific text with different text.": "Belirtilen metni farklı bir metinle değiştirir.",
	"Selects everything.": "Her şeyi seçer.",
	"Undoes the last action.": "Son eylemi geri alır.",
	"Redoes the previously undone action.": "Son geri alınan eylemi yineler.",
	"Displays program information, version number, and copyright.": "Program bilgisini, sürüm numarasını ve telif hakkını görüntüler.",
	"Quits Paint.": "Paint'ten çıkar.",
	"Opens Paint Help.": "Paint Yardımı'nı açar.",
	"Displays instructions about how to use Help.": "Yardım'ın nasıl kullanılacağı ile ilgili yönergeler görüntüler.",
	"Displays Help for areas you click on.": "Tıklattığınız alanlarla ilgili Yardım görüntüler.",
	"Displays Help for the current task or command.": "Geçerli görev veya komut için yardım ekranını gösterir.",
	"Centers this bitmap as the desktop wallpaper.": "Bu bit eşlemini masaüstü duvar kağıdı olarak ortalar.",
	"Tiles this bitmap as the desktop wallpaper.": "Bu bit eşlemini masaüstü duvar kağıdı olarak döşer.",
	"Sends the selection using mail or fax.": "Seçimi posta veya faks kullanarak gönderir.",
	"Prints the selection.": "Seçimi yazdırır.",
	"Shows or hides the thumbnail.": "Parçacığı gösterir veya gizler.",
	"Shows Paint Help.": "Paint Yardımı'nı görüntüler.",
	"Shows or hides the status bar.": "Durum çubuğunu gösterir veya gizler.",
	"Shows or hides the tool box.": "Araç çubuğunu gösterir veya gizler.",
	"Shows or hides the color box.": "Renk kutusunu gösterir veya gizler.",
	"Only a Far East font can be used for vertical editing.": "Sadece Uzak Doğu yazıtipleri dikey yazmak için kullanılabilir.",
	"Changes the window size.": "Pencere boyutunu değiştirir.",
	"Changes the window position.": "Pencere konumunu değiştirir.",
	"Reduces the window to an icon.": "Pencereyi bir simge boyutuna küçültür.",
	"Enlarges the window to full size.": "Pencereyi tam boyuta genişletir.",
	"Switches to the next document window.": "Sonraki belge penceresine geçer.",
	"Switches to the previous document window.": "Önceki belge penceresine geçer.",
	"Closes the active window and asks if you want to save changes.": "Etkin pencereyi kapatır ve değişiklikleri kaydetmek isteyip istemediğinizi sorar.",
	"Restores the window to normal size.": "Pencereyi normal boyutuna döndürür.",
	"Activates the task list.": "Görev listesini etkinleştirir.",
	"All Files (*.*)": "Tüm Dosyalar (*.*)",
	"Untitled": "Adsız",
	"an unnamed file": "isimsiz bir dosya",
	"&Hide": "&Gizle",
	"Hide": "Gizle",
	"No error message is available.": "Geçerli hata iletisi yok.",
	"An unsupported operation was attempted.": "Desteklenmeyen bir işlem istendi.",
	"A required resource was unavailable.": "Gerekli bir kaynak kullanılmaz durumda.",
	"Out of memory.": "Bellek yetersiz.",
	"An unknown error has occurred.": "Bilinmeyen bir hata oluştu.",
	"on %1": "%1 üzerinde",
	"&One Page": "&Bir Sayfa",
	"One Page": "Bir Sayfa",
	"&Two Page": "İ&ki Sayfa",
	"Two Page": "İki Sayfa",
	"Page %u": "Sayfa %u",
	"Pages %u-%u": "Sayfa %u-%u",
	"Printer Files (*.prn)|*.prn|All Files (*.*)|*.*||": "Yazıcı Dosyaları (*.prn)|*.prn|Tüm Dosyalar (*.*)|*.*||",
	"Print to File": "Dosyaya Yazdır",
	"to %1": "%1 dosyasına",
	"&Update %1": "%1 Nesnesini &Güncelleştir",
	"Update %1": "%1 Nesnesini Güncelleştir",
	"E&xit && Return to %1": "Çık ve %1 &Uygulamasına Geri Dön",
	"Exit && Return to %1": "Çık ve %1 Uygulamasına Geri Dön",
	"Linked %s": "Bağlı %s",
	"Unknown Type": "Bilinmeyen Tür",
	"Invalid filename.": "Geçersiz dosya adı.",
	"Failed to open document.": "Belge açılamadı.",
	"Failed to save document.": "Belge kaydedilemedi.",
	"Save changes to %1?": "%1 içindeki değişiklikler kaydedilsin mi?",
	"Failed to create empty document.": "Boş belge oluşturulamadı.",
	"The file is too large to open.": "Dosya açılamayacak kadar büyük.",
	"Could not start print job.": "Yazdırma işlemi başlatılamadı.",
	"Failed to launch help.": "Yardım başlatılamadı.",
	"Internal application error.": "İç uygulama hatası.",
	"Command failed.": "Komut başarısız.",
	"Insufficient memory to perform operation.": "İşlemi yürütmek için bellek yetersiz.",
	"System registry entries have been removed and the INI file (if any) was deleted.": "Sistem kayıt girdileri kaldırıldı ve (varsa) INI dosyaları silindi.",
	"Not all of the system registry entries (or INI file) were removed.": "Sistem kayıt girdilerinin (veya INI dosyalarının) hepsi kaldırılmadı.",
	"This program requires the file %s, which was not found on this system.": "Bu program için, sisteminizde mevcut olmayan %s dosyası gereklidir.",
	"This program is linked to the missing export %s in the file %s. This machine may have an incompatible version of %s.": "Bu program %s dosyasındaki eksik dış %s 'e bağlanmış. Bu makinede %s 'in uyumsuz sürümü bulunuyor olabilir.",
	"Please enter an integer.": "Lütfen bir tamsayı girin.",
	"Please enter a number.": "Lütfen bir sayı girin.",
	"Please enter an integer between %1 and %2.": "Lütfen %1 ile %2 arasında bir tamsayı girin.",
	"Please enter a number between %1 and %2.": "Lütfen %1 ile %2 arasında bir sayı girin.",
	"Please enter no more than %1 characters.": "Lütfen en çok %1 karakter girin.",
	"Please select a button.": "Lütfen bir düğme seçin.",
	"Please enter an integer between 0 and 255.": "Lütfen 0 ile 255 arasında bir tamsayı girin.",
	"Please enter a positive integer.": "Lütfen pozitif bir tamsayı girin.",
	"Please enter a date and/or time.": "Lütfen tarih ve/veya saat girin.",
	"Please enter a currency.": "Lütfen para birimi girin.",
	"Unexpected file format.": "Beklenilmeyen dosya biçimi.",
	"Cannot find this file.": "Bu dosya bulunamıyor.",
	"Please verify that the correct path and file name are given.": "Lütfen doğru yolun ve dosya adının verildiğini doğrulayın.",
	"Destination disk drive is full.": "Hedef disk sürücü dolu.",
	"Unable to read from %1, it is opened by someone else.": "%1 okunamıyor, başka birisi tarafından açılmış.",
	"Unable to write to %1, it is read-only or opened by someone else.": "%1 dosyasına yazılamıyor, salt okunur veya bir başkası tarafından açılmış.",
	"An unexpected error occurred while reading %1.": "%1 dosyası okunurken beklenilmeyen bir hata oluştu.",
	"An unexpected error occurred while writing %1.": "%1 dosyası yazılırken beklenilmeyen bir hata oluştu.",
	"Unable to register document.": "Belge kaydedilemedi.",
	"The document may already be open.": "Belge zaten açık olabilir.",
	"Update %1 before proceeding?": "Devam etmeden önce %1 güncelleştirilsin mi?",
	"Could not update client.": "İstemci güncelleştirilemedi.",
	"Failed to register. ActiveX features may not work properly.": "Kayıt yapılamadı. ActiveX özellikleri düzgün çalışmayabilir.",
	"Failed to update the system registry.": "Sistem kayıt defteri güncelleştirilemedi.",
	"Please try using REGEDIT.": "Lütfen REGEDIT'i kullanarak deneyin.",
	"Unable to read write-only property.": "Salt yazılır özelliği okunamıyor.",
	"Unable to write read-only property.": "Salt okunur özelliği yazılamıyor.",
	"Unable to load mail system support.": "Posta sistemi desteği yüklenemedi.",
	"Mail system DLL is invalid.": "Posta sistem DLL'i geçersiz.",
	"Send Mail failed to send message.": "Posta Gönder, ileti'yi gönderemedi.",
	"No error occurred.": "Hata oluşmadı.",
	"An unknown error occurred while accessing %1.": "%1 erişiminde bilinmeyen bir hata oluştu.",
	"%1 was not found.": "%1 bulunamadı.",
	"%1 contains an invalid path.": "%1 geçersiz bir yol içeriyor.",
	"%1 could not be opened because there are too many open files.": "Çok fazla açık dosya olduğundan %1 açılamadı.",
	"Access to %1 was denied.": "%1 erişimi engellendi.",
	"An invalid file handle was associated with %1.": "%1 ile geçersiz bir dosya tutamacı ilişkilendirilmiş.",
	"%1 could not be removed because it is the current directory.": "%1 geçerli dizin olduğundan kaldırılamadı.",
	"%1 could not be created because the directory is full.": "Dizin dolu olduğundan %1 oluşturulamadı.",
	"Seek failed on %1": "%1 üzerinde arama başarısız",
	"A hardware I/O error was reported while accessing %1.": "%1 erişimi sırasında donanım G/Ç hatası bildirildi.",
	"A sharing violation occurred while accessing %1.": "%1 erişimi sırasında paylaşım ihlali oluştu.",
	"A locking violation occurred while accessing %1.": "%1 erişimi sırasında kilit ihlali oluştu.",
	"Disk full while accessing %1.": "%1 erişimi sırasında disk doldu.",
	"An attempt was made to access %1 past its end.": "%1 erişimi denemesi sonunu aştı.",
	"An attempt was made to write to the reading %1.": "%1 okumasına yazmaya çalışıldı.",
	"An attempt was made to read from the writing %1.": "%1 yazısından okunmaya çalışıldı.",
	"%1 has a bad format.": "%1 hatalı biçime sahip.",
	"%1 contained an unexpected object.": "%1 beklenmeyen bir nesne içerdi.",
	"%1 contains an incorrect schema.": "%1 doğru olmayan bir düzen içeriyor.",
	"Selects a rectangular part of the picture to move, copy, or edit.": "Taşımak, kopyalamak veya düzenlemek için resmin dikdörtgen bir parçasını seçer.",
	"Select": "Seç",
	"Selects a free-form part of the picture to move, copy, or edit.": "Taşımak, kopyalamak veya düzenlemek için resmin serbest şekilli bir parçasını seçer.",
	"Free-Form Select": "Serbest Şekil Seçimi",
	"Inserts text into the picture.": "Metni resmin içine yerleştirir.",
	"Fills an area with the current drawing color.": "Bir alanı geçerli çizim rengiyle doldurur.",
	"Fill With Color": "Renkle Doldur",
	"Draws a straight line with the selected line width.": "Seçili çizgi kalınlığında bir düz çizgi çizer.",
	"Line": "Çizgi",
	"Draws using an airbrush of the selected size.": "Seçili boyutta bir püskürtme kabı kullanarak çizer.",
	"Airbrush": "Püskürtme kabı",
	"Draws a curved line with the selected line width.": "Seçili çizgi kalınlığında kıvrımlı bir çizgi çizer.",
	"Curve": "Kıvrım",
	"Draws a polygon with the selected fill style.": "Seçili doldurma biçemiyle bir çokgen çizer.",
	"Polygon": "Çokgen",
	"Draws a rounded rectangle with the selected fill style.": "Seçili doldurma biçemiyle yuvarlatılmış bir dikdörtgen çizer.",
	"Rounded Rectangle": "Yuvarlatılmış Dikdörtgen",
	"Draws a free-form line one pixel wide.": "Bir piksel genişliğinde serbest şekilli çizgi çizer.",
	"Pencil": "Kalem",
	"Erases a portion of the picture, using the selected eraser shape.": "Seçili silici şeklini kullanarak resmin bir parçasını siler.",
	"Eraser/Color Eraser": "Silgi/Renk Silicisi",
	"Changes the magnification.": "Büyütme oranını değiştirir.",
	"Magnifier": "Büyüteç",
	"Picks up a color from the picture for drawing.": "Çizim için resimden bir renk seçer.",
	"Pick Color": "Renk Seç",
	"Draws using a brush with the selected shape and size.": "Seçili şekil ve boyutta bir fırçayla çizer.",
	"Brush": "Fırça",
	"Draws a rectangle with the selected fill style.": "Seçili doldurma biçemiyle bir dikdörtgen çizer.",
	"Rectangle": "Dikdörtgen",
	"Draws a filled rectangle.": "Dolu bir dikdörtgen çizer.",
	"Draws an ellipse with the selected fill style.": "Seçili doldurma biçemiyle bir elips çizer.",
	"Ellipse": "Elips",
	"Draws a filled ellipse.": "Dolu bir elips çizer.",
	"Makes the current selection either opaque or transparent.": "Geçerli seçimi donuk veya saydam yapar.",
	"Creates a new color.": "Yeni bir renk oluşturur.",
	"Uses a previously saved palette of colors.": "Önceden kaydedilen bir renk paletini kullanır.",
	"Saves the current palette of colors to a file.": "Geçerli renk paletini bir dosyaya kaydeder.",
	"You must save the file before choosing it as Wallpaper.": "Dosyayı Duvar Kağıdı olarak kullanmadan önce kaydetmelisiniz.",
	"The selection is now larger than the bitmap.": "Seçim şimdi bit eşlemden daha geniş.",
	"Would you like the bitmap enlarged?": "Bit eşlemin genişletilmesini ister misiniz?",
	"The image in the clipboard is larger than the bitmap.": "Pano içindeki resim, bit eşlemden daha geniş.",
	"The file is not in the correct format.": "Dosya doğru biçimde değil.",
	"Not enough room to paste text.": "Metni yapıştırmak için yer yok.",
	"Enlarge the text area and try again.": "Metin alanını genişletip yeniden deneyin.",
	"Places the text.": "Metni yerleştirir."
});
