//
// NOTE: This is a generated file! Don't edit it directly.
// Eventually community translation will be set up on some translation platform.
// 
// Generated with: npm run update-localization
//
loaded_localizations("pt-br", {
	"Attributes": "Atributos",
	"&Width:": "&Largura:",
	"Width:": "Largura:",
	"&Height:": "&Altura:",
	"Height:": "Altura:",
	"Units": "Unidades",
	"&Inches": "P&olegadas",
	"Inches": "Polegadas",
	"&Pixels": "Pi&xels",
	"Pixels": "Pixels",
	"Colors": "Cores",
	"&Black and white": "Preto e &branco",
	"Black and white": "Preto e branco",
	"Co&lors": "Co&res",
	"Transparency": "Transparência",
	"Use &Transparent background color": "Usar cor de fundo &transparente",
	"Use Transparent background color": "Usar cor de fundo transparente",
	"Select &Color": "Selecionar &cor",
	"Select Color": "Selecionar a cor",
	"Cancel": "Cancelar",
	"&Default": "&Padrão",
	"Default": "Padrão",
	"Custom Zoom": "Zoom personalizado",
	"Current zoom:": "Zoom atual:",
	"Zoom to": "Nível de zoom",
	"Flip and Rotate": "Inverter e girar",
	"Flip or rotate": "Inverter ou girar",
	"&Flip horizontal": "Inverter &horizontalmente",
	"Flip horizontal": "Inverter horizontalmente",
	"Flip &vertical": "Inverter &verticalmente",
	"Flip vertical": "Inverter verticalmente",
	"&Rotate by angle": "&Girar",
	"Rotate by angle": "Girar",
	"Stretch and Skew": "Alongar e inclinar",
	"Stretch": "Alongar",
	"Skew": "Inclinar",
	"Degrees": "graus",
	"Color Table": "Tabela de cores",
	"New": "Novo",
	"&New ": "&Novo ",
	"New ": "Novo ",
	"&Help": "Aj&uda",
	"Help": "Ajuda",
	"Printing": "Imprimindo",
	"on the": "em",
	"&Print": "&Imprimir",
	"Print": "Imprimir",
	"&Next Page": "Página &seg.",
	"Next Page": "Página seg.",
	"Pre&v Page": "Página a&nt.",
	"Prev Page": "Página ant.",
	"Zoom &In": "&Mais zoom",
	"Zoom In": "Mais zoom",
	"Zoom &Out": "Men&os zoom",
	"Zoom Out": "Menos zoom",
	"&Close": "&Fechar",
	"Close": "Fechar",
	"Grid Settings": "Configurações da grade",
	"&Pixel Grid": "&Grade de pixels",
	"Pixel Grid": "Grade de pixels",
	"&Tile Grid": "G&rade lado a lado",
	"Tile Grid": "Grade lado a lado",
	"H&eight:": "&Altura:",
	"Text": "Texto",
	"Undo": "Desfazer",
	"Cut": "Recortar",
	"Copy": "Copiar",
	"Paste": "Colar",
	"Clear Selection": "Limpar seleção",
	"Select All": "Selecionar tudo",
	"Text Toolbar": "Barra de ferramentas de texto",
	"Selection": "Seleção",
	"Cu&t": "&Recortar",
	"&Copy": "&Copiar",
	"&Paste": "C&olar",
	"C&lear Selection": "&Limpar seleção",
	"Select &All": "Selecionar &tudo",
	"C&opy To": "Copiar &para",
	"Copy To": "Copiar para",
	"Paste &From": "Colar &de",
	"Paste From": "Colar de",
	"Flip/&Rotate": "Inverter/&girar",
	"Flip/Rotate": "Inverter/girar",
	"&Stretch/Skew": "&Alongar/inclinar",
	"Stretch/Skew": "Alongar/inclinar",
	"&Invert Colors": "&Inverter cores",
	"Invert Colors": "Inverter cores",
	"Thumbnail": "Miniatura",
	"&File": "&Arquivo",
	"File": "Arquivo",
	"&New": "&Novo",
	"&Open": "A&brir",
	"Open": "Abrir",
	"&Save": "&Salvar",
	"Save": "Salvar",
	"Save &As": "Salvar &como",
	"Save As": "Salvar como",
	"Print Pre&view": "&Visualizar impressão",
	"Print Preview": "Visualizar impressão",
	"Page Se&tup": "Con&figurar página",
	"Page Setup": "Configurar página",
	"S&end": "&Enviar",
	"Send": "Enviar",
	"Set As &Wallpaper (Tiled)": "Configurar como papel de parede (&lado a lado)",
	"Set As Wallpaper (Tiled)": "Configurar como papel de parede (lado a lado)",
	"Set As Wa&llpaper (Centered)": "Configurar como papel de parede (cen&tralizado)",
	"Set As Wallpaper (Centered)": "Configurar como papel de parede (centralizado)",
	"Recent File": "Arquivo recente",
	"E&xit": "Sai&r",
	"Exit": "Sair",
	"&Edit": "&Editar",
	"Edit": "Editar",
	"&Undo": "Desfa&zer",
	"&Repeat": "R&epetir",
	"Repeat": "Repetir",
	"&View": "E&xibir",
	"View": "Exibir",
	"&Tool Box": "Caixa de &ferramentas",
	"Tool Box": "Caixa de ferramentas",
	"&Color Box": "Caixa de &cores",
	"Color Box": "Caixa de cores",
	"&Status Bar": "Barra de &status",
	"Status Bar": "Barra de status",
	"T&ext Toolbar": "&Barra de ferramentas de texto",
	"&Normal Size": "Tama&nho normal",
	"Normal Size": "Tamanho normal",
	"&Large Size": "Tamanho gran&de",
	"Large Size": "Tamanho grande",
	"C&ustom": "Personali&zar",
	"Custom": "Personalizar",
	"Show &Grid": "Mos&trar grade",
	"Show Grid": "Mostrar grade",
	"Show T&humbnail": "Mostrar &miniatura",
	"Show Thumbnail": "Mostrar miniatura",
	"&View Bitmap": "E&xibir bitmap",
	"View Bitmap": "Exibir bitmap",
	"&Image": "&Imagem",
	"Image": "Imagem",
	"&Flip/Rotate": "Inverter/&girar",
	"&Attributes": "A&tributos",
	"&Clear Image": "&Limpar imagem",
	"Clear Image": "Limpar imagem",
	"&Draw Opaque": "&Desenho opaco",
	"Draw Opaque": "Desenho opaco",
	"&Colors": "&Cores",
	"&Edit Colors": "&Editar cores",
	"Edit Colors": "Editar cores",
	"&Help Topics": "&Tópicos da Ajuda",
	"Help Topics": "Tópicos da Ajuda",
	"&About Paint": "So&bre o Paint",
	"About Paint": "Sobre o Paint",
	"&Update": "A&tualizar",
	"Update": "Atualizar",
	"Save Copy &As": "Salvar cópia &como",
	"Save Copy As": "Salvar cópia como",
	"untitled": "imagem",
	"Bitmap Image": "Imagem de bitmap",
	"Bitmap Files (*.bmp)": "Arquivos de bitmap (*.bmp)",
	"PCX Files": "Arquivos PCX",
	"Icon Files": "Arquivos de ícone",
	"Monochrome Bitmap (*.bmp;*.dib)": "Bitmap monocromático (*.bmp;*.dib)",
	"16 Color Bitmap (*.bmp;*.dib)": "Bitmap de 16 cores (*.bmp;*.dib)",
	"256 Color Bitmap (*.bmp;*.dib)": "Bitmap de 256 cores (*.bmp;*.dib)",
	"Paint cannot open this file.": "O Paint não pode abrir este arquivo.",
	"Paint cannot read this file.": "O Paint não pode ler este arquivo.",
	"This file is read-only.": "Este arquivo é somente leitura.",
	"To save your changes, use a different filename.": "Para salvar suas alterações, utilize um nome de arquivo diferente.",
	"This file is already open.": "Este arquivo já está aberto.",
	"This is not a valid .PCS file.": "Este não é um arquivo .PCS válido.",
	"This file is open for editing and cannot be overwritten.": "Este arquivo está aberto para edição e não pode ser sobrescrito.",
	"Use a different filename to save your changes.": "Utilize um nome de arquivo diferente para salvar suas alterações.",
	"This is not a valid bitmap file, or its format is not currently supported.": "Este não é um arquivo de bitmap válido ou o seu formato não é atualmente aceito.",
	"This is not a valid icon.": "Este não é um ícone válido.",
	"This is not a valid cursor.": "Este não é um cursor válido.",
	"Save was interrupted, so your file has not been saved.": "O salvamento foi interrompido. O seu arquivo não foi salvo.",
	"You cannot save to a read-only file.": "Você não pode salvar em um arquivo somente leitura.",
	"Use a different file name.": "Utilize um nome de arquivo diferente.",
	"This file is already in use.": "Este arquivo já está em uso.",
	"Close the program, and then try again.": "Feche o programa e tente novamente.",
	"Paint cannot save this file.": "O Paint não pode salvar este arquivo.",
	"Paint cannot save to the same filename with a different file type.": "O Paint não pode salvar arquivos de tipos diferentes com o mesmo nome.",
	"The grid spacing must be an integer between %d and %d.": "O espaçamento da grade deve ser um número inteiro entre %d e %d.",
	"There is not enough memory or resources to complete operation.": "Memória ou recursos insuficientes para completar a operação.",
	"Close some programs, and then try again.": "Feche alguns programas e tente novamente.",
	"Low on memory or resources.": "Memória ou recursos insuficientes.",
	"Group error.": "Erro de grupo.",
	"Paint was unable to print your document. Please make sure you have sufficient disk space and that your printer is working correctly.": "O Paint não pôde imprimir seu documento. Verifique se você possui espaço em disco suficiente e se sua impressora está funcionando corretamente.",
	"Saving into this format may cause some loss of color information.": "O salvamento neste formato poderá causar perda de informações sobre as cores.",
	"Do you want to continue?": "Deseja continuar?",
	"Converting to black and white cannot be undone.  This action affects the current file and may cause some loss of color information.": "A conversão para preto e branco não pode ser desfeita. Esta ação afeta o arquivo atual e pode causar a perda de algumas informações sobre cores.",
	"Bitmaps must be greater than one pixel on a side.": "Arquivos de bitmap devem ser maiores que 1 pixel em um lado.",
	"Generic error.": "Erro genérico.",
	"File not found.": "Arquivo não encontrado.",
	"Bad path.": "Caminho incorreto.",
	"Too many open files.": "Existem muitos arquivos abertos.",
	"Access denied.": "Acesso negado.",
	"Invalid file.": "Arquivo inválido.",
	"Remove current folder.": "Remover a pasta atual.",
	"Folder full.": "Pasta cheia.",
	"Bad seek.": "Pesquisa incorreta.",
	"Hard IO error.": "Erro de E/S de hardware.",
	"Sharing violation.": "Violação de compartilhamento.",
	"Lock violation.": "Violação de bloqueio.",
	"Disk full.": "Disco cheio.",
	"End of file.": "Final de arquivo.",
	"Error getting the Clipboard Data!": "Erro ao obter os dados da área de transferência!",
	"No Printer Found @ page setup": "Nenhuma impressora encontrada na configuração da página",
	"24-bit Bitmap (*.bmp;*.dib)": "Bitmap de 24 bits (*.bmp;*.dib)",
	"All Files": "Todos os arquivos",
	"Palette|*.pal|": "Paleta|*.pal|",
	"untitled.pal": "imagem.pal",
	"OLE 2.0 was unable to start.": "O OLE 2.0 não pôde ser iniciado.",
	"Make sure that you are using the correct version of the OLE libraries.": "Certifique-se de que você esteja usando a versão correta das bibliotecas de OLE.",
	"Resets the text be without any attributes.": "Redefine o texto para não ter nenhum atributo.",
	"Sets or clears the text bold attribute.": "Define ou limpa o atributo negrito do texto.",
	"Sets or clears the text italic attribute.": "Define ou limpa o atributo itálico do texto.",
	"Selects the font used by the text.": "Seleciona a fonte utilizada pelo texto.",
	"Selects the point size of the text.": "Seleciona o tamanho do ponto do texto.",
	"Sets or clears the text underline attribute.": "Define ou limpa o atributo sublinhado do texto.",
	"Shows or hides the tooltips.": "Mostra ou oculta as dicas para uso de ferramentas.",
	"Show Paint Help.": "Mostrar a Ajuda do Paint.",
	"Sends a picture by using mail or fax.": "Envia a figura utilizando correio ou fax.",
	"Copies the selection to a file.": "Copia a seleção para um arquivo.",
	"Pastes a file into the selection.": "Cola o arquivo na seleção.",
	"Zooms the picture to 100%.": "Aplica zoom na figura em 100%.",
	"Zooms the picture to 400%.": "Aplica zoom na figura em 400%.",
	"Zooms the picture.": "Aplica zoom na figura.",
	"Displays the entire picture.": "Exibe a figura inteira.",
	"Shows or hides the thumbnail view of the picture.": "Mostra ou oculta a miniatura da imagem.",
	"Shows or hides the grid.": "Mostra ou oculta a grade.",
	"Shows or hides the text toolbar.": "Mostra ou oculta a barra de ferramentas do texto.",
	"Flips or rotates the picture or a selection.": "Inverte ou gira a figura ou uma seleção.",
	"Stretches or skews the picture or a selection.": "Alonga ou inclina a figura ou uma seleção.",
	"Inverts the colors of the picture or a selection.": "Inverte as cores da figura ou de uma seleção.",
	"Changes the attributes of the picture.": "Altera os atributos da figura.",
	"Clears the picture or selection.": "Limpa a figura ou seleção.",
	"The font size must be a numeric value.": "O tamanho da fonte deve ser um valor numérico.",
	"Contains commands for working with the selected item(s).": "Contém comandos para trabalhar com o(s) item(ns) selecionado(s).",
	"Contains commands for selecting and transferring items.": "Contém comandos para selecionar e transferir itens.",
	"Contains commands for customizing this window.": "Contém comandos para personalizar esta janela.",
	"Contains commands for manipulating pictures and setting attributes.": "Contém comandos para manipular figuras e definir atributos.",
	"Contains commands for using custom colors and drawing options.": "Contém comandos para utilizar cores personalizadas e opções de desenho.",
	"Contains commands for displaying Help for and information about Paint.": "Contém comandos para exibir a Ajuda e informação sobre o Paint.",
	"Cannot save file.": "Não é possível salvar o arquivo.",
	"Error removing temporary file.": "Erro na remoção do arquivo temporário.",
	"Get Colors": "Obter cores",
	"Save Colors": "Salvar cores",
	"File last saved:": "Último arquivo gravado:",
	"Not Available": "Não disponível",
	"Size on disk:": "Tamanho no disco:",
	"Painting": "Pintando",
	"Fonts": "Fontes",
	"Tools": "Ferramentas",
	"All Picture Files": "Todos os arquivos de imagem",
	"For Help, click Help Topics on the Help Menu.": "Para obter Ajuda, clique em 'Tópicos da Ajuda' no menu 'Ajuda'.",
	"Select an area on which to get Help.": "Selecionar uma área sobre a qual se quer obter Ajuda.",
	"%1 in %2": "%1 em %2",
	"Creates a new document.": "Cria um novo documento.",
	"Opens an existing document.": "Abre um documento existente.",
	"Closes the active document.": "Fecha o documento ativo.",
	"Saves the active document.": "Salva o documento ativo.",
	"Saves the active document with a new name.": "Salva o documento ativo com um novo nome.",
	"Changes the page layout.": "Altera o layout da página.",
	"Specifies the default printer setup.": "Especifica a configuração da impressora padrão.",
	"Prints the active document and sets printing options.": "Imprime o documento ativo e configura as opções de impressão.",
	"Displays full pages.": "Exibe páginas inteiras.",
	"Opens this document.": "Abre este documento.",
	"Deletes the selection.": "Exclui a seleção.",
	"Erases everything.": "Apaga tudo.",
	"Copies the selection and puts it on the Clipboard.": "Copia a seleção e a coloca na área de transferência.",
	"Cuts the selection and puts it on the Clipboard.": "Recorta a seleção e a coloca na área de transferência.",
	"Finds the specified text.": "Localiza o texto especificado.",
	"Inserts the contents of the Clipboard.": "Insere o conteúdo da área de transferência.",
	"Repeats the last action.": "Repete a última ação.",
	"Replaces specific text with different text.": "Substitui o texto específico por um texto diferente.",
	"Selects everything.": "Seleciona tudo.",
	"Undoes the last action.": "Desfaz a última ação.",
	"Redoes the previously undone action.": "Refaz a ação desfeita anteriormente.",
	"Displays program information, version number, and copyright.": "Exibe informações do programa, número da versão e copyright.",
	"Quits Paint.": "Encerra o Paint.",
	"Opens Paint Help.": "Abre a Ajuda do Paint.",
	"Displays instructions about how to use Help.": "Exibe instruções sobre como utilizar a Ajuda.",
	"Displays Help for areas you click on.": "Exibe Ajuda para as áreas onde você clicou.",
	"Displays Help for the current task or command.": "Exibe Ajuda para a tarefa ou comando atual.",
	"Centers this bitmap as the desktop wallpaper.": "Centraliza este bitmap como papel de parede da área de trabalho.",
	"Tiles this bitmap as the desktop wallpaper.": "Posiciona lado a lado este bitmap como papel de parede da área de trabalho.",
	"Sends the selection using mail or fax.": "Envia a figura utilizando correio ou fax.",
	"Prints the selection.": "Imprime a seleção.",
	"Shows or hides the thumbnail.": "Mostra ou oculta a miniatura.",
	"Shows Paint Help.": "Mostra a Ajuda do Paint.",
	"Shows or hides the status bar.": "Mostra ou oculta a barra de status.",
	"Shows or hides the tool box.": "Mostra ou oculta a caixa de ferramentas.",
	"Shows or hides the color box.": "Mostra ou oculta a caixa de cores.",
	"Only a Far East font can be used for vertical editing.": "Somente fontes para o Extremo Oriente podem ser editadas na vertical.",
	"Changes the window size.": "Altera o tamanho da janela.",
	"Changes the window position.": "Altera a posição da janela.",
	"Reduces the window to an icon.": "Reduz esta janela a um ícone.",
	"Enlarges the window to full size.": "Amplia a janela para o tamanho máximo.",
	"Switches to the next document window.": "Alterna para a janela do próximo documento.",
	"Switches to the previous document window.": "Alterna para a janela do documento anterior.",
	"Closes the active window and asks if you want to save changes.": "Fecha a janela ativa e pergunta se deseja salvar as alterações.",
	"Restores the window to normal size.": "Restaura a janela ao tamanho normal.",
	"Activates the task list.": "Ativa a lista de tarefas.",
	"All Files (*.*)": "Todos os arquivos (*.*)",
	"Untitled": "Sem nome",
	"an unnamed file": "um arquivo sem nome",
	"&Hide": "&Ocultar",
	"Hide": "Ocultar",
	"No error message is available.": "Não há mensagens de erro disponíveis.",
	"An unsupported operation was attempted.": "Foi feita uma tentativa de executar uma operação não aceita.",
	"A required resource was unavailable.": "Um recurso necessário não estava disponível.",
	"Out of memory.": "Sem memória.",
	"An unknown error has occurred.": "Ocorreu um erro desconhecido.",
	"on %1": "em %1",
	"&One Page": "&Uma página",
	"One Page": "Uma página",
	"&Two Page": "&Duas pág.",
	"Two Page": "Duas pág.",
	"Page %u": "Página %u",
	"Pages %u-%u": "Páginas %u-%u",
	"Printer Files (*.prn)|*.prn|All Files (*.*)|*.*||": "Arquivos de impressora (*.prn)|*.prn|Todos os arquivos (*.*)|*.*||",
	"Print to File": "Imprimir em arquivo",
	"to %1": "para %1",
	"&Update %1": "&Atualizar %1",
	"Update %1": "Atualizar %1",
	"E&xit && Return to %1": "Sai&r e retornar a %1",
	"Exit && Return to %1": "Sair e retornar a %1",
	"Linked %s": "%s vinculado",
	"Unknown Type": "Tipo desconhecido",
	"Invalid filename.": "Nome de arquivo inválido.",
	"Failed to open document.": "Não foi possível abrir o documento.",
	"Failed to save document.": "Não foi possível salvar o documento.",
	"Save changes to %1?": "Salvar as alterações em %1?",
	"Failed to create empty document.": "Não foi possível criar um documento vazio.",
	"The file is too large to open.": "O arquivo é muito grande para ser aberto.",
	"Could not start print job.": "Não foi possível iniciar o trabalho de impressão.",
	"Failed to launch help.": "Não foi possível iniciar a Ajuda.",
	"Internal application error.": "Erro interno do aplicativo.",
	"Command failed.": "O comando falhou.",
	"Insufficient memory to perform operation.": "Memória insuficiente para executar a operação.",
	"System registry entries have been removed and the INI file (if any) was deleted.": "As entradas no Registro do sistema foram removidas e o arquivo INI (se havia) foi excluído.",
	"Not all of the system registry entries (or INI file) were removed.": "Não foram removidas todas as entradas do Registro do sistema (ou o arquivo INI).",
	"This program requires the file %s, which was not found on this system.": "Este programa requer o arquivo %s que não foi encontrado neste sistema.",
	"This program is linked to the missing export %s in the file %s. This machine may have an incompatible version of %s.": "Este programa está vinculado ao %s de exportação não encontrado no arquivo %s. Talvez este computador tenha uma versão incompatível de %s.",
	"Please enter an integer.": "Digite um número inteiro.",
	"Please enter a number.": "Digite um número.",
	"Please enter an integer between %1 and %2.": "Digite um número inteiro entre %1 e %2.",
	"Please enter a number between %1 and %2.": "Digite um número entre %1 e %2.",
	"Please enter no more than %1 characters.": "Digite no máximo %1 caracteres.",
	"Please select a button.": "Selecione um botão.",
	"Please enter an integer between 0 and 255.": "Digite um número inteiro entre 0 e 255.",
	"Please enter a positive integer.": "Digite um número inteiro positivo.",
	"Please enter a date and/or time.": "Digite uma data e/ou hora.",
	"Please enter a currency.": "Digite uma unidade monetária.",
	"Unexpected file format.": "Formato de arquivo inesperado.",
	"Cannot find this file.": "Não é possível encontrar este arquivo.",
	"Please verify that the correct path and file name are given.": "Verifique se o caminho e o nome do arquivo estão corretos.",
	"Destination disk drive is full.": "A unidade de disco de destino está cheia.",
	"Unable to read from %1, it is opened by someone else.": "Não é possível ler de %1. Ele está aberto por outra pessoa.",
	"Unable to write to %1, it is read-only or opened by someone else.": "Não é possível gravar em %1. Ele é somente leitura ou está aberto por outra pessoa.",
	"An unexpected error occurred while reading %1.": "Ocorreu um erro inesperado durante a leitura de %1.",
	"An unexpected error occurred while writing %1.": "Ocorreu um erro inesperado durante a gravação de %1.",
	"Unable to register document.": "Não é possível registrar o documento.",
	"The document may already be open.": "O documento pode já estar aberto.",
	"Update %1 before proceeding?": "Atualizar %1 antes de prosseguir?",
	"Could not update client.": "Não foi possível atualizar o cliente.",
	"Failed to register. ActiveX features may not work properly.": "Não foi possível registrar. Os recursos ActiveX podem não funcionar corretamente.",
	"Failed to update the system registry.": "Não foi possível atualizar o Registro do sistema.",
	"Please try using REGEDIT.": "Tente usar o REGEDIT.",
	"Unable to read write-only property.": "Não é possível ler, propriedade somente gravação.",
	"Unable to write read-only property.": "Não é possível gravar, propriedade somente leitura.",
	"Unable to load mail system support.": "Não é possível carregar o suporte ao sistema de correio.",
	"Mail system DLL is invalid.": "A DLL do sistema de correio é inválida.",
	"Send Mail failed to send message.": "Não foi possível enviar a mensagem.",
	"No error occurred.": "Não houve erros.",
	"An unknown error occurred while accessing %1.": "Ocorreu um erro desconhecido durante o acesso a %1.",
	"%1 was not found.": "%1 não foi encontrado.",
	"%1 contains an invalid path.": "%1 contém um caminho inválido.",
	"%1 could not be opened because there are too many open files.": "%1 não pôde ser aberto porque existem muitos arquivos abertos.",
	"Access to %1 was denied.": "O acesso a %1 foi negado.",
	"An invalid file handle was associated with %1.": "Um identificador de arquivo inválido foi associado a %1.",
	"%1 could not be removed because it is the current directory.": "%1 não pôde ser removida porque é a pasta atual.",
	"%1 could not be created because the directory is full.": "%1 não pôde ser criado porque a pasta está cheia.",
	"Seek failed on %1": "A pesquisa falhou em %1",
	"A hardware I/O error was reported while accessing %1.": "Foi relatado um erro de E/S de hardware durante o acesso a %1.",
	"A sharing violation occurred while accessing %1.": "Ocorreu uma violação de compartilhamento durante o acesso a %1.",
	"A locking violation occurred while accessing %1.": "Ocorreu uma violação de bloqueio durante o acesso a %1.",
	"Disk full while accessing %1.": "Disco cheio durante o acesso a %1.",
	"An attempt was made to access %1 past its end.": "Foi feita uma tentativa de acesso a %1 depois de seu fim.",
	"An attempt was made to write to the reading %1.": "Foi feita uma tentativa de gravar em %1, que é somente leitura.",
	"An attempt was made to read from the writing %1.": "Foi feita uma tentativa de ler de %1, que é somente gravação.",
	"%1 has a bad format.": "%1 tem um formato incorreto.",
	"%1 contained an unexpected object.": "%1 continha um objeto inesperado.",
	"%1 contains an incorrect schema.": "%1 contém um esquema incorreto.",
	"Selects a rectangular part of the picture to move, copy, or edit.": "Seleciona uma parte retangular da figura para mover, copiar ou editar.",
	"Select": "Seleção",
	"Selects a free-form part of the picture to move, copy, or edit.": "Seleciona uma parte em forma livre da figura para ser movida, copiada ou editada.",
	"Free-Form Select": "Selecionar forma livre",
	"Inserts text into the picture.": "Insere o texto na figura.",
	"Fills an area with the current drawing color.": "Preenche uma área com a cor de desenho atual.",
	"Fill With Color": "Preencher com cor",
	"Draws a straight line with the selected line width.": "Desenha uma linha reta com a largura de linha selecionada.",
	"Line": "Linha",
	"Draws using an airbrush of the selected size.": "Desenha com um spray do tamanho selecionado.",
	"Airbrush": "Spray",
	"Draws a curved line with the selected line width.": "Desenha uma linha curva com a largura de linha selecionada.",
	"Curve": "Curva",
	"Draws a polygon with the selected fill style.": "Desenha um polígono com o estilo de preenchimento selecionado.",
	"Polygon": "Polígono",
	"Draws a rounded rectangle with the selected fill style.": "Desenha um retângulo arredondado com o estilo de preenchimento selecionado.",
	"Rounded Rectangle": "Retângulo arredondado",
	"Draws a free-form line one pixel wide.": "Desenha uma linha de um pixel em forma livre.",
	"Pencil": "Lápis",
	"Erases a portion of the picture, using the selected eraser shape.": "Apaga uma parte da figura, usando a forma de apagador selecionada.",
	"Eraser/Color Eraser": "Apagador/Apagador de cor",
	"Changes the magnification.": "Altera a ampliação.",
	"Magnifier": "Ampliador",
	"Picks up a color from the picture for drawing.": "Seleciona uma cor da figura para desenhar.",
	"Pick Color": "Seleciona cor",
	"Draws using a brush with the selected shape and size.": "Desenha utilizando um pincel com a forma e tamanho selecionados.",
	"Brush": "Pincel",
	"Draws a rectangle with the selected fill style.": "Desenha um retângulo com o estilo de preenchimento selecionado.",
	"Rectangle": "Retângulo",
	"Draws a filled rectangle.": "Desenha um retângulo preenchido.",
	"Draws an ellipse with the selected fill style.": "Desenha uma elipse com o estilo de preenchimento selecionado.",
	"Ellipse": "Elipse",
	"Draws a filled ellipse.": "Desenha uma elipse preenchida.",
	"Makes the current selection either opaque or transparent.": "Torna a seleção atual opaca ou transparente.",
	"Creates a new color.": "Cria uma nova cor.",
	"Uses a previously saved palette of colors.": "Utiliza a paleta de cores salva previamente.",
	"Saves the current palette of colors to a file.": "Salva a paleta de cores atual em um arquivo.",
	"You must save the file before choosing it as Wallpaper.": "Você deve salvar o arquivo antes de defini-lo como papel de parede.",
	"The selection is now larger than the bitmap.": "A seleção é agora maior do que o bitmap.",
	"Would you like the bitmap enlarged?": "Deseja aumentar o bitmap?",
	"The image in the clipboard is larger than the bitmap.": "A imagem na área de transferência é maior do que o bitmap.",
	"The file is not in the correct format.": "O arquivo não está no formato correto.",
	"Not enough room to paste text.": "Espaço insuficiente para colar o texto.",
	"Enlarge the text area and try again.": "Aumente a área de texto e tente novamente.",
	"Places the text.": "Posiciona o texto."
});
