//
// NOTE: This is a generated file! Don't edit it directly.
// Eventually community translation will be set up on some translation platform.
// 
// Generated with: npm run update-localization
//
loaded_localizations("sk", {
	"Attributes": "Atribúty",
	"&Width:": "Ší&rka:",
	"Width:": "Šírka:",
	"&Height:": "&Výška:",
	"Height:": "Výška:",
	"Units": "Jednotky",
	"&Inches": "p&alce",
	"Inches": "palce",
	"C&m": "c&m",
	"Cm": "cm",
	"&Pixels": "pi&xely",
	"Pixels": "pixely",
	"Colors": "Farby",
	"&Black and white": "Čierno&bielo",
	"Black and white": "Čiernobielo",
	"Co&lors": "&Farebne",
	"Transparency": "Fólia",
	"Use &Transparent background color": "P&oužiť farebné pozadie",
	"Use Transparent background color": "Použiť farebné pozadie",
	"Select &Color": "V&ybrať farbu",
	"Select Color": "Vybrať farbu",
	"Cancel": "Zrušiť",
	"&Default": "&Predvolené",
	"Default": "Predvolené",
	"Custom Zoom": "Vlastná mierka",
	"Current zoom:": "Aktuálna mierka:",
	"Zoom to": "Mierka",
	"Flip and Rotate": "Prevrátiť a otočiť",
	"Flip or rotate": "Prevrátiť alebo otočiť",
	"&Flip horizontal": "P&revrátiť vodorovne",
	"Flip horizontal": "Prevrátiť vodorovne",
	"Flip &vertical": "Prevrátiť &zvislo",
	"Flip vertical": "Prevrátiť zvislo",
	"&Rotate by angle": "&Otočiť o uhol",
	"Rotate by angle": "Otočiť o uhol",
	"Stretch and Skew": "Roztiahnutie alebo skosenie",
	"Stretch": "Roztiahnuť",
	"&Horizontal:": "&Vodorovne:",
	"Horizontal:": "Vodorovne:",
	"&Vertical:": "&Zvislo:",
	"Vertical:": "Zvislo:",
	"Skew": "Skosiť",
	"H&orizontal:": "Vo&dorovne:",
	"Degrees": "stupňov",
	"V&ertical:": "Zvi&slo:",
	"Color Table": "Tabuľka farieb",
	"New": "Nový",
	"&New ": "&Nový ",
	"New ": "Nový ",
	"&Help": "&Pomocník",
	"Help": "Pomocník",
	"Printing": "Prebieha tlač",
	"on the": "na",
	"&Print": "&Tlačiť",
	"Print": "Tlačiť",
	"&Next Page": "N&asled.",
	"Next Page": "Nasled.",
	"Pre&v Page": "&Predch.",
	"Prev Page": "Predch.",
	"Zoom &In": "P&riblížiť",
	"Zoom In": "Priblížiť",
	"Zoom &Out": "&Vzdialiť",
	"Zoom Out": "Vzdialiť",
	"&Close": "&Zavrieť",
	"Close": "Zavrieť",
	"Grid Settings": "Nastavenie mriežky",
	"&Pixel Grid": "Mriežka pi&xelov",
	"Pixel Grid": "Mriežka pixelov",
	"&Tile Grid": "&Mriežka",
	"Tile Grid": "Mriežka",
	"pixels": "pixelov",
	"H&eight:": "&Výška:",
	"Undo": "Späť",
	"Cut": "Vystrihnúť",
	"Copy": "Kopírovať",
	"Paste": "Prilepiť",
	"Clear Selection": "Vymazať výber",
	"Select All": "Vybrať všetko",
	"Text Toolbar": "Panel písma",
	"Selection": "Výber",
	"Cu&t": "&Vystrihnúť",
	"&Copy": "&Kopírovať",
	"&Paste": "&Prilepiť",
	"C&lear Selection": "Vy&mazať výber",
	"Select &All": "Vy&brať všetko",
	"C&opy To": "K&opírovať do",
	"Copy To": "Kopírovať do",
	"Paste &From": "Pri&lepiť z",
	"Paste From": "Prilepiť z",
	"Flip/&Rotate": "Prev&rátiť alebo otočiť",
	"Flip/Rotate": "Prevrátiť alebo otočiť",
	"&Stretch/Skew": "Roztiahnuť alebo &skosiť",
	"Stretch/Skew": "Roztiahnuť alebo skosiť",
	"&Invert Colors": "&Invertovať farby",
	"Invert Colors": "Invertovať farby",
	"Thumbnail": "Miniatúra",
	"&File": "&Súbor",
	"File": "Súbor",
	"&New": "&Nový",
	"&Open": "&Otvoriť",
	"Open": "Otvoriť",
	"&Save": "&Uložiť",
	"Save": "Uložiť",
	"Save &As": "Uložiť &ako",
	"Save As": "Uložiť ako",
	"Print Pre&view": "U&kážka pred tlačou",
	"Print Preview": "Ukážka pred tlačou",
	"Page Se&tup": "Nasta&venie strany",
	"Page Setup": "Nastavenie strany",
	"S&end": "O&doslať",
	"Send": "Odoslať",
	"Set As &Wallpaper (Tiled)": "Nastaviť ako tap&etu (dlaždice)",
	"Set As Wallpaper (Tiled)": "Nastaviť ako tapetu (dlaždice)",
	"Set As Wa&llpaper (Centered)": "Nastaviť ako ta&petu (centrovať)",
	"Set As Wallpaper (Centered)": "Nastaviť ako tapetu (centrovať)",
	"Recent File": "Naposledy otvorený súbor",
	"E&xit": "&Skončiť",
	"Exit": "Skončiť",
	"&Edit": "Úpr&avy",
	"Edit": "Úpravy",
	"&Undo": "&Späť",
	"&Repeat": "&Opakovať",
	"Repeat": "Opakovať",
	"&View": "&Zobraziť",
	"View": "Zobraziť",
	"&Tool Box": "Panel s &nástrojmi",
	"Tool Box": "Panel s nástrojmi",
	"&Color Box": "Panel &farieb",
	"Color Box": "Panel farieb",
	"Ctrl+L": "Ctrl+A",
	"&Status Bar": "&Stavový riadok",
	"Status Bar": "Stavový riadok",
	"T&ext Toolbar": "Panel &písma",
	"&Zoom": "&Lupa",
	"Zoom": "Lupa",
	"&Normal Size": "&Normálna veľkosť",
	"Normal Size": "Normálna veľkosť",
	"&Large Size": "&Zväčšená veľkosť",
	"Large Size": "Zväčšená veľkosť",
	"C&ustom": "&Vlastná",
	"Custom": "Vlastná",
	"Show &Grid": "Zobraziť m&riežku",
	"Show Grid": "Zobraziť mriežku",
	"Show T&humbnail": "Zobraziť &miniatúru",
	"Show Thumbnail": "Zobraziť miniatúru",
	"&View Bitmap": "&Celá obrazovka",
	"View Bitmap": "Celá obrazovka",
	"&Image": "&Obrázok",
	"Image": "Obrázok",
	"&Flip/Rotate": "Prev&rátiť alebo otočiť",
	"&Attributes": "&Atribúty",
	"&Clear Image": "Vy&mazať obrázok",
	"Clear Image": "Vymazať obrázok",
	"&Draw Opaque": "&Kresliť nepriesvitne",
	"Draw Opaque": "Kresliť nepriesvitne",
	"&Colors": "&Farby",
	"&Edit Colors": "Upraviť &farby",
	"Edit Colors": "Upraviť farby",
	"&Help Topics": "&Témy Pomocníka",
	"Help Topics": "Témy Pomocníka",
	"&About Paint": "Č&o je Skicár",
	"About Paint": "Čo je Skicár",
	"&Update": "&Aktualizovať",
	"Update": "Aktualizovať",
	"Save Copy &As": "&Uložiť kópiu ako",
	"Save Copy As": "Uložiť kópiu ako",
	"Paint": "Skicár",
	"untitled": "Bez_názvu",
	"Bitmap Image": "Bitová mapa",
	"Bitmap Files (*.bmp)": "Súbory bitových máp (*.bmp)",
	"Paint.Picture": "Obrázok.Skicár",
	"PCX Files": "Súbory PCX",
	"Icon Files": "Súbory ikon",
	"Monochrome Bitmap (*.bmp;*.dib)": "Čiernobiela bitová mapa (*.bmp;*.dib)",
	"16 Color Bitmap (*.bmp;*.dib)": "16-farebná bitová mapa (*.bmp;*.dib)",
	"256 Color Bitmap (*.bmp;*.dib)": "256-farebná bitová mapa (*.bmp;*.dib)",
	"Paint cannot open this file.": "Program Skicár nemôže otvoriť tento súbor.",
	"Paint cannot read this file.": "Program Skicár nemôže prečítať tento súbor.",
	"This file is read-only.": "Tento súbor je iba na čítanie.",
	"To save your changes, use a different filename.": "Ak chcete zmeny uložiť, zadajte iný názov súboru.",
	"This file is already open.": "Tento súbor je už otvorený.",
	"This is not a valid .PCS file.": "Toto nie je platný súbor typu .PCS.",
	"This file is open for editing and cannot be overwritten.": "Súbor je otvorený pre úpravy a nedá sa prepísať.",
	"Use a different filename to save your changes.": "Ak chcete zmeny uložiť, zadajte iný názov súboru.",
	"This is not a valid bitmap file, or its format is not currently supported.": "Toto nie je platný súbor bitovej mapy alebo jeho formát nie je momentálne podporovaný.",
	"This is not a valid icon.": "Toto nie je platná ikona.",
	"This is not a valid cursor.": "Toto nie je platný kurzor.",
	"Save was interrupted, so your file has not been saved.": "Ukladanie bolo prerušené, súbor nie je uložený.",
	"You cannot save to a read-only file.": "Súbor, určený iba na čítanie, sa nedá uložiť.",
	"Use a different file name.": "Zadajte iný názov súboru.",
	"This file is already in use.": "Tento súbor sa už používa.",
	"Close the program, and then try again.": "Skončite program a pokúste sa znova.",
	"Paint cannot save this file.": "Program Skicár nemôže tento súbor uložiť.",
	"Paint cannot save to the same filename with a different file type.": "Program Skicár nemôže uložiť pod rovnakým názvom súbor iného typu.",
	"The grid spacing must be an integer between %d and %d.": "Hustota mriežky sa zadáva ako celé číslo v intervale %d až %d.",
	"There is not enough memory or resources to complete operation.": "Na dokončenie operácie nie je dostatok pamäte alebo prostriedkov.",
	"Close some programs, and then try again.": "Skončite niektoré programy a pokúste sa znova.",
	"Low on memory or resources.": "Nedostatok pamäte alebo prostriedkov.",
	"Group error.": "Chyba skupiny.",
	"Paint was unable to print your document. Please make sure you have sufficient disk space and that your printer is working correctly.": "Skicár nemôže vytlačiť dokument. Skontrolujte, či je dostatok miesta na disku a či tlačiareň pracuje správne.",
	"Saving into this format may cause some loss of color information.": "Uloženie v tomto formáte môže spôsobiť stratu informácie o farbách.",
	"Do you want to continue?": " Chcete pokračovať?",
	"Converting to black and white cannot be undone.  This action affects the current file and may cause some loss of color information.": "Prevod na čiernobiely obrázok sa nedá vrátiť späť. Táto akcia upraví súbor a môže spôsobiť stratu informácií o farbách.",
	"Bitmaps must be greater than one pixel on a side.": "Veľkosť strany bitovej mapy musí byť väčšia než jeden pixel.",
	"Generic error.": "Všeobecná chyba.",
	"File not found.": "Súbor sa nenašiel.",
	"Bad path.": "Chybná cesta.",
	"Too many open files.": "Príliš veľa otvorených súborov.",
	"Access denied.": "Prístup bol odmietnutý.",
	"Invalid file.": "Neplatný súbor.",
	"Remove current folder.": "Odstrániť aktuálny priečinok.",
	"Folder full.": "Priečinok je plný.",
	"Bad seek.": "Chybné vystavenie.",
	"Hard IO error.": "Vážna IO chyba.",
	"Sharing violation.": "Poručenie zdieľania.",
	"Lock violation.": "Uzamknutie narušené.",
	"Disk full.": "Disk je plný.",
	"End of file.": "Koniec súboru.",
	"Error getting the Clipboard Data!": "Chyba počas získavania údajov zo Schránky.",
	"No Printer Found @ page setup": "Chýba tlačiareň pre nastavenie strany",
	"24-bit Bitmap (*.bmp;*.dib)": "24-bitová mapa (*.bmp;*.dib)",
	"All Files": "Všetky súbory",
	"Palette|*.pal|": "Paleta|*.pal|",
	"untitled.pal": "Obrázok.pal",
	"OLE 2.0 was unable to start.": "OLE 2.0 sa nedá spustiť.",
	"Make sure that you are using the correct version of the OLE libraries.": "Presvedčte sa, či používate správnu verziu knižníc OLE.",
	"Resets the text be without any attributes.": "Zruší všetky atribúty textu. ",
	"Sets or clears the text bold attribute.": "Zapne alebo vypne tučné písmo.",
	"Sets or clears the text italic attribute.": "Zapne alebo vypne kurzívu.",
	"Selects the font used by the text.": "Vyberie písmo pre písanie textu.",
	"Selects the point size of the text.": "Vyberie výšku textu v bodoch.",
	"Sets or clears the text underline attribute.": "Zapne alebo vypne podčiarknutie písma.",
	"Shows or hides the tooltips.": "Zobrazí alebo skryje popisy tlačidiel.",
	"Show Paint Help.": "Zobrazí Pomocníka programu Skicár.",
	"Sends a picture by using mail or fax.": "Odošle obrázok poštou alebo faxom.",
	"Copies the selection to a file.": "Skopíruje vybratú časť do súboru.",
	"Pastes a file into the selection.": "Prilepí súbor do vybranej časti.",
	"Zooms the picture to 100%.": "Nastaví mierku na 100%.",
	"Zooms the picture to 400%.": "Nastaví mierku na 400%.",
	"Zooms the picture.": "Priblíži obrázok.",
	"Displays the entire picture.": "Zobrazí celý obrázok.",
	"Shows or hides the thumbnail view of the picture.": "Zobrazí alebo skryje miniatúru obrázka.",
	"Shows or hides the grid.": "Zobrazí alebo skryje mriežku.",
	"Shows or hides the text toolbar.": "Zobrazí alebo skryje panel písma.",
	"Flips or rotates the picture or a selection.": "Prevráti alebo otočí obrázok, alebo vybranú časť.",
	"Stretches or skews the picture or a selection.": "Roztiahne alebo skosí obrázok, alebo vybranú časť.",
	"Inverts the colors of the picture or a selection.": "Invertuje farby obrázka alebo vybranej časti.",
	"Changes the attributes of the picture.": "Zmení atribúty obrázka.",
	"Clears the picture or selection.": "Vymaže obrázok alebo vybranú časť.",
	"The font size must be a numeric value.": "Veľkosť písma musí byť číselná hodnota.",
	"Contains commands for working with the selected item(s).": "Obsahuje príkazy pre prácu s vybranými položkami.",
	"Contains commands for selecting and transferring items.": "Obsahuje príkazy pre výber a prenos jednotiek.",
	"Contains commands for customizing this window.": "Obsahuje príkazy pre prispôsobenie zobrazenia okna.",
	"Contains commands for manipulating pictures and setting attributes.": "Obsahuje príkazy pre manipuláciu s obrázkom a pre nastavenie atribútov.",
	"Contains commands for using custom colors and drawing options.": "Obsahuje príkazy pre prácu s farbami a pre nastavenie možností maľovania.",
	"Contains commands for displaying Help for and information about Paint.": "Obsahuje príkazy pre zobrazenie Pomocníka a informácií o programe Skicár.",
	"Cannot save file.": "Súbor nemožno uložiť.",
	"Error removing temporary file.": "Chyba pri odstraňovaní dočasného súboru.",
	"Get Colors": "Prevziať farby",
	"Save Colors": "Uložiť farby",
	"File last saved:": "Posledné uloženie súboru: Nie je k dispozícii",
	"Size on disk:": "Veľkosť disku: Nie je k dispozícii",
	"%s bytes": "%s bajtov",
	"Painting": "Maľovať",
	"Fonts": "Písma",
	"Tools": "Nástroje",
	"All Picture Files": "Všetky súbory obrázkov",
	"For Help, click Help Topics on the Help Menu.": "Pomocníka získate kliknutím na položku Témy Pomocníka z ponuky Pomocník.",
	"Select an area on which to get Help.": "Kliknite na oblasť obrazovky, ku ktorej chcete radu od Pomocníka.",
	"%1 in %2": "%1 v %2",
	"%1 - %2": "%2 - %1",
	"Creates a new document.": "Vytvorí nový dokument.",
	"Opens an existing document.": "Otvorí existujúci dokument.",
	"Closes the active document.": "Zavrie aktuálny dokument.",
	"Saves the active document.": "Uloží aktuálny dokument.",
	"Saves the active document with a new name.": "Uloží aktuálny dokument pod novým názvom.",
	"Changes the page layout.": "Zmení vzhľad tlačovej strany.",
	"Specifies the default printer setup.": "Nastaví predvolenú tlačiareň. ",
	"Prints the active document and sets printing options.": "Vytlačí aktívny dokument a nastaví spôsob tlače.",
	"Displays full pages.": "Zobrazí celé strany.",
	"Opens this document.": "Otvorí tento dokument.",
	"Deletes the selection.": "Odstráni výber.",
	"Erases everything.": "Vymaže všetko.",
	"Copies the selection and puts it on the Clipboard.": "Skopíruje výber do Schránky.",
	"Cuts the selection and puts it on the Clipboard.": "Vystrihne výber a vloží ho do Schránky.",
	"Finds the specified text.": "Hľadá zadaný text.",
	"Inserts the contents of the Clipboard.": "Vloží obsah Schránky.",
	"Repeats the last action.": "Zopakuje predchádzajúcu akciu.",
	"Replaces specific text with different text.": "Nahradí zadaný text iným textom.",
	"Selects everything.": "Vyberie všetko.",
	"Undoes the last action.": "Vráti späť predchádzajúcu akciu.",
	"Redoes the previously undone action.": "Znova vykoná vrátenú akciu.",
	"Displays program information, version number, and copyright.": "Zobrazí informácie o programe, verzii a autorských právach.",
	"Quits Paint.": "Skončí program Skicár.",
	"Opens Paint Help.": "Otvorí Pomocníka programu Skicár.",
	"Displays instructions about how to use Help.": "Zobrazí návod k práci s Pomocníkom.",
	"Displays Help for areas you click on.": "Zobrazí Pomocníka pre oblasť, na ktorú ste klikli.",
	"Displays Help for the current task or command.": "Zobrazí Pomocníka pre túto úlohu alebo príkaz.",
	"Centers this bitmap as the desktop wallpaper.": "Použije vycentrovaný obrázok ako tapetu pracovnej plochy.",
	"Tiles this bitmap as the desktop wallpaper.": "Použije obrázok ako tapetu na celú pracovnú plochu.",
	"Sends the selection using mail or fax.": "Odošle výber poštou alebo faxom.",
	"Prints the selection.": "Vytlačí výber.",
	"Shows or hides the thumbnail.": "Zobrazí alebo skryje miniatúru.",
	"Shows Paint Help.": "Zobrazí Pomocníka programu Skicár.",
	"Shows or hides the status bar.": "Zobrazí alebo skryje stavový riadok.",
	"Shows or hides the tool box.": "Zobrazí alebo skryje panel s nástrojmi.",
	"Shows or hides the color box.": "Zobrazí alebo skryje panel farieb.",
	"Only a Far East font can be used for vertical editing.": "Pre zvislé písanie sa dajú použiť len písma ďalekého východu.",
	"Changes the window size.": "Zmení veľkosť okna.",
	"Changes the window position.": "Zmení polohu okna.",
	"Reduces the window to an icon.": "Zmenší okno na ikonu.",
	"Enlarges the window to full size.": "Zväčší okno na plnú veľkosť.",
	"Switches to the next document window.": "Prepne do nasledujúceho okna dokumentu.",
	"Switches to the previous document window.": "Prepne do predchádzajúceho okna dokumentu.",
	"Closes the active window and asks if you want to save changes.": "Zatvorí aktívne okno a spýta sa, či sa majú zmeny uložiť.",
	"Restores the window to normal size.": "Obnoví normálnu veľkosť okna.",
	"Activates the task list.": "Aktivuje zoznam úloh.",
	"All Files (*.*)": "Všetky súbory (*.*)",
	"Untitled": "Bez názvu",
	"an unnamed file": "nepomenovaný súbor",
	"&Hide": "&Skryť",
	"Hide": "Skryť",
	"No error message is available.": "Žiadne chybové hlásenie nie je k dispozícii.",
	"An unsupported operation was attempted.": "Pokus o nepodporovanú operáciu.",
	"A required resource was unavailable.": "Požadovaný prostriedok nebol k dispozícii.",
	"Out of memory.": "Nedostatok pamäte.",
	"An unknown error has occurred.": "Vyskytla sa neznáma chyba.",
	"on %1": "na %1",
	"&One Page": "&Jedna strana",
	"One Page": "Jedna strana",
	"&Two Page": "&Dve strany",
	"Two Page": "Dve strany",
	"Page %u": "Strana %u",
	"Pages %u-%u": "Strany %u-%u",
	"Printer Files (*.prn)|*.prn|All Files (*.*)|*.*||": "Súbory tlačiarne (*.prn)|*.prn|Všetky súbory (*.*)|*.*||",
	"Print to File": "Tlačiť do súboru",
	"to %1": "do %1",
	"&Update %1": "&Aktualizovať %1",
	"Update %1": "Aktualizovať %1",
	"E&xit && Return to %1": "&Skončiť a vrátiť sa k %1",
	"Exit && Return to %1": "Skončiť a vrátiť sa k %1",
	"Linked %s": "Prepojený %s",
	"Unknown Type": "Neznámy typ",
	"Invalid filename.": "Neplatný názov súboru.",
	"Failed to open document.": "Dokument sa nepodarilo otvoriť.",
	"Failed to save document.": "Dokument sa nepodarilo uložiť.",
	"Save changes to %1?": "Uložiť zmeny do súboru %1?",
	"Failed to create empty document.": "Prázdny dokument sa nepodarilo vytvoriť.",
	"The file is too large to open.": "Tento súbor sa nedá otvoriť. Je príliš veľký.",
	"Could not start print job.": "Tlačovú úlohu sa nepodarilo spustiť.",
	"Failed to launch help.": "Pomocník sa nespustil.",
	"Internal application error.": "Vnútorná chyba aplikácie.",
	"Command failed.": "Príkaz sa nevykonal.",
	"Insufficient memory to perform operation.": "Nedostatok pamäte na vykonanie operácie.",
	"System registry entries have been removed and the INI file (if any) was deleted.": "Položky v databáze Registry a súbor INI (ak existoval) boli odstránené.",
	"Not all of the system registry entries (or INI file) were removed.": "Niektoré položky databázy Registry (alebo súbor INI) neboli odstránené.",
	"This program requires the file %s, which was not found on this system.": "Program potrebuje súbor %s, ktorý sa v systéme nenašiel.",
	"This program is linked to the missing export %s in the file %s. This machine may have an incompatible version of %s.": "Program je pripojený na chýbajúci export %s súboru %s. Počítač má pravdepodobne nekompatibilnú verziu systému %s.",
	"Please enter an integer.": "Zadajte celé číslo.",
	"Please enter a number.": "Zadajte číslo.",
	"Please enter an integer between %1 and %2.": "Zadajte celé číslo od %1 do %2.",
	"Please enter a number between %1 and %2.": "Zadajte číslo od %1 do %2.",
	"Please enter no more than %1 characters.": "Zadajte maximálne %1 znakov.",
	"Please select a button.": "Kliknite na tlačidlo.",
	"Please enter an integer between 0 and 255.": "Zadajte celé číslo od 0 do 255.",
	"Please enter a positive integer.": "Zadajte celé kladné číslo.",
	"Please enter a date and/or time.": "Zadajte dátum alebo čas.",
	"Please enter a currency.": "Zadajte menu.",
	"Unexpected file format.": "Neočakávaný formát súboru.",
	"Cannot find this file.": "Súbor sa nenašiel.",
	"Please verify that the correct path and file name are given.": "Skontrolujte, či bola zadaná správna cesta a názov súboru.",
	"Destination disk drive is full.": "Cieľová disková jednotka je plná.",
	"Unable to read from %1, it is opened by someone else.": "Zo súboru %1 sa nedá čítať, pretože je už otvorený.",
	"Unable to write to %1, it is read-only or opened by someone else.": "Do súboru %1 sa nedá zapisovať, pretože je iba na čítanie alebo otvorený iným používateľom.",
	"An unexpected error occurred while reading %1.": "Počas čítania %1 sa vyskytla neočakávaná chyba.",
	"An unexpected error occurred while writing %1.": "Počas zapisovania %1 sa vyskytla neočakávaná chyba.",
	"Unable to register document.": "Dokument sa nedá zaregistrovať.",
	"The document may already be open.": "Už je pravdepodobne otvorený.",
	"Update %1 before proceeding?": "Aktualizovať %1 pred pokračovaním?",
	"Could not update client.": "Klient sa nedá aktualizovať.",
	"Failed to register. ActiveX features may not work properly.": "Registrácia nebola úspešná. Funkcie ActiveX asi nebudú pracovať správne.",
	"Failed to update the system registry.": "Databáza Registry sa neaktualizovala.",
	"Please try using REGEDIT.": "Pokúste sa použiť program Regedit.",
	"Unable to read write-only property.": "Nie je možné čítať vlastnosť, ktorá je iba na zápis.",
	"Unable to write read-only property.": "Nie je možné zapísať vlastnosť, ktorá je iba na čítanie.",
	"Unable to load mail system support.": "Systémová podpora elektronickej pošty sa nedá načítať.",
	"Mail system DLL is invalid.": "Systémová DLL pošty nie je platná.",
	"Send Mail failed to send message.": "Odoslanie správy nebolo úspešné.",
	"No error occurred.": "Nevyskytla sa žiadna chyba.",
	"An unknown error occurred while accessing %1.": "Počas prístupu na %1 sa vyskytla neznáma chyba.",
	"%1 was not found.": "%1 sa nenašiel.",
	"%1 contains an invalid path.": "%1 obsahuje neplatnú cestu.",
	"%1 could not be opened because there are too many open files.": "%1 sa nedá otvoriť, pretože je otvorených príliš veľa súborov.",
	"Access to %1 was denied.": "Prístup k %1 bol odmietnutý.",
	"An invalid file handle was associated with %1.": "K %1 bol priradený neplatný popisovač súboru.",
	"%1 could not be removed because it is the current directory.": "%1 sa nedá odstrániť, pretože je to aktuálny adresár.",
	"%1 could not be created because the directory is full.": "%1 sa nedá vytvoriť, pretože adresár je plný.",
	"Seek failed on %1": "Hľadanie zlyhalo na %1",
	"A hardware I/O error was reported while accessing %1.": "Počas prístupu k %1 bola hlásená vstupno-výstupná chyba hardvéru.",
	"A sharing violation occurred while accessing %1.": "Počas prístupu k %1 sa vyskytlo porušenie zdieľania.",
	"A locking violation occurred while accessing %1.": "Počas prístupu k %1 sa vyskytlo porušenie uzamknutia.",
	"Disk full while accessing %1.": "Disk sa zaplnil počas prístupu na %1.",
	"An attempt was made to access %1 past its end.": "Pokus o prístup k %1 po jeho skončení.",
	"An attempt was made to write to the reading %1.": "Prebehol pokus o zápis do %1, ktorý sa načítava.",
	"An attempt was made to read from the writing %1.": "Prebehol pokus o čítanie %1, do ktorého sa zapisuje.",
	"%1 has a bad format.": "%1 má nesprávny formát.",
	"%1 contained an unexpected object.": "%1 obsahuje neočakávaný objekt.",
	"%1 contains an incorrect schema.": "%1 obsahuje nesprávnu schému.",
	"Selects a rectangular part of the picture to move, copy, or edit.": "Vyberie pravouhlú časť obrázka, ktorá sa bude premiestňovať, kopírovať, alebo upravovať.",
	"Select": "Výber",
	"Selects a free-form part of the picture to move, copy, or edit.": "Ohraničením vyberie časť obrázka, ktorá sa bude premiestňovať, kopírovať, alebo upravovať.",
	"Free-Form Select": "Laso",
	"Inserts text into the picture.": "Vloží text do obrázka.",
	"Fills an area with the current drawing color.": "Vyplní oblasť aktuálnou farbou pera.",
	"Fill With Color": "Farebná výplň",
	"Draws a straight line with the selected line width.": "Kreslí čiaru vybratej hrúbky.",
	"Line": "Čiara",
	"Draws using an airbrush of the selected size.": "Kreslí sprejom vybratej veľkosti.",
	"Airbrush": "Sprej",
	"Draws a curved line with the selected line width.": "Kreslí krivku vybratej hrúbky.",
	"Curve": "Krivka",
	"Draws a polygon with the selected fill style.": "Kreslí mnohouholník s vybratou výplňou.",
	"Polygon": "Mnohouholník",
	"Draws a rounded rectangle with the selected fill style.": "Kreslí zaoblený obdĺžnik s vybratou výplňou.",
	"Rounded Rectangle": "Zaoblený obdĺžnik",
	"Draws a free-form line one pixel wide.": "Kreslí od ruky čiaru hrúbky jedného bodu.",
	"Pencil": "Ceruzka",
	"Erases a portion of the picture, using the selected eraser shape.": "Vymaže časť obrázka vybratým tvarom gumy.",
	"Eraser/Color Eraser": "Guma a guma farieb",
	"Changes the magnification.": "Zmení mierku zobrazenia.",
	"Magnifier": "Lupa",
	"Picks up a color from the picture for drawing.": "Vyberie farbu z obrázka do pera.",
	"Pick Color": "Kvapkadlo",
	"Draws using a brush with the selected shape and size.": "Kreslí štetcom vybratého tvaru a hrúbky.",
	"Brush": "Štetec",
	"Draws a rectangle with the selected fill style.": "Kreslí obdĺžnik s vybratou výplňou.",
	"Rectangle": "Obdĺžnik",
	"Draws a filled rectangle.": "Kreslí plný obdĺžnik.",
	"Draws an ellipse with the selected fill style.": "Kreslí elipsu s vybratou výplňou.",
	"Ellipse": "Elipsa",
	"Draws a filled ellipse.": "Kreslí plnú elipsu.",
	"Makes the current selection either opaque or transparent.": "Urobí aktuálny výber nepriehľadným, alebo priehľadným.",
	"Creates a new color.": "Vytvorí novú farbu.",
	"Uses a previously saved palette of colors.": "Použije už uloženú paletu farieb.",
	"Saves the current palette of colors to a file.": "Uloží túto paletu farieb do súboru.",
	"You must save the file before choosing it as Wallpaper.": "Predtým, než obrázok použijete ako tapetu, musíte ho uložiť.",
	"The selection is now larger than the bitmap.": "Vybraná časť je teraz väčšia ako bitová mapa.",
	"Would you like the bitmap enlarged?": "Má sa bitová mapa zväčšiť?",
	"The image in the clipboard is larger than the bitmap.": "Obrázok v Schránke je väčší ako bitová mapa.",
	"The file is not in the correct format.": "Formát súboru nie je správny.",
	"Not enough room to paste text.": "Na prilepenie textu nie je dostatok miesta.",
	"Enlarge the text area and try again.": "Zväčšite oblasť pre text a pokúste sa znova.",
	"Places the text.": "Umiestni text."
});
