//
// NOTE: This is a generated file! Don't edit it directly.
// Eventually community translation will be set up on some translation platform.
// 
// Generated with: npm run update-localization
//
loaded_localizations("el", {
	"Attributes": "Χαρακτηριστικά",
	"&Width:": "Π&λάτος:",
	"Width:": "Πλάτος:",
	"&Height:": "Ύ&ψος:",
	"Height:": "Ύψος:",
	"Units": "Μονάδες",
	"&Inches": "Ί&ντσες",
	"Inches": "Ίντσες",
	"C&m": "&Εκατοστά",
	"Cm": "Εκατοστά",
	"&Pixels": "Pi&χel",
	"Pixels": "Piχel",
	"Colors": "Χρώματα",
	"&Black and white": "Ασπρό&μαυρη",
	"Black and white": "Ασπρόμαυρη",
	"Co&lors": "Έ&γχρωμη",
	"Transparency": "Διαφάνεια",
	"Use &Transparent background color": "Χρήση &διαφανούς χρώματος φόντου",
	"Use Transparent background color": "Χρήση διαφανούς χρώματος φόντου",
	"Select &Color": "Επ&ιλογή χρώματος",
	"Select Color": "Επιλογή χρώματος",
	"OK": "ΟΚ",
	"Cancel": "Άκυρο",
	"&Default": "&Προεπιλογή",
	"Default": "Προεπιλογή",
	"Custom Zoom": "Προσαρμοσμένο ζουμ",
	"Current zoom:": "Τρέχον ζουμ:",
	"Zoom to": "Ζουμ κατά",
	"Flip and Rotate": "Αναστροφή και περιστροφή",
	"Flip or rotate": "Αναστροφή ή περιστροφή",
	"&Flip horizontal": "Ορι&ζόντια αναστροφή",
	"Flip horizontal": "Οριζόντια αναστροφή",
	"Flip &vertical": "&Κατακόρυφη αναστροφή",
	"Flip vertical": "Κατακόρυφη αναστροφή",
	"&Rotate by angle": "&Περιστροφή κατά γωνία",
	"Rotate by angle": "Περιστροφή κατά γωνία",
	"Stretch and Skew": "Αυξομείωση και παραμόρφωση",
	"Stretch": "Αυξομείωση",
	"&Horizontal:": "&Οριζόντια:",
	"Horizontal:": "Οριζόντια:",
	"&Vertical:": "&Κάθετη:",
	"Vertical:": "Κάθετη:",
	"Skew": "Παραμόρφωση",
	"H&orizontal:": "Οριζό&ντια:",
	"Degrees": "Μοίρες",
	"V&ertical:": "Κάθ&ετη:",
	"Color Table": "Πίνακας χρωμάτων",
	"New": "Δημιουργία",
	"&New ": "&Δημιουργία ",
	"New ": "Δημιουργία ",
	"&Help": "&Βοήθεια",
	"Help": "Βοήθεια",
	"Printing": "Γίνεται εκτύπωση",
	"on the": "στο",
	"&Print": "Εκ&τύπωση",
	"Print": "Εκτύπωση",
	"&Next Page": "&Επόμενη σελίδα",
	"Next Page": "Επόμενη σελίδα",
	"Pre&v Page": "&Προηγούμενη σελίδα",
	"Prev Page": "Προηγούμενη σελίδα",
	"Zoom &In": "&Μεγέθυνση",
	"Zoom In": "Μεγέθυνση",
	"Zoom &Out": "&Σμίκρυνση",
	"Zoom Out": "Σμίκρυνση",
	"&Close": "&Κλείσιμο",
	"Close": "Κλείσιμο",
	"Grid Settings": "Ρυθμίσεις πλέγματος",
	"&Pixel Grid": "Π&λέγμα pixel",
	"Pixel Grid": "Πλέγμα pixel",
	"&Tile Grid": "Παρά&θεση στο πλέγμα",
	"Tile Grid": "Παράθεση στο πλέγμα",
	"pixels": "pixel",
	"H&eight:": "Ύ&ψος:",
	"Text": "Κείμενο",
	"Undo": "Αναίρεση",
	"Cut": "Αποκοπή",
	"Copy": "Αντιγραφή",
	"Paste": "Επικόλληση",
	"Clear Selection": "Καθαρισμός επιλεγμένης περιοχής",
	"Select All": "Επιλογή όλων",
	"Text Toolbar": "Γραμμή εργαλείων κειμένου",
	"Selection": "Επιλεγμένη περιοχή",
	"Cu&t": "Απο&κοπή",
	"&Copy": "Αντι&γραφή",
	"&Paste": "&Επικόλληση",
	"C&lear Selection": "Κα&θαρισμός επιλεγμένης περιοχής",
	"Select &All": "Επι&λογή όλων",
	"C&opy To": "Αντιγραφή &στο",
	"Copy To": "Αντιγραφή στο",
	"Paste &From": "Ε&πικόλληση από",
	"Paste From": "Επικόλληση από",
	"Flip/&Rotate": "Αναστρο&φή/περιστροφή",
	"Flip/Rotate": "Αναστροφή/περιστροφή",
	"&Stretch/Skew": "Αυ&ξομείωση/παραμόρφωση",
	"Stretch/Skew": "Αυξομείωση/παραμόρφωση",
	"&Invert Colors": "Α&ρνητικά χρώματα",
	"Invert Colors": "Αρνητικά χρώματα",
	"Thumbnail": "Μικρογραφία",
	"&File": "&Αρχείο",
	"File": "Αρχείο",
	"&New": "&Δημιουργία",
	"&Open": "Άν&οιγμα",
	"Open": "Άνοιγμα",
	"&Save": "&Αποθήκευση",
	"Save": "Αποθήκευση",
	"Save &As": "Αποθήκευση &ως",
	"Save As": "Αποθήκευση ως",
	"Print Pre&view": "&Προεπισκόπηση εκτύπωσης",
	"Print Preview": "Προεπισκόπηση εκτύπωσης",
	"Page Se&tup": "Διαμό&ρφωση σελίδας",
	"Page Setup": "Διαμόρφωση σελίδας",
	"S&end": "Αποστο&λή",
	"Send": "Αποστολή",
	"Set As &Wallpaper (Tiled)": "Ορισμός ως &Ταπετσαρία (σε παράθεση)",
	"Set As Wallpaper (Tiled)": "Ορισμός ως Ταπετσαρία (σε παράθεση)",
	"Set As Wa&llpaper (Centered)": "Ορισμός ως Ταπετ&σαρία (στο κέντρο)",
	"Set As Wallpaper (Centered)": "Ορισμός ως Ταπετσαρία (στο κέντρο)",
	"Recent File": "Πρόσφατο αρχείο",
	"E&xit": "Έ&ξοδος",
	"Exit": "Έξοδος",
	"&Edit": "Επε&ξεργασία",
	"Edit": "Επεξεργασία",
	"&Undo": "&Αναίρεση",
	"&Repeat": "Επανάλη&ψη",
	"Repeat": "Επανάληψη",
	"&View": "Π&ροβολή",
	"View": "Προβολή",
	"&Tool Box": "&Εργαλειοθήκη",
	"Tool Box": "Εργαλειοθήκη",
	"&Color Box": "Πλαίσιο χρω&μάτων",
	"Color Box": "Πλαίσιο χρωμάτων",
	"&Status Bar": "&Γραμμή κατάστασης",
	"Status Bar": "Γραμμή κατάστασης",
	"T&ext Toolbar": "Γραμμή εργαλείων κειμέ&νου",
	"&Zoom": "&Ζουμ",
	"Zoom": "Ζουμ",
	"&Normal Size": "&Φυσικό μέγεθος",
	"Normal Size": "Φυσικό μέγεθος",
	"&Large Size": "&Μεγάλο μέγεθος",
	"Large Size": "Μεγάλο μέγεθος",
	"C&ustom": "Προ&σαρμογή",
	"Custom": "Προσαρμογή",
	"Show &Grid": "Εμφάνιση &πλέγματος",
	"Show Grid": "Εμφάνιση πλέγματος",
	"Show T&humbnail": "Εμφάνιση μι&κρογραφίας",
	"Show Thumbnail": "Εμφάνιση μικρογραφίας",
	"&View Bitmap": "&Προβολή bitmap",
	"View Bitmap": "Προβολή bitmap",
	"&Image": "Ει&κόνα",
	"Image": "Εικόνα",
	"&Flip/Rotate": "Ανασ&τροφή/περιστροφή",
	"&Attributes": "&Χαρακτηριστικά",
	"&Clear Image": "Κα&θαρισμός εικόνας",
	"Clear Image": "Καθαρισμός εικόνας",
	"Ctrl+Shft+N": "Ctrl+Shift+Ν",
	"&Draw Opaque": "&Αδιαφανής σχεδίαση",
	"Draw Opaque": "Αδιαφανής σχεδίαση",
	"&Colors": "&Χρώματα",
	"&Edit Colors": "&Επεξεργασία χρωμάτων",
	"Edit Colors": "Επεξεργασία χρωμάτων",
	"&Help Topics": "Θέματα στη &Βοήθεια",
	"Help Topics": "Θέματα στη Βοήθεια",
	"&About Paint": "&Πληροφορίες για τη Ζωγραφική",
	"About Paint": "Πληροφορίες για τη Ζωγραφική",
	"&Update": "&Ενημέρωση",
	"Update": "Ενημέρωση",
	"Save Copy &As": "Αποθήκευση αντι&γράφου ως",
	"Save Copy As": "Αποθήκευση αντιγράφου ως",
	"Paint": "Ζωγραφική",
	"untitled": "ανώνυμο",
	"Bitmap Image": "Εικόνα bitmap",
	"Bitmap Files (*.bmp)": "Αρχεία bitmap (*.bmp)",
	"Paint.Picture": "Ζωγραφική. Εικόνα",
	"PCX Files": "Αρχεία PCX",
	"Icon Files": "Αρχεία εικονιδίων",
	"Monochrome Bitmap (*.bmp;*.dib)": "Μονόχρωμο bitmap (*.bmp;*.dib)",
	"16 Color Bitmap (*.bmp;*.dib)": "Bitmap 16 χρωμάτων (*.bmp;*.dib)",
	"256 Color Bitmap (*.bmp;*.dib)": "Bitmap 256 χρωμάτων (*.bmp;*.dib)",
	"Paint cannot open this file.": "Δεν είναι δυνατό να ανοίξει η Ζωγραφική αυτό το αρχείο.",
	"Paint cannot read this file.": "Δεν είναι δυνατό να διαβάσει η Ζωγραφική αυτό το αρχείο.",
	"This file is read-only.": "Αυτό το αρχείο είναι μόνο για ανάγνωση.",
	"To save your changes, use a different filename.": "Για να φυλάξετε τις αλλαγές σας, χρησιμοποιήστε διαφορετικό όνομα αρχείου.",
	"This file is already open.": "Αυτό το αρχείο είναι ήδη ανοιχτό.",
	"This is not a valid .PCS file.": "Αυτό δεν είναι έγκυρο αρχείο .PCS.",
	"This file is open for editing and cannot be overwritten.": "Αυτό το αρχείο είναι ανοιχτό για διορθώσεις και δεν μπορεί να αντικατασταθεί.",
	"Use a different filename to save your changes.": "Χρησιμοποιήστε διαφορετικό όνομα αρχείου για να φυλάξετε τις αλλαγές σας.",
	"This is not a valid bitmap file, or its format is not currently supported.": "Αυτό δεν είναι έγκυρο αρχείο bitmap ή η μορφή του δεν υποστηρίζεται πλέον.",
	"This is not a valid icon.": "Αυτό δεν είναι έγκυρο εικονίδιο.",
	"This is not a valid cursor.": "Αυτός δεν είναι έγκυρος δρομέας.",
	"Save was interrupted, so your file has not been saved.": "Η αποθήκευση διακόπηκε, γι' αυτό δεν σώθηκε το αρχείο σας.",
	"You cannot save to a read-only file.": "Δεν μπορείτε να αποθηκεύσετε σε ένα αρχείο μόνο για ανάγνωση.",
	"Use a different file name.": "Χρησιμοποιήστε διαφορετικό όνομα αρχείου.",
	"This file is already in use.": "Αυτό το αρχείο χρησιμοποιείται ήδη.",
	"Close the program, and then try again.": "Κλείστε το πρόγραμμα και μετά ξαναπροσπαθήστε.",
	"Paint cannot save this file.": "Η Ζωγραφική δεν μπορεί να αποθηκεύσει αυτό το αρχείο.",
	"Paint cannot save to the same filename with a different file type.": "Η Ζωγραφική δεν μπορεί να αποθηκεύσει με το ίδιο όνομα ένα αρχείο διαφορετικού τύπου.",
	"The grid spacing must be an integer between %d and %d.": "Η απόσταση του πλέγματος πρέπει να είναι ακέραιος μεταξύ %d και %d.",
	"There is not enough memory or resources to complete operation.": "Δεν υπάρχει αρκετή μνήμη ή πόροι για να ολοκληρωθεί η λειτουργία.",
	"Close some programs, and then try again.": "Κλείστε μερικά προγράμματα και ξαναπροσπαθήστε.",
	"Low on memory or resources.": "Ελλιπής μνήμη ή πόροι.",
	"Group error.": "Παρουσιάστηκε σφάλμα ομάδας.",
	"Paint was unable to print your document. Please make sure you have sufficient disk space and that your printer is working correctly.": "Η Ζωγραφική δεν μπορεί να τυπώσει το έγγραφό σας. Βεβαιωθείτε ότι υπάρχει επαρκής χώρος στο δίσκο σας και ότι ο εκτυπωτής σας δουλεύει σωστά.",
	"Saving into this format may cause some loss of color information.": "Αποθηκεύοντας σε αυτήν τη μορφή μπορεί να προκαλέσετε απώλεια πληροφοριών χρώματος.",
	"Do you want to continue?": "Θέλετε να συνεχίσετε;",
	"Converting to black and white cannot be undone.  This action affects the current file and may cause some loss of color information.": "Η μετατροπή σε ασπρόμαυρο δεν είναι δυνατό να αναιρεθεί.  Αυτή η ενέργεια επηρεάζει το τρέχον αρχείο και ίσως προκαλέσει απώλεια χρωματικών πληροφοριών.",
	"Bitmaps must be greater than one pixel on a side.": "Τα bitmaps πρέπει να είναι μεγαλύτερα από ένα pixel σε κάθε πλευρά τους.",
	"Generic error.": "Παρουσιάστηκε γενικό σφάλμα.",
	"File not found.": "Το αρχείο δεν βρέθηκε.",
	"Bad path.": "Ακατάλληλη διαδρομή δίσκου.",
	"Too many open files.": "Υπάρχουν πάρα πολλά ανοιχτά αρχεία.",
	"Access denied.": "Δεν επιτράπηκε η πρόσβαση.",
	"Invalid file.": "Το αρχείο δεν είναι έγκυρο.",
	"Remove current folder.": "Κατάργηση τρέχοντος φακέλου.",
	"Folder full.": "Ο φάκελος είναι γεμάτος.",
	"Bad seek.": "Εσφαλμένη αναζήτηση.",
	"Hard IO error.": "Παρουσιάστηκε σφάλμα υλικού IO.",
	"Sharing violation.": "Παραβίαση κοινής χρήσης.",
	"Lock violation.": "Παραβίαση κλειδώματος.",
	"Disk full.": "Ο δίσκος είναι γεμάτος.",
	"End of file.": "Τέλος του αρχείου.",
	"Error getting the Clipboard Data!": "Παρουσιάστηκε σφάλμα κατά τη λήψη των δεδομένων του Πρόχειρου!",
	"No Printer Found @ page setup": "Δεν βρέθηκε εκτυπωτής @ διαμόρφωση σελίδας",
	"24-bit Bitmap (*.bmp;*.dib)": "Bitmap 24-bit (*.bmp;*.dib)",
	"All Files": "Όλα τα αρχεία",
	"Palette|*.pal|": "Παλέτα|*.pal|",
	"OLE 2.0 was unable to start.": "Δεν ήταν δυνατό να ξεκινήσει το OLE 2.0.",
	"Make sure that you are using the correct version of the OLE libraries.": "Βεβαιωθείτε ότι χρησιμοποιείτε τη σωστή έκδοση των βιβλιοθηκών OLE.",
	"Resets the text be without any attributes.": "Αποκατάσταση του κειμένου χωρίς χαρακτηριστικά.",
	"Sets or clears the text bold attribute.": "Ορισμός ή κατάργηση του χαρακτηριστικού έντονου κειμένου.",
	"Sets or clears the text italic attribute.": "Ορισμός ή κατάργηση του χαρακτηριστικού πλάγιου κειμένου.",
	"Selects the font used by the text.": "Επιλογή της γραμματοσειράς για το κείμενο.",
	"Selects the point size of the text.": "Επιλογή του μεγέθους του κειμένου σε στιγμές.",
	"Sets or clears the text underline attribute.": "Ορισμός ή κατάργηση του χαρακτηριστικού υπογράμμισης.",
	"Shows or hides the tooltips.": "Εμφάνιση/απόκρυψη των επεξηγήσεων εργαλείων.",
	"Show Paint Help.": "Εμφάνιση Βοήθειας για τη Ζωγραφική.",
	"Sends a picture by using mail or fax.": "Αποστολή μίας εικόνας χρησιμοποιώντας ταχυδρομείο ή fax.",
	"Copies the selection to a file.": "Αντιγραφή της επιλεγμένης περιοχής σε ένα αρχείο.",
	"Pastes a file into the selection.": "Επικόλληση ενός αρχείου στην επιλεγμένη περιοχή.",
	"Zooms the picture to 100%.": "Μεγέθυνση της εικόνας στο 100%.",
	"Zooms the picture to 400%.": "Μεγέθυνση της εικόνας στο 400%.",
	"Zooms the picture.": "Μεγέθυνση της εικόνας.",
	"Displays the entire picture.": "Εμφάνιση ολόκληρης της εικόνας.",
	"Shows or hides the thumbnail view of the picture.": "Εμφάνιση/απόκρυψη της προβολής της εικόνας σε μικρογραφία.",
	"Shows or hides the grid.": "Εμφάνιση/απόκρυψη του πλέγματος.",
	"Shows or hides the text toolbar.": "Εμφάνιση/απόκρυψη της γραμμής εργαλείων κειμένου.",
	"Flips or rotates the picture or a selection.": "Αναστροφή ή περιστροφή της εικόνας ή της επιλεγμένης περιοχής.",
	"Stretches or skews the picture or a selection.": "Μεγέθυνση ή παραμόρφωση της εικόνας ή της επιλεγμένης περιοχής.",
	"Inverts the colors of the picture or a selection.": "Αναστροφή των χρωμάτων της εικόνας ή της επιλεγμένης περιοχής.",
	"Changes the attributes of the picture.": "Αλλαγή των χαρακτηριστικών της εικόνας.",
	"Clears the picture or selection.": "Σβήσιμο της εικόνας ή της επιλεγμένης περιοχής.",
	"The font size must be a numeric value.": "Το μέγεθος της γραμματοσειράς πρέπει να είναι αριθμητική τιμή.",
	"Contains commands for working with the selected item(s).": "Εντολές για εργασία με τα επιλεγμένα στοιχεία.",
	"Contains commands for selecting and transferring items.": "Εντολές για την επιλογή και μεταφορά στοιχείων.",
	"Contains commands for customizing this window.": "Εντολές για την προσαρμογή αυτού του παράθυρου.",
	"Contains commands for manipulating pictures and setting attributes.": "Εντολές για το χειρισμό εικόνων και τη ρύθμιση χαρακτηριστικών.",
	"Contains commands for using custom colors and drawing options.": "Εντολές για τη χρήση προσαρμοσμένων χρωμάτων και επιλογών σχεδίασης.",
	"Contains commands for displaying Help for and information about Paint.": "Εντολές για την εμφάνιση Βοήθειας και πληροφοριών για τη Ζωγραφική.",
	"Cannot save file.": "Δεν είναι δυνατό να αποθηκευτεί το αρχείο.",
	"Error removing temporary file.": "Παρουσιάστηκε σφάλμα κατά την κατάργηση του προσωρινού αρχείου.",
	"Get Colors": "Λήψη χρωμάτων",
	"Save Colors": "Αποθήκευση χρωμάτων",
	"File last saved:": "Τελευταία αποθήκευση:",
	"Not Available": "Μη διαθέσιμη",
	"Size on disk:": "Μέγεθος στο δίσκο:",
	"%s bytes": "%s byte",
	"Painting": "Χρωματισμός",
	"Fonts": "Γραμματοσειρές",
	"Tools": "Εργαλεία",
	"All Picture Files": "Όλα τα αρχεία εικόνας",
	"For Help, click Help Topics on the Help Menu.": "Για βοήθεια, επιλέξτε τα \"Θέματα στη Βοήθεια\" από το μενού \"Βοήθεια\".",
	"Select an area on which to get Help.": "Επιλέξτε μία περιοχή για την οποία θέλετε Βοήθεια.",
	"%1 in %2": "%1 σε %2",
	"Creates a new document.": "Δημιουργεί ένα νέο έγγραφο.",
	"Opens an existing document.": "Ανοίγει ένα υπάρχον έγγραφο.",
	"Closes the active document.": "Κλείνει το ενεργό έγγραφο.",
	"Saves the active document.": "Αποθηκεύει το ενεργό έγγραφο.",
	"Saves the active document with a new name.": "Αποθηκεύει το ενεργό έγγραφο με νέο όνομα.",
	"Changes the page layout.": "Αλλάζει τη διάταξη της σελίδας.",
	"Specifies the default printer setup.": "Καθορίζει τις προεπιλεγμένες παραμέτρους εκτύπωσης.",
	"Prints the active document and sets printing options.": "Εκτυπώνει το ενεργό έγγραφο και ρυθμίζει τις παραμέτρους εκτύπωσης.",
	"Displays full pages.": "Εμφανίζει ολόκληρες σελίδες.",
	"Opens this document.": "Ανοίγει αυτό το έγγραφο.",
	"Deletes the selection.": "Διαγράφει την επιλεγμένη περιοχή.",
	"Erases everything.": "Διαγραφή όλων.",
	"Copies the selection and puts it on the Clipboard.": "Αντιγράφει την επιλεγμένη περιοχή και την τοποθετεί στο Πρόχειρο.",
	"Cuts the selection and puts it on the Clipboard.": "Αποκόβει την επιλεγμένη περιοχή και την τοποθετεί στο Πρόχειρο.",
	"Finds the specified text.": "Βρίσκει το καθορισμένο κείμενο.",
	"Inserts the contents of the Clipboard.": "Εισάγει τα περιεχόμενα του Προχείρου.",
	"Repeats the last action.": "Επαναλαμβάνει την τελευταία ενέργεια.",
	"Replaces specific text with different text.": "Αντικαθιστά ένα συγκεκριμένο κείμενο με διαφορετικό.",
	"Selects everything.": "Επιλέγει όλα τα στοιχεία.",
	"Undoes the last action.": "Αναιρεί την τελευταία ενέργεια.",
	"Redoes the previously undone action.": "Επαναλαμβάνει την τελευταία ενέργεια που αναιρέθηκε.",
	"Displays program information, version number, and copyright.": "Εμφανίζει πληροφορίες για το πρόγραμμα, την έκδοση και τα δικαιώματα.",
	"Quits Paint.": "Κλείνει τη Ζωγραφική.",
	"Opens Paint Help.": "Ανοίγει τη Βοήθεια για τη Ζωγραφική.",
	"Displays instructions about how to use Help.": "Εμφανίζει οδηγίες για τη χρήση της Βοήθειας.",
	"Displays Help for areas you click on.": "Εμφανίζει Βοήθεια για τα στοιχεία που κάνετε κλικ.",
	"Displays Help for the current task or command.": "Εμφανίζει Βοήθεια για την τρέχουσα εργασία ή εντολή.",
	"Centers this bitmap as the desktop wallpaper.": "Τοποθετεί στο κέντρο αυτό το bitmap ως ταπετσαρία της επιφάνεια εργασίας.",
	"Tiles this bitmap as the desktop wallpaper.": "Τοποθετεί σε παράθεση αυτό το bitmap ως ταπετσαρία στην επιφάνεια εργασίας.",
	"Sends the selection using mail or fax.": "Αποστέλλει την επιλεγμένη περιοχή χρησιμοποιώντας ταχυδρομείο ή fax.",
	"Prints the selection.": "Εκτυπώνει την επιλεγμένη περιοχή.",
	"Shows or hides the thumbnail.": "Εμφανίζει ή κρύβει τη μικρογραφία.",
	"Shows Paint Help.": "Εμφανίζει τη Βοήθεια για τη Ζωγραφική.",
	"Shows or hides the status bar.": "Εμφανίζει ή κρύβει τη γραμμή κατάστασης.",
	"Shows or hides the tool box.": "Εμφανίζει ή κρύβει την εργαλειοθήκη.",
	"Shows or hides the color box.": "Εμφανίζει ή κρύβει το πλαίσιο χρωμάτων.",
	"Only a Far East font can be used for vertical editing.": "Μόνο γραμματοσειρά Far East μπορεί να χρησιμοποιηθεί για κατακόρυφη γραφή.",
	"Changes the window size.": "Αλλάζει το μέγεθος του παραθύρου.",
	"Changes the window position.": "Αλλάζει τη θέση του παραθύρου.",
	"Reduces the window to an icon.": "Σμικρύνει το παράθυρο σε εικονίδιο.",
	"Enlarges the window to full size.": "Μεγεθύνει το παράθυρο στο μέγιστο μέγεθος.",
	"Switches to the next document window.": "Περνά στο επόμενο παράθυρο εγγράφου.",
	"Switches to the previous document window.": "Περνά στο προηγούμενο παράθυρο εγγράφου.",
	"Closes the active window and asks if you want to save changes.": "Κλείνει το ενεργό παράθυρο και ρωτά για αποθήκευση των αλλαγών.",
	"Restores the window to normal size.": "Επαναφέρει το παράθυρο στο κανονικό μέγεθος.",
	"Activates the task list.": "Ενεργοποιεί τη λίστα εργασιών.",
	"All Files (*.*)": "Όλα τα αρχεία (*.*)",
	"Untitled": "Ανώνυμο",
	"an unnamed file": "ανώνυμο αρχείο",
	"&Hide": "&Απόκρυψη",
	"Hide": "Απόκρυψη",
	"No error message is available.": "Δεν υπάρχει διαθέσιμο μήνυμα σφάλματος.",
	"An unsupported operation was attempted.": "Έγινε προσπάθεια εκτέλεσης μιας λειτουργίας που δεν υποστηρίζεται.",
	"A required resource was unavailable.": "Ένας απαραίτητος πόρος δεν ήταν διαθέσιμος.",
	"Out of memory.": "Η μνήμη εξαντλήθηκε.",
	"An unknown error has occurred.": "Παρουσιάστηκε άγνωστο σφάλμα.",
	"on %1": "σε %1",
	"&One Page": "&Μία σελίδα",
	"One Page": "Μία σελίδα",
	"&Two Page": "&Δύο σελίδες",
	"Two Page": "Δύο σελίδες",
	"Page %u": "Σελίδα %u",
	"Pages %u-%u": "Σελίδες %u-%u",
	"Printer Files (*.prn)|*.prn|All Files (*.*)|*.*||": "Αρχεία εκτυπωτή (*.prn)|*.prn|Όλα τα αρχεία (*.*)|*.*||",
	"Print to File": "Εκτύπωση σε αρχείο",
	"to %1": "στο %1",
	"&Update %1": "&Ενημέρωση του %1",
	"Update %1": "Ενημέρωση του %1",
	"E&xit && Return to %1": "Έ&ξοδος && επιστροφή στο %1",
	"Exit && Return to %1": "Έξοδος && επιστροφή στο %1",
	"Linked %s": "Δεσμός %s",
	"Unknown Type": "Άγνωστου τύπου",
	"Invalid filename.": "Το όνομα του αρχείου δεν είναι έγκυρο.",
	"Failed to open document.": "Το άνοιγμα του εγγράφου απέτυχε.",
	"Failed to save document.": "Η αποθήκευση του εγγράφου απέτυχε.",
	"Save changes to %1?": "Να αποθηκευτούν οι αλλαγές στο %1;",
	"Failed to create empty document.": "Η δημιουργία κενού εγγράφου απέτυχε.",
	"The file is too large to open.": "Δεν είναι δυνατό να ανοιχτεί το αρχείο γιατί είναι υπερβολικά μεγάλο.",
	"Could not start print job.": "Δεν είναι δυνατό να ξεκινήσει η εργασία εκτύπωσης.",
	"Failed to launch help.": "Η εκκίνηση της Βοήθειας απέτυχε.",
	"Internal application error.": "Εσωτερικό σφάλμα εφαρμογής.",
	"Command failed.": "Η εντολή απέτυχε.",
	"Insufficient memory to perform operation.": "Η μνήμη δεν επαρκεί για να ολοκληρωθεί η λειτουργία.",
	"System registry entries have been removed and the INI file (if any) was deleted.": "Οι καταχωρήσεις στο αρχείο μητρώου έχουν καταργηθεί και το αρχείο INI (εφόσον υπήρχε) έχει διαγραφεί.",
	"Not all of the system registry entries (or INI file) were removed.": "Δεν καταργήθηκαν όλες οι καταχωρήσεις στο μητρώο του συστήματος (ή το αρχείο INI).",
	"This program requires the file %s, which was not found on this system.": "Αυτό το πρόγραμμα χρειάζεται το αρχείο %s το οποίο δεν βρέθηκε στο σύστημά σας.",
	"This program is linked to the missing export %s in the file %s. This machine may have an incompatible version of %s.": "Το στοιχείο %s στο αρχείο %s με το οποίο συνδέεται αυτό το πρόγραμμα λείπει. Αυτή η μηχανή ίσως δεν έχει συμβατή έκδοση του %s.",
	"Please enter an integer.": "Πληκτρολογήστε έναν ακέραιο αριθμό.",
	"Please enter a number.": "Πληκτρολογήστε έναν αριθμό.",
	"Please enter an integer between %1 and %2.": "Πληκτρολογήστε έναν ακέραιο μεταξύ %1 και %2.",
	"Please enter a number between %1 and %2.": "Πληκτρολογήστε έναν αριθμό μεταξύ %1 και %2.",
	"Please enter no more than %1 characters.": "Μην πληκτρολογήσετε περισσότερους από %1 χαρακτήρες.",
	"Please select a button.": "Επιλέξτε ένα κουμπί.",
	"Please enter an integer between 0 and 255.": "Πληκτρολογήστε έναν ακέραιο μεταξύ 0 και 255.",
	"Please enter a positive integer.": "Πληκτρολογήστε έναν θετικό ακέραιο.",
	"Please enter a date and/or time.": "Πληκτρολογήστε ημερομηνία ή/και ώρα.",
	"Please enter a currency.": "Πληκτρολογήστε μία νομισματική μονάδα.",
	"Unexpected file format.": "Μη αναμενόμενη μορφή αρχείου.",
	"Cannot find this file.": "Δεν είναι δυνατό να βρεθεί αυτό το αρχείο.",
	"Please verify that the correct path and file name are given.": "Βεβαιωθείτε ότι δώσατε σωστά το όνομα αρχείου και τη διαδρομή.",
	"Destination disk drive is full.": "Η μονάδα δίσκου προορισμού είναι γεμάτη.",
	"Unable to read from %1, it is opened by someone else.": "Δεν είναι δυνατή η ανάγνωση του αρχείου %1 επειδή έχει ανοιχτεί από κάποιον άλλο.",
	"Unable to write to %1, it is read-only or opened by someone else.": "Δεν είναι δυνατή η εγγραφή στο %1 επειδή είναι μόνο για ανάγνωση ή έχει ανοιχτεί από κάποιον άλλο.",
	"An unexpected error occurred while reading %1.": "Παρουσιάστηκε ένα μη αναμενόμενο σφάλμα κατά την ανάγνωση του %1.",
	"An unexpected error occurred while writing %1.": "Εκδηλώθηκε ένα μη αναμενόμενο σφάλμα κατά την εγγραφή στο %1.",
	"Unable to register document.": "Δεν ήταν δυνατό να καταχωρηθεί το έγγραφο.",
	"The document may already be open.": "Το έγγραφο ίσως είναι ήδη ανοιχτό.",
	"Update %1 before proceeding?": "Να ενημερωθεί το %1 πριν από τη συνέχεια;",
	"Could not update client.": "Δεν ήταν δυνατό να ενημερωθεί το πρόγραμμα-πελάτης.",
	"Failed to register. ActiveX features may not work properly.": "Η καταχώρηση απέτυχε. Τα χαρακτηριστικά του ActiveX ίσως δεν λειτουργήσουν σωστά.",
	"Failed to update the system registry.": "Η ενημέρωση του μητρώου συστήματος απέτυχε.",
	"Please try using REGEDIT.": "Προσπαθήστε χρησιμοποιώντας το REGEDIT.",
	"Unable to read write-only property.": "Δεν είναι δυνατή η ανάγνωση μιας ιδιότητας που είναι μόνο για εγγραφή.",
	"Unable to write read-only property.": "Δεν είναι δυνατή η εγγραφή σε μία ιδιότητα που είναι μόνο για ανάγνωση.",
	"Unable to load mail system support.": "Δεν είναι δυνατό να φορτωθεί η υποστήριξη συστήματος αλληλογραφίας.",
	"Mail system DLL is invalid.": "Το DLL του συστήματος ταχυδρομείου δεν είναι έγκυρο.",
	"Send Mail failed to send message.": "Η Αποστολή Αλληλογραφίας απέτυχε να στείλει το μήνυμα.",
	"No error occurred.": "Δεν παρουσιάστηκε σφάλμα.",
	"An unknown error occurred while accessing %1.": "Παρουσιάστηκε ένα άγνωστο σφάλμα κατά την πρόσβαση στο %1.",
	"%1 was not found.": "Το %1 δεν βρέθηκε.",
	"%1 contains an invalid path.": "Το %1 περιέχει  μία μη έγκυρη διαδρομή.",
	"%1 could not be opened because there are too many open files.": "Δεν είναι δυνατό να ανοιχτεί το %1 γιατί υπάρχουν πολλά ανοικτά αρχεία.",
	"Access to %1 was denied.": "Δεν επιτράπηκε η πρόσβαση στο %1.",
	"An invalid file handle was associated with %1.": "Ο δείκτης χειρισμού αρχείου που συσχετίστηκε με το %1 δεν είναι έγκυρος.",
	"%1 could not be removed because it is the current directory.": "Δεν είναι δυνατή η κατάργηση του %1 γιατί είναι ο τρέχων κατάλογος.",
	"%1 could not be created because the directory is full.": "Δεν είναι δυνατή η δημιουργία του %1 γιατί ο κατάλογος είναι πλήρης.",
	"Seek failed on %1": "Η αναζήτηση στο αρχείο %1 απέτυχε",
	"A hardware I/O error was reported while accessing %1.": "Αναφέρθηκε σφάλμα υλικού εισόδου/εξόδου κατά την πρόσβαση στο %1.",
	"A sharing violation occurred while accessing %1.": "Παρουσιάστηκε παραβίαση κοινής χρήσης κατά την πρόσβαση στο %1.",
	"A locking violation occurred while accessing %1.": "Παρουσιάστηκε παραβίαση κλειδώματος κατά την πρόσβαση στο %1.",
	"Disk full while accessing %1.": "Ο δίσκος γέμισε κατά την πρόσβαση στο %1.",
	"An attempt was made to access %1 past its end.": "Έγινε προσπάθεια πρόσβασης μετά το τέλος του %1.",
	"An attempt was made to write to the reading %1.": "Έγινε προσπάθεια εγγραφής στο αρχείο ανάγνωσης %1.",
	"An attempt was made to read from the writing %1.": "Έγινε προσπάθεια ανάγνωσης από το αρχείο εγγραφής %1.",
	"%1 has a bad format.": "Το %1 έχει ακατάλληλη μορφή.",
	"%1 contained an unexpected object.": "Το %1 περιέχει ένα μη αναμενόμενο αντικείμενο.",
	"%1 contains an incorrect schema.": "Το %1 περιέχει μια εσφαλμένη διάταξη.",
	"Selects a rectangular part of the picture to move, copy, or edit.": "Επιλογή ορθογώνιου τμήματος για μετακίνηση, αποκοπή ή διόρθωση.",
	"Select": "Επιλογή",
	"Selects a free-form part of the picture to move, copy, or edit.": "Επιλογή τμήματος με ελεύθερη μορφή για μετακίνηση, αποκοπή ή διόρθωση.",
	"Free-Form Select": "Επιλογή ελεύθερης μορφής",
	"Inserts text into the picture.": "Εισαγωγή κειμένου στην εικόνα.",
	"Fills an area with the current drawing color.": "Γέμισμα περιοχής με το τρέχον χρώμα σχεδίασης.",
	"Fill With Color": "Γέμισμα με χρώμα",
	"Draws a straight line with the selected line width.": "Σχεδίαση ευθείας γραμμής με το επιλεγμένο πλάτος γραμμής.",
	"Line": "Γραμμή",
	"Draws using an airbrush of the selected size.": "Σχεδίαση με αερογράφο στο επιλεγμένο μέγεθος.",
	"Airbrush": "Αερογράφος",
	"Draws a curved line with the selected line width.": "Σχεδίαση καμπύλης γραμμής με το επιλεγμένο πλάτος γραμμής.",
	"Curve": "Καμπύλη",
	"Draws a polygon with the selected fill style.": "Σχεδίαση πολυγώνου με το επιλεγμένο γέμισμα.",
	"Polygon": "Πολύγωνο",
	"Draws a rounded rectangle with the selected fill style.": "Σχεδίαση στρογγυλεμένου ορθογώνιου με το επιλεγμένο γέμισμα.",
	"Rounded Rectangle": "Στρογγυλεμένο ορθογώνιο",
	"Draws a free-form line one pixel wide.": "Ελεύθερη σχεδίαση γραμμής με πλάτος ένα pixel.",
	"Pencil": "Μολύβι",
	"Erases a portion of the picture, using the selected eraser shape.": "Σβήσιμο τμήματος της εικόνας με χρήση της επιλεγμένης γόμας.",
	"Eraser/Color Eraser": "Γόμα/Έγχρωμη γόμα",
	"Changes the magnification.": "Αλλαγή της μεγέθυνσης.",
	"Magnifier": "Μεγεθυντικός φακός",
	"Picks up a color from the picture for drawing.": "Επιλογή χρώματος από την εικόνα για σχεδίαση.",
	"Pick Color": "Συλλογή χρώματος",
	"Draws using a brush with the selected shape and size.": "Σχεδίαση με πινέλο με το επιλεγμένο σχήμα και μέγεθος.",
	"Brush": "Πινέλο",
	"Draws a rectangle with the selected fill style.": "Σχεδίαση ορθογώνιου με το επιλεγμένο γέμισμα.",
	"Rectangle": "Ορθογώνιο",
	"Draws a filled rectangle.": "Σχεδίαση γεμισμένου ορθογώνιου.",
	"Draws an ellipse with the selected fill style.": "Σχεδίαση έλλειψης με το επιλεγμένο γέμισμα.",
	"Ellipse": "Έλλειψη",
	"Draws a filled ellipse.": "Σχεδίαση γεμισμένης έλλειψης.",
	"Makes the current selection either opaque or transparent.": "Μεταβολή της τρέχουσας επιλεγμένης περιοχής σε αδιαφανή ή διαφανή.",
	"Creates a new color.": "Δημιουργία νέου χρώματος.",
	"Uses a previously saved palette of colors.": "Χρήση ήδη αποθηκευμένης παλέτας χρωμάτων.",
	"Saves the current palette of colors to a file.": "Αποθήκευση της τρέχουσας παλέτας χρωμάτων σε ένα αρχείο.",
	"You must save the file before choosing it as Wallpaper.": "Πρέπει να αποθηκεύσετε το αρχείο πριν το επιλέξετε ως ταπετσαρία.",
	"The selection is now larger than the bitmap.": "Η επιλεγμένη περιοχή είναι τώρα μεγαλύτερη από το bitmap.",
	"Would you like the bitmap enlarged?": "Μήπως θέλετε να μεγαλώσει το bitmap;",
	"The image in the clipboard is larger than the bitmap.": "Η εικόνα στο Πρόχειρο είναι μεγαλύτερη από το bitmap.",
	"The file is not in the correct format.": "Το αρχείο δεν έχει τη σωστή μορφή.",
	"Not enough room to paste text.": "Δεν υπάρχει αρκετός χώρος για την επικόλληση του κειμένου.",
	"Enlarge the text area and try again.": "Μεγεθύνετε την περιοχή του κειμένου και ξαναπροσπαθήστε.",
	"Places the text.": "Τοποθέτηση κειμένου."
});
