//
// NOTE: This is a generated file! Don't edit it directly.
// Eventually community translation will be set up on some translation platform.
// 
// Generated with: npm run update-localization
//
loaded_localizations("de", {
	"Attributes": "Attribute",
	"&Width:": "&Breite:",
	"Width:": "Breite:",
	"&Height:": "&Höhe:",
	"Height:": "Höhe:",
	"Units": "Maßeinheit",
	"&Inches": "&Zoll",
	"Inches": "Zoll",
	"C&m": "&cm",
	"Cm": "cm",
	"&Pixels": "&Pixel",
	"Pixels": "Pixel",
	"Colors": "Farben",
	"&Black and white": "&Schwarzweiß",
	"Black and white": "Schwarzweiß",
	"Co&lors": "&Farben",
	"Transparency": "Transparenz",
	"Use &Transparent background color": "&Transparente Hintergrundfarbe",
	"Use Transparent background color": "Transparente Hintergrundfarbe",
	"Select &Color": "Farbe aus&wählen",
	"Select Color": "Farbe wählen",
	"Cancel": "Abbrechen",
	"&Default": "St&andard",
	"Default": "Standard",
	"Custom Zoom": "Vergrößerung",
	"Current zoom:": "Aktueller Zoomfaktor:",
	"Zoom to": "Neuer Zoomfaktor",
	"Flip and Rotate": "Bild drehen und spiegeln",
	"Flip or rotate": "Spiegeln oder drehen",
	"&Flip horizontal": "&Horizontal spiegeln",
	"Flip horizontal": "Horizontal spiegeln",
	"Flip &vertical": "&Vertikal spiegeln",
	"Flip vertical": "Vertikal spiegeln",
	"&Rotate by angle": "&Drehen im Winkel von:",
	"Rotate by angle": "Drehen im Winkel von:",
	"Stretch and Skew": "Bild strecken und zerren",
	"Stretch": "Strecken",
	"&Vertical:": "&Vertikal:",
	"Vertical:": "Vertikal:",
	"Skew": "Zerren",
	"Degrees": "Grad",
	"V&ertical:": "V&ertikal:",
	"Color Table": "Farbtabelle",
	"New": "Neu",
	"&New ": "&Neu",
	"New ": "Neu",
	"&Help": "&Hilfe",
	"Help": "Hilfe",
	"Printing": "Drucken von",
	"on the": "auf",
	"&Print": "&Drucken",
	"Print": "Drucken",
	"&Next Page": "&Weiter",
	"Next Page": "Weiter",
	"Pre&v Page": "&Zurück",
	"Prev Page": "Zurück",
	"Zoom &In": "&Vergrößern",
	"Zoom In": "Vergrößern",
	"Zoom &Out": "V&erkleinern",
	"Zoom Out": "Verkleinern",
	"&Close": "&Schließen",
	"Close": "Schließen",
	"Grid Settings": "Rastereinstellungen",
	"&Pixel Grid": "&Feinraster",
	"Pixel Grid": "Feinraster",
	"&Tile Grid": "&Grobraster",
	"Tile Grid": "Grobraster",
	"pixels": "Pixel",
	"H&eight:": "&Höhe:",
	"Undo": "Rückgängig",
	"Cut": "Ausschneiden",
	"Copy": "Kopieren",
	"Paste": "Einfügen",
	"Clear Selection": "Löschen",
	"Select All": "Alles markieren",
	"Text Toolbar": "Formatsymbolleiste",
	"Selection": "Auswahl",
	"Cu&t": "&Ausschneiden",
	"&Copy": "&Kopieren",
	"&Paste": "&Einfügen",
	"C&lear Selection": "&Löschen",
	"Select &All": "Alles &markieren",
	"C&opy To": "Kopiere&n nach",
	"Copy To": "Kopieren nach",
	"Paste &From": "Einfügen a&us",
	"Paste From": "Einfügen von",
	"Flip/&Rotate": "D&rehen/Spiegeln",
	"Flip/Rotate": "Drehen/Spiegeln",
	"&Stretch/Skew": "&Strecken/Zerren",
	"Stretch/Skew": "Strecken/Zerren",
	"&Invert Colors": "&Farben umkehren",
	"Invert Colors": "Farben umkehren",
	"Thumbnail": "Miniaturansicht",
	"&File": "&Datei",
	"File": "Datei",
	"&New": "&Neu",
	"Ctrl+N": "Strg+N",
	"&Open": "Ö&ffnen",
	"Open": "Öffnen",
	"Ctrl+O": "Strg+O",
	"&Save": "&Speichern",
	"Save": "Speichern",
	"Ctrl+S": "Strg+S",
	"Save &As": "Speichern &unter",
	"Save As": "Speichern unter",
	"Print Pre&view": "Seitenansi&cht",
	"Print Preview": "Seitenansicht",
	"Page Se&tup": "Seite ein&richten",
	"Page Setup": "Seite einrichten",
	"Ctrl+P": "Strg+P",
	"S&end": "S&enden",
	"Send": "Senden",
	"Set As &Wallpaper (Tiled)": "Als &Hintergrund (Fläche)",
	"Set As Wallpaper (Tiled)": "Als Hintergrund (Fläche)",
	"Set As Wa&llpaper (Centered)": "A&ls Hintergrund (Zentriert)",
	"Set As Wallpaper (Centered)": "Als Hintergrund (Zentriert)",
	"Recent File": "Vorherige Datei",
	"E&xit": "&Beenden",
	"Exit": "Beenden",
	"&Edit": "&Bearbeiten",
	"Edit": "Bearbeiten",
	"&Undo": "&Rückgängig",
	"Ctrl+Z": "Strg+Z",
	"&Repeat": "&Wiederholen",
	"Repeat": "Wiederholen",
	"Ctrl+X": "Strg+X",
	"Ctrl+C": "Strg+C",
	"Ctrl+V": "Strg+V",
	"Del": "Entf",
	"Ctrl+A": "Strg+A",
	"&View": "&Ansicht",
	"View": "Ansicht",
	"&Tool Box": "&Toolbox",
	"Tool Box": "Toolbox",
	"Ctrl+T": "Strg+T",
	"&Color Box": "&Farbpalette",
	"Color Box": "Farbpalette",
	"Ctrl+L": "Strg+F",
	"&Status Bar": "Status&leiste",
	"Status Bar": "Statusleiste",
	"T&ext Toolbar": "F&ormatsymbolleiste",
	"&Zoom": "&Zoomfaktor",
	"Zoom": "Zoomfaktor",
	"&Normal Size": "&Normalgröße",
	"Normal Size": "Normalgröße",
	"Ctrl+PgUp": "Strg+<",
	"&Large Size": "&Stark vergrößert",
	"Large Size": "Stark vergrößert",
	"Ctrl+PgDn": "Strg+>",
	"C&ustom": "&Benutzerdefiniert",
	"Custom": "Benutzerdefiniert",
	"Show &Grid": "&Raster einblenden",
	"Show Grid": "Raster einblenden",
	"Ctrl+G": "Strg+R",
	"Show T&humbnail": "&Miniaturansicht einblenden",
	"Show Thumbnail": "Miniaturansicht einblenden",
	"&View Bitmap": "&Gesamtbild",
	"View Bitmap": "Gesamtbild",
	"Ctrl+F": "Strg+G",
	"&Image": "B&ild",
	"Image": "Bild",
	"&Flip/Rotate": "D&rehen/Spiegeln",
	"Ctrl+R": "Strg+D",
	"Ctrl+W": "Strg+K",
	"Ctrl+I": "Strg+U",
	"&Attributes": "&Attribute",
	"Ctrl+E": "Strg+E",
	"&Clear Image": "&Bild löschen",
	"Clear Image": "Bild löschen",
	"Ctrl+Shft+N": "Strg+Umschalt+N",
	"&Draw Opaque": "&Deckend zeichnen",
	"Draw Opaque": "Deckend zeichnen",
	"&Colors": "&Farben",
	"&Edit Colors": "&Palette bearbeiten",
	"Edit Colors": "Farben bearbeiten",
	"&Help Topics": "&Hilfethemen",
	"Help Topics": "Hilfethemen",
	"&About Paint": "Inf&o",
	"About Paint": "Info",
	"&Update": "&Aktualisieren",
	"Update": "Aktualisieren",
	"Save Copy &As": "Speichern &unter",
	"Save Copy As": "Kopie speichern unter",
	"untitled": "Unbenannt",
	"Bitmap Image": "Bitmap-Bild",
	"Bitmap Files (*.bmp)": "Bitmap-Dateien (*.bmp)",
	"PCX Files": "PCX-Dateien",
	"Icon Files": "Symboldateien",
	"Monochrome Bitmap (*.bmp;*.dib)": "Monochrom-Bitmap (*.bmp;*.dib)",
	"16 Color Bitmap (*.bmp;*.dib)": "16-Farben-Bitmap (*.bmp;*.dib)",
	"256 Color Bitmap (*.bmp;*.dib)": "256-Farben-Bitmap (*.bmp;*.dib)",
	"Paint cannot open this file.": "Die Datei konnte nicht geöffnet werden.",
	"Paint cannot read this file.": "Die Datei konnte nicht gelesen werden.",
	"This file is read-only.": "Diese Datei ist schreibgeschützt.",
	"To save your changes, use a different filename.": "Verwenden Sie zum Speichern der Änderungen einen anderen Dateinamen.",
	"This file is already open.": "Diese Datei ist bereits geöffnet.",
	"This is not a valid .PCS file.": "Dies ist keine gültige .PCS-Datei.",
	"This file is open for editing and cannot be overwritten.": "Die Datei ist zur Bearbeitung geöffnet und kann nicht überschrieben werden.",
	"Use a different filename to save your changes.": "Verwenden Sie zum Speichern der Änderungen einen anderen Dateinamen.",
	"This is not a valid bitmap file, or its format is not currently supported.": "Dies ist keine gültige Bitmapdatei,  oder das Format wird nicht unterstützt.",
	"This is not a valid icon.": "Dies ist kein gültiges Symbol.",
	"This is not a valid cursor.": "Dies ist kein gültiger Cursor.",
	"Save was interrupted, so your file has not been saved.": "Der Speichervorgang wurde unterbrochen. Die Datei wurde nicht gespeichert.",
	"You cannot save to a read-only file.": "Eine schreibgeschützte Datei kann nicht gespeichert werden.",
	"Use a different file name.": "Verwenden Sie einen anderen Dateinamen.",
	"This file is already in use.": "Diese Datei wird bereits verwendet.",
	"Close the program, and then try again.": "Beenden Sie das Programm, und wiederholen Sie den Vorgang.",
	"Paint cannot save this file.": "Diese Datei kann nicht gespeichert werden.",
	"Paint cannot save to the same filename with a different file type.": "Die Datei kann nicht unter demselben Namen in einem anderen Format gespeichert werden.",
	"The grid spacing must be an integer between %d and %d.": "Der Wert für die Rasterweite muss eine ganze Zahl im Bereich von %d bis %d sein.",
	"There is not enough memory or resources to complete operation.": "Für den Vorgang sind nicht genügend Arbeitsspeicher oder Ressourcen verfügbar.",
	"Close some programs, and then try again.": "Schließen Sie andere Programme, und wiederholen Sie den Vorgang.",
	"Low on memory or resources.": "Nicht genügend Speicher oder Ressourcen.",
	"Group error.": "Gruppierungsfehler.",
	"Paint was unable to print your document. Please make sure you have sufficient disk space and that your printer is working correctly.": "Das Dokument konnte nicht gedruckt werden. Überprüfen Sie, ob genügend Speicherplatz verfügbar ist und der Drucker richtig funktioniert.",
	"Saving into this format may cause some loss of color information.": "Das Speichern in diesem Format kann zum Verlust von Farbinformationen führen.",
	"Do you want to continue?": "Möchten Sie den Vorgang fortsetzen?",
	"Converting to black and white cannot be undone.  This action affects the current file and may cause some loss of color information.": "Eine Konvertierung in die Farben Schwarz oder Weiß kann nicht rückgängig gemacht werden. Dieser Vorgang hat evtl. den Verlust von Farbinformationen zur Folge.",
	"Bitmaps must be greater than one pixel on a side.": "Die Mindestgröße einer Bitmap beträgt 1 Pixel pro Seite.",
	"Generic error.": "Allgemeiner Fehler.",
	"File not found.": "Datei nicht gefunden.",
	"Bad path.": "Ungültiger Pfad.",
	"Too many open files.": "Zu viele Dateien geöffnet.",
	"Access denied.": "Zugriff verweigert.",
	"Invalid file.": "Ungültige Datei.",
	"Remove current folder.": "Aktuellen Ordner löschen.",
	"Folder full.": "Ordner ist voll.",
	"Bad seek.": "Positionierungsfehler.",
	"Hard IO error.": "Ein-/Ausgabefehler.",
	"Sharing violation.": "Zugriffsverletzung.",
	"Lock violation.": "Sperrverletzung.",
	"Disk full.": "Datenträger ist voll.",
	"End of file.": "Dateiende.",
	"Error getting the Clipboard Data!": "Fehler beim Lesen der Zwischenablagedaten!",
	"No Printer Found @ page setup": "Kein Drucker bei Seiteneinrichtung gefunden",
	"24-bit Bitmap (*.bmp;*.dib)": "24-Bit-Bitmap (*.bmp;*.dib)",
	"All Files": "Alle Dateien",
	"untitled.pal": "unbenannt.pal",
	"OLE 2.0 was unable to start.": "OLE 2.0 konnte nicht gestartet werden.",
	"Make sure that you are using the correct version of the OLE libraries.": "Stellen Sie sicher, dass Sie die richtige Version der OLE-Bibliotheken verwenden.",
	"Resets the text be without any attributes.": "Setzt die Textattribute zurück.",
	"Sets or clears the text bold attribute.": "Aktiviert oder deaktiviert den Fettdruck.",
	"Sets or clears the text italic attribute.": "Aktiviert oder deaktiviert die Kursivschrift.",
	"Selects the font used by the text.": "Wählt eine Schriftart aus.",
	"Selects the point size of the text.": "Wählt den Schriftgrad aus.",
	"Sets or clears the text underline attribute.": "Aktiviert oder deaktiviert die Textunterstreichung.",
	"Shows or hides the tooltips.": "Blendet die QuickInfo ein oder aus.",
	"Show Paint Help.": "Zeigt die Paint-Hilfe an.",
	"Sends a picture by using mail or fax.": "Übermittelt ein Bild per Email oder Fax.",
	"Copies the selection to a file.": "Kopiert die Auswahl in eine Datei.",
	"Pastes a file into the selection.": "Fügt eine Datei in die Auswahl ein.",
	"Zooms the picture to 100%.": "Stellt das Bild in Normalgröße dar.",
	"Zooms the picture to 400%.": "Vergrößert das Bild um das Vierfache.",
	"Zooms the picture.": "Legt den Zoomfaktor für das Bild fest.",
	"Displays the entire picture.": "Zeigt das Gesamtbild an.",
	"Shows or hides the thumbnail view of the picture.": "Blendet die Miniaturansicht ein oder aus.",
	"Shows or hides the grid.": "Blendet das Raster ein oder aus.",
	"Shows or hides the text toolbar.": "Blendet die Formatsymbolleiste ein oder aus.",
	"Flips or rotates the picture or a selection.": "Dreht oder spiegelt das Bild oder einen Bildausschnitt.",
	"Stretches or skews the picture or a selection.": "Streckt oder zerrt das Bild oder einen Ausschnitt.",
	"Inverts the colors of the picture or a selection.": "Kehrt die Farben des Bildes oder Ausschnitts um.",
	"Changes the attributes of the picture.": "Ändert die Bildattribute.",
	"Clears the picture or selection.": "Löscht das Bild oder einen Bildausschnitt.",
	"The font size must be a numeric value.": "Geben Sie eine Zahl für den Schriftgrad ein.",
	"Contains commands for working with the selected item(s).": "Befehle zur Arbeit mit gewählten Elementen",
	"Contains commands for selecting and transferring items.": "Befehle zum Auswählen und Übertragen von Elementen",
	"Contains commands for customizing this window.": "Enthält Befehle zum Ändern des Fensters",
	"Contains commands for manipulating pictures and setting attributes.": "Befehle zur Bildbearbeitung und zum Festlegen von Attributen",
	"Contains commands for using custom colors and drawing options.": "Befehle für benutzerdefinierte Farben und Zeichenoptionen",
	"Contains commands for displaying Help for and information about Paint.": "Befehle zum Anzeigen der Hilfe und Informationen über Paint",
	"Cannot save file.": "Datei kann nicht gespeichert werden.",
	"Error removing temporary file.": "Fehler beim Entfernen der temporären Datei.",
	"Get Colors": "Palette laden",
	"Save Colors": "Palette speichern",
	"File last saved:": "Zuletzt gespeichert:",
	"Not Available": "Nicht verfügbar",
	"Size on disk:": "Dateigröße:",
	"%s bytes": "%s Bytes",
	"Painting": "Zeichnung",
	"Fonts": "Schriftarten",
	"Tools": "Extras",
	"All Picture Files": "Alle Bilddateien",
	"For Help, click Help Topics on the Help Menu.": "Klicken Sie im Menü \"Hilfe\" auf \"Hilfethemen\".",
	"Select an area on which to get Help.": "Wählen Sie einen Bereich aus, über den Sie sich informieren möchten.",
	"Creates a new document.": "Erstellt ein neues Dokument.",
	"Opens an existing document.": "Öffnet ein vorhandenes Dokument.",
	"Closes the active document.": "Schließt das aktive Dokument.",
	"Saves the active document.": "Speichert das aktive Dokument.",
	"Saves the active document with a new name.": "Speichert das aktive Dokument unter neuem Namen.",
	"Changes the page layout.": "Ändert die Seitengestaltung.",
	"Specifies the default printer setup.": "Definiert die Standarddruckerkonfiguration.",
	"Prints the active document and sets printing options.": "Druckt das aktive Dokument und ändert Druckoptionen.",
	"Displays full pages.": "Zeigt die Seitenansicht an.",
	"Opens this document.": "Öffnet das angegebene Dokument.",
	"Deletes the selection.": "Löscht die Auswahl.",
	"Erases everything.": "Löscht das gesamte Dokument.",
	"Copies the selection and puts it on the Clipboard.": "Kopiert die Auswahl in die Zwischenablage.",
	"Cuts the selection and puts it on the Clipboard.": "Überträgt die Auswahl in die Zwischenablage.",
	"Finds the specified text.": "Sucht nach dem angegebenen Text.",
	"Inserts the contents of the Clipboard.": "Fügt den Inhalt der Zwischenablage ein.",
	"Repeats the last action.": "Wiederholt den letzten Vorgang.",
	"Replaces specific text with different text.": "Ersetzt den angegebenen Text.",
	"Selects everything.": "Markiert das gesamte Dokument.",
	"Undoes the last action.": "Macht den letzten Vorgang rückgängig.",
	"Redoes the previously undone action.": "Wiederholt den rückgängig gemachten Vorgang.",
	"Displays program information, version number, and copyright.": "Zeigt Angaben zum Programm, Copyright und zur Version an.",
	"Quits Paint.": "Beendet Paint.",
	"Opens Paint Help.": "Öffnet die Paint-Hilfe.",
	"Displays instructions about how to use Help.": "Zeigt Anweisungen zur Arbeit mit der Hilfe an.",
	"Displays Help for areas you click on.": "Zeigt Hilfe zu dem Element an, auf das Sie klicken.",
	"Displays Help for the current task or command.": "Zeigt Hilfe zum aktuellen Vorgang oder Befehl an.",
	"Centers this bitmap as the desktop wallpaper.": "Wählt die Bitmap als Desktophintergrund (Mitte) aus.",
	"Tiles this bitmap as the desktop wallpaper.": "Wählt die Bitmap als Desktophintergrund (Fläche) aus.",
	"Sends the selection using mail or fax.": "Übermittelt die Auswahl per E-Mail oder Fax.",
	"Prints the selection.": "Druckt die Auswahl.",
	"Shows or hides the thumbnail.": "Blendet die Miniaturansicht ein oder aus.",
	"Shows Paint Help.": "Zeigt die Paint-Hilfe an.",
	"Shows or hides the status bar.": "Blendet die Statusleiste ein oder aus.",
	"Shows or hides the tool box.": "Blendet die Toolbox ein oder aus.",
	"Shows or hides the color box.": "Blendet die Farbpalette ein oder aus.",
	"Only a Far East font can be used for vertical editing.": "Für die vertikale Bearbeitung kann nur eine Fernostschriftart verwendet werden.",
	"Changes the window size.": "Ändert die Fenstergröße.",
	"Changes the window position.": "Ändert die Fensterposition.",
	"Reduces the window to an icon.": "Minimiert das Fenster.",
	"Enlarges the window to full size.": "Maximiert das Fenster.",
	"Switches to the next document window.": "Wechselt zum nächsten Dokumentfenster.",
	"Switches to the previous document window.": "Wechselt zum vorherigen Dokumentfenster.",
	"Closes the active window and asks if you want to save changes.": "Schließt das Fenster und fordert zum Speichern auf.",
	"Restores the window to normal size.": "Stellt das Fenster wieder in Normalgröße her.",
	"Activates the task list.": "Aktiviert den Task-Manager.",
	"All Files (*.*)": "Alle Dateien (*.*)",
	"Untitled": "Unbenannt",
	"an unnamed file": "eine unbenannte Datei",
	"&Hide": "&Ausblenden",
	"Hide": "Ausblenden",
	"No error message is available.": "Es ist keine Fehlermeldung verfügbar.",
	"An unsupported operation was attempted.": "Ein Vorgang wurde nicht unterstützt.",
	"A required resource was unavailable.": "Eine erforderliche Ressource war nicht verfügbar.",
	"Out of memory.": "Nicht genügend Arbeitsspeicher",
	"An unknown error has occurred.": "Unbekannter Fehler",
	"on %1": "auf %1",
	"&One Page": "E&inseitig",
	"One Page": "Einseitig",
	"&Two Page": "Zwe&iseitig",
	"Two Page": "Zweiseitig",
	"Page %u": "Seite %u",
	"Pages %u-%u": "Seiten %u-%u",
	"Output.prn": "Ausgabe.prn",
	"Printer Files (*.prn)|*.prn|All Files (*.*)|*.*||": "Druckdateien (*.prn)|*.prn|Alle Dateien (*.*)|*.*||",
	"Print to File": "Ausdruck in Datei",
	"to %1": "zu %1",
	"&Update %1": "%1 &aktualisieren",
	"Update %1": "%1 aktualisieren",
	"E&xit && Return to %1": "&Beenden und zurück zu %1",
	"Exit && Return to %1": "Beenden und zurück zu %1",
	"Linked %s": "Verknüpft %s",
	"Unknown Type": "Unbekannter Typ",
	"Invalid filename.": "Ungültiger Dateiname",
	"Failed to open document.": "Das Dokument konnte nicht geöffnet werden.",
	"Failed to save document.": "Das Dokument konnte nicht gespeichert werden.",
	"Save changes to %1?": "Änderungen an %1 speichern?",
	"Failed to create empty document.": "Es konnte kein leeres Dokument erstellt werden.",
	"The file is too large to open.": "Die Datei ist zu groß zum Öffnen.",
	"Could not start print job.": "Der Druckauftrag konnte nicht gestartet werden.",
	"Failed to launch help.": "Die Hilfe konnte nicht gestartet werden.",
	"Internal application error.": "Interner Fehler der Anwendung",
	"Command failed.": "Der Befehl konnte nicht ausgeführt werden.",
	"Insufficient memory to perform operation.": "Nicht genügend Arbeitsspeicher für diesen Vorgang.",
	"System registry entries have been removed and the INI file (if any) was deleted.": "Einträge in der Systemregistrierung wurden entfernt, und die INI-Datei (falls vorhanden) wurde gelöscht.",
	"Not all of the system registry entries (or INI file) were removed.": "Nicht alle Einträge in der Systemregistrierung (oder INI-Dateien) wurden entfernt.",
	"This program requires the file %s, which was not found on this system.": "Die für dieses Programm erforderliche Datei %s wurde nicht gefunden.",
	"This program is linked to the missing export %s in the file %s. This machine may have an incompatible version of %s.": "Dieses Programm ist mit dem fehlenden Export %s in der Datei %s verknüpft. Möglicherweise ist die Version von %s inkompatibel.",
	"Please enter an integer.": "Geben Sie eine ganze Zahl ein.",
	"Please enter a number.": "Geben Sie eine Zahl ein.",
	"Please enter an integer between %1 and %2.": "Geben Sie eine ganze Zahl zwischen %1 und %2 ein.",
	"Please enter a number between %1 and %2.": "Geben Sie eine Zahl zwischen %1 und %2 ein.",
	"Please enter no more than %1 characters.": "Geben Sie maximal %1 Zeichen ein.",
	"Please select a button.": "Klicken Sie auf eine Schaltfläche.",
	"Please enter an integer between 0 and 255.": "Geben Sie eine ganze Zahl zwischen 0 und 255 ein.",
	"Please enter a positive integer.": "Geben Sie eine positive ganze Zahl ein.",
	"Please enter a date and/or time.": "Geben Sie ein Datum und/oder eine Uhrzeit ein.",
	"Please enter a currency.": "Geben Sie eine Währung ein.",
	"Unexpected file format.": "Unerwartetes Dateiformat.",
	"Cannot find this file.": "Diese Datei wurde nicht gefunden.",
	"Please verify that the correct path and file name are given.": "Stellen Sie sicher, dass die Pfad- und Dateinamenangabe richtig ist.",
	"Destination disk drive is full.": "Das Ziellaufwerk ist voll.",
	"Unable to read from %1, it is opened by someone else.": "%1 konnte nicht gelesen werden. Die Datei ist anderweitig geöffnet.",
	"Unable to write to %1, it is read-only or opened by someone else.": "Die Datei %1 konnte nicht geschrieben werden. Sie ist schreibgeschützt oder anderweitig geöffnet.",
	"An unexpected error occurred while reading %1.": "Beim Lesen von %1 ist ein unerwarteter Fehler aufgetreten.",
	"An unexpected error occurred while writing %1.": "Beim Schreiben von %1 ist ein unerwarteter Fehler aufgetreten.",
	"Unable to register document.": "Das Dokument konnte nicht registriert werden.",
	"The document may already be open.": "Das Dokument ist möglicherweise bereits geöffnet.",
	"Update %1 before proceeding?": "Möchten Sie %1 vor dem Fortsetzen aktualisieren?",
	"Could not update client.": "Client konnte nicht aktualisiert werden.",
	"Failed to register. ActiveX features may not work properly.": "Fehler beim Registrieren. Es können ggf. Fehler bei ActiveX-Funktionen auftreten.",
	"Failed to update the system registry.": "Die Systemregistrierung konnte nicht aktualisiert werden.",
	"Please try using REGEDIT.": "Aktualisieren Sie sie über REGEDIT.",
	"Unable to read write-only property.": "Das Schreibschutzattribut kann nicht gelesen werden.",
	"Unable to write read-only property.": "Das Schreibschutzattribut kann nicht geschrieben werden.",
	"Unable to load mail system support.": "Die Unterstützung für das Mailsystem konnte nicht geladen werden.",
	"Mail system DLL is invalid.": "Die DLL des Mailsystems ist ungültig.",
	"Send Mail failed to send message.": "Eine Nachricht konnte nicht gesendet werden.",
	"No error occurred.": "Kein Fehler.",
	"An unknown error occurred while accessing %1.": "Unbekannter Fehler beim Zugriff auf %1.",
	"%1 was not found.": "%1 wurde nicht gefunden.",
	"%1 contains an invalid path.": "%1 enthält eine ungültige Pfadangabe.",
	"%1 could not be opened because there are too many open files.": "%1 konnte nicht geöffnet werden, da zu viele Dateien geöffnet sind.",
	"Access to %1 was denied.": "Der Zugriff auf %1 wurde verweigert.",
	"An invalid file handle was associated with %1.": "%1 wurde eine ungültige Dateizugriffsnummer zugeordnet.",
	"%1 could not be removed because it is the current directory.": "%1 konnte nicht entfernt werden, da es das aktuelle Verzeichnis ist.",
	"%1 could not be created because the directory is full.": "%1 konnte nicht erstellt werden, da das Verzeichnis voll ist.",
	"Seek failed on %1": "Der Suchvorgang auf %1 ist fehlgeschlagen.",
	"A hardware I/O error was reported while accessing %1.": "Beim Zugriff auf %1 wurde ein Hardware-E/A-Fehler gemeldet.",
	"A sharing violation occurred while accessing %1.": "Zugriffsverletzung beim Zugriff auf %1.",
	"A locking violation occurred while accessing %1.": "Sperrverletzung beim Zugriff auf %1.",
	"Disk full while accessing %1.": "Festplatte war beim Zugriff auf %1 voll.",
	"An attempt was made to access %1 past its end.": "Es wurde versucht, auf eine Stelle hinter dem Ende von %1 zuzugreifen.",
	"An attempt was made to write to the reading %1.": "%1 ist nur lesbar. Es wurde versucht, darauf zu schreiben.",
	"An attempt was made to read from the writing %1.": "%1 ist lesegeschützt. Es wurde versucht, davon zu lesen.",
	"%1 has a bad format.": "%1 hat ein ungültiges Format.",
	"%1 contained an unexpected object.": "%1 enthält ein unerwartetes Objekt.",
	"%1 contains an incorrect schema.": "%1 enthält ein ungültiges Schema.",
	"Selects a rectangular part of the picture to move, copy, or edit.": "Markiert ein Rechteck zum Bearbeiten.",
	"Select": "Auswahl",
	"Selects a free-form part of the picture to move, copy, or edit.": "Markiert einen formfreien Ausschnitt zum Bearbeiten.",
	"Free-Form Select": "Freihandauswahl",
	"Inserts text into the picture.": "Fügt Text im Bild ein.",
	"Fills an area with the current drawing color.": "Füllt einen Bereich mit der aktuellen Farbe.",
	"Fill With Color": "Farbfüller",
	"Draws a straight line with the selected line width.": "Zeichnet eine Gerade mit der gewählten Strichbreite.",
	"Line": "Linien",
	"Draws using an airbrush of the selected size.": "Zeichnet mit dem gewählten Airbrushmuster.",
	"Draws a curved line with the selected line width.": "Zeichnet eine gekrümmte Linie mit der gewählten Strichbreite.",
	"Curve": "Bögen",
	"Draws a polygon with the selected fill style.": "Zeichnet ein Vieleck mit der gewählten Füllung.",
	"Polygon": "Vieleck",
	"Draws a rounded rectangle with the selected fill style.": "Zeichnet ein gerundetes Rechteck mit gewählter  Füllung.",
	"Rounded Rectangle": "Gerundetes Rechteck",
	"Draws a free-form line one pixel wide.": "Zeichnet eine formfreie Linie mit einem Pixel Breite.",
	"Pencil": "Stift",
	"Erases a portion of the picture, using the selected eraser shape.": "Löscht einen Bildbereich mit der gewählten Radiererform.",
	"Eraser/Color Eraser": "Radierer",
	"Changes the magnification.": "Ändert den Vergrößerungsfaktor.",
	"Magnifier": "Lupe",
	"Picks up a color from the picture for drawing.": "Wählt eine Farbe des Bildes zum Zeichnen aus.",
	"Pick Color": "Farbe auswählen",
	"Draws using a brush with the selected shape and size.": "Zeichnet mit dem Pinsel der gewählten Form und Größe.",
	"Brush": "Pinsel",
	"Draws a rectangle with the selected fill style.": "Zeichnet ein Rechteck mit gewählter Füllung.",
	"Rectangle": "Rechteck",
	"Draws a filled rectangle.": "Zeichnet ein gefülltes Rechteck.",
	"Draws an ellipse with the selected fill style.": "Zeichnet eine Ellipse mit gewählter Füllung.",
	"Draws a filled ellipse.": "Zeichnet eine gefüllte Ellipse.",
	"Makes the current selection either opaque or transparent.": "Macht die aktuelle Auswahl durchsichtig oder undurchsichtig.",
	"Creates a new color.": "Erstellt eine neue Farbe.",
	"Uses a previously saved palette of colors.": "Ruft eine zuvor gespeicherte Farbpalette auf.",
	"Saves the current palette of colors to a file.": "Speichert die aktuelle Farbpalette in einer Datei.",
	"You must save the file before choosing it as Wallpaper.": "Sie müssen die Datei speichern, bevor Sie sie als Hintergrund auswählen.",
	"The selection is now larger than the bitmap.": "Die Auswahl ist jetzt größer als die Bitmap.",
	"Would you like the bitmap enlarged?": "Möchten Sie die Bitmap vergrößern?",
	"The image in the clipboard is larger than the bitmap.": "Das Bild in der Zwischenablage ist größer als die Bitmap.",
	"The file is not in the correct format.": "Die Datei hat das falsche Format.",
	"Not enough room to paste text.": "Nicht genügend Platz zur Texteingabe.",
	"Enlarge the text area and try again.": "Vergrößern Sie vor der Eingabe das Textfeld.",
	"Places the text.": "Platziert den Text."
});
