//
// NOTE: This is a generated file! Don't edit it directly.
// Eventually community translation will be set up on some translation platform.
// 
// Generated with: npm run update-localization
//
loaded_localizations("pt", {
	"Attributes": "Atributos",
	"MS Shell Dlg": "MS Sans Serif",
	"&Width:": "&Largura:",
	"Width:": "Largura:",
	"&Height:": "&Altura:",
	"Height:": "Altura:",
	"Units": "Unidades",
	"&Inches": "Pol&egadas",
	"Inches": "Polegadas",
	"C&m": "&Cm",
	"Cm": "Cm",
	"Colors": "Cores",
	"&Black and white": "Preto e &branco",
	"Black and white": "Preto e branco",
	"Co&lors": "C&ores",
	"Transparency": "Transparência",
	"Use &Transparent background color": "Utilizar cor de fundo &transparente",
	"Use Transparent background color": "Utilizar cor de fundo transparente",
	"Select &Color": "&Seleccionar cor",
	"Select Color": "Seleccionar cor",
	"Cancel": "Cancelar",
	"&Default": "Pre&definido",
	"Default": "Predefinido",
	"Custom Zoom": "Personalizar zoom",
	"Current zoom:": "Zoom actual:",
	"Zoom to": "Aplicar zoom até",
	"Flip and Rotate": "Inverter e rodar",
	"Flip or rotate": "Inverter ou rodar",
	"&Flip horizontal": "&Inverter na horizontal",
	"Flip horizontal": "Inverter na horizontal",
	"Flip &vertical": "In&verter na vertical",
	"Flip vertical": "Inverter na vertical",
	"&Rotate by angle": "&Rodar por ângulo",
	"Rotate by angle": "Rodar por ângulo",
	"Stretch and Skew": "Esticar e torcer",
	"Stretch": "Esticar",
	"Skew": "Torcer",
	"Degrees": "graus",
	"Color Table": "Tabela de cores",
	"New": "Novo",
	"&New ": "&Novo ",
	"New ": "Novo ",
	"&Help": "&Ajuda",
	"Help": "Ajuda",
	"Printing": "A imprimir",
	"on the": "em",
	"&Print": "&Imprimir",
	"Print": "Imprimir",
	"&Next Page": "Página &seg.",
	"Next Page": "Página seg.",
	"Pre&v Page": "Página &ant.",
	"Prev Page": "Página ant.",
	"Zoom &In": "Mais &zoom",
	"Zoom In": "Mais zoom",
	"Zoom &Out": "Men&os zoom",
	"Zoom Out": "Menos zoom",
	"&Close": "Fe&char",
	"Close": "Fechar",
	"Grid Settings": "Definições de grelha",
	"                  ": "                                    ",
	"&Pixel Grid": "Grelha de &pixels",
	"Pixel Grid": "Grelha de pixels",
	"&Tile Grid": "Grelha de &mosaicos",
	"Tile Grid": "Grelha de mosaicos",
	"H&eight:": "&Altura:",
	"Undo": "Anular",
	"Cut": "Cortar",
	"Copy": "Copiar",
	"Paste": "Colar",
	"Clear Selection": "Limpar selecção",
	"Select All": "Seleccionar tudo",
	"Text Toolbar": "Barra de ferramentas de texto",
	"Cu&t": "Cor&tar",
	"&Copy": "&Copiar",
	"&Paste": "Co&lar",
	"C&lear Selection": "Limpar &selecção",
	"Select &All": "Seleccion&ar tudo",
	"C&opy To": "C&opiar para",
	"Copy To": "Copiar para",
	"Paste &From": "Colar &de",
	"Paste From": "Colar de",
	"Flip/&Rotate": "Inverter/&rodar",
	"Flip/Rotate": "Inverter/rodar",
	"&Stretch/Skew": "&Esticar/torcer",
	"Stretch/Skew": "Esticar/torcer",
	"&Invert Colors": "&Inverter cores",
	"Invert Colors": "Inverter cores",
	"Thumbnail": "Miniatura",
	"&File": "&Ficheiro",
	"File": "Ficheiro",
	"&New": "&Novo",
	"Ctrl+N": "Ctrl+O",
	"&Open": "&Abrir",
	"Open": "Abrir",
	"Ctrl+O": "Ctrl+A",
	"&Save": "&Guardar",
	"Save": "Guardar",
	"Ctrl+S": "Ctrl+G",
	"Save &As": "Guardar &como",
	"Save As": "Guardar como",
	"Print Pre&view": "&Pré-visualizar",
	"Print Preview": "Pré-visualizar",
	"Page Se&tup": "Config&urar página",
	"Page Setup": "Configurar página",
	"S&end": "&Enviar",
	"Send": "Enviar",
	"Set As &Wallpaper (Tiled)": "&Definir como imagem de fundo (mosaico)",
	"Set As Wallpaper (Tiled)": "Definir como imagem de fundo (mosaico)",
	"Set As Wa&llpaper (Centered)": "Definir como &fundo (centrado)",
	"Set As Wallpaper (Centered)": "Definir como fundo (centrado)",
	"Recent File": "Ficheiro recente",
	"E&xit": "&Sair",
	"Exit": "Sair",
	"&Edit": "&Editar",
	"Edit": "Editar",
	"&Undo": "An&ular",
	"&Repeat": "&Repetir",
	"Repeat": "Repetir",
	"Ctrl+A": "Ctrl+T",
	"&View": "&Ver",
	"View": "Ver",
	"&Tool Box": "Caixa de ferramen&tas",
	"Tool Box": "Caixa de ferramentas",
	"&Color Box": "&Caixa de cores",
	"Color Box": "Caixa de cores",
	"Ctrl+L": "Ctrl+A",
	"&Status Bar": "Barra de e&stado",
	"Status Bar": "Barra de estado",
	"T&ext Toolbar": "Barra de f&erramentas de texto",
	"&Normal Size": "&Tamanho normal",
	"Normal Size": "Tamanho normal",
	"&Large Size": "Tamanho &grande",
	"Large Size": "Tamanho grande",
	"C&ustom": "&Personalizar",
	"Custom": "Personalizar",
	"Show &Grid": "&Mostrar grelha",
	"Show Grid": "Mostrar grelha",
	"Show T&humbnail": "Mostrar mi&niatura",
	"Show Thumbnail": "Mostrar miniatura",
	"&View Bitmap": "&Ver mapa de bits",
	"View Bitmap": "Ver mapa de bits",
	"&Image": "&Imagem",
	"Image": "Imagem",
	"&Flip/Rotate": "I&nverter/rodar",
	"&Attributes": "&Atributos",
	"&Clear Image": "&Limpar imagem",
	"Clear Image": "Limpar imagem",
	"&Draw Opaque": "&Desenhar opaco",
	"Draw Opaque": "Desenhar opaco",
	"&Colors": "&Cores",
	"&Edit Colors": "&Editar cores",
	"Edit Colors": "Editar cores",
	"&Help Topics": "&Tópicos da Ajuda",
	"Help Topics": "Tópicos da Ajuda",
	"&About Paint": "&Acerca do Paint",
	"About Paint": "Acerca do Paint",
	"&Update": "Act&ualizar",
	"Update": "Actualizar",
	"Save Copy &As": "Guard&ar cópia como",
	"Save Copy As": "Guardar cópia como",
	"untitled": "Sem título",
	"Bitmap Image": "Imagem de mapa de bits",
	"Bitmap Files (*.bmp)": "Ficheiros de mapa de bits (*.bmp)",
	"PCX Files": "Ficheiros PCX",
	"Icon Files": "Ficheiros de ícones",
	"Monochrome Bitmap (*.bmp;*.dib)": "Mapa de bits monocromático (*.bmp;*.dib)",
	"16 Color Bitmap (*.bmp;*.dib)": "Mapa de bits de 16 cores (*.bmp;*.dib)",
	"256 Color Bitmap (*.bmp;*.dib)": "Mapa de bits de 256 cores (*.bmp;*.dib)",
	"Paint cannot open this file.": "O Paint não pode abrir este ficheiro.",
	"Paint cannot read this file.": "O Paint não pode ler este ficheiro.",
	"This file is read-only.": "Este ficheiro é só de leitura.",
	"To save your changes, use a different filename.": "Para guardar as alterações, utilize outro nome de ficheiro.",
	"This file is already open.": "Este ficheiro já está aberto.",
	"This is not a valid .PCS file.": "Este não é um ficheiro .PCS válido.",
	"This file is open for editing and cannot be overwritten.": "Este ficheiro está aberto para edição e não pode ser substituído.",
	"Use a different filename to save your changes.": "Utilize outro nome de ficheiro para guardar as alterações.",
	"This is not a valid bitmap file, or its format is not currently supported.": "Este não é um ficheiro de mapa de bits válido, ou o seu formato não é actualmente suportado.",
	"This is not a valid icon.": "Não é um ícone válido.",
	"This is not a valid cursor.": "Não é um cursor válido.",
	"Save was interrupted, so your file has not been saved.": "A operação de guardar foi interrompida, por isso o seu ficheiro não foi guardado.",
	"You cannot save to a read-only file.": "Não pode guardar num ficheiro só de leitura.",
	"Use a different file name.": "Utilize outro nome de ficheiro.",
	"This file is already in use.": "Este ficheiro já está a ser utilizado.",
	"Close the program, and then try again.": "Feche o programa e tente de novo.",
	"Paint cannot save this file.": "O Paint não pode guardar este ficheiro.",
	"Paint cannot save to the same filename with a different file type.": "O Paint não pode guardar num mesmo nome um tipo de ficheiro diferente.",
	"The grid spacing must be an integer between %d and %d.": "O espaçamento da grelha tem de ser um número inteiro entre %d e %d.",
	"There is not enough memory or resources to complete operation.": "Não existe memória suficiente ou recursos para concluir a operação.",
	"Close some programs, and then try again.": "Feche alguns programas e tente de novo.",
	"Low on memory or resources.": "Memória ou recursos insuficientes.",
	"Group error.": "Erro do grupo.",
	"Paint was unable to print your document. Please make sure you have sufficient disk space and that your printer is working correctly.": "O paint não conseguiu imprimir o seu documento. Certifique-se de que tem espaço suficiente em disco e que a sua impressora está a funcionar correctamente.",
	"Saving into this format may cause some loss of color information.": "Guardar neste formato pode causar perda de informação sobre a cor.",
	"Do you want to continue?": "Deseja continuar?",
	"Converting to black and white cannot be undone.  This action affects the current file and may cause some loss of color information.": "A conversão em preto e branco não pode ser anulada. Esta acção afecta o ficheiro actual e pode causar a perda de informação sobre as cores.",
	"Bitmaps must be greater than one pixel on a side.": "Os mapas de bits têm de ter mais que um pixel num dos lados.",
	"Generic error.": "Erro genérico.",
	"File not found.": "Ficheiro não encontrado.",
	"Bad path.": "Caminho incorrecto.",
	"Too many open files.": "Existem demasiados ficheiros abertos.",
	"Access denied.": "Acesso negado.",
	"Invalid file.": "Ficheiro inválido.",
	"Remove current folder.": "Remover pasta actual.",
	"Folder full.": "Pasta cheia.",
	"Bad seek.": "Pesquisa incorrecta.",
	"Hard IO error.": "Erro de entrada/saída.",
	"Sharing violation.": "Violação de partilha.",
	"Lock violation.": "Violação de bloqueio.",
	"Disk full.": "Disco cheio.",
	"End of file.": "Fim do ficheiro.",
	"Error getting the Clipboard Data!": "Erro ao obter os dados da Área de Transferência!",
	"No Printer Found @ page setup": "Não foi encontrada nenhuma impressora durante a configuração da página",
	"24-bit Bitmap (*.bmp;*.dib)": "Mapa de bits de 24 bits (*.bmp;*.dib)",
	"All Files": "Todos os ficheiros",
	"Palette|*.pal|": "Paleta|*.pal|",
	"OLE 2.0 was unable to start.": "O OLE 2.0 não foi iniciado.",
	"Make sure that you are using the correct version of the OLE libraries.": "Certifique-se de que está a utilizar a versão correcta das bibliotecas OLE.",
	"Resets the text be without any attributes.": "Repõe o texto sem quaisquer atributos.",
	"Sets or clears the text bold attribute.": "Activa ou desactiva o atributo de negrito no texto.",
	"Sets or clears the text italic attribute.": "Activa ou desactiva o atributo de itálico no texto.",
	"Selects the font used by the text.": "Selecciona o tipo de letra utilizado pelo texto.",
	"Selects the point size of the text.": "Selecciona o tamanho do texto em pontos.",
	"Sets or clears the text underline attribute.": "Define ou limpa o atributo de sublinhado no texto.",
	"Shows or hides the tooltips.": "Mostra ou oculta as descrições.",
	"Show Paint Help.": "Mostrar a ajuda do Paint.",
	"Sends a picture by using mail or fax.": "Envia uma imagem por correio ou fax.",
	"Copies the selection to a file.": "Copia a selecção para um ficheiro.",
	"Pastes a file into the selection.": "Cola um ficheiro na selecção.",
	"Zooms the picture to 100%.": "Mostra a imagem com 100% do seu tamanho original.",
	"Zooms the picture to 400%.": "Mostra a imagem com 400% do seu tamanho original.",
	"Zooms the picture.": "Aplica zoom à imagem.",
	"Displays the entire picture.": "Mostra a imagem completa.",
	"Shows or hides the thumbnail view of the picture.": "Mostra ou oculta a vista da miniatura da imagem.",
	"Shows or hides the grid.": "Mostra ou oculta a grelha.",
	"Shows or hides the text toolbar.": "Mostra ou oculta a barra de ferramentas de texto.",
	"Flips or rotates the picture or a selection.": "Inverte ou roda a imagem ou uma selecção.",
	"Stretches or skews the picture or a selection.": "Estica ou torce a imagem ou uma selecção.",
	"Inverts the colors of the picture or a selection.": "Inverte as cores da imagem ou de uma selecção.",
	"Changes the attributes of the picture.": "Altera os atributos da imagem.",
	"Clears the picture or selection.": "Limpa imagem ou selecção.",
	"The font size must be a numeric value.": "O tamanho do tipo de letra tem de ser um valor numérico.",
	"Contains commands for working with the selected item(s).": "Contém comandos para trabalhar com os itens seleccionados.",
	"Contains commands for selecting and transferring items.": "Contém comandos para seleccionar e transferir itens.",
	"Contains commands for customizing this window.": "Contém comandos para personalizar esta janela.",
	"Contains commands for manipulating pictures and setting attributes.": "Contém comandos para manipular imagens e definir atributos.",
	"Contains commands for using custom colors and drawing options.": "Contém comandos para utilizar cores personalizadas e opções de desenho.",
	"Contains commands for displaying Help for and information about Paint.": "Contém comandos para visualizar a ajuda e as informações sobre o Paint.",
	"Cannot save file.": "Impossível guardar o ficheiro.",
	"Error removing temporary file.": "Erro ao remover o ficheiro temporário.",
	"Get Colors": "Obter cores",
	"Save Colors": "Guardar cores",
	"File last saved:": "Última gravação do ficheiro:",
	"Not Available": "Não disponível",
	"Size on disk:": "Tamanho em disco:",
	"Painting": "A pintar",
	"Fonts": "Tipos de letra",
	"Tools": "Ferramentas",
	"All Picture Files": "Todos os ficheiros de imagens",
	"For Help, click Help Topics on the Help Menu.": "Para obter ajuda, faça clique sobre 'Tópicos da ajuda' no menu 'Ajuda'.",
	"Select an area on which to get Help.": "Seleccione uma área sobre a qual deseja obter ajuda.",
	"%1 in %2": "%1 em %2",
	"Creates a new document.": "Cria um novo documento.",
	"Opens an existing document.": "Abre um documento existente.",
	"Closes the active document.": "Fecha o documento activo.",
	"Saves the active document.": "Guarda o documento activo.",
	"Saves the active document with a new name.": "Guarda com um novo nome o documento activo.",
	"Changes the page layout.": "Altera o esquema da página.",
	"Specifies the default printer setup.": "Especifica a configuração da impressora predefinida.",
	"Prints the active document and sets printing options.": "Imprime o documento activo e define as opções de impressão.",
	"Displays full pages.": "Mostra páginas completas.",
	"Opens this document.": "Abre este documento.",
	"Deletes the selection.": "Elimina a selecção.",
	"Erases everything.": "Apaga tudo.",
	"Copies the selection and puts it on the Clipboard.": "Copia a selecção e coloca-a na Área de Transferência.",
	"Cuts the selection and puts it on the Clipboard.": "Corta a selecção e coloca-a na Área de Transferência.",
	"Finds the specified text.": "Localiza o texto especificado.",
	"Inserts the contents of the Clipboard.": "Insere o conteúdo da Área de Transferência.",
	"Repeats the last action.": "Repete a última acção.",
	"Replaces specific text with different text.": "Substitui texto específico por texto diferente.",
	"Selects everything.": "Selecciona tudo.",
	"Undoes the last action.": "Anula a última acção.",
	"Redoes the previously undone action.": "Repete a acção previamente anulada.",
	"Displays program information, version number, and copyright.": "Mostra informações sobre o programa, número da versão e copyright.",
	"Quits Paint.": "Sai do Paint.",
	"Opens Paint Help.": "Abre a ajuda do Paint.",
	"Displays instructions about how to use Help.": "Mostra instruções acerca do uso da ajuda.",
	"Displays Help for areas you click on.": "Mostra ajuda para as áreas em que fizer clique.",
	"Displays Help for the current task or command.": "Mostra a ajuda para a tarefa ou o comando actuais.",
	"Centers this bitmap as the desktop wallpaper.": "Centra este mapa de bits como imagem de fundo do Ambiente de Trabalho.",
	"Tiles this bitmap as the desktop wallpaper.": "Coloca este mapa de bits em mosaico como imagem de fundo do Ambiente de Trabalho.",
	"Sends the selection using mail or fax.": "Envia a selecção por correio ou por fax.",
	"Prints the selection.": "Imprime a selecção.",
	"Shows or hides the thumbnail.": "Mostra ou oculta a miniatura.",
	"Shows Paint Help.": "Mostra a ajuda do Paint.",
	"Shows or hides the status bar.": "Mostra ou oculta a barra de estado.",
	"Shows or hides the tool box.": "Mostra ou oculta a caixa de ferramentas.",
	"Shows or hides the color box.": "Mostra ou oculta a caixa de cores.",
	"Only a Far East font can be used for vertical editing.": "Só um tipo de letra do Oriente pode ser usado para editar verticalmente.",
	"Changes the window size.": "Altera o tamanho da janela.",
	"Changes the window position.": "Altera a posição da janela.",
	"Reduces the window to an icon.": "Reduz a janela a um ícone.",
	"Enlarges the window to full size.": "Aumenta a janela para ecrã inteiro.",
	"Switches to the next document window.": "Muda para a janela de documento seguinte.",
	"Switches to the previous document window.": "Muda para a janela de documento anterior.",
	"Closes the active window and asks if you want to save changes.": "Fecha a janela activa e pergunta se pretende guardar as alterações.",
	"Restores the window to normal size.": "Restaura o tamanho normal da janela.",
	"Activates the task list.": "Activa a lista de tarefas.",
	"All Files (*.*)": "Todos os ficheiros (*.*)",
	"Untitled": "Sem título",
	"an unnamed file": "um ficheiro sem nome",
	"&Hide": "&Ocultar",
	"Hide": "Ocultar",
	"No error message is available.": "Não existe nenhuma mensagem de erro disponível.",
	"An unsupported operation was attempted.": "Foi tentada uma operação não suportada.",
	"A required resource was unavailable.": "Um recurso necessário não estava disponível.",
	"Out of memory.": "Memória esgotada.",
	"An unknown error has occurred.": "Ocorreu um erro desconhecido.",
	"on %1": "em %1",
	"&One Page": "&Uma página",
	"One Page": "Uma página",
	"&Two Page": "&Duas pág.",
	"Two Page": "Duas pág.",
	"Page %u": "Página %u",
	"Pages %u-%u": "Páginas %u-%u",
	"Printer Files (*.prn)|*.prn|All Files (*.*)|*.*||": "Ficheiros de impressora (*.prn)|*.prn|Todos os ficheiros (*.*)|*.*||",
	"Print to File": "Imprimir para ficheiro",
	"to %1": "para %1",
	"&Update %1": "Act&ualizar %1",
	"Update %1": "Actualizar %1",
	"E&xit && Return to %1": "Sai&r e regressar a %1",
	"Exit && Return to %1": "Sair e regressar a %1",
	"Linked %s": "Ligado %s",
	"Unknown Type": "Tipo desconhecido",
	"Invalid filename.": "Nome de ficheiro inválido.",
	"Failed to open document.": "Ocorreu uma falha ao abrir o documento.",
	"Failed to save document.": "Ocorreu uma falha ao guardar o documento.",
	"Save changes to %1?": "Guardar as alterações a %1?",
	"Failed to create empty document.": "Ocorreu uma falha ao criar um documento vazio.",
	"The file is too large to open.": "O ficheiro é demasiado grande para ser aberto.",
	"Could not start print job.": "Não foi possível iniciar a tarefa de impressão.",
	"Failed to launch help.": "Ocorreu uma falha ao iniciar a ajuda.",
	"Internal application error.": "Erro interno da aplicação.",
	"Command failed.": "O comando falhou.",
	"Insufficient memory to perform operation.": "Memória insuficiente para efectuar a operação.",
	"System registry entries have been removed and the INI file (if any) was deleted.": "As entradas no registo do sistema foram removidas e o ficheiro INI (se existente) foi eliminado.",
	"Not all of the system registry entries (or INI file) were removed.": "Nem todas as entradas no registo do sistema (ou ficheiro INI) foram removidas.",
	"This program requires the file %s, which was not found on this system.": "Este programa necessita do ficheiro %s, que não foi encontrado no sistema.",
	"This program is linked to the missing export %s in the file %s. This machine may have an incompatible version of %s.": "Este programa está ligado à exportação %s em falta no ficheiro %s. Este computador pode ter uma versão incompatível de %s.",
	"Please enter an integer.": "Introduza um número inteiro.",
	"Please enter a number.": "Introduza um número.",
	"Please enter an integer between %1 and %2.": "Introduza um número inteiro entre %1 e %2.",
	"Please enter a number between %1 and %2.": "Introduza um número entre %1 e %2.",
	"Please enter no more than %1 characters.": "Não introduza mais que %1 caracteres.",
	"Please select a button.": "Seleccione um botão.",
	"Please enter an integer between 0 and 255.": "Introduza um número inteiro entre 0 e 255.",
	"Please enter a positive integer.": "Introduza um número inteiro positivo.",
	"Please enter a date and/or time.": "Introduza uma data e/ou hora.",
	"Please enter a currency.": "Introduza uma unidade monetária.",
	"Unexpected file format.": "Formato inesperado de ficheiro.",
	"Cannot find this file.": "Não é possível localizar este ficheiro.",
	"Please verify that the correct path and file name are given.": "Verifique se indicou correctamente o caminho e o nome de ficheiro.",
	"Destination disk drive is full.": "A unidade de destino está cheia.",
	"Unable to read from %1, it is opened by someone else.": "Não é possível ler a partir de %1. Está aberto por outro utilizador.",
	"Unable to write to %1, it is read-only or opened by someone else.": "Não foi possível escrever em %1. É só de leitura ou foi aberto por outro utilizador.",
	"An unexpected error occurred while reading %1.": "Ocorreu um erro inesperado ao ler %1.",
	"An unexpected error occurred while writing %1.": "Ocorreu um erro inesperado ao escrever %1.",
	"Unable to register document.": "Não é possível registar o documento.",
	"The document may already be open.": "O documento pode já estar aberto.",
	"Update %1 before proceeding?": "Deseja actualizar %1 antes de continuar?",
	"Could not update client.": "Não foi possível actualizar o cliente.",
	"Failed to register. ActiveX features may not work properly.": "Ocorreu uma falha ao registar. As funcionalidades do ActiveX podem não funcionar correctamente.",
	"Failed to update the system registry.": "Ocorreu uma falha ao actualizar o registo do sistema.",
	"Please try using REGEDIT.": "Tente utilizar o REGEDIT.",
	"Unable to read write-only property.": "Não é possível ler a propriedade só de escrita.",
	"Unable to write read-only property.": "Não é possível escrever a propriedade só de leitura.",
	"Unable to load mail system support.": "Não é possível carregar o suporte ao sistema de correio.",
	"Mail system DLL is invalid.": "A DLL do sistema de correio é inválida.",
	"Send Mail failed to send message.": "A função 'Enviar correio' falhou ao enviar a mensagem.",
	"No error occurred.": "Não ocorreu nenhum erro.",
	"An unknown error occurred while accessing %1.": "Ocorreu um erro desconhecido ao aceder a %1.",
	"%1 was not found.": "%1 não foi encontrado.",
	"%1 contains an invalid path.": "%1 contém um caminho inválido.",
	"%1 could not be opened because there are too many open files.": "Não foi possível abrir %1 porque há demasiados ficheiros abertos.",
	"Access to %1 was denied.": "Foi negado o acesso a %1.",
	"An invalid file handle was associated with %1.": "Foi associado a %1 um identificador de ficheiro inválido.",
	"%1 could not be removed because it is the current directory.": "Não foi possível remover %1 porque é o directório actual.",
	"%1 could not be created because the directory is full.": "Não foi possível criar %1 porque o directório está cheio.",
	"Seek failed on %1": "A procura falhou em %1",
	"A hardware I/O error was reported while accessing %1.": "Foi comunicado um erro de E/S de hardware ao aceder a %1.",
	"A sharing violation occurred while accessing %1.": "Ocorreu uma violação de partilha ao aceder a %1.",
	"A locking violation occurred while accessing %1.": "Ocorreu uma violação de bloqueio ao aceder a %1.",
	"Disk full while accessing %1.": "O disco ficou cheio ao aceder a %1.",
	"An attempt was made to access %1 past its end.": "Foi efectuada uma tentativa de aceder a %1 já depois do respectivo fim.",
	"An attempt was made to write to the reading %1.": "Foi efectuada uma tentativa de escrever em %1 (leitura).",
	"An attempt was made to read from the writing %1.": "Foi efectuada uma tentativa de ler a partir de %1 (escrita).",
	"%1 has a bad format.": "%1 tem um formato inválido.",
	"%1 contained an unexpected object.": "%1 continha um objecto inesperado.",
	"%1 contains an incorrect schema.": "%1 contém um esquema incorrecto.",
	"Selects a rectangular part of the picture to move, copy, or edit.": "Selecciona uma parte rectangular da imagem para mover, copiar ou editar.",
	"Select": "Seleccionar",
	"Selects a free-form part of the picture to move, copy, or edit.": "Selecciona de forma livre uma parte da imagem para mover, copiar ou editar.",
	"Free-Form Select": "Seleccionar forma livre",
	"Inserts text into the picture.": "Insere texto na imagem.",
	"Text": "Texto",
	"Fills an area with the current drawing color.": "Preenche uma área com a cor de desenho actual.",
	"Fill With Color": "Preencher com cor",
	"Draws a straight line with the selected line width.": "Desenha uma linha recta com a largura seleccionada.",
	"Line": "Linha",
	"Draws using an airbrush of the selected size.": "Desenha utilizando um aerógrafo do tamanho seleccionado.",
	"Airbrush": "Aerógrafo",
	"Draws a curved line with the selected line width.": "Desenha uma linha curva com a largura seleccionada.",
	"Curve": "Curva",
	"Draws a polygon with the selected fill style.": "Desenha um polígono com o estilo de preenchimento seleccionado.",
	"Polygon": "Polígono",
	"Draws a rounded rectangle with the selected fill style.": "Desenha um rectângulo arredondado com o estilo de preenchimento seleccionado.",
	"Rounded Rectangle": "Rectângulo arredondado",
	"Draws a free-form line one pixel wide.": "Desenha uma linha de forma livre com um pixel de largura.",
	"Pencil": "Lápis",
	"Erases a portion of the picture, using the selected eraser shape.": "Apaga uma parte da imagem utilizando a borracha com a forma seleccionada.",
	"Eraser/Color Eraser": "Borracha/apagar cor",
	"Changes the magnification.": "Altera a ampliação.",
	"Magnifier": "Lupa",
	"Picks up a color from the picture for drawing.": "Escolhe uma cor da imagem para o desenho.",
	"Pick Color": "Escolher cor",
	"Draws using a brush with the selected shape and size.": "Desenha utilizando um pincel com a forma e o tamanho seleccionados.",
	"Brush": "Pincel",
	"Draws a rectangle with the selected fill style.": "Desenha um rectângulo com o estilo de preenchimento seleccionado.",
	"Rectangle": "Rectângulo",
	"Draws a filled rectangle.": "Desenha um rectângulo preenchido.",
	"Draws an ellipse with the selected fill style.": "Desenha uma elipse com o estilo de preenchimento seleccionado.",
	"Ellipse": "Elipse",
	"Draws a filled ellipse.": "Desenha uma elipse preenchida.",
	"Makes the current selection either opaque or transparent.": "Torna a selecção actual opaca ou transparente.",
	"Creates a new color.": "Cria uma nova cor.",
	"Uses a previously saved palette of colors.": "Utiliza uma paleta de cores anteriormente guardada.",
	"Saves the current palette of colors to a file.": "Guarda a actual paleta de cores num ficheiro.",
	"You must save the file before choosing it as Wallpaper.": "Tem de guardar o ficheiro antes de o escolher como imagem de fundo.",
	"The selection is now larger than the bitmap.": "A selecção é maior que o mapa de bits.",
	"Would you like the bitmap enlarged?": "Deseja aumentar o mapa de bits?",
	"The image in the clipboard is larger than the bitmap.": "A imagem existente na Área de Transferência é maior que o mapa de bits.",
	"The file is not in the correct format.": "O ficheiro não tem o formato correcto.",
	"Not enough room to paste text.": "Não existe espaço suficiente para colar texto.",
	"Enlarge the text area and try again.": "Aumente a área de texto e tente de novo.",
	"Places the text.": "Coloca o texto."
});
