//
// NOTE: This is a generated file! Don't edit it directly.
// Eventually community translation will be set up on some translation platform.
// 
// Generated with: npm run update-localization
//
loaded_localizations("pl", {
	"Attributes": "Atrybuty",
	"&Width:": "&Szerokość:",
	"Width:": "Szerokość:",
	"&Height:": "W&ysokość:",
	"Height:": "Wysokość:",
	"Units": "Jednostki",
	"&Inches": "Cal&e",
	"Inches": "Cale",
	"&Pixels": "Pi&ksele",
	"Pixels": "Piksele",
	"Colors": "Kolory",
	"&Black and white": "&Czarno-biały",
	"Black and white": "Czarno-biały",
	"Co&lors": "K&olorowy",
	"Transparency": "Przezroczystość",
	"Use &Transparent background color": "Używaj &przezroczystego tła",
	"Use Transparent background color": "Używaj przezroczystego tła",
	"Select &Color": "&Wybierz kolor",
	"Select Color": "Wybierz kolor",
	"Cancel": "Anuluj",
	"&Default": "&Domyślne",
	"Default": "Domyślne",
	"Custom Zoom": "Powiększenie niestandardowe",
	"Current zoom:": "Bieżące powiększenie:",
	"Zoom to": "Powiększenie",
	"Flip and Rotate": "Przerzuć/obróć",
	"Flip or rotate": "Przerzuć lub obróć",
	"&Flip horizontal": "&Przerzuć w poziomie",
	"Flip horizontal": "Przerzuć w poziomie",
	"Flip &vertical": "Przerzuć w pio&nie",
	"Flip vertical": "Przerzuć w pionie",
	"&Rotate by angle": "&Obróć o kąt",
	"Rotate by angle": "Obróć o kąt",
	"Stretch and Skew": "Rozciągnij/pochyl",
	"Stretch": "Rozciągnij",
	"&Horizontal:": "W p&oziomie:",
	"Horizontal:": "W poziomie:",
	"&Vertical:": "W pio&nie:",
	"Vertical:": "W pionie:",
	"Skew": "Pochyl",
	"H&orizontal:": "W &poziomie:",
	"Degrees": "stopni",
	"V&ertical:": "&W pionie:",
	"Color Table": "Tabela kolorów",
	"New": "Nowy",
	"&New ": "&Nowy",
	"New ": "Nowy",
	"&Help": "Pomo&c",
	"Help": "Pomoc",
	"Printing": "Trwa drukowanie",
	"on the": "na",
	"&Print": "&Drukuj",
	"Print": "Drukuj",
	"&Next Page": "&Następna strona",
	"Next Page": "Następna strona",
	"Pre&v Page": "&Poprzednia strona",
	"Prev Page": "Poprzednia strona",
	"Zoom &In": "Po&większ",
	"Zoom In": "Powiększ",
	"Zoom &Out": "Po&mniejsz",
	"Zoom Out": "Pomniejsz",
	"&Close": "&Zamknij",
	"Close": "Zamknij",
	"Grid Settings": "Ustawienia siatki",
	"&Pixel Grid": "&Siatka pikseli",
	"Pixel Grid": "Siatka pikseli",
	"&Tile Grid": "Si&atka sąsiadująca",
	"Tile Grid": "Siatka sąsiadująca",
	"pixels": "pikseli",
	"H&eight:": "&Wysokość:",
	"Text": "Tekst",
	"Undo": "Cofnij",
	"Cut": "Wytnij",
	"Copy": "Kopiuj",
	"Paste": "Wklej",
	"Clear Selection": "Wyczyść zaznaczenie",
	"Select All": "Zaznacz wszystko",
	"Text Toolbar": "Pasek narzędzi tekstowych",
	"Selection": "Zaznaczenie",
	"Cu&t": "&Wytnij",
	"&Copy": "&Kopiuj",
	"&Paste": "Wkl&ej",
	"C&lear Selection": "Wyczyść z&aznaczenie",
	"Select &All": "Zaz&nacz wszystko",
	"C&opy To": "Kopiuj &do",
	"Copy To": "Kopiuj do",
	"Paste &From": "Wklej &z",
	"Paste From": "Wklej z",
	"Flip/&Rotate": "&Przerzuć/Obróć",
	"Flip/Rotate": "Przerzuć/Obróć",
	"&Stretch/Skew": "Roz&ciągnij/Pochyl",
	"Stretch/Skew": "Rozciągnij/Pochyl",
	"&Invert Colors": "&Odwróć kolory",
	"Invert Colors": "Odwróć kolory",
	"Thumbnail": "Miniatura",
	"&File": "&Plik",
	"File": "Plik",
	"&New": "&Nowy",
	"&Open": "&Otwórz",
	"Open": "Otwórz",
	"Ctrl+O": "Ctrl+0",
	"&Save": "&Zapisz",
	"Save": "Zapisz",
	"Save &As": "Z&apisz jako",
	"Save As": "Zapisz jako",
	"Print Pre&view": "&Podgląd wydruku",
	"Print Preview": "Podgląd wydruku",
	"Page Se&tup": "&Ustawienia strony",
	"Page Setup": "Ustawienia strony",
	"S&end": "&Wyślij",
	"Send": "Wyślij",
	"Set As &Wallpaper (Tiled)": "Ustaw jako &tapetę (sąsiadująco)",
	"Set As Wallpaper (Tiled)": "Ustaw jako tapetę (sąsiadująco)",
	"Set As Wa&llpaper (Centered)": "U&staw jako tapetę (wyśrodkowaną)",
	"Set As Wallpaper (Centered)": "Ustaw jako tapetę (wyśrodkowaną)",
	"Recent File": "Niedawno używany plik",
	"E&xit": "Za&kończ",
	"Exit": "Zakończ",
	"&Edit": "&Edycja",
	"Edit": "Edycja",
	"&Undo": "&Cofnij",
	"&Repeat": "&Powtórz",
	"Repeat": "Powtórz",
	"&View": "&Widok",
	"View": "Widok",
	"&Tool Box": "&Przybornik",
	"Tool Box": "Przybornik",
	"&Color Box": "Pole &koloru",
	"Color Box": "Pole koloru",
	"Ctrl+L": "Ctrl+A",
	"&Status Bar": "Pa&sek stanu",
	"Status Bar": "Pasek stanu",
	"T&ext Toolbar": "Pasek &narzędzi tekstowych",
	"&Zoom": "P&owiększenie",
	"Zoom": "Powiększenie",
	"&Normal Size": "&Normalny rozmiar",
	"Normal Size": "Normalny rozmiar",
	"&Large Size": "&Duży rozmiar",
	"Large Size": "Duży rozmiar",
	"C&ustom": "&Inny",
	"Custom": "Inny",
	"Show &Grid": "Pokaż &siatkę",
	"Show Grid": "Pokaż siatkę",
	"Show T&humbnail": "Pokaż &miniaturę",
	"Show Thumbnail": "Pokaż miniaturę",
	"&View Bitmap": "Pokaż &mapę bitową",
	"View Bitmap": "Pokaż mapę bitową",
	"&Image": "O&braz",
	"Image": "Obraz",
	"&Flip/Rotate": "&Przerzuć/Obróć",
	"&Attributes": "&Atrybuty",
	"&Clear Image": "&Wyczyść obraz",
	"Clear Image": "Wyczyść obraz",
	"&Draw Opaque": "Ry&suj nieprzezroczyste",
	"Draw Opaque": "Rysuj nieprzezroczyste",
	"&Colors": "K&olory",
	"&Edit Colors": "&Edytuj kolory",
	"Edit Colors": "Edytuj kolory",
	"&Help Topics": "&Tematy Pomocy",
	"Help Topics": "Tematy Pomocy",
	"&About Paint": "Paint — i&nformacje",
	"About Paint": "Paint — informacje",
	"&Update": "&Aktualizuj",
	"Update": "Aktualizuj",
	"Save Copy &As": "Z&apisz kopię jako",
	"Save Copy As": "Zapisz kopię jako",
	"untitled": "bez nazwy",
	"Bitmap Image": "Mapa bitowa",
	"Bitmap Files (*.bmp)": "Pliki map bitowych (*.bmp)",
	"Paint.Picture": "Pbraz Paint.",
	"PCX Files": "Pliki PCX",
	"Icon Files": "Pliki ikon",
	"Monochrome Bitmap (*.bmp;*.dib)": "Monochromatyczna mapa bitowa (*.bmp;*.dib)",
	"16 Color Bitmap (*.bmp;*.dib)": "Mapa bitowa 16 kolorowa  (*.bmp;*.dib)",
	"256 Color Bitmap (*.bmp;*.dib)": "Mapa bitowa 256 kolorowa (*.bmp;*.dib)",
	"Paint cannot open this file.": "Nie można otworzyć tego pliku w programie Paint. ",
	"Paint cannot read this file.": "Program Paint nie może odczytać tego pliku.",
	"This file is read-only.": "Ten plik jest tylko do odczytu.",
	"To save your changes, use a different filename.": "Aby zapisać zmiany, użyj innej nazwy pliku.",
	"This file is already open.": "Ten plik jest już otwarty.",
	"This is not a valid .PCS file.": "To nie jest poprawny plik .PCS.",
	"This file is open for editing and cannot be overwritten.": "Ten plik jest otwarty do edycji i nie można go zastąpić.",
	"Use a different filename to save your changes.": "Użyj innej nazwy pliku do zapisania zmian.",
	"This is not a valid bitmap file, or its format is not currently supported.": "To nie jest poprawny plik mapy bitowej.",
	"This is not a valid icon.": "To nie jest poprawna ikona.",
	"This is not a valid cursor.": "To nie jest poprawny kursor.",
	"Save was interrupted, so your file has not been saved.": "Proces zapisywania został przerwany, więc plik nie został zapisany.",
	"You cannot save to a read-only file.": "Nie można zapisać pliku tylko do odczytu",
	"Use a different file name.": "Użyj innej nazwy pliku.",
	"This file is already in use.": "Ten plik jest już używany.",
	"Close the program, and then try again.": "Zamknij program i ponów próbę.",
	"Paint cannot save this file.": "Zapisanie tego pliku jest niemożliwe.",
	"Paint cannot save to the same filename with a different file type.": "Nie można zapisać pliku z tą samą nazwą lecz innego typu",
	"The grid spacing must be an integer between %d and %d.": "Odstęp linii siatki musi być liczbą całkowitą pomiędzy %d i %d.",
	"There is not enough memory or resources to complete operation.": "Za mało pamięci lub zasobów do zakończenia operacji.",
	"Close some programs, and then try again.": "Zamknij kilka programów i spróbuj ponownie.",
	"Low on memory or resources.": "Za mało pamięci lub zasobów. Zamknij niektóre programy i spróbuj ponownie.",
	"Group error.": "Błąd grupowy.",
	"Paint was unable to print your document. Please make sure you have sufficient disk space and that your printer is working correctly.": "Program Paint nie mógł wydrukować dokumentu. Upewnij się czy ilość wolnej przestrzeni na dysku jest wystarczająca oraz czy drukarka działa poprawnie.",
	"Saving into this format may cause some loss of color information.": "Zachowanie w tym formacie może spowodować, że pewne informacje o kolorach mogą zostać utracone.",
	"Do you want to continue?": "Czy chcesz kontynuować?",
	"Converting to black and white cannot be undone.  This action affects the current file and may cause some loss of color information.": "Konwersja na format czarno-biały nie może zostać cofnięta. Akcja ta może spowodować zmiany w aktualnym pliku lub utratę informacji o kolorach.",
	"Bitmaps must be greater than one pixel on a side.": "Bok map bitowych musi mieć co najmniej jeden piksel.",
	"Generic error.": "Błąd ogólny.",
	"File not found.": "Nie odnaleziono pliku.",
	"Bad path.": "Błędna ścieżka.",
	"Too many open files.": "Za dużo otwartych plików.",
	"Access denied.": "Dostęp zabroniony.",
	"Invalid file.": "Nieprawidłowy plik.",
	"Remove current folder.": "Usuń bieżący folder.",
	"Folder full.": "Folder jest pełny.",
	"Bad seek.": "Błędne poszukiwanie.",
	"Hard IO error.": "Błąd sprzętowy We-Wy.",
	"Sharing violation.": "Naruszenie zasad współużytkowania.",
	"Lock violation.": "Naruszenie blokady.",
	"Disk full.": "Dysk jest pełny.",
	"End of file.": "Koniec pliku.",
	"Error getting the Clipboard Data!": "Błąd uzyskania danych ze Schowka!",
	"No Printer Found @ page setup": "Nie znaleziono drukarki @ układ strony",
	"24-bit Bitmap (*.bmp;*.dib)": "Mapa bitowa 24 bitowa (*.bmp;*.dib)",
	"All Files": "Wszystkie pliki",
	"Palette|*.pal|": "Paleta|*.pal|",
	"untitled.pal": "bez nazwy.pal",
	"OLE 2.0 was unable to start.": "Nie można był uruchomić łączenia i osadzania obiektów (OLE).",
	"Make sure that you are using the correct version of the OLE libraries.": "Należy się upewnić, czy jest używana prawidłowa wersja bibliotek OLE.",
	"Resets the text be without any attributes.": "Przywraca tekst bez żadnych atrybutów.",
	"Sets or clears the text bold attribute.": "Ustawia lub czyści atrybut tekstu pogrubionego.",
	"Sets or clears the text italic attribute.": "Ustawia lub czyści atrybut tekstu pisanego kursywą.",
	"Selects the font used by the text.": "Zaznacza czcionki używane w tekście.",
	"Selects the point size of the text.": "Zaznacz rozmiar punktowy tekstu.",
	"Sets or clears the text underline attribute.": "Ustawia lub czyści atrybut tekstu podkreślonego.",
	"Shows or hides the tooltips.": "Pokazuje lub ukrywa  etykietki.",
	"Show Paint Help.": "Pokaż Pomoc programu Paint.",
	"Sends a picture by using mail or fax.": "Wysyła obraz za pomocą poczty lub faksu.",
	"Copies the selection to a file.": "Kopiuje zaznaczenie do pliku.",
	"Pastes a file into the selection.": "Wkleja plik do zaznaczenia.",
	"Zooms the picture to 100%.": "Powiększa obraz do 100%.",
	"Zooms the picture to 400%.": "Powiększa obraz do 400%.",
	"Zooms the picture.": "Powiększa obraz.",
	"Displays the entire picture.": "Wyświetla cały obraz.",
	"Shows or hides the thumbnail view of the picture.": "Pokazuje lub ukrywa podgląd obrazu.",
	"Shows or hides the grid.": "Pokazuje lub ukrywa siatkę.",
	"Shows or hides the text toolbar.": "Pokazuje lub ukrywa tekstowy pasek narzędzi.",
	"Flips or rotates the picture or a selection.": "Przerzuca/obraca obraz lub zaznaczenie.",
	"Stretches or skews the picture or a selection.": "Rozciąga/pochyla obraz lub zaznaczenie.",
	"Inverts the colors of the picture or a selection.": "Odwraca kolory obrazu lub zaznaczenia.",
	"Changes the attributes of the picture.": "Zmienia atrybuty obrazu.",
	"Clears the picture or selection.": "Czyści obraz lub zaznaczenie.",
	"The font size must be a numeric value.": "Rozmiar czcionki musi być wartością liczbową.",
	"Contains commands for working with the selected item(s).": "Zawiera polecenia służące do pracy z wybranym elementem(elementami).",
	"Contains commands for selecting and transferring items.": "Zawiera polecenia służące do wybierania i przenoszenia elementów.",
	"Contains commands for customizing this window.": "Zawiera polecenia służące do dostosowania tego okna.",
	"Contains commands for manipulating pictures and setting attributes.": "Zawiera polecenia służące do manipulacji rysunkami i ustawiania atrybutów.",
	"Contains commands for using custom colors and drawing options.": "Zawiera polecenia służące do używania niestandardowych kolorów i opcji rysowania.",
	"Contains commands for displaying Help for and information about Paint.": "Zawiera polecenia służące do wyświetlania Pomocy i informacji o programie Paint.",
	"Cannot save file.": "Nie można zapisać pliku jest .",
	"Error removing temporary file.": "Błąd usuwania pliku tymczasowego.",
	"Get Colors": "Pobierz kolory",
	"Save Colors": "Zapisz kolory",
	"File last saved:": "Ostatnie zapisanie pliku:",
	"Not Available": "Niedostępne",
	"Size on disk:": "Rozmiar na dysku:",
	"%s bytes": "%s bajtów",
	"Painting": "Malowanie",
	"Fonts": "Czcionki",
	"Tools": "Narzędzia",
	"All Picture Files": "Wszystkie pliki rysunków",
	"For Help, click Help Topics on the Help Menu.": "Aby uzyskać Pomoc, kliknij polecenie Tematy Pomocy w menu Pomoc.",
	"Select an area on which to get Help.": "Wybierz obszar, na temat którego chcesz uzyskać Pomoc.",
	"%1 in %2": "%1 w %2",
	"Creates a new document.": "Tworzy nowy dokument.",
	"Opens an existing document.": "Otwiera istniejący dokument.",
	"Closes the active document.": "Zamyka aktywny dokument.",
	"Saves the active document.": "Zapisuje aktywny dokument.",
	"Saves the active document with a new name.": "Zapisuje aktywny dokument pod nową nazwą.",
	"Changes the page layout.": "Zmienia układ strony.",
	"Specifies the default printer setup.": "Określa ustawienie drukarki domyślnej.",
	"Prints the active document and sets printing options.": "Drukuje aktywny dokument i ustawia opcje wydruku.",
	"Displays full pages.": "Wyświetla całe strony.",
	"Opens this document.": "Otwiera ten dokument.",
	"Deletes the selection.": "Kasuje zaznaczenie.",
	"Erases everything.": "Kasuje wszystko.",
	"Copies the selection and puts it on the Clipboard.": "Kopiuje zaznaczenie i umieszcza je w Schowku.",
	"Cuts the selection and puts it on the Clipboard.": "Wycina zaznaczenie i wstawia je do Schowka.",
	"Finds the specified text.": "Znajduje określony tekst.",
	"Inserts the contents of the Clipboard.": "Wstawia zawartość Schowka.",
	"Repeats the last action.": "Powtarza ostatnią czynność.",
	"Replaces specific text with different text.": "Zamienia określony tekst na inny tekst.",
	"Selects everything.": "Zaznacza wszystko.",
	"Undoes the last action.": "Cofa ostatnią czynność.",
	"Redoes the previously undone action.": "Przywraca cofniętą uprzednio czynność.",
	"Displays program information, version number, and copyright.": "Wyświetla informacje o programie, numerze wersji i prawach autorskich.",
	"Quits Paint.": "Kończy działanie programu Paint.",
	"Opens Paint Help.": "Otwiera Pomoc programu Paint.",
	"Displays instructions about how to use Help.": "Wyświetla wskazówki na temat korzystania z Pomocy.",
	"Displays Help for areas you click on.": "Wyświetla Pomoc na temat klikniętych obszarów.",
	"Displays Help for the current task or command.": "Wyświetla Pomoc na temat bieżącego zadania lub polecenia.",
	"Centers this bitmap as the desktop wallpaper.": "Wyśrodkowuje tę mapę bitową jako tapetę pulpitu.",
	"Tiles this bitmap as the desktop wallpaper.": "Ustawia sąsiadująco tę mapę bitową jako tapetę pulpitu.",
	"Sends the selection using mail or fax.": "Wysyła zaznaczenie za pomocą poczty lub faksu.",
	"Prints the selection.": "Drukuje zaznaczenie.",
	"Shows or hides the thumbnail.": "Pokazuje lub ukrywa podgląd.",
	"Shows Paint Help.": "Pokazuje Pomoc programu Paint.",
	"Shows or hides the status bar.": "Pokazuje lub ukrywa pasek stanu.",
	"Shows or hides the tool box.": "Pokazuje lub ukrywa przybornik.",
	"Shows or hides the color box.": "Pokazuje lub ukrywa pole koloru.",
	"Only a Far East font can be used for vertical editing.": "Tylko czcionka Far East może być użyta do edycji pionowej.",
	"Changes the window size.": "Zmienia rozmiar okna.",
	"Changes the window position.": "Zmienia położenie okna.",
	"Reduces the window to an icon.": "Zmniejsza okno do ikony.",
	"Enlarges the window to full size.": "Powiększa okno do pełnego rozmiaru.",
	"Switches to the next document window.": "Przełącza do następnego okna dokumentu.",
	"Switches to the previous document window.": "Przełącza do poprzedniego okna dokumentu.",
	"Closes the active window and asks if you want to save changes.": "Zamyka aktywne okno i pyta, czy chcesz zapisać zmiany.",
	"Restores the window to normal size.": "Przywraca normalny rozmiar okna.",
	"Activates the task list.": "Uaktywnia listę zadań.",
	"All Files (*.*)": "Wszystkie pliki (*.*)",
	"Untitled": "Bez tytułu",
	"an unnamed file": "plik bez nazwy",
	"&Hide": "&Ukryj",
	"Hide": "Ukryj",
	"No error message is available.": "Komunikat o błędzie nie jest dostępny.",
	"An unsupported operation was attempted.": "Dokonano próby wykonania nieobsługiwanej operacji.",
	"A required resource was unavailable.": "Wymagane zasoby nie były dostępne.",
	"Out of memory.": "Za mało pamięci.",
	"An unknown error has occurred.": "Wystąpił nieznany błąd.",
	"on %1": "na %1",
	"&One Page": "&Jedna strona",
	"One Page": "Jedna strona",
	"&Two Page": "&Dwie strony",
	"Two Page": "Dwie strony",
	"Page %u": "Strona %u",
	"Pages %u-%u": "Strony %u-%u",
	"Printer Files (*.prn)|*.prn|All Files (*.*)|*.*||": "Pliki drukarki (*.prn)|*.prn|Wszystkie Pliki (*.*)|*.*||",
	"Print to File": "Drukuj do pliku",
	"to %1": "do %1",
	"&Update %1": "&Aktualizuj %1",
	"Update %1": "Aktualizuj %1",
	"E&xit && Return to %1": "Wy&jście && Powrót do %1",
	"Exit && Return to %1": "Wyjście && Powrót do %1",
	"Linked %s": "Łączony %s",
	"Unknown Type": "Nieznany typ",
	"Invalid filename.": "Niewłaściwa nazwa pliku.",
	"Failed to open document.": "Nie można otworzyć dokumentu.",
	"Failed to save document.": "Nie można zapisać dokumentu.",
	"Save changes to %1?": "Zapisać zmiany w %1?",
	"Failed to create empty document.": "Nie można utworzyć pustego dokumentu.",
	"The file is too large to open.": "Ten plik jest zbyt duży, aby go otworzyć.",
	"Could not start print job.": "Nie można rozpocząć zadania drukowania.",
	"Failed to launch help.": "Uruchomienie Pomocy nie powiodło się.",
	"Internal application error.": "Wewnętrzny błąd aplikacji.",
	"Command failed.": "Nie można wykonać polecenia.",
	"Insufficient memory to perform operation.": "Niewystarczająca ilość pamięci, aby wykonać operację.",
	"System registry entries have been removed and the INI file (if any) was deleted.": "Wpisy rejestru systemowego  i plik INI (jeżeli istniał) zostały usunięte.",
	"Not all of the system registry entries (or INI file) were removed.": "Nie wszystkie wpisy rejestru (lub pliku INI) zostały usunięte.",
	"This program requires the file %s, which was not found on this system.": "Nie znaleziony został plik %s, którego wymaga ten program..",
	"This program is linked to the missing export %s in the file %s. This machine may have an incompatible version of %s.": "Ten program jest podłączony do utraconego wyjścia %s w pliku %s. Komputer może posiadać niezgodną wersję %s.",
	"Please enter an integer.": "Wprowadź liczbę całkowitą.",
	"Please enter a number.": "Wprowadź liczbę.",
	"Please enter an integer between %1 and %2.": "Wprowadź całkowitą liczbę dodatnią z przedziału od %1 do %2.",
	"Please enter a number between %1 and %2.": "Wprowadź liczbę z przedziału od %1 do %2.",
	"Please enter no more than %1 characters.": "Wprowadź nie więcej znaków niż %1.",
	"Please select a button.": "Wybierz przycisk.",
	"Please enter an integer between 0 and 255.": "Wprowadź liczbę całkowitą z zakresu od 0 do 255.",
	"Please enter a positive integer.": "Wprowadź liczbę dodatnią.",
	"Please enter a date and/or time.": "Podaj datę i godzinę.",
	"Please enter a currency.": "Podaj walutę.",
	"Unexpected file format.": "Nieoczekiwany format pliku.",
	"Cannot find this file.": "Nie można odnaleźć pliku.",
	"Please verify that the correct path and file name are given.": "Upewnij się, czy podano  poprawną ścieżkę i nazwę pliku.",
	"Destination disk drive is full.": "Dysk docelowy jest pełny.",
	"Unable to read from %1, it is opened by someone else.": "Nie można odczytać z %1, jest on otwarty przez inną osobę.",
	"Unable to write to %1, it is read-only or opened by someone else.": "Nie można zapisać do %1, jest on tylko do odczytu lub jest otwarty przez inną osobę.",
	"An unexpected error occurred while reading %1.": "Wystąpił nieoczekiwany błąd podczas odczytu %1.",
	"An unexpected error occurred while writing %1.": "Wystąpił nieoczekiwany błąd podczas zapisu %1.",
	"Unable to register document.": "Nie można zarejestrować dokumentu.",
	"The document may already be open.": "Być może ten dokument jest już otwarty.",
	"Update %1 before proceeding?": "Czy aktualizować %1 przed wykonaniem polecenia?",
	"Could not update client.": "Nie można aktualizować danych klienta.",
	"Failed to register. ActiveX features may not work properly.": "Nie można zarejestrować. ActiveX może działać niesprawnie.",
	"Failed to update the system registry.": "Aktualizacja rejestru systemowego nie powiodła się.",
	"Please try using REGEDIT.": "Spróbuj użyć programu REGEDIT.",
	"Unable to read write-only property.": "Odczyt nie jest możliwy — właściwość tylko do zapisu.",
	"Unable to write read-only property.": "Nie można zapisać — właściwość tylko do odczytu.",
	"Unable to load mail system support.": "Nie można załadować obsługi systemu poczty.",
	"Mail system DLL is invalid.": "Biblioteka DLL systemu poczty jest nieprawidłowa.",
	"Send Mail failed to send message.": "Nie można wysłać wiadomości.",
	"No error occurred.": "Nie wystąpił żaden błąd.",
	"An unknown error occurred while accessing %1.": "Wystąpił nieznany błąd podczas dostępu do %1.",
	"%1 was not found.": "Nie znaleziono %1.",
	"%1 contains an invalid path.": "%1 zawiera nieprawidłową ścieżkę.",
	"%1 could not be opened because there are too many open files.": "%1 nie może być otwarty, ponieważ zbyt wiele plików jest otwartych.",
	"Access to %1 was denied.": "Brak dostępu do %1.",
	"An invalid file handle was associated with %1.": "Nieprawidłowe dojście było skojarzone z %1.",
	"%1 could not be removed because it is the current directory.": "%1 nie mógł być usunięty, ponieważ jest to bieżący katalog.",
	"%1 could not be created because the directory is full.": "%1 nie mógł być utworzony, ponieważ katalog jest pełny.",
	"Seek failed on %1": "Wyszukanie na %1 nie udało się.",
	"A hardware I/O error was reported while accessing %1.": "Zgłoszony został błąd sprzętowy we-wy podczas dostępu do %1.",
	"A sharing violation occurred while accessing %1.": "Nastąpiło naruszenie zasad współużytkowania podczas dostępu do %1.",
	"A locking violation occurred while accessing %1.": "Nastąpiło naruszenie blokady podczas dostępu do %1.",
	"Disk full while accessing %1.": "Dysk zapełniony podczas dostępu do %1.",
	"An attempt was made to access %1 past its end.": "Dokonano próby dostępu do %1 poza jego końcem.",
	"An attempt was made to write to the reading %1.": "Dokonano próby zapisu przy odczycie %1.",
	"An attempt was made to read from the writing %1.": "Dokonano próby odczytu przy zapisywaniu %1.",
	"%1 has a bad format.": "%1 ma zły format.",
	"%1 contained an unexpected object.": "%1 zawiera nie oczekiwany obiekt.",
	"%1 contains an incorrect schema.": "%1 zawiera nieprawidłowy schemat.",
	"Selects a rectangular part of the picture to move, copy, or edit.": "Zaznacza prostokątną część rysunku do przesunięcia, skopiowania lub edycji.",
	"Select": "Zaznacz",
	"Selects a free-form part of the picture to move, copy, or edit.": "Zaznacza część rysunku do przesunięcia, skopiowania lub edycji.",
	"Free-Form Select": "Zaznacz dowolny kształt",
	"Inserts text into the picture.": "Wstawia tekst do rysunku.",
	"Fills an area with the current drawing color.": "Wypełnia obszar bieżącym kolorem rysowania.",
	"Fill With Color": "Wypełnianie kolorem",
	"Draws a straight line with the selected line width.": "Rysuje linię prostą o wybranej grubości.",
	"Line": "Linia",
	"Draws using an airbrush of the selected size.": "Rysuje za pomocą aerografu o wybranym rozmiarze.",
	"Airbrush": "Aerograf",
	"Draws a curved line with the selected line width.": "Rysuje linię krzywą o wybranej grubości.",
	"Curve": "Krzywa",
	"Draws a polygon with the selected fill style.": "Rysuje wielokąt o wybranym stylu wypełnienia.",
	"Polygon": "Wielokąt",
	"Draws a rounded rectangle with the selected fill style.": "Rysuje zaokrąglony prostokąt o wybranym stylu wypełnienia.",
	"Rounded Rectangle": "Zaokrąglony prostokąt",
	"Draws a free-form line one pixel wide.": "Rysuje krzywą dowolnego kształtu o szerokości jednego piksela.",
	"Pencil": "Ołówek",
	"Erases a portion of the picture, using the selected eraser shape.": "Wymazuje część rysunku używając gumki o wybranym kształcie.",
	"Eraser/Color Eraser": "Gumka/Gumka kolorowa",
	"Changes the magnification.": "Zmienia powiększenie.",
	"Magnifier": "Lupa",
	"Picks up a color from the picture for drawing.": "Przejmuje kolor z rysunku do rysowania.",
	"Pick Color": "Weź kolor",
	"Draws using a brush with the selected shape and size.": "Rysuje pędzlem o wybranym kształcie i rozmiarze.",
	"Brush": "Pędzel",
	"Draws a rectangle with the selected fill style.": "Rysuje prostokąt o wybranym stylu wypełnienia.",
	"Rectangle": "Prostokąt",
	"Draws a filled rectangle.": "Rysuje wypełniony prostokąt.",
	"Draws an ellipse with the selected fill style.": "Rysuje elipsę o wybranym stylu wypełnienia.",
	"Ellipse": "Elipsa",
	"Draws a filled ellipse.": "Rysuje wypełnioną elipsę.",
	"Makes the current selection either opaque or transparent.": "Powoduje, że bieżące zaznaczenie jest przezroczyste lub nie.",
	"Creates a new color.": "Tworzy nowy kolor.",
	"Uses a previously saved palette of colors.": "Używa zapisanej uprzednio palety kolorów.",
	"Saves the current palette of colors to a file.": "Zapisuje bieżącą paletę kolorów w pliku.",
	"You must save the file before choosing it as Wallpaper.": "Przed wybraniem pliku jako tapety należy go zapisać.",
	"The selection is now larger than the bitmap.": "Zaznaczenie jest teraz większe niż mapa bitowa.",
	"Would you like the bitmap enlarged?": "Czy chcesz powiększyć mapę bitową?",
	"The image in the clipboard is larger than the bitmap.": "Obraz w Schowku jest większy niż mapa bitowa.",
	"The file is not in the correct format.": "Plik jest w nieprawidłowym formacie.",
	"Not enough room to paste text.": "Za mało miejsca do wklejenia tekstu.",
	"Enlarge the text area and try again.": "Powiększ obszar tekstu i spróbuj ponownie.",
	"Places the text.": "Umieszcza tekst."
});
