//
// NOTE: This is a generated file! Don't edit it directly.
// Eventually community translation will be set up on some translation platform.
// 
// Generated with: npm run update-localization
//
loaded_localizations("sl", {
	"Attributes": "Atributi",
	"MS Shell Dlg": "MS Sans Serif",
	"&Width:": "&Širina:",
	"Width:": "Širina:",
	"&Height:": "&Višina:",
	"Height:": "Višina:",
	"Units": "Enote",
	"&Inches": "pal&ci",
	"Inches": "palci",
	"C&m": "c&m",
	"Cm": "cm",
	"&Pixels": "p&el",
	"Pixels": "pel",
	"Colors": "Barve",
	"&Black and white": "&Črno-belo",
	"Black and white": "Črno-belo",
	"Co&lors": "&Barvno",
	"Transparency": "Prosojnost",
	"Use &Transparent background color": "&Prosojna barva ozadja",
	"Use Transparent background color": "Prosojna barva ozadja",
	"Select &Color": "&Izberi barvo ",
	"Select Color": "Izbira barve",
	"OK": "V redu",
	"Cancel": "Prekliči",
	"&Default": "P&rivzeto",
	"Default": "Privzeto",
	"Custom Zoom": "Po meri",
	"Current zoom:": "Trenutni faktor:",
	"Zoom to": "Faktor povečave",
	"Flip and Rotate": "Zrcaljenje in sukanje",
	"Flip or rotate": "Zrcaljenje ali sukanje",
	"&Flip horizontal": "&Vodoravno zrcaljenje",
	"Flip horizontal": "Vodoravno zrcaljenje",
	"Flip &vertical": "&Navpično zrcaljenje",
	"Flip vertical": "Navpično zrcaljenje",
	"&Rotate by angle": "Sukanje &za",
	"Rotate by angle": "Sukanje za",
	"Stretch and Skew": "Raztegovanje in nagibanje",
	"Stretch": "Raztegovanje",
	"&Horizontal:": "&Vodoravno:",
	"Horizontal:": "Vodoravno:",
	"&Vertical:": "&Navpično:",
	"Vertical:": "Navpično:",
	"Skew": "Nagibanje",
	"H&orizontal:": "V&odoravno:",
	"Degrees": "stopinj",
	"V&ertical:": "N&avpično:",
	"Color Table": "Barvna tabela",
	"New": "Nova",
	"&New ": "&Nova ",
	"New ": "Nova ",
	"&Help": "&Pomoč",
	"Help": "Pomoč",
	"Printing": "Tiskanje",
	"on the": "na",
	"&Print": "Na&tisni ",
	"Print": "Natisni ",
	"&Next Page": "&Naprej",
	"Next Page": "Naprej",
	"Pre&v Page": "N&azaj",
	"Prev Page": "Nazaj",
	"Zoom &In": "&Povečaj",
	"Zoom In": "Povečaj",
	"Zoom &Out": "P&omanjšaj",
	"Zoom Out": "Pomanjšaj",
	"&Close": "&Zapri",
	"Close": "Zapri",
	"Grid Settings": "Nastavitve mreže",
	"&Pixel Grid": "&Fina mreža",
	"Pixel Grid": "Fina mreža",
	"&Tile Grid": "&Groba mreža",
	"Tile Grid": "Groba mreža",
	"pixels": "slikovnih pik",
	"H&eight:": "&Višina:",
	"Text": "Besedilo",
	"Undo": "Razveljavi",
	"Cut": "Izreži",
	"Copy": "Kopiraj",
	"Paste": "Prilepi",
	"Clear Selection": "Izbriši izbor",
	"Select All": "Izberi vse",
	"Text Toolbar": "Oblikovanje besedila",
	"Selection": "Izbor",
	"Cu&t": "&Izreži",
	"&Copy": "&Kopiraj",
	"&Paste": "&Prilepi",
	"C&lear Selection": "Izbri&ši izbor",
	"Select &All": "Izberi &vse",
	"C&opy To": "Kopir&aj v ",
	"Copy To": "Kopiranje v datoteko",
	"Paste &From": "Pril&epi iz ",
	"Paste From": "Lepljenje v izbor",
	"Flip/&Rotate": "&Zrcali/Zasukaj ",
	"Flip/Rotate": "Zrcali/Zasukaj ",
	"&Stretch/Skew": "&Raztegni/Nagni ",
	"Stretch/Skew": "Raztegni/Nagni ",
	"&Invert Colors": "&Barvni negativ",
	"Invert Colors": "Barvni negativ",
	"Thumbnail": "Sličica",
	"&File": "&Datoteka",
	"File": "Datoteka",
	"&New": "&Nova",
	"&Open": "&Odpri ",
	"Open": "Odpri",
	"&Save": "&Shrani",
	"Save": "Shrani",
	"Save &As": "Shrani &kot ",
	"Save As": "Shrani kot",
	"Print Pre&view": "Pre&dogled tiskanja",
	"Print Preview": "Predogled tiskanja",
	"Page Se&tup": "P&riprava strani ",
	"Page Setup": "Priprava strani ",
	"S&end": "Po&šlji ",
	"Send": "Pošlji ",
	"Set As &Wallpaper (Tiled)": "Kot oz&adje (razpostavi)",
	"Set As Wallpaper (Tiled)": "Kot ozadje (razpostavi)",
	"Set As Wa&llpaper (Centered)": "Kot ozadj&e (na sredino)",
	"Set As Wallpaper (Centered)": "Kot ozadje (na sredino)",
	"Recent File": "Nedavna datoteka",
	"E&xit": "Iz&hod",
	"Exit": "Izhod",
	"&Edit": "&Urejanje",
	"Edit": "Urejanje",
	"&Undo": "&Razveljavi",
	"&Repeat": "P&onovi",
	"Repeat": "Ponovi",
	"&View": "Pogl&ed",
	"View": "Pogled",
	"&Tool Box": "&Orodja",
	"Tool Box": "Orodja",
	"&Color Box": "&Paleta z barvami",
	"Color Box": "Paleta z barvami",
	"Ctrl+L": "Ctrl+A",
	"&Status Bar": "&Vrstica stanja",
	"Status Bar": "Vrstica stanja",
	"T&ext Toolbar": "O&blikovanje besedila",
	"&Normal Size": "&Običajna velikost",
	"Normal Size": "Običajna velikost",
	"&Large Size": "&Velika povečava",
	"Large Size": "Velika povečava",
	"C&ustom": "&Po meri ",
	"Custom": "Po meri ",
	"Show &Grid": "Prikaži &mrežo",
	"Show Grid": "Prikaži mrežo",
	"Show T&humbnail": "Prikaži sl&ičico",
	"Show Thumbnail": "Prikaži sličico",
	"&View Bitmap": "&Celotna slika",
	"View Bitmap": "Celotna slika",
	"&Image": "&Slika",
	"Image": "Slika",
	"&Flip/Rotate": "&Zrcali/Zasukaj ",
	"&Attributes": "&Atributi ",
	"&Clear Image": "Izbri&ši sliko",
	"Clear Image": "Izbriši sliko",
	"Ctrl+Shft+N": "Ctrl+Shift+N",
	"&Draw Opaque": "&Riši prekrivajoče",
	"Draw Opaque": "Riši prekrivajoče",
	"&Colors": "&Barve",
	"&Edit Colors": "&Priprava barvne palete ",
	"Edit Colors": "Priprava barvne palete",
	"&Help Topics": "&Teme pomoči",
	"Help Topics": "Teme pomoči",
	"&About Paint": "Vi&zitka",
	"About Paint": "Vizitka",
	"&Update": "&Posodobi",
	"Update": "Posodobi",
	"Save Copy &As": "Shrani kopijo &kot ",
	"Save Copy As": "Shrani kopijo kot",
	"Paint": "Slikar",
	"untitled": "neimenovana",
	"Bitmap Image": "Bitna slika",
	"Bitmap Files (*.bmp)": "Datoteke z bitnimi slikami (*.bmp)",
	"PCX Files": "PCX datoteke",
	"Icon Files": "Ikonske datoteke",
	"Monochrome Bitmap (*.bmp;*.dib)": "Enobarvna bitna slika (*.bmp;*.dib)",
	"16 Color Bitmap (*.bmp;*.dib)": "16-barvna bitna slika (*.bmp;*.dib)",
	"256 Color Bitmap (*.bmp;*.dib)": "256-barvna bitna slika (*.bmp;*.dib)",
	"Paint cannot open this file.": "Datoteke ni mogoče odpreti.",
	"Paint cannot read this file.": "Datoteke ni mogoče prebrati.",
	"This file is read-only.": "Ta datoteka je samo za branje.",
	"To save your changes, use a different filename.": "Če želite shraniti spremembe, spremenite ime datoteke.",
	"This file is already open.": "Ta datoteka je že odprta.",
	"This is not a valid .PCS file.": "To ni veljavna .PCS datoteka.",
	"This file is open for editing and cannot be overwritten.": "Ta datoteka je v uporabi in je ni mogoče prepisati.",
	"Use a different filename to save your changes.": "Če želite shraniti spremembe, spremenite ime datoteke.",
	"This is not a valid bitmap file, or its format is not currently supported.": "To ni veljavna datoteka z bitno sliko oz. ta format trenutno ni podprt.",
	"This is not a valid icon.": "To ni veljavna ikona.",
	"This is not a valid cursor.": "To ni veljavna kazalka.",
	"Save was interrupted, so your file has not been saved.": "Shranjevanje je bilo prekinjeno, zato datoteka ni bila shranjena.",
	"You cannot save to a read-only file.": "Datoteke, ki je samo za branje, ne morete shraniti.",
	"Use a different file name.": "Spremenite ime datoteke.",
	"This file is already in use.": "Ta datoteka je v uporabi.",
	"Close the program, and then try again.": "Končajte program in poskusite znova.",
	"Paint cannot save this file.": "Datoteke ni mogoče shraniti.",
	"Paint cannot save to the same filename with a different file type.": "Datoteke ni mogoče zapisati z drugačno obliko zapisa pod istim imenom.",
	"The grid spacing must be an integer between %d and %d.": "Razmik med črtami mreže mora biti celo število v obsegu od %d do %d.",
	"There is not enough memory or resources to complete operation.": "Na voljo ni dovolj pomnilnika ali sredstev, da bi bilo mogoče dokončati operacijo.",
	"Close some programs, and then try again.": "Končajte nekaj programov in zatem poskusite znova.",
	"Low on memory or resources.": "Zmanjkuje pomnilnika ali sredstev.",
	"Group error.": "Napaka pri združevanju v skupino.",
	"Paint was unable to print your document. Please make sure you have sufficient disk space and that your printer is working correctly.": "Slikar ni uspel natisniti dokumenta. Poskrbite, da bo na disku dovolj prostora in da bo tiskalnik deloval pravilno.",
	"Saving into this format may cause some loss of color information.": "Shranjevanje v tej obliki ima lahko za posledico izgubo informacij o barvah.",
	"Do you want to continue?": "Ali želite nadaljevati?",
	"Converting to black and white cannot be undone.  This action affects the current file and may cause some loss of color information.": "Pretvorbe v črno-belo sliko ni mogoče razveljaviti. Taka pretvorba vpliva na trenutno datoteko in ima za posledico izgubo informacij o barvah.",
	"Bitmaps must be greater than one pixel on a side.": "Najmanjša razsežnost bitne slike sme biti ena slikovna pika.",
	"Generic error.": "Splošna napaka.",
	"File not found.": "Datoteke ni mogoče najti.",
	"Bad path.": "Neveljavna pot.",
	"Too many open files.": "Odprtih je preveč datotek.",
	"Access denied.": "Dostop zavrnjen.",
	"Invalid file.": "Neveljavna datoteka.",
	"Remove current folder.": "Izbriši trenutno mapo.",
	"Folder full.": "Mapa je polna.",
	"Bad seek.": "Napaka pri iskanju.",
	"Hard IO error.": "Vhodno-izhodna napaka.",
	"Sharing violation.": "Kršitev skupne rabe.",
	"Lock violation.": "Kršitev zaklepanja.",
	"Disk full.": "Disk je poln.",
	"End of file.": "Konec datoteke.",
	"Error getting the Clipboard Data!": "Napaka pri branju podatkov iz odložišča!",
	"No Printer Found @ page setup": "Med pripravo strani ni bilo mogoče najti tiskalnika",
	"24-bit Bitmap (*.bmp;*.dib)": "24-bitna bitna slika (*.bmp;*.dib)",
	"All Files": "Vse datoteke",
	"Palette|*.pal|": "Paleta|*.pal|",
	"OLE 2.0 was unable to start.": "OLE 2.0 ni bilo mogoče zagnati.",
	"Make sure that you are using the correct version of the OLE libraries.": "Poskrbite, da boste uporabljali pravo različico knjižnic OLE.",
	"Resets the text be without any attributes.": "Izklopi vse atribute besedila.",
	"Sets or clears the text bold attribute.": "Vklopi ali izklopi krepki tisk.",
	"Sets or clears the text italic attribute.": "Vklopi ali izklopi ležeči tisk.",
	"Selects the font used by the text.": "Izbira pisave za besedilo.",
	"Selects the point size of the text.": "Izbira velikosti besedila.",
	"Sets or clears the text underline attribute.": "Vklopi ali izklopi podčrtavanje besedila.",
	"Shows or hides the tooltips.": "Prikaže ali skrije opise orodij.",
	"Show Paint Help.": "Prikaže pomoč.",
	"Sends a picture by using mail or fax.": "Sliko odpošlje po elektronski pošti ali s faksom.",
	"Copies the selection to a file.": "Prekopira izbor v datoteko.",
	"Pastes a file into the selection.": "V izbor prilepi vsebino datoteke.",
	"Zooms the picture to 100%.": "Prikaže sliko v naravni velikosti.",
	"Zooms the picture to 400%.": "Prikaže sliko štirikrat povečano.",
	"Zooms the picture.": "Omogoča izbiro faktorja povečave.",
	"Displays the entire picture.": "Prikaže celotno sliko.",
	"Shows or hides the thumbnail view of the picture.": "Prikaže ali skrije sličico.",
	"Shows or hides the grid.": "Prikaže ali skrije mrežo.",
	"Shows or hides the text toolbar.": "Prikaže ali skrije vrstico za oblikovanje besedila.",
	"Flips or rotates the picture or a selection.": "Zrcali ali zasuka sliko ali izbor.",
	"Stretches or skews the picture or a selection.": "Raztegne ali nagne sliko ali izbor.",
	"Inverts the colors of the picture or a selection.": "Sliko ali izbor prikaže kot negativ.",
	"Changes the attributes of the picture.": "Spremeni atribute slike.",
	"Clears the picture or selection.": "Izbriše sliko ali izbor.",
	"The font size must be a numeric value.": "Za velikost pisave morate vnesti številko.",
	"Contains commands for working with the selected item(s).": "Ukazi za delo z izbranimi elementi.",
	"Contains commands for selecting and transferring items.": "Ukazi za izbiranje in prenos elementov.",
	"Contains commands for customizing this window.": "Ukazi za spreminjanje videza okna.",
	"Contains commands for manipulating pictures and setting attributes.": "Ukazi za obdelavo slik in postavljanje atributov.",
	"Contains commands for using custom colors and drawing options.": "Ukazi za uporabo namešanih barv in možnosti za risanje.",
	"Contains commands for displaying Help for and information about Paint.": "Ukaza za prikaz pomoči in informacij o programu.",
	"Cannot save file.": "Datoteke ni mogoče shraniti.",
	"Error removing temporary file.": "Napaka pri brisanju začasne datoteke.",
	"Get Colors": "Odpiranje barvne palete",
	"Save Colors": "Shranjevanje barvne palete",
	"File last saved:": "Zadnjič shranjeno:",
	"Not Available": "ni na voljo",
	"Size on disk:": "Velikost na disku:",
	"%s bytes": "%sB",
	"Painting": "Slikanje",
	"Fonts": "Pisave",
	"Tools": "Orodja",
	"All Picture Files": "vse slikovne datoteke",
	"For Help, click Help Topics on the Help Menu.": "Če potrebujete pomoč, kliknite ukaz »Teme pomoči« v meniju »Pomoč«.",
	"Select an area on which to get Help.": "Izberite področje, o katerem želite dobiti informacije.",
	"%1 in %2": "%1 v %2",
	"Creates a new document.": "Ustvari nov dokument.",
	"Opens an existing document.": "Odpre obstoječ dokument.",
	"Closes the active document.": "Zapre aktivni dokument.",
	"Saves the active document.": "Shrani aktivni dokument.",
	"Saves the active document with a new name.": "Shrani aktivni dokument pod novim imenom.",
	"Changes the page layout.": "Spremeni postavitev strani.",
	"Specifies the default printer setup.": "Definira privzete nastavitve za tiskalnik.",
	"Prints the active document and sets printing options.": "Omogoča nastavitev možnosti za tiskanje in natisne dokument.",
	"Displays full pages.": "Prikaže cele strani.",
	"Opens this document.": "Odpre ta dokument.",
	"Deletes the selection.": "Izbriše izbor.",
	"Erases everything.": "Izbriše vse.",
	"Copies the selection and puts it on the Clipboard.": "Prekopira izbor in ga shrani v odložišče.",
	"Cuts the selection and puts it on the Clipboard.": "Izreže izbor in ga shrani v odložišče.",
	"Finds the specified text.": "Poišče navedeno besedilo.",
	"Inserts the contents of the Clipboard.": "Vstavi vsebino odložišča.",
	"Repeats the last action.": "Ponovi zadnje dejanje.",
	"Replaces specific text with different text.": "Zamenja določeno besedilo z drugim.",
	"Selects everything.": "Izbere vse.",
	"Undoes the last action.": "Razveljavi zadnje dejanje.",
	"Redoes the previously undone action.": "Ponovno uveljavi prej razveljavljeno dejanje.",
	"Displays program information, version number, and copyright.": "Informacije o programu, številki različice in avtorskih pravicah.",
	"Quits Paint.": "Izhod iz programa.",
	"Opens Paint Help.": "Odpre pomoč.",
	"Displays instructions about how to use Help.": "Prikaže navodila za uporabo pomoči.",
	"Displays Help for areas you click on.": "Prikaže opis elementa, ki ga kliknete.",
	"Displays Help for the current task or command.": "Prikaže pojasnilo v zvezi s trenutnim opravilom ali ukazom.",
	"Centers this bitmap as the desktop wallpaper.": "Sliko za ozadje ustvari tako, da postavi bitno sliko na sredino.",
	"Tiles this bitmap as the desktop wallpaper.": "Sliko za ozadje ustvari tako, da razpostavi bitne slike po zaslonu.",
	"Sends the selection using mail or fax.": "Izbor odpošlje po elektronski pošti ali s faksom.",
	"Prints the selection.": "Natisne izbor.",
	"Shows or hides the thumbnail.": "Prikaže ali skrije sličico.",
	"Shows Paint Help.": "Prikaže pomoč.",
	"Shows or hides the status bar.": "Prikaže ali skrije vrstico stanja.",
	"Shows or hides the tool box.": "Prikaže ali skrije orodja.",
	"Shows or hides the color box.": "Prikaže ali skrije barvno paleto.",
	"Only a Far East font can be used for vertical editing.": "Za navpično urejanje lahko uporabite samo daljnevzhodno pisavo.",
	"Changes the window size.": "Spremeni velikost okna.",
	"Changes the window position.": "Spremeni položaj okna.",
	"Reduces the window to an icon.": "Zmanjša okno na velikost ikone.",
	"Enlarges the window to full size.": "Poveča okno na največjo velikost.",
	"Switches to the next document window.": "Preklopi v naslednje dokumentno okno.",
	"Switches to the previous document window.": "Preklopi v prejšnje dokumentno okno.",
	"Closes the active window and asks if you want to save changes.": "Zapre aktivno okno in vas povpraša, ali želite shraniti spremembe.",
	"Restores the window to normal size.": "Obnovi običajno velikost okna.",
	"Activates the task list.": "Aktivira seznam opravil.",
	"All Files (*.*)": "Vse datoteke (*.*)",
	"Untitled": "Neimenovana",
	"an unnamed file": "neimenovana datoteka",
	"&Hide": "&Skrij",
	"Hide": "Skrij",
	"No error message is available.": "Na voljo ni nobenega sporočila o napaki.",
	"An unsupported operation was attempted.": "Prišlo je do poskusa izvedbe nepodprte operacije.",
	"A required resource was unavailable.": "Zahtevano sredstvo ni bilo na voljo.",
	"Out of memory.": "Zmanjkalo je pomnilnika.",
	"An unknown error has occurred.": "Prišlo je do neznane napake.",
	"on %1": "na %1",
	"&One Page": "&Ena stran",
	"One Page": "Ena stran",
	"&Two Page": "&Dve strani",
	"Two Page": "Dve strani",
	"Page %u": "Stran %u",
	"Pages %u-%u": "Strani %u-%u",
	"Printer Files (*.prn)|*.prn|All Files (*.*)|*.*||": "Tiskalniške datoteke (*.prn)|*.prn|Vse datoteke (*.*)|*.*||",
	"Print to File": "Tiskanje v datoteko",
	"to %1": "v %1",
	"&Update %1": "&Posodobi %1",
	"Update %1": "Posodobi %1",
	"E&xit && Return to %1": "I&zhod in vrnitev v %1",
	"Exit && Return to %1": "Izhod in vrnitev v %1",
	"Linked %s": "Povezan %s",
	"Unknown Type": "Neznana vrsta",
	"Invalid filename.": "Neveljavno ime datoteke.",
	"Failed to open document.": "Dokumenta ni bilo mogoče odpreti.",
	"Failed to save document.": "Dokumenta ni bilo mogoče shraniti.",
	"Save changes to %1?": "Ali želite shraniti spremembe v %1?",
	"Failed to create empty document.": "Praznega dokumenta ni bilo mogoče ustvariti.",
	"The file is too large to open.": "Datoteke ni mogoče odpreti, ker je prevelika.",
	"Could not start print job.": "Tiskalnega posla ni bilo mogoče začeti.",
	"Failed to launch help.": "Pomoči ni bilo mogoče zagnati.",
	"Internal application error.": "Notranja napaka programa.",
	"Command failed.": "Ukaz se ni izvedel.",
	"Insufficient memory to perform operation.": "Za izvedbo operacije ni dovolj pomnilnika.",
	"System registry entries have been removed and the INI file (if any) was deleted.": "Vnosi v sistemski register so bili odstranjeni in INI datoteka je bila izbrisana.",
	"Not all of the system registry entries (or INI file) were removed.": "Vsi vnosi v sistemski register (ali INI datoteko) niso bili odstranjeni.",
	"This program requires the file %s, which was not found on this system.": "Ta program zahteva datoteko %s, ki je na tem računalniku ni bilo mogoče najti.",
	"This program is linked to the missing export %s in the file %s. This machine may have an incompatible version of %s.": "Ta program je povezan z manjkajočim %s v datoteki %s. Morda ima ta računalnik nezdružljivo različico %s.",
	"Please enter an integer.": "Vnesite celo število.",
	"Please enter a number.": "Vnesite število.",
	"Please enter an integer between %1 and %2.": "Vnesite celo število med %1 in %2.",
	"Please enter a number between %1 and %2.": "Vnesite število med %1 in %2.",
	"Please enter no more than %1 characters.": "Največje dovoljeno število znakov je %1.",
	"Please select a button.": "Izberite gumb.",
	"Please enter an integer between 0 and 255.": "Vnesite celo število med 0 in 255.",
	"Please enter a positive integer.": "Vnesite pozitivno celo število.",
	"Please enter a date and/or time.": "Vnesite datum in/ali čas.",
	"Please enter a currency.": "Vnesite valuto.",
	"Unexpected file format.": "Nepričakovana oblika zapisa datoteke.",
	"Cannot find this file.": "Te datoteke ni mogoče najti.",
	"Please verify that the correct path and file name are given.": "Preverite, ali ste pravilno vnesli ime datoteke in mesto.",
	"Destination disk drive is full.": "Ciljni pogon je poln.",
	"Unable to read from %1, it is opened by someone else.": "Datoteke %1 ni mogoče brati, ker jo je odprl nekdo drug.",
	"Unable to write to %1, it is read-only or opened by someone else.": "V datoteko %1 ni mogoče pisati, ker je samo za branje ali pa jo ima nekdo odprto.",
	"An unexpected error occurred while reading %1.": "Pri branju %1 je prišlo do nepričakovane napake.",
	"An unexpected error occurred while writing %1.": "Pri pisanju %1 je prišlo do nepričakovane napake.",
	"Unable to register document.": "Dokumenta ni mogoče registrirati.",
	"The document may already be open.": "Morda je že odprt.",
	"Update %1 before proceeding?": "Ali želite zdaj posodobiti %1?",
	"Could not update client.": "Odjemalca ni bilo mogoče posodobiti.",
	"Failed to register. ActiveX features may not work properly.": "Registracija ni uspela. ActiveX funkcije morda ne bodo delovale pravilno.",
	"Failed to update the system registry.": "Sistemskega registra ni bilo mogoče posodobiti.",
	"Please try using REGEDIT.": "Poskusite uporabiti REGEDIT.",
	"Unable to read write-only property.": "Lastnosti »samo za pisanje« ni mogoče prebrati.",
	"Unable to write read-only property.": "Lastnosti »samo za branje« ni mogoče zapisati.",
	"Unable to load mail system support.": "Podpore za poštni sistem ni bilo mogoče naložiti.",
	"Mail system DLL is invalid.": "DLL knjižnica poštnega sistema ni veljavna.",
	"Send Mail failed to send message.": "Sporočila ni bilo mogoče poslati.",
	"No error occurred.": "Brez napak",
	"An unknown error occurred while accessing %1.": "Pri dostopu do %1 je prišlo do neznane napake.",
	"%1 was not found.": "%1 ni bilo mogoče najti.",
	"%1 contains an invalid path.": "%1 vsebuje neveljavno pot.",
	"%1 could not be opened because there are too many open files.": "%1 ni bilo mogoče odpreti, ker je preveč odprtih datotek.",
	"Access to %1 was denied.": "Dostop do %1 je bil zavrnjen.",
	"An invalid file handle was associated with %1.": "Datoteki %1 je bila dodeljena neveljavna koda za dostop.",
	"%1 could not be removed because it is the current directory.": "%1 ni mogoče odstraniti, ker je to trenutna mapa.",
	"%1 could not be created because the directory is full.": "%1 ni bilo mogoče ustvariti, ker je mapa polna.",
	"Seek failed on %1": "Pozicioniranje na %1 je spodletelo.",
	"A hardware I/O error was reported while accessing %1.": "Pri dostopu do %1 je bila javljena V/I napaka.",
	"A sharing violation occurred while accessing %1.": "Pri dostopu do %1 je prišlo do kršitve skupne rabe.",
	"A locking violation occurred while accessing %1.": "Pri dostopu do %1 je prišlo do kršitve zaklepanja.",
	"Disk full while accessing %1.": "Pri dostopu do %1 je na disku zmanjkalo prostora.",
	"An attempt was made to access %1 past its end.": "Prišlo je do poskusa dostopa prek konca %1.",
	"An attempt was made to write to the reading %1.": "Prišlo je do poskusa pisanja v brano %1.",
	"An attempt was made to read from the writing %1.": "Prišlo je do poskusa branja iz zapisovane %1.",
	"%1 has a bad format.": "%1 ima napačno obliko zapisa.",
	"%1 contained an unexpected object.": "%1 vsebuje nepričakovani predmet.",
	"%1 contains an incorrect schema.": "%1 vsebuje nepravilno shemo.",
	"Selects a rectangular part of the picture to move, copy, or edit.": "Označi pravokotni del slike, ki ga lahko premaknete, kopirate ali uredite.",
	"Select": "Izbor",
	"Selects a free-form part of the picture to move, copy, or edit.": "Izbere poljubno oblikovan del slike, ki ga lahko premaknete, kopirate ali uredite.",
	"Free-Form Select": "Prostoročni izbor",
	"Inserts text into the picture.": "V sliko vstavi besedilo.",
	"Fills an area with the current drawing color.": "Področje zapolni s trenutno izbrano barvo.",
	"Fill With Color": "Barvno polnilo",
	"Draws a straight line with the selected line width.": "Risanje ravne črte izbrane širine.",
	"Line": "Črta",
	"Draws using an airbrush of the selected size.": "Risanje z razpršilcem izbrane širine.",
	"Airbrush": "Razpršilec",
	"Draws a curved line with the selected line width.": "Risanje krivulje izbrane širine.",
	"Curve": "Krivulja",
	"Draws a polygon with the selected fill style.": "Risanje mnogokotnika z izbranim polnilom.",
	"Polygon": "Mnogokotnik",
	"Draws a rounded rectangle with the selected fill style.": "Risanje zaobljenega pravokotnika z izbranim polnilom.",
	"Rounded Rectangle": "Zaobljeni pravokotnik",
	"Draws a free-form line one pixel wide.": "Prostoročno risanje črte s širino ene slikovne pike.",
	"Pencil": "Svinčnik",
	"Erases a portion of the picture, using the selected eraser shape.": "Brisanje dela slike z izbrano vrsto radirke.",
	"Eraser/Color Eraser": "Radirka/Barvna radirka",
	"Changes the magnification.": "Spremeni povečavo.",
	"Magnifier": "Lupa",
	"Picks up a color from the picture for drawing.": "Orodje za izbiro barve risanja iz slike.",
	"Pick Color": "Kapalka",
	"Draws using a brush with the selected shape and size.": "Risanje s čopičem izbrane oblike in velikosti.",
	"Brush": "Čopič",
	"Draws a rectangle with the selected fill style.": "Risanje pravokotnika z izbranim polnilom.",
	"Rectangle": "Pravokotnik",
	"Draws a filled rectangle.": "Risanje pobarvanega pravokotnika.",
	"Draws an ellipse with the selected fill style.": "Risanje elipse z izbranim polnilom.",
	"Ellipse": "Elipsa",
	"Draws a filled ellipse.": "Risanje pobarvane elipse.",
	"Makes the current selection either opaque or transparent.": "Naredi trenutni izbor prozoren ali neprozoren.",
	"Creates a new color.": "Ustvari novo barvo.",
	"Uses a previously saved palette of colors.": "Odpre shranjeno barvno paleto.",
	"Saves the current palette of colors to a file.": "Trenutno barvno paleto shrani v datoteko.",
	"You must save the file before choosing it as Wallpaper.": "Datoteko morate shraniti, preden jo lahko uporabite kot ozadje.",
	"The selection is now larger than the bitmap.": "Izbor je večji kot bitna slika.",
	"Would you like the bitmap enlarged?": "Ali želite povečati bitno sliko?",
	"The image in the clipboard is larger than the bitmap.": "Slika v odložišču je večja kot bitna slika.",
	"The file is not in the correct format.": "Oblika zapisa datoteke ni pravilna.",
	"Not enough room to paste text.": "Na voljo ni dovolj prostora, da bi bilo mogoče prilepiti besedilo.",
	"Enlarge the text area and try again.": "Povečajte področje za besedilo in poskusite znova.",
	"Places the text.": "Namesti besedilo."
});
