//
// NOTE: This is a generated file! Don't edit it directly.
// Eventually community translation will be set up on some translation platform.
// 
// Generated with: npm run update-localization
//
loaded_localizations("zh-simplified", {
	"Attributes": "属性",
	"MS Shell Dlg": "宋体",
	"&Width:": "宽度(&W):",
	"Width:": "宽度:",
	"&Height:": "高度(&H):",
	"Height:": "高度:",
	"Units": "单位",
	"&Inches": "英寸(&I)",
	"Inches": "英寸",
	"C&m": "厘米(&M)",
	"Cm": "厘米",
	"&Pixels": "象素(&P)",
	"Pixels": "象素",
	"Colors": "颜色",
	"&Black and white": "黑白(&B)",
	"Black and white": "黑白",
	"Co&lors": "颜色(&L)",
	"Transparency": "透明胶片",
	"Use &Transparent background color": "使用透明背景颜色(&T)",
	"Use Transparent background color": "使用透明背景颜色",
	"Select &Color": "选择颜色(&C)",
	"Select Color": "选择颜色",
	"OK": "确定",
	"Cancel": "取消",
	"&Default": "默认(&D)",
	"Default": "默认",
	"Custom Zoom": "自定义缩放",
	"Current zoom:": "当前缩放比例:",
	"Zoom to": "缩放比例",
	"&100%": "100%(&1)",
	"100%": "100%",
	"&200%": "200%(&2)",
	"200%": "200%",
	"&400%": "400%(&4)",
	"400%": "400%",
	"&600%": "600%(&6)",
	"600%": "600%",
	"&800%": "800%(&8)",
	"800%": "800%",
	"Flip and Rotate": "翻转和旋转",
	"Flip or rotate": "翻转或旋转",
	"&Flip horizontal": "水平翻转(&F)",
	"Flip horizontal": "水平翻转",
	"Flip &vertical": "垂直翻转(&V)",
	"Flip vertical": "垂直翻转",
	"&Rotate by angle": "按一定角度旋转(&R)",
	"Rotate by angle": "按一定角度旋转",
	"&90°": "90 度(&9)",
	"90°": "90 度",
	"&180°": "180 度(&1)",
	"180°": "180 度",
	"&270°": "270 度(&2)",
	"270°": "270 度",
	"Stretch and Skew": "拉伸和扭曲",
	"Stretch": "拉伸",
	"&Horizontal:": "水平(&H):",
	"Horizontal:": "水平:",
	"&Vertical:": "垂直(&V):",
	"Vertical:": "垂直:",
	"Skew": "扭曲",
	"H&orizontal:": "水平(&O):",
	"Degrees": "度",
	"V&ertical:": "垂直(&E):",
	"Color Table": "颜色表",
	"New": "新建",
	"&New ": "新建(&N)",
	"New ": "新建",
	"&Help": "帮助(&H)",
	"Help": "帮助",
	"Printing": "正在打印",
	"on the": "在",
	"&Print": "打印(&P)",
	"Print": "打印",
	"&Next Page": "下一页(&N)",
	"Next Page": "下一页",
	"Pre&v Page": "上一页(&V)",
	"Prev Page": "上一页",
	"Zoom &In": "放大(&I)",
	"Zoom In": "放大",
	"Zoom &Out": "缩小(&O)",
	"Zoom Out": "缩小",
	"&Close": "关闭(&C)",
	"Close": "关闭",
	"Grid Settings": "网格设置",
	"                  ": "               ",
	"&Pixel Grid": "象素网格(&P)",
	"Pixel Grid": "象素网格",
	"&Tile Grid": "平铺网格(&T)",
	"Tile Grid": "平铺网格",
	"pixels": "象素",
	"H&eight:": "高度(&E):",
	"Text": "文字",
	"Undo": "撤消",
	"Cut": "剪切",
	"Copy": "复制",
	"Paste": "粘贴",
	"Clear Selection": "清除选定区域",
	"Select All": "全选",
	"Text Toolbar": "文字工具栏",
	"Selection": "选定区域",
	"Cu&t": "剪切(&T)",
	"&Copy": "复制(&C)",
	"&Paste": "粘贴(&P)",
	"C&lear Selection": "清除选择(&L)",
	"Select &All": "全选(&A)",
	"C&opy To": "复制到(&O)",
	"Copy To": "复制到",
	"Paste &From": "粘贴自(&F)",
	"Paste From": "粘贴自",
	"Flip/&Rotate": "翻转/旋转(&R)",
	"Flip/Rotate": "翻转/旋转",
	"&Stretch/Skew": "拉伸/扭曲(&S)",
	"Stretch/Skew": "拉伸/扭曲",
	"&Invert Colors": "反色(&I)",
	"Invert Colors": "反色",
	"Thumbnail": "缩略图",
	"&File": "文件(&F)",
	"File": "文件",
	"&New": "新建(&N)",
	"&Open": "打开(&O)",
	"Open": "打开",
	"&Save": "保存(&S)",
	"Save": "保存",
	"Save &As": "另存为(&A)",
	"Save As": "另存为",
	"Print Pre&view": "打印预览(&V)",
	"Print Preview": "打印预览",
	"Page Se&tup": "页面设置(&T)",
	"Page Setup": "页面设置",
	"S&end": "发送(&D)",
	"Send": "发送",
	"Set As &Wallpaper (Tiled)": "设置为墙纸(平铺)(&W)",
	"Set As Wallpaper (Tiled)": "设置为墙纸(平铺)",
	"Set As Wa&llpaper (Centered)": "设置为墙纸(居中)(&L)",
	"Set As Wallpaper (Centered)": "设置为墙纸(居中)",
	"Recent File": "当前文件",
	"E&xit": "退出(&X)",
	"Exit": "退出",
	"&Edit": "编辑(&E)",
	"Edit": "编辑",
	"&Undo": "撤消(&U)",
	"&Repeat": "重复(&R)",
	"Repeat": "重复",
	"&View": "查看(&V)",
	"View": "查看",
	"&Tool Box": "工具箱(&T)",
	"Tool Box": "工具箱",
	"&Color Box": "颜料盒(&C)",
	"Color Box": "颜料盒",
	"&Status Bar": "状态栏(&S)",
	"Status Bar": "状态栏",
	"T&ext Toolbar": "文字工具栏(&E)",
	"&Zoom": "缩放(&Z)",
	"Zoom": "缩放",
	"&Normal Size": "常规尺寸(&N)",
	"Normal Size": "常规尺寸",
	"Ctrl+PgUp": " Ctrl+PgUp",
	"&Large Size": "大尺寸(&L)",
	"Large Size": "大尺寸",
	"Ctrl+PgDn": " Ctrl+PgDn",
	"C&ustom": "自定义(&C)",
	"Custom": "自定义",
	"Show &Grid": "显示网格(&G)",
	"Show Grid": "显示网格",
	"Show T&humbnail": "显示缩略图(&H)",
	"Show Thumbnail": "显示缩略图",
	"&View Bitmap": "全图(&V)",
	"View Bitmap": "全图",
	"&Image": "图象(&I)",
	"Image": "图象",
	"&Flip/Rotate": "翻转/旋转(&F)",
	"&Attributes": "属性(&A)",
	"&Clear Image": "清除图象(&C)",
	"Clear Image": "清除图象",
	"&Draw Opaque": "不透明处理(&D)",
	"Draw Opaque": "不透明处理",
	"&Colors": "颜色(&C)",
	"&Edit Colors": "编辑颜色(&E)",
	"Edit Colors": "编辑颜色",
	"&Help Topics": "帮助主题(&H)",
	"Help Topics": "帮助主题",
	"&About Paint": "关于画图(&A)",
	"About Paint": "关于画图",
	"&Update": "更新(&U)",
	"Update": "更新",
	"Save Copy &As": "另存为(&A)",
	"Save Copy As": "将副本存为",
	"Paint": "画图",
	"untitled": "未命名",
	"Bitmap Image": "位图图象",
	"Bitmap Files (*.bmp)": "位图文件(*.bmp)",
	"PCX Files": "PCX 文件",
	"Icon Files": "图标文件",
	"Monochrome Bitmap (*.bmp;*.dib)": "单色位图 (*.bmp;*.dib)",
	"16 Color Bitmap (*.bmp;*.dib)": "16 色位图 (*.bmp;*.dib)",
	"256 Color Bitmap (*.bmp;*.dib)": "256 色位图 (*.bmp;*.dib)",
	"Paint cannot open this file.": "画图程序无法打开该文件。",
	"Paint cannot read this file.": "画图程序无法读取该文件。",
	"This file is read-only.": "该文件为只读文件。",
	"To save your changes, use a different filename.": "请选用其他文件名保存改动后的结果。",
	"This file is already open.": "该文件已打开。",
	"This is not a valid .PCS file.": "无效的 .PCS 文件。",
	"This file is open for editing and cannot be overwritten.": "该文件已被打开用于编辑，无法改写。",
	"Use a different filename to save your changes.": "请选用其他文件名保存改动后的结果。",
	"This is not a valid bitmap file, or its format is not currently supported.": "无效的位图文件，或者当前尚不支持这种文件格式。",
	"This is not a valid icon.": "无效的图标。",
	"This is not a valid cursor.": "无效的光标。",
	"Save was interrupted, so your file has not been saved.": "保存被中断，所以文件未被保存。",
	"You cannot save to a read-only file.": "不能保存到只读文件中，请选用其他文件名。",
	"This file is already in use.": "文件已在使用。",
	"Close the program, and then try again.": "请关闭程序，然后再试。",
	"Paint cannot save this file.": "画图程序不能保存该文件。",
	"Paint cannot save to the same filename with a different file type.": "画图程序不能以不同的文件类型保存同名文件。",
	"The grid spacing must be an integer between %d and %d.": "网格宽度必须是 %d 和 %d 之间的整数。",
	"There is not enough memory or resources to complete operation.": "内存或资源不够，无法完成操作。",
	"Close some programs, and then try again.": "请关闭部分程序，然后再试。",
	"Low on memory or resources.": "内存或资源不够。",
	"Group error.": "组错误。",
	"Paint was unable to print your document. Please make sure you have sufficient disk space and that your printer is working correctly.": "画图程序无法打印文档。请确认磁盘空间是否足够以及打印机是否能正常工作。",
	"Saving into this format may cause some loss of color information.": "保存为这种格式可能会丢失某些颜色信息。",
	"Do you want to continue?": "是否还要继续?",
	"Converting to black and white cannot be undone.  This action affects the current file and may cause some loss of color information.": "转换为黑白图像后将无法恢复。该操作可能会影响到当前文件，并导致部分颜色信息丢失。",
	"Bitmaps must be greater than one pixel on a side.": "位图必须大于一个象素。",
	"Generic error.": "常规错误。",
	"File not found.": "找不到文件。",
	"Bad path.": "路径不对。",
	"Too many open files.": "打开的文件太多。",
	"Access denied.": "禁止访问。",
	"Invalid file.": "无效文件。",
	"Remove current folder.": "删除当前文件夹。",
	"Folder full.": "文件夹已满。",
	"Bad seek.": "定位不对。",
	"Hard IO error.": "硬件 IO 错误。",
	"Sharing violation.": "共享侵犯。",
	"Lock violation.": "锁定侵犯。",
	"Disk full.": "磁盘已满。",
	"End of file.": "文件尾。",
	"Error getting the Clipboard Data!": "获取剪贴板数据出错！",
	"No Printer Found @ page setup": "未找到打印机@页面设置",
	"24-bit Bitmap (*.bmp;*.dib)": "24 位位图 (*.bmp;*.dib)",
	"All Files": "所有文件",
	"Palette|*.pal|": "调色板|*.pal|",
	"OLE 2.0 was unable to start.": "无法启动 OLE 2.0 。",
	"Make sure that you are using the correct version of the OLE libraries.": "请确认所使用的 OLE 库版本是否正确。",
	"Resets the text be without any attributes.": "取消文字的所有属性。",
	"Sets or clears the text bold attribute.": "设置或清除字体的加粗属性。",
	"Sets or clears the text italic attribute.": "设置或清除字体的斜体属性。",
	"Selects the font used by the text.": "选定正文字体。",
	"Selects the point size of the text.": "选定文字磅值。",
	"Sets or clears the text underline attribute.": "设置或清除字体加下划线属性。",
	"Shows or hides the tooltips.": "显示或隐藏工具提示。",
	"Show Paint Help.": "显示画图帮助。",
	"Sends a picture by using mail or fax.": "通过邮件或传真发送图片。",
	"Copies the selection to a file.": "将所选内容复制到文件。",
	"Pastes a file into the selection.": "将文件粘贴到选定区域。",
	"Zooms the picture to 100%.": "保持图片的原有尺寸。",
	"Zooms the picture to 400%.": "将图片放大至四倍。",
	"Zooms the picture.": "缩放图片。",
	"Displays the entire picture.": "显示整个图片。",
	"Shows or hides the thumbnail view of the picture.": "显示或隐藏图片的缩略图。",
	"Shows or hides the grid.": "显示或隐藏网格。",
	"Shows or hides the text toolbar.": "显示或隐藏文字工具栏。",
	"Flips or rotates the picture or a selection.": "翻转或旋转图片或选定的区域。",
	"Stretches or skews the picture or a selection.": "拉伸或扭曲图片或选定的区域。",
	"Inverts the colors of the picture or a selection.": "反转图片或所选区域的颜色。",
	"Changes the attributes of the picture.": "更改图片的属性。",
	"Clears the picture or selection.": "清除图片或选定区域。",
	"The font size must be a numeric value.": "字体大小应为数值。",
	"Contains commands for working with the selected item(s).": "包含处理所选项目的命令。",
	"Contains commands for selecting and transferring items.": "包括选定和传送某些项目的命令。",
	"Contains commands for customizing this window.": "包含自定义窗口的命令。",
	"Contains commands for manipulating pictures and setting attributes.": "包含处理图片和设置属性的命令。",
	"Contains commands for using custom colors and drawing options.": "包含使用自定义颜色和绘图选项的命令。",
	"Contains commands for displaying Help for and information about Paint.": "包含显示图画程序的帮助信息以及其他有关信息的命令。",
	"Cannot save file.": "不能保存文件。",
	"Error removing temporary file.": "删除临时文件时出错。",
	"Get Colors": "获取颜色",
	"Save Colors": "保存颜色",
	"File last saved:": "上次保存的文件:",
	"Not Available": "无法使用",
	"Size on disk:": "磁盘大小:",
	"%s bytes": "%s 字节",
	"Painting": "画图",
	"Bitmap": "位图",
	"Fonts": "字体",
	"Tools": "工具",
	"x": "X",
	"All Picture Files": "所有图片文件",
	"For Help, click Help Topics on the Help Menu.": "要获得帮助，请在“帮助”菜单中，单击“帮助主题”。",
	"Select an area on which to get Help.": "选定要了解其帮助信息的区域。",
	"%1 in %2": "%2 中的 %1",
	"Creates a new document.": "创建新文档。",
	"Opens an existing document.": "打开现有文档。",
	"Closes the active document.": "关闭活动文档。",
	"Saves the active document.": "保存活动文档。",
	"Saves the active document with a new name.": "用其他文件名保存活动文档。",
	"Changes the page layout.": "改变页面布局。",
	"Specifies the default printer setup.": "指明默认打印机设置。",
	"Prints the active document and sets printing options.": "打印活动文档并设置打印选项。",
	"Displays full pages.": "显示整页。",
	"Opens this document.": "打开本文档。",
	"Deletes the selection.": "删除所选内容。",
	"Erases everything.": "全部删除。",
	"Copies the selection and puts it on the Clipboard.": "复制所选内容并放入剪贴板。",
	"Cuts the selection and puts it on the Clipboard.": "剪切所选内容并放入剪贴板。",
	"Finds the specified text.": "查找指定文字。",
	"Inserts the contents of the Clipboard.": "插入剪贴板内容。",
	"Repeats the last action.": "重复上一操作。",
	"Replaces specific text with different text.": "用不同的文字替换指定的文字。",
	"Selects everything.": "选定所有项目。",
	"Undoes the last action.": "撤消上一操作。",
	"Redoes the previously undone action.": "重做上一次被撤消的操作。",
	"Displays program information, version number, and copyright.": "显示程序信息、版本号和版权。",
	"Quits Paint.": "退出画图。",
	"Opens Paint Help.": "打开画图帮助。",
	"Displays instructions about how to use Help.": "显示如何使用帮助的指令。",
	"Displays Help for areas you click on.": "显示单击区域的帮助。",
	"Displays Help for the current task or command.": "显示当前任务或命令的帮助。",
	"Centers this bitmap as the desktop wallpaper.": "将该位图作为桌面墙纸居中显示。",
	"Tiles this bitmap as the desktop wallpaper.": "将该位图作为桌面墙纸平铺显示。",
	"Sends the selection using mail or fax.": "通过邮件或传真发送选定的内容。",
	"Prints the selection.": "打印选定的内容。",
	"Shows or hides the thumbnail.": "显示或隐藏缩略图。",
	"Shows Paint Help.": "显示画图帮助。",
	"Shows or hides the status bar.": "显示或隐藏状态栏。",
	"Shows or hides the tool box.": "显示或隐藏工具框。",
	"Shows or hides the color box.": "显示或隐藏颜色盒。",
	"Only a Far East font can be used for vertical editing.": "只能使用远东字体进行垂直编辑。",
	"Changes the window size.": "更改窗口大小。",
	"Changes the window position.": "更改窗口位置。",
	"Reduces the window to an icon.": "将窗口缩为图标。",
	"Enlarges the window to full size.": "将窗口扩为全屏。",
	"Switches to the next document window.": "转至下一个文档窗口。",
	"Switches to the previous document window.": "转至前一个文档窗口。",
	"Closes the active window and asks if you want to save changes.": "关闭活动窗口，询问是否保存所做的改动。",
	"Restores the window to normal size.": "将窗口恢复为正常大小。",
	"Activates the task list.": "激活任务列表。",
	"All Files (*.*)": "所有文件 (*.*)",
	"Untitled": "未定标题",
	"an unnamed file": "未命名文件",
	"&Hide": "隐藏(&H)",
	"Hide": "隐藏",
	"No error message is available.": "没有可用的错误消息。",
	"An unsupported operation was attempted.": "视图执行不支持的操作。",
	"A required resource was unavailable.": "没有必需的资源。",
	"Out of memory.": "内存不足。",
	"An unknown error has occurred.": "出现了未知错误。",
	"on %1": "在 %1 上",
	"&One Page": "单页(&O)",
	"One Page": "单页",
	"&Two Page": "双页(&T)",
	"Two Page": "双页",
	"Page %u": "第 %u 页",
	"Pages %u-%u": " %u-%u 页",
	"Printer Files (*.prn)|*.prn|All Files (*.*)|*.*||": "打印文件 (*.prn)|*.prn|所有文件 (*.*)|*.*||",
	"Print to File": "打印到文件",
	"to %1": "到 %1",
	"&Update %1": "更新 %1(&U)",
	"Update %1": "更新 %1",
	"E&xit && Return to %1": "退出并返回到 %1(&X)",
	"Exit && Return to %1": "退出并返回到 %1",
	"Linked %s": "链接的 %s",
	"Unknown Type": "未知类型",
	"Invalid filename.": "无效文件名。",
	"Failed to open document.": "不能打开文件。",
	"Failed to save document.": "不能保存文件。",
	"Save changes to %1?": "将更改后的结果保存到 %1 吗？",
	"Failed to create empty document.": "创建空文档失败。",
	"The file is too large to open.": "文件太大，无法打开。",
	"Could not start print job.": "无法开始打印作业。",
	"Failed to launch help.": "帮助调入失败。",
	"Internal application error.": "内部应用程序错误。",
	"Command failed.": "命令无效。",
	"Insufficient memory to perform operation.": "内存不够，无法执行操作。",
	"System registry entries have been removed and the INI file (if any) was deleted.": "系统注册表项和 INI 文件（如果有）已被删除。",
	"Not all of the system registry entries (or INI file) were removed.": "并未删除所有系统注册表项（或 INI 文件）。",
	"This program requires the file %s, which was not found on this system.": "系统上找不到该程序必需的 %s文件。",
	"This program is linked to the missing export %s in the file %s. This machine may have an incompatible version of %s.": "该程序被链接到丢失的导出项 %s (在文件 %s 中)。所使用的 %s 版本可能不兼容。",
	"Please enter an integer.": "请输入一个整数。",
	"Please enter a number.": "请输入一个数字。",
	"Please enter an integer between %1 and %2.": "请输入在 %1 和 %2 之间的一个整数。",
	"Please enter a number between %1 and %2.": "请键入介于 %1 和 %2 之间的数字。",
	"Please enter no more than %1 characters.": "请输入 %1 个以内的字符。",
	"Please select a button.": "请选定某个按钮。",
	"Please enter an integer between 0 and 255.": "请输入介于 0 和 255 之间的一个整数。",
	"Please enter a positive integer.": "请输入一个正整数。",
	"Please enter a date and/or time.": "请输入日期和 / 或时间。",
	"Please enter a currency.": "请输入货币。",
	"Unexpected file format.": "意外的文件格式。",
	"Cannot find this file.": "找不到这份文件。",
	"Please verify that the correct path and file name are given.": "请确定路径和文件名是否正确。",
	"Destination disk drive is full.": "目标盘已满。",
	"Unable to read from %1, it is opened by someone else.": " %1 已被其他用户打开，因此无法从中读取数据。",
	"Unable to write to %1, it is read-only or opened by someone else.": " %1 为只读文件或者已被其他用户打开，因此无法写入。",
	"An unexpected error occurred while reading %1.": "读 %1 时出现了意外错误。",
	"An unexpected error occurred while writing %1.": "写 %1 时出现了意外错误。",
	"Unable to register document.": "无法注册文档。",
	"The document may already be open.": "该文档可能已被打开。",
	"Update %1 before proceeding?": "先更新 %1 再继续吗？",
	"Could not update client.": "无法更新客户。",
	"Failed to register. ActiveX features may not work properly.": "注册失败。ActiveX 功能将工作不正确。",
	"Failed to update the system registry.": "更新系统注册表失败。",
	"Please try using REGEDIT.": "请使用 REGEDIT 试一试。",
	"Unable to read write-only property.": "不能读取只写属性。",
	"Unable to write read-only property.": "不能写只读特性。",
	"Unable to load mail system support.": "不能加载邮件系统支持。",
	"Mail system DLL is invalid.": "邮件系统动态链接库无效。",
	"Send Mail failed to send message.": "“发送邮件”命令执行失败。",
	"No error occurred.": "没有出现错误。",
	"An unknown error occurred while accessing %1.": "访问 %1 时出现了未知错误。",
	"%1 was not found.": "找不到 %1。",
	"%1 contains an invalid path.": "%1 包含无效的路径。",
	"%1 could not be opened because there are too many open files.": "打开的文件太多，无法打开 %1。",
	"Access to %1 was denied.": "拒绝访问 %1。",
	"An invalid file handle was associated with %1.": "一个无效的文件句柄和 %1 关联。",
	"%1 could not be removed because it is the current directory.": "%1为当前目录，因此不能删除。",
	"%1 could not be created because the directory is full.": "目录已满，无法创建 %1。",
	"Seek failed on %1": "在 %1 上的查找失败",
	"A hardware I/O error was reported while accessing %1.": "访问 %1 时报告一个硬件 I/O 错误。",
	"A sharing violation occurred while accessing %1.": "访问 %1 时发生共享侵犯。",
	"A locking violation occurred while accessing %1.": "访问 %1 时发生锁定侵犯。",
	"Disk full while accessing %1.": "访问 %1 时磁盘已满。",
	"An attempt was made to access %1 past its end.": "试图访问 %1 结尾之后的数据。",
	"An attempt was made to write to the reading %1.": "试图将数据写入正读取的 %1 中。",
	"An attempt was made to read from the writing %1.": "试图从正写入的 %1 中读取数据。",
	"%1 has a bad format.": "%1 格式错误。",
	"%1 contained an unexpected object.": "%1 包含意外的对象。",
	"%1 contains an incorrect schema.": "%1 包含不正确的模式。",
	"Selects a rectangular part of the picture to move, copy, or edit.": "在图片中选定一个矩形区域，以进行移动、复制或者编辑。",
	"Select": "选定",
	"Selects a free-form part of the picture to move, copy, or edit.": "从图片中裁剪任意形状的一块进行移动、复制和编辑。",
	"Free-Form Select": "任意形状的裁剪",
	"Inserts text into the picture.": "在图片中插入文字。",
	"Fills an area with the current drawing color.": "使用当前的绘图色填充某块区域。",
	"Fill With Color": "用颜色填充",
	"Draws a straight line with the selected line width.": "用选定的线宽画一条直线。",
	"Line": "直线",
	"Draws using an airbrush of the selected size.": "用选定大小的喷枪绘图。",
	"Airbrush": "喷枪",
	"Draws a curved line with the selected line width.": "用选定的线宽画一条曲线。",
	"Curve": "曲线",
	"Draws a polygon with the selected fill style.": "用选定的填充模式画多边形。",
	"Polygon": "多边形",
	"Draws a rounded rectangle with the selected fill style.": "用选定的填充模式画圆角矩形。",
	"Rounded Rectangle": "圆角矩形",
	"Draws a free-form line one pixel wide.": "用单象素线宽画任意形状的线条。",
	"Pencil": "铅笔",
	"Erases a portion of the picture, using the selected eraser shape.": "使用选定橡皮抹去图片的一部分。",
	"Eraser/Color Eraser": "橡皮/颜色橡皮",
	"Changes the magnification.": "更改放大倍数。",
	"Magnifier": "放大",
	"Picks up a color from the picture for drawing.": "请在图片上选取一种颜色用以画图。",
	"Pick Color": "取色",
	"Draws using a brush with the selected shape and size.": "用选定形状和大小的刷子绘图",
	"Brush": "刷子",
	"Draws a rectangle with the selected fill style.": "用选定的填充模式画矩形。",
	"Rectangle": "矩形",
	"Draws a filled rectangle.": "画实心矩形。",
	"Draws an ellipse with the selected fill style.": "用选定的填充模式画椭圆。",
	"Ellipse": "椭圆",
	"Draws a filled ellipse.": "画实心椭圆。",
	"Makes the current selection either opaque or transparent.": "设置当前选定区域的透明特性。",
	"Creates a new color.": "创建新颜色。",
	"Uses a previously saved palette of colors.": "选用以前保存的调色板。",
	"Saves the current palette of colors to a file.": "将当前颜色的调色板存入文件。",
	"You must save the file before choosing it as Wallpaper.": "必须在将文件选为墙纸前进行保存。",
	"The selection is now larger than the bitmap.": "所选区域比位图大。",
	"Would you like the bitmap enlarged?": "是否希望放大位图?",
	"The image in the clipboard is larger than the bitmap.": "剪贴板中的图象比位图大。是否希望扩大位图?",
	"The file is not in the correct format.": "文件格式不对。",
	"Not enough room to paste text.": "空间不够，无法粘贴文字。",
	"Enlarge the text area and try again.": "请加大文字区，然后重试。",
	"Places the text.": "放置文字。"
});
