//
// NOTE: This is a generated file! Don't edit it directly.
// Eventually community translation will be set up on some translation platform.
// 
// Generated with: npm run update-localization
//
loaded_localizations("it", {
	"Attributes": "Attributi",
	"&Width:": "&Larghezza:",
	"Width:": "Larghezza:",
	"&Height:": "&Altezza:",
	"Height:": "Altezza:",
	"Units": "Unità di misura",
	"&Inches": "&Pollici",
	"Inches": "Pollici",
	"C&m": "&Cm",
	"Cm": "Cm",
	"&Pixels": "Pi&xel",
	"Pixels": "Pixel",
	"Colors": "Colori",
	"&Black and white": "&Bianco e nero",
	"Black and white": "Bianco e nero",
	"Co&lors": "C&olori",
	"Transparency": "Lucido",
	"Use &Transparent background color": "Usa colore di sfondo &trasparente",
	"Use Transparent background color": "Usa colore di sfondo trasparente",
	"Select &Color": "Sele&ziona colore",
	"Select Color": "Seleziona colore",
	"Cancel": "Annulla",
	"&Default": "P&redefiniti",
	"Default": "Predefiniti",
	"Custom Zoom": "Personalizza zoom",
	"Current zoom:": "Zoom corrente:",
	"Zoom to": "Percentuale zoom",
	"Flip and Rotate": "Capovolgi o ruota",
	"Flip or rotate": "Capovolgi o ruota",
	"&Flip horizontal": "&Capovolgi orizzontalmente",
	"Flip horizontal": "Capovolgi orizzontalmente",
	"Flip &vertical": "Capo&volgi verticalmente",
	"Flip vertical": "Capovolgi verticalmente",
	"&Rotate by angle": "&Ruota di",
	"Rotate by angle": "Ruota di",
	"Stretch and Skew": "Allunga e inclina",
	"Stretch": "Allunga",
	"&Horizontal:": "&Orizzontalmente:",
	"Horizontal:": "Orizzontalmente:",
	"&Vertical:": "&Verticalmente:",
	"Vertical:": "Verticalmente:",
	"Skew": "Inclina",
	"H&orizontal:": "Ori&zzontalmente:",
	"Degrees": "gradi",
	"V&ertical:": "V&erticalmente:",
	"Color Table": "Tavola colori",
	"New": "Nuova connessione",
	"&New ": "&Nuovo ",
	"New ": "Nuovo ",
	"&Help": "&?",
	"Help": "?",
	"Printing": "Stampa in corso",
	"on the": "su",
	"&Print": "Sta&mpa",
	"Print": "Stampa",
	"&Next Page": "S&uccessiva",
	"Next Page": "Successiva",
	"Pre&v Page": "&Precedente",
	"Prev Page": "Precedente",
	"Zoom &In": "Zoom &avanti",
	"Zoom In": "Zoom avanti",
	"Zoom &Out": "Zoom &indietro",
	"Zoom Out": "Zoom indietro",
	"&Close": "&Chiudi",
	"Close": "Chiudi",
	"Grid Settings": "Impostazioni griglia",
	"&Pixel Grid": "&Griglia in pixel",
	"Pixel Grid": "Griglia in pixel",
	"&Tile Grid": "A&ffianca griglia",
	"Tile Grid": "Affianca griglia",
	"pixels": "pixel",
	"H&eight:": "&Altezza:",
	"Text": "Testo",
	"Undo": "Annulla",
	"Cut": "Taglia",
	"Copy": "Copia",
	"Paste": "Incolla",
	"Clear Selection": "Cancella area selezionata",
	"Select All": "Seleziona tutto",
	"Text Toolbar": "Barra degli strumenti di testo",
	"Selection": "Selezione",
	"Cu&t": "&Taglia",
	"&Copy": "&Copia",
	"&Paste": "&Incolla",
	"C&lear Selection": "Cance&lla area selezionata",
	"Select &All": "&Seleziona tutto",
	"C&opy To": "C&opia su",
	"Copy To": "Copia su",
	"Paste &From": "Incolla &da",
	"Paste From": "Incolla da",
	"Flip/&Rotate": "Capovolgi/R&uota",
	"Flip/Rotate": "Capovolgi/Ruota",
	"&Stretch/Skew": "&Allunga/Inclina",
	"Stretch/Skew": "Allunga/Inclina",
	"&Invert Colors": "In&verti colori",
	"Invert Colors": "Inverti colori",
	"Thumbnail": "Panoramica",
	"&New": "&Nuovo",
	"Ctrl+N": "CTRL+N",
	"&Open": "&Apri",
	"Open": "Apri",
	"Ctrl+O": "CTRL+F12",
	"&Save": "&Salva",
	"Save": "Salva",
	"Ctrl+S": "MAIUSC+F12",
	"Save &As": "Salva &con nome",
	"Save As": "Salva con nome",
	"Print Pre&view": "Anteprima &di stampa",
	"Print Preview": "Anteprima di stampa",
	"Page Se&tup": "&Imposta pagina",
	"Page Setup": "Imposta pagina",
	"Ctrl+P": "CTRL+MAIUSC+F12",
	"S&end": "In&via",
	"Send": "Invia",
	"Set As &Wallpaper (Tiled)": "Im&posta come sfondo (affiancato)",
	"Set As Wallpaper (Tiled)": "Imposta come sfondo (affiancato)",
	"Set As Wa&llpaper (Centered)": "Imp&osta come sfondo (centrato)",
	"Set As Wallpaper (Centered)": "Imposta come sfondo (centrato)",
	"Recent File": "File recente",
	"E&xit": "&Esci",
	"Exit": "Esci",
	"Alt+F4": "ALT+F4",
	"&Edit": "&Modifica",
	"Edit": "Modifica",
	"&Undo": "&Annulla",
	"Ctrl+Z": "CTRL+Z",
	"&Repeat": "&Ripeti",
	"Repeat": "Ripeti",
	"Ctrl+X": "CTRL+X",
	"Ctrl+C": "CTRL+C",
	"Ctrl+V": "CTRL+V",
	"Del": "CANC",
	"Ctrl+A": "CTRL+5 (Tn)",
	"&View": "&Visualizza",
	"View": "Visualizza",
	"&Tool Box": "&Casella degli strumenti",
	"Tool Box": "Casella degli strumenti",
	"Ctrl+T": "CTRL+T",
	"&Color Box": "&Tavolozza",
	"Color Box": "Tavolozza",
	"Ctrl+L": "CTRL+O",
	"&Status Bar": "&Barra di stato",
	"Status Bar": "Barra di stato",
	"T&ext Toolbar": "B&arra degli strumenti di testo",
	"&Normal Size": "&Dimensioni normali",
	"Normal Size": "Dimensioni normali",
	"Ctrl+PgUp": "CTRL+PGSU",
	"&Large Size": "I&ngrandisci",
	"Large Size": "Ingrandisci",
	"Ctrl+PgDn": "CTRL+PGGIÙ",
	"C&ustom": "Personali&zza",
	"Custom": "Personalizza",
	"Show &Grid": "Mostra &griglia",
	"Show Grid": "Mostra griglia",
	"Ctrl+G": "CTRL+G",
	"Show T&humbnail": "&Mostra Panoramica",
	"Show Thumbnail": "Mostra Panoramica",
	"&View Bitmap": "&Visualizza bitmap",
	"View Bitmap": "Visualizza bitmap",
	"Ctrl+F": "CTRL+F",
	"&Image": "&Immagine",
	"Image": "Immagine",
	"&Flip/Rotate": "&Capovolgi/Ruota",
	"Ctrl+W": "CTRL+W",
	"&Attributes": "A&ttributi",
	"Ctrl+E": "CTRL+E",
	"&Clear Image": "Ca&ncella immagine",
	"Clear Image": "Cancella immagine",
	"Ctrl+Shft+N": "CTRL+MAIUSC+N",
	"&Draw Opaque": "&Opaco",
	"Draw Opaque": "Opaco",
	"&Colors": "&Colori",
	"&Edit Colors": "&Modifica colori",
	"Edit Colors": "Modifica colori",
	"&Help Topics": "&Guida in linea",
	"Help Topics": "Guida in linea",
	"&About Paint": "&Informazioni su Paint",
	"About Paint": "Informazioni su Paint",
	"&Update": "&Aggiorna",
	"Update": "Aggiorna",
	"Save Copy &As": "Salva &copia con nome",
	"Save Copy As": "Salva copia con nome.",
	"untitled": "Immagine",
	"Bitmap Image": "Immagine bitmap",
	"Bitmap Files (*.bmp)": "File bitmap(*.bmp)",
	"PCX Files": "File PCX",
	"Icon Files": "File icona",
	"Monochrome Bitmap (*.bmp;*.dib)": "Bitmap monocromatica (*.bmp;*.dib)",
	"16 Color Bitmap (*.bmp;*.dib)": "Bitmap a 16 colori (*.bmp;*.dib)",
	"256 Color Bitmap (*.bmp;*.dib)": "Bitmap a 256 colori (*.bmp;*.dib)",
	"Paint cannot open this file.": "Impossibile aprire il file.",
	"Paint cannot read this file.": "Impossibile leggere il file.",
	"This file is read-only.": "Il file è di sola lettura.",
	"To save your changes, use a different filename.": "Per salvare le modifiche, utilizzare un nome di file diverso.",
	"This file is already open.": "Il file è già aperto.",
	"This is not a valid .PCS file.": "Non è un file PCS valido.",
	"This file is open for editing and cannot be overwritten.": "Impossibile sovrascrivere il file in quanto è in fase di modifica.",
	"Use a different filename to save your changes.": "Per salvare le modifiche, utilizzare un nome di file diverso.",
	"This is not a valid bitmap file, or its format is not currently supported.": "File bitmap non valido o formato del file non supportato.",
	"This is not a valid icon.": "Non è un'icona valida.",
	"This is not a valid cursor.": "Puntatore non valido.",
	"Save was interrupted, so your file has not been saved.": "Salvataggio annullato. Il file non è stato salvato.",
	"You cannot save to a read-only file.": "Impossibile salvare su un file di sola lettura.",
	"Use a different file name.": "Utilizzare un nome diverso.",
	"This file is already in use.": "Il file è già in uso.",
	"Close the program, and then try again.": "Chiudere l'applicazione e riprovare.",
	"Paint cannot save this file.": "Impossibile salvare il file.",
	"Paint cannot save to the same filename with a different file type.": "Impossibile salvare il file con lo stesso nome con un tipo di file diverso.",
	"The grid spacing must be an integer between %d and %d.": "Il valore per la spaziatura della griglia deve essere un intero compreso tra %d e %d.",
	"There is not enough memory or resources to complete operation.": "Memoria o risorse insufficienti per completare l'operazione.",
	"Close some programs, and then try again.": "Chiudere una o più applicazioni e riprovare.",
	"Low on memory or resources.": "Memoria o risorse insufficienti.",
	"Group error.": "Errore di gruppo.",
	"Paint was unable to print your document. Please make sure you have sufficient disk space and that your printer is working correctly.": "Impossibile stampare il documento. Assicurarsi di disporre di spazio su disco sufficiente e del corretto funzionamento della stampante.",
	"Saving into this format may cause some loss of color information.": "Il salvataggio in questo formato potrebbe provocare perdita di informazioni sul colore.",
	"Do you want to continue?": "Procedere?",
	"Converting to black and white cannot be undone.  This action affects the current file and may cause some loss of color information.": "Impossibile convertire in bianco e nero. Questa operazione potrebbe influenzare il file corrente e far perdere alcune informazioni sul colore.",
	"Bitmaps must be greater than one pixel on a side.": "Le bitmap devono essere più grandi di 1x1 pixel.",
	"Generic error.": "Errore generico.",
	"File not found.": "Impossibile trovare il file.",
	"Bad path.": "Percorso non valido.",
	"Too many open files.": "Troppi file aperti.",
	"Access denied.": "Accesso negato.",
	"Invalid file.": "File non valido.",
	"Remove current folder.": "Rimuove la cartella corrente.",
	"Folder full.": "Cartella piena.",
	"Bad seek.": "Ricerca non riuscita.",
	"Hard IO error.": "Errore di I/O.",
	"Sharing violation.": "Violazione di condivisione.",
	"Lock violation.": "Violazione di protezione.",
	"Disk full.": "Disco pieno.",
	"End of file.": "Fine del file.",
	"Error getting the Clipboard Data!": "Errore durante la visualizzazione dei dati negli Appunti.",
	"No Printer Found @ page setup": "Impossibile trovare @ page setup",
	"24-bit Bitmap (*.bmp;*.dib)": "Bitmap a 24 bit (*.bmp;*.dib)",
	"All Files": "Tutti i file",
	"Palette|*.pal|": "Tavolozza|*.pal|",
	"OLE 2.0 was unable to start.": "Impossibile avviare OLE 2.0.",
	"Make sure that you are using the correct version of the OLE libraries.": "Verificare che la versione delle librerie OLE in uso sia corretta.",
	"Resets the text be without any attributes.": "Reimposta il testo anche senza attributi.",
	"Sets or clears the text bold attribute.": "Imposta o cancella l'attributo in grassetto del testo.",
	"Sets or clears the text italic attribute.": "Imposta o cancella l'attributo in corsivo del testo.",
	"Selects the font used by the text.": "Seleziona il tipo di carattere utilizzato dal testo.",
	"Selects the point size of the text.": "Seleziona le dimensioni in punti del testo.",
	"Sets or clears the text underline attribute.": "Imposta o cancella l'attributo sottolineato del testo.",
	"Shows or hides the tooltips.": "Mostra o nasconde la descrizione comandi.",
	"Show Paint Help.": "Mostra la Guida di Paint.",
	"Sends a picture by using mail or fax.": "Invia l'immagine per posta elettronica o fax.",
	"Copies the selection to a file.": "Copia la selezione su un file.",
	"Pastes a file into the selection.": "Incolla un file nella selezione.",
	"Zooms the picture to 100%.": "Ripristina le dimensioni originali.",
	"Zooms the picture to 400%.": "Ingrandisce l'immagine del 400%.",
	"Zooms the picture.": "Ingrandisce l'immagine.",
	"Displays the entire picture.": "Visualizza l'immagine intera.",
	"Shows or hides the thumbnail view of the picture.": "Mostra o nasconde Panoramica dell'immagine.",
	"Shows or hides the grid.": "Mostra o nasconde la griglia.",
	"Shows or hides the text toolbar.": "Mostra o nasconde la barra degli strumenti di testo.",
	"Flips or rotates the picture or a selection.": "Capovolge o ruota l'immagine o l'area selezionata.",
	"Stretches or skews the picture or a selection.": "Allunga o inclina l'immagine o l'area selezionata.",
	"Inverts the colors of the picture or a selection.": "Inverte i colori dell'immagine o dell'area selezionata.",
	"Changes the attributes of the picture.": "Modifica gli attributi dell'immagine.",
	"Clears the picture or selection.": "Cancella l'immagine o annulla la selezione.",
	"The font size must be a numeric value.": "La dimensione del carattere deve essere un valore numerico.",
	"Contains commands for working with the selected item(s).": "Comandi per la gestione dell'oggetto o degli oggetti selezionati.",
	"Contains commands for selecting and transferring items.": "Comandi per la selezione e il trasferimento degli oggetti.",
	"Contains commands for customizing this window.": "Comandi per la personalizzazione della finestra.",
	"Contains commands for manipulating pictures and setting attributes.": "Comandi per la gestione delle immagini e l'impostazione degli attributi.",
	"Contains commands for using custom colors and drawing options.": "Comandi per l'utilizzo dei colori personalizzati e delle opzioni.",
	"Contains commands for displaying Help for and information about Paint.": "Comandi per la visualizzazione della Guida e delle informazioni su Paint.",
	"Cannot save file.": "Impossibile salvare il file.",
	"Error removing temporary file.": "Errore durante la rimozione del file temporaneo.",
	"Get Colors": "Carica colori",
	"Save Colors": "Salva colori",
	"File last saved:": "Ultimo salvataggio:",
	"Not Available": "Non disponibile",
	"Size on disk:": "Dimensioni su disco:",
	"%s bytes": "%s byte",
	"Painting": "Disegno in corso",
	"Fonts": "Tipi di carattere",
	"Tools": "Strumenti",
	"All Picture Files": "Tutti i file immagine",
	"For Help, click Help Topics on the Help Menu.": "Scegliere Guida in linea dal menu ? per visualizzare la Guida di Paint.",
	"Select an area on which to get Help.": "Selezionare un'area per la quale si desidera visualizzare la Guida.",
	"%1 in %2": "%1 su %2",
	"Creates a new document.": "Crea un nuovo documento.",
	"Opens an existing document.": "Apre un documento esistente.",
	"Closes the active document.": "Chiude il documento attivo.",
	"Saves the active document.": "Salva il documento attivo.",
	"Saves the active document with a new name.": "Salva il documento attivo con un nuovo nome.",
	"Changes the page layout.": "Modifica le impostazioni della pagina.",
	"Specifies the default printer setup.": "Specifica l'impostazione della stampante predefinita.",
	"Prints the active document and sets printing options.": "Stampa il documento attivo e imposta le opzioni di stampa.",
	"Displays full pages.": "Mostra le pagine intere.",
	"Opens this document.": "Apre il documento.",
	"Deletes the selection.": "Annulla la selezione.",
	"Erases everything.": "Cancella tutto.",
	"Copies the selection and puts it on the Clipboard.": "Copia l'area selezionata negli Appunti.",
	"Cuts the selection and puts it on the Clipboard.": "Taglia l'area selezionata e la copia negli Appunti.",
	"Finds the specified text.": "Trova il testo specificato.",
	"Inserts the contents of the Clipboard.": "Inserisce il contenuto degli Appunti.",
	"Repeats the last action.": "Ripete l'ultima operazione.",
	"Replaces specific text with different text.": "Sostituisce del testo specifico con altro testo.",
	"Selects everything.": "Seleziona tutto.",
	"Undoes the last action.": "Annulla l'ultima operazione.",
	"Redoes the previously undone action.": "Ripete l'ultima operazione annullata.",
	"Displays program information, version number, and copyright.": "Visualizza le informazioni sul programma, il numero della versione e il copyright.",
	"Quits Paint.": "Chiude Paint.",
	"Opens Paint Help.": "Apre la Guida di Paint.",
	"Displays instructions about how to use Help.": "Visualizza istruzioni sull'utilizzo della Guida.",
	"Displays Help for areas you click on.": "Visualizza la Guida corrispondente all'area selezionata.",
	"Displays Help for the current task or command.": "Apre la Guida.",
	"Centers this bitmap as the desktop wallpaper.": "Imposta la bitmap come nuovo sfondo centrato.",
	"Tiles this bitmap as the desktop wallpaper.": "Imposta la bitmap come nuovo sfondo affiancato.",
	"Sends the selection using mail or fax.": "Invia la selezione per posta elettronica o fax.",
	"Prints the selection.": "Stampa l'area selezionata.",
	"Shows or hides the thumbnail.": "Mostra o nasconde Panoramica.",
	"Shows Paint Help.": "Mostra la Guida di Paint.",
	"Shows or hides the status bar.": "Mostra o nasconde la barra di stato.",
	"Shows or hides the tool box.": "Mostra o nasconde la casella degli strumenti.",
	"Shows or hides the color box.": "Mostra o nasconde la tavolozza.",
	"Only a Far East font can be used for vertical editing.": "Per la composizione verticale è possibile utilizzare solamente caratteri delle lingue dell'estremo oriente.",
	"Changes the window size.": "Modifica le dimensioni della finestra.",
	"Changes the window position.": "Modifica la posizione della finestra.",
	"Reduces the window to an icon.": "Riduce a icona la finestra.",
	"Enlarges the window to full size.": "Ingrandisce la finestra a tutto schermo.",
	"Switches to the next document window.": "Passa alla finestra di documento successiva.",
	"Switches to the previous document window.": "Torna alla finestra di documento precedente.",
	"Closes the active window and asks if you want to save changes.": "Chiude la finestra attiva e chiede di salvare il documento.",
	"Restores the window to normal size.": "Ripristina le dimensioni normali della finestra.",
	"Activates the task list.": "Attiva l'elenco dei processi.",
	"All Files (*.*)": "Tutti i file (*.*)",
	"Untitled": "Senza nome",
	"an unnamed file": "file senza nome",
	"&Hide": "&Nascondi",
	"Hide": "Nascondi",
	"No error message is available.": "Nessun messaggio di errore disponibile.",
	"An unsupported operation was attempted.": "Si è tentato di eseguire un'operazione non supportata.",
	"A required resource was unavailable.": "Risorsa richiesta non disponibile.",
	"Out of memory.": "Memoria insufficiente.",
	"An unknown error has occurred.": "Errore sconosciuto.",
	"on %1": "su %1",
	"&One Page": "&Una pagina",
	"One Page": "Una pagina",
	"&Two Page": "&Due pagine",
	"Two Page": "Due pagine",
	"Page %u": "Pagina %u",
	"Pages %u-%u": "Pagine %u-%u",
	"Printer Files (*.prn)|*.prn|All Files (*.*)|*.*||": "File di stampa (*.prn)|*.prn|Tutti i file (*.*)|*.*||",
	"Print to File": "Stampa su file",
	"to %1": "su %1",
	"&Update %1": "&Aggiorna %1",
	"Update %1": "Aggiorna %1",
	"E&xit && Return to %1": "&Esci e torna a %1",
	"Exit && Return to %1": "Esci e torna a %1",
	"Linked %s": "Collegamento di %s",
	"Unknown Type": "Tipo sconosciuto",
	"Invalid filename.": "Nome file non valido.",
	"Failed to open document.": "Impossibile aprire il documento.",
	"Failed to save document.": "Impossibile salvare il documento.",
	"Save changes to %1?": "Salvare le modifiche apportate a %1?",
	"Failed to create empty document.": "Impossibile creare un documento vuoto.",
	"The file is too large to open.": "File troppo grande per essere aperto.",
	"Could not start print job.": "Impossibile avviare il processo di stampa.",
	"Failed to launch help.": "Impossibile aprire la Guida.",
	"Internal application error.": "Errore interno dell'applicazione.",
	"Command failed.": "Comando non riuscito.",
	"Insufficient memory to perform operation.": "Memoria insufficiente per eseguire l'operazione.",
	"System registry entries have been removed and the INI file (if any) was deleted.": "Le voci del registro di sistema sono state rimosse e il file .INI (se presente) è stato eliminato",
	"Not all of the system registry entries (or INI file) were removed.": "Non tutte le voci del registro di sistema (o file .INI) sono state rimosse.",
	"This program requires the file %s, which was not found on this system.": "Il programma richiede il file %s che non è stato trovato nel sistema.",
	"This program is linked to the missing export %s in the file %s. This machine may have an incompatible version of %s.": "Questo programma è collegato all'esportazione mancante %s nel file %s. Questo computer potrebbe avere un versione di %s non compatibile.",
	"Please enter an integer.": "Immettere un numero intero.",
	"Please enter a number.": "Immettere un numero.",
	"Please enter an integer between %1 and %2.": "Immettere un numero intero compreso tra %1 e %2.",
	"Please enter a number between %1 and %2.": "Immettere un numero compreso tra %1 e %2.",
	"Please enter no more than %1 characters.": "Immettere un numero massimo di %1 caratteri.",
	"Please select a button.": "Scegliere un pulsante.",
	"Please enter an integer between 0 and 255.": "Immettere un numero intero compreso tra 0 e 255.",
	"Please enter a positive integer.": "Immettere un numero intero positivo.",
	"Please enter a date and/or time.": "Immettere una data e/o un'ora.",
	"Please enter a currency.": "Immettere una valuta.",
	"Unexpected file format.": "Formato file imprevisto.",
	"Cannot find this file.": "Impossibile trovare il file.",
	"Please verify that the correct path and file name are given.": "Verificare che il nome del file e il percorso siano corretti.",
	"Destination disk drive is full.": "L'unità di destinazione è piena.",
	"Unable to read from %1, it is opened by someone else.": "Impossibile leggere da %1, il file è correntemente in uso.",
	"Unable to write to %1, it is read-only or opened by someone else.": "Impossibile scrivere su %1, il file è di sola lettura o è stato aperto da un altro utente.",
	"An unexpected error occurred while reading %1.": "Errore imprevisto durante la lettura di %1.",
	"An unexpected error occurred while writing %1.": "Errore imprevisto durante la scrittura di %1.",
	"Unable to register document.": "Impossibile registrare il documento.",
	"The document may already be open.": "Il documento potrebbe essere aperto.",
	"Update %1 before proceeding?": "Aggiornare %1 prima di procedere?",
	"Could not update client.": "Impossibile aggiornare il client.",
	"Failed to register. ActiveX features may not work properly.": "Registrazione non riuscita. Le caratteristiche ActiveX potrebbero non funzionare correttamente.",
	"Failed to update the system registry.": "Impossibile aggiornare il registro di configurazione del sistema.",
	"Please try using REGEDIT.": "Riprovare usando REGEDIT.",
	"Unable to read write-only property.": "Impossibile leggere: proprietà di sola scrittura.",
	"Unable to write read-only property.": "Impossibile scrivere: proprietà di sola lettura.",
	"Unable to load mail system support.": "Impossibile caricare il supporto per la posta elettronica.",
	"Mail system DLL is invalid.": "La DLL del sistema di posta elettronica non è valida.",
	"Send Mail failed to send message.": "Impossibile inviare messaggi.",
	"No error occurred.": "Nessun errore rilevato.",
	"An unknown error occurred while accessing %1.": "Errore sconosciuto durante l'accesso a %1.",
	"%1 was not found.": "Impossibile trovare %1.",
	"%1 contains an invalid path.": "%1 contiene un percorso non valido.",
	"%1 could not be opened because there are too many open files.": "Impossibile aprire %1. Troppi file aperti.",
	"Access to %1 was denied.": "Accesso a %1 negato.",
	"An invalid file handle was associated with %1.": "Handle di file non valido associato a %1.",
	"%1 could not be removed because it is the current directory.": "Impossibile rimuovere %1 poiché si tratta della directory corrente.",
	"%1 could not be created because the directory is full.": "Impossibile creare %1 poiché la directory è piena.",
	"Seek failed on %1": "Ricerca non riuscita su %1",
	"A hardware I/O error was reported while accessing %1.": "Errore di I/O dell'hardware rilevato durante l'accesso a %1.",
	"A sharing violation occurred while accessing %1.": "Violazione di condivisione durante l'accesso a %1.",
	"A locking violation occurred while accessing %1.": "Violazione di blocco durante l'accesso a %1.",
	"Disk full while accessing %1.": "Disco pieno durante l'accesso a %1.",
	"An attempt was made to access %1 past its end.": "Tentativo di accedere a %1 dopo la sua fine.",
	"An attempt was made to write to the reading %1.": "Tentativo di scrittura su %1 in lettura.",
	"An attempt was made to read from the writing %1.": "Tentativo di lettura su %1 in scrittura.",
	"%1 has a bad format.": "Formato di %1 non valido.",
	"%1 contained an unexpected object.": "%1 conteneva un oggetto imprevisto.",
	"%1 contains an incorrect schema.": "%1 contiene una combinazione non corretta.",
	"Selects a rectangular part of the picture to move, copy, or edit.": "Seleziona una parte rettangolare dell'immagine da spostare, copiare o modificare.",
	"Select": "Seleziona",
	"Selects a free-form part of the picture to move, copy, or edit.": "Seleziona una parte dell'immagine da spostare, copiare o modificare.",
	"Free-Form Select": "Seleziona parte",
	"Inserts text into the picture.": "Inserisce del testo nell'immagine.",
	"Fills an area with the current drawing color.": "Riempie un'area con il colore selezionato.",
	"Fill With Color": "Riempi",
	"Draws a straight line with the selected line width.": "Disegna una linea retta utilizzando lo spessore selezionato.",
	"Line": "Linea",
	"Draws using an airbrush of the selected size.": "Disegna utilizzando un aerografo con le dimensioni selezionate.",
	"Airbrush": "Aerografo",
	"Draws a curved line with the selected line width.": "Disegna una curva utilizzando lo spessore selezionato.",
	"Curve": "Curva",
	"Draws a polygon with the selected fill style.": "Disegna un poligono utilizzando il tipo di riempimento selezionato.",
	"Polygon": "Poligono",
	"Draws a rounded rectangle with the selected fill style.": "Disegna un rettangolo arrotondato utilizzando il tipo di riempimento selezionato.",
	"Rounded Rectangle": "Rettangolo arrotondato",
	"Draws a free-form line one pixel wide.": "Disegna una linea di spessore pari ad un pixel.",
	"Pencil": "Matita",
	"Erases a portion of the picture, using the selected eraser shape.": "Cancella una parte dell'immagine, utilizzando la gomma selezionata.",
	"Eraser/Color Eraser": "Cancella/Cancella colore",
	"Changes the magnification.": "Modifica il tipo di ingrandimento.",
	"Magnifier": "Ingrandisci",
	"Picks up a color from the picture for drawing.": "Sceglie un colore dall'immagine per disegnare.",
	"Pick Color": "Scegli colore",
	"Draws using a brush with the selected shape and size.": "Disegna utilizzando un pennello con la forma e le dimensioni selezionate.",
	"Brush": "Pennello",
	"Draws a rectangle with the selected fill style.": "Disegna un rettangolo utilizzando il tipo di riempimento selezionato.",
	"Rectangle": "Rettangolo",
	"Draws a filled rectangle.": "Disegna un rettangolo riempito.",
	"Draws an ellipse with the selected fill style.": "Disegna un'ellisse utilizzando il tipo di riempimento selezionato.",
	"Ellipse": "Ellisse",
	"Draws a filled ellipse.": "Disegna un'ellisse riempita.",
	"Makes the current selection either opaque or transparent.": "Rende la selezione corrente opaca o trasparente.",
	"Creates a new color.": "Crea un nuovo colore.",
	"Uses a previously saved palette of colors.": "Utilizza la tavolozza di colori salvata precedentemente.",
	"Saves the current palette of colors to a file.": "Salva la tavolozza di colori corrente su un file.",
	"You must save the file before choosing it as Wallpaper.": "È necessario salvare il file prima di utilizzarlo come sfondo.",
	"The selection is now larger than the bitmap.": "L'area selezionata è più grande della bitmap.",
	"Would you like the bitmap enlarged?": "Ingrandire la bitmap?",
	"The image in the clipboard is larger than the bitmap.": "L'immagine negli Appunti è più grande della bitmap.",
	"The file is not in the correct format.": "Formato file non corretto.",
	"Not enough room to paste text.": "Spazio insufficiente per incollare il testo.",
	"Enlarge the text area and try again.": "Ingrandire l'area del testo e riprovare.",
	"Places the text.": "Colloca il testo."
});
