//
// NOTE: This is a generated file! Don't edit it directly.
// Eventually community translation will be set up on some translation platform.
// 
// Generated with: npm run update-localization
//
loaded_localizations("hu", {
	"Attributes": "Tulajdonságok",
	"&Width:": "S&zélesség:",
	"Width:": "Szélesség:",
	"&Height:": "&Magasság:",
	"Height:": "Magasság:",
	"Units": "Egység",
	"&Inches": "&hüvelyk",
	"Inches": "hüvelyk",
	"C&m": "&cm",
	"Cm": "cm",
	"&Pixels": "&képpont",
	"Pixels": "képpont",
	"Colors": "Színek",
	"&Black and white": "&Fekete-fehér",
	"Black and white": "Fekete-fehér",
	"Co&lors": "&Színes",
	"Transparency": "Áttetszőség",
	"Use &Transparent background color": "Á&tlátszó háttérszín használata",
	"Use Transparent background color": "Átlátszó háttérszín használata",
	"Select &Color": "Szí&n választása",
	"Select Color": "Szín választása",
	"Cancel": "Mégse",
	"&Default": "&Alapértelmezett",
	"Default": "Alapértelmezett",
	"Custom Zoom": "Egyéni méret",
	"Current zoom:": "Jelenlegi méret:",
	"Zoom to": "Nagyítás",
	"Flip and Rotate": "Tükrözés és forgatás",
	"Flip or rotate": "Tükrözés és forgatás",
	"&Flip horizontal": "&Vízszintes tükrözés",
	"Flip horizontal": "Vízszintes tükrözés",
	"Flip &vertical": "Függőleges &tükrözés",
	"Flip vertical": "Függőleges tükrözés",
	"&Rotate by angle": "&Forgatás",
	"Rotate by angle": "Forgatás",
	"Stretch and Skew": "Nyújtás és döntés",
	"Stretch": "Nyújtás",
	"&Horizontal:": "&Vízszintes:",
	"Horizontal:": "Vízszintes:",
	"&Vertical:": "&Függőleges:",
	"Vertical:": "Függőleges:",
	"Skew": "Döntés",
	"H&orizontal:": "Ví&zszintes:",
	"Degrees": "fok",
	"V&ertical:": "Függől&eges:",
	"Color Table": "Színtábla",
	"New": "Új",
	"&New ": "Ú&j",
	"New ": "Új",
	"&Help": "&Súgó",
	"Help": "Súgó",
	"Printing": "Nyomtatott dokumentum:",
	"on the": "Nyomtató:",
	"&Print": "Ny&omtatás",
	"Print": "Nyomtatás",
	"&Next Page": "Kö&vetkező oldal",
	"Next Page": "Következő oldal",
	"Pre&v Page": "Előző ol&dal",
	"Prev Page": "Előző oldal",
	"Zoom &In": "&Nagyítás",
	"Zoom In": "Nagyítás",
	"Zoom &Out": "K&icsinyítés",
	"Zoom Out": "Kicsinyítés",
	"&Close": "&Bezárás",
	"Close": "Bezárás",
	"Grid Settings": "Rács beállításai",
	"&Pixel Grid": "&Képpontokként",
	"Pixel Grid": "Képpontokként",
	"&Tile Grid": "&Egyéni",
	"Tile Grid": "Egyéni",
	"pixels": "képpont",
	"H&eight:": "&Magasság:",
	"Text": "Szöveg",
	"Undo": "Visszavonás",
	"Cut": "Kivágás ",
	"Copy": "Másolás ",
	"Paste": "Beillesztés",
	"Clear Selection": "Kijelölés törlése",
	"Select All": "Mindet kijelöli",
	"Text Toolbar": "Szöveg eszköztár",
	"Selection": "Kijelölés",
	"Cu&t": "&Kivágás ",
	"&Copy": "&Másolás ",
	"&Paste": "&Beillesztés",
	"C&lear Selection": "Kijelölés &törlése",
	"Select &All": "Min&det kijelöli",
	"C&opy To": "Fájlba más&olás",
	"Copy To": "Fájlba másolás",
	"Paste &From": "Fájl beilles&ztése",
	"Paste From": "Fájl beillesztése",
	"Flip/&Rotate": "Tükrözés/&Forgatás",
	"Flip/Rotate": "Tükrözés/Forgatás",
	"&Stretch/Skew": "&Nyújtás/Döntés",
	"Stretch/Skew": "Nyújtás/Döntés",
	"&Invert Colors": "&Színek megfordítása",
	"Invert Colors": "Színek megfordítása",
	"Thumbnail": "Vázlat",
	"&File": "&Fájl ",
	"File": "Fájl ",
	"&New": "Ú&j",
	"&Open": "&Megnyitás",
	"Open": "Megnyitás",
	"&Save": "M&entés",
	"Save": "Mentés",
	"Save &As": "Menté&s másként",
	"Save As": "Mentés másként",
	"Print Pre&view": "Nyom&tatási kép",
	"Print Preview": "Nyomtatási kép",
	"Page Se&tup": "&Oldalbeállítás",
	"Page Setup": "Oldalbeállítás",
	"S&end": "Kül&dés",
	"Send": "Küldés",
	"Set As &Wallpaper (Tiled)": "&Felhasználás tapétaként (Mozaik)",
	"Set As Wallpaper (Tiled)": "Felhasználás tapétaként (Mozaik)",
	"Set As Wa&llpaper (Centered)": "Fel&használás tapétaként (Középre)",
	"Set As Wallpaper (Centered)": "Felhasználás tapétaként (Középre)",
	"Recent File": "Legutóbbi fájl",
	"E&xit": "&Kilépés",
	"Exit": "Kilépés",
	"&Edit": "S&zerkesztés",
	"Edit": "Szerkesztés",
	"&Undo": "&Visszavonás",
	"&Repeat": "&Ismét",
	"Repeat": "Ismét",
	"&View": "&Nézet ",
	"View": "Nézet ",
	"&Tool Box": "S&zerszámkészlet",
	"Tool Box": "Szerszámkészlet",
	"&Color Box": "P&aletta",
	"Color Box": "Paletta",
	"Ctrl+L": "Ctrl+A",
	"&Status Bar": "Állapot&sor",
	"Status Bar": "Állapotsor",
	"T&ext Toolbar": "Szöveg eszköz&tár",
	"&Zoom": "&Nagyítás",
	"Zoom": "Nagyítás",
	"&Normal Size": "&Normál méret",
	"Normal Size": "Normál méret",
	"&Large Size": "Nagy &méret",
	"Large Size": "Nagy méret",
	"C&ustom": "&Egyéni beállítás",
	"Custom": "Egyéni beállítás",
	"Show &Grid": "&Rács megjelenítése",
	"Show Grid": "Rács megjelenítése",
	"Show T&humbnail": "&Vázlat megjelenítése",
	"Show Thumbnail": "Vázlat megjelenítése",
	"&View Bitmap": "&Bitkép megjelenítése",
	"View Bitmap": "Bitkép megjelenítése",
	"&Image": "&Kép",
	"Image": "Kép",
	"&Flip/Rotate": "Tükrözés/&Forgatás",
	"&Attributes": "&Tulajdonságok",
	"&Clear Image": "&Kép törlése",
	"Clear Image": "Kép törlése",
	"&Draw Opaque": "Ne&m átlátszó",
	"Draw Opaque": "Nem átlátszó",
	"&Colors": "Szín&ek",
	"&Edit Colors": "&Színek szerkesztése",
	"Edit Colors": "Színek szerkesztése",
	"&Help Topics": "&Tartalom",
	"Help Topics": "Tartalom",
	"&About Paint": "&Névjegy",
	"About Paint": "Névjegy",
	"&Update": "&Frissítés",
	"Update": "Frissítés",
	"Save Copy &As": "&Másolat mentése másként",
	"Save Copy As": "Másolat mentése másként",
	"untitled": "névtelen",
	"Bitmap Image": "Bitkép",
	"Bitmap Files (*.bmp)": "Bitkép fájlok (*.bmp)",
	"PCX Files": "PCX fájl",
	"Icon Files": "Ikon fájl",
	"Monochrome Bitmap (*.bmp;*.dib)": "Fekete-fehér bitkép (*.bmp;*.dib)",
	"16 Color Bitmap (*.bmp;*.dib)": "16 színű bitkép (*.bmp;*.dib)",
	"256 Color Bitmap (*.bmp;*.dib)": "256 színű bitkép (*.bmp;*.dib)",
	"Paint cannot open this file.": "A Paint nem tudja megnyitni ezt a fájlt.",
	"Paint cannot read this file.": "A Paint nem tudja olvasni ezt a fájlt.",
	"This file is read-only.": "A fájl írásvédett.",
	"To save your changes, use a different filename.": "A módosítások mentéséhez használjon más fájlnevet.",
	"This file is already open.": "A fájl már meg van nyitva.",
	"This is not a valid .PCS file.": "Érvénytelen .PCS fájl",
	"This file is open for editing and cannot be overwritten.": "A fájl szerkesztésre van megnyitva, és nem lehet felülírni.",
	"Use a different filename to save your changes.": "A módosítások mentéséhez használjon más fájlnevet.",
	"This is not a valid bitmap file, or its format is not currently supported.": "Érvénytelen bitkép fájl, vagy a formátuma nem támogatott.",
	"This is not a valid icon.": "Érvénytelen ikon",
	"This is not a valid cursor.": "Érvénytelen kurzor",
	"Save was interrupted, so your file has not been saved.": "A mentés megszakadt, a fájl mentésére nem került sor.",
	"You cannot save to a read-only file.": "Írásvédett fájlba nem lehet menteni.",
	"Use a different file name.": "Használjon más fájlnevet.",
	"This file is already in use.": "A fájl már használatban van.",
	"Close the program, and then try again.": "Zárja be a programot, majd próbálkozzon újra.",
	"Paint cannot save this file.": "A Paint nem tudja menteni ezt a fájlt.",
	"Paint cannot save to the same filename with a different file type.": "A Paint nem tudja menteni a fájlt ugyanazzal a fájlnévvel, de más fájltípussal.",
	"The grid spacing must be an integer between %d and %d.": "A rácsköznek %d és %d közötti egész számnak kell lennie.",
	"There is not enough memory or resources to complete operation.": "Nincs elegendő memória vagy erőforrás a művelet befejezéséhez.",
	"Close some programs, and then try again.": "Zárjon be néhány programot, majd próbálkozzon újra.",
	"Low on memory or resources.": "Kevés a memória vagy az  erőforrás.",
	"Group error.": "Csoporthiba",
	"Paint was unable to print your document. Please make sure you have sufficient disk space and that your printer is working correctly.": "A Paint nem tudta a dokumentumot kinyomtatni. Győződjön meg arról, hogy van elegendő szabad hely a merevlemezen, és arról, hogy a nyomtató megfelelően működik.",
	"Saving into this format may cause some loss of color information.": "Ha ebben a formátumban ment, színveszteséget okozhat.",
	"Do you want to continue?": "Biztosan folytatja?",
	"Converting to black and white cannot be undone.  This action affects the current file and may cause some loss of color information.": "A fekete-fehér konverzió nem vonható vissza.  Ez a művelet a színinformáció elvesztésével jár.",
	"Bitmaps must be greater than one pixel on a side.": "A bitkép minden oldalának legalább két képpont szélesnek kell lennie.",
	"Generic error.": "Általános hiba",
	"File not found.": "A fájl nem található.",
	"Bad path.": "Rossz elérési út",
	"Too many open files.": "Túl sok fájl van megnyitva.",
	"Access denied.": "A hozzáférés megtagadva.",
	"Invalid file.": "Érvénytelen fájl",
	"Remove current folder.": "Távolítsa el az aktuális mappát.",
	"Folder full.": "A mappa megtelt.",
	"Bad seek.": "Rossz keresés",
	"Hard IO error.": "Súlyos IO hiba",
	"Sharing violation.": "Megosztásmegsértés",
	"Lock violation.": "Zárolásmegsértés",
	"Disk full.": "A lemez megtelt.",
	"End of file.": "Vége van a fájlnak.",
	"Error getting the Clipboard Data!": "Hiba a Vágólap adatainak vételekor!",
	"No Printer Found @ page setup": "Nem található nyomtató @ oldalbeállítás",
	"24-bit Bitmap (*.bmp;*.dib)": "24 bites bitkép (*.bmp;*.dib)",
	"All Files": "Minden fájl",
	"Palette|*.pal|": "Paletta|*.pal|",
	"OLE 2.0 was unable to start.": "Az OLE 2.0 nem tudott elindulni.",
	"Make sure that you are using the correct version of the OLE libraries.": "Győződjön meg arról, hogy az OLE függvénytárak megfelelő verzióját használja-e.",
	"Resets the text be without any attributes.": "A szöveget attribútumok nélküli alapállapotba állítása",
	"Sets or clears the text bold attribute.": "A szöveg félkövér attribútumának beállítása vagy törlése",
	"Sets or clears the text italic attribute.": "A szöveg dőlt attribútumának beállítása vagy törlése",
	"Selects the font used by the text.": "A szöveg által használt betűtípus kijelölése",
	"Selects the point size of the text.": "A szöveg pontméretének kijelölése",
	"Sets or clears the text underline attribute.": "A szöveg aláhúzott attribútumának beállítása vagy törlése",
	"Shows or hides the tooltips.": "Gombnevek megjelenítése vagy elrejtése",
	"Show Paint Help.": "A Paint Súgójának megjelenítése",
	"Sends a picture by using mail or fax.": "Kép küldése levélként vagy faxként",
	"Copies the selection to a file.": "A kijelölt rész fájlba másolása",
	"Pastes a file into the selection.": "Fájlt beillesztése a kijelölésbe",
	"Zooms the picture to 100%.": "A kép nagyítása 100%.",
	"Zooms the picture to 400%.": "A kép nagyítása 400%.",
	"Zooms the picture.": "A kép nagyítása",
	"Displays the entire picture.": "A teljes kép megjelenítése",
	"Shows or hides the thumbnail view of the picture.": "A kép vázlatának megjelenítése vagy elrejtése",
	"Shows or hides the grid.": "A rács megjelenítése vagy elrejtése",
	"Shows or hides the text toolbar.": "A Szöveg eszköztár megjelenítése vagy elrejtése",
	"Flips or rotates the picture or a selection.": "Kép vagy kijelölés tükrözése vagy forgatása",
	"Stretches or skews the picture or a selection.": "Kép vagy kijelölés megnyújtása vagy megdöntése",
	"Inverts the colors of the picture or a selection.": "Kép vagy kijelölés színeinek megfordítása",
	"Changes the attributes of the picture.": "A kép jellemzőinek a módosítása",
	"Clears the picture or selection.": "A kép vagy a kijelölés törlése",
	"The font size must be a numeric value.": "A betű méretének numerikus értéknek kell lennie.",
	"Contains commands for working with the selected item(s).": "A kijelölt elemmel vagy elemekkel való munkára szolgáló parancsok",
	"Contains commands for selecting and transferring items.": "Elemek kijelölésére és átvitelére szolgáló parancsok",
	"Contains commands for customizing this window.": "Parancsok ennek az ablaknak a testreszabásához.",
	"Contains commands for manipulating pictures and setting attributes.": "Képek kezelésére és attribútumok beállítására szolgáló parancsok",
	"Contains commands for using custom colors and drawing options.": "Egyéni színek és rajzoló beállítások használatára szolgáló parancsok",
	"Contains commands for displaying Help for and information about Paint.": "A Paint Súgójának és információinak megjelenítésére szolgáló parancsok",
	"Cannot save file.": "A fájlt nem lehet menteni.",
	"Error removing temporary file.": "Hiba ideiglenes fájl eltávolításakor",
	"Get Colors": "Színek betöltése",
	"Save Colors": "Színek mentése",
	"File last saved:": "Utolsó mentés:",
	"Not Available": "Nincs adat",
	"Size on disk:": "Méret a lemezen:",
	"%s bytes": "%s bájt",
	"Painting": "Kép",
	"Bitmap": "Bitkép",
	"Fonts": "Betűtípusok",
	"Tools": "Eszközök ",
	"All Picture Files": "Minden képfájl",
	"For Help, click Help Topics on the Help Menu.": "Ha segítségre van szüksége, kattintson a Súgó menü Témakörök parancsára.",
	"Select an area on which to get Help.": "Jelölje ki azt a területet, melyhez segítséget szeretne.",
	"%1 in %2": "%1 a következőben: %2",
	"Creates a new document.": "Új dokumentum létrehozása",
	"Opens an existing document.": "Létező dokumentum megnyitása",
	"Closes the active document.": "Az aktív dokumentum bezárása",
	"Saves the active document.": "Az aktív dokumentum mentése",
	"Saves the active document with a new name.": "Az aktív dokumentum mentése új néven",
	"Changes the page layout.": "Az oldalbeállítás módosítása",
	"Specifies the default printer setup.": "Az alapnyomtató beállításainak megadása",
	"Prints the active document and sets printing options.": "Az aktív dokumentum nyomtatása és a nyomtatási beállítások megadása",
	"Displays full pages.": "Teljes oldalak megjelenítése",
	"Opens this document.": "A dokumentum megnyitása",
	"Deletes the selection.": "A kijelölés törlése",
	"Erases everything.": "Minden törlése",
	"Copies the selection and puts it on the Clipboard.": "A kijelölt rész másolása a Vágólapra  ",
	"Cuts the selection and puts it on the Clipboard.": "A kijelölés kivágása és a Vágólapra másolása",
	"Finds the specified text.": "A megadott szöveg keresése",
	"Inserts the contents of the Clipboard.": "A Vágólap tartalmának beillesztése",
	"Repeats the last action.": "A legutóbbi művelet megismétlése",
	"Replaces specific text with different text.": "A megadott szöveg helyettesítése egy másik szöveggel",
	"Selects everything.": "Mindent kijelöl.",
	"Undoes the last action.": "A legutóbbi művelet visszavonása",
	"Redoes the previously undone action.": "Az előzőleg visszavont művelet visszavonása",
	"Displays program information, version number, and copyright.": "Programinformáció, verziószám és szerzői jogi szöveg megjelenítése",
	"Quits Paint.": "Kilépés a Paint programból",
	"Opens Paint Help.": "A Paint Súgójának megnyitása",
	"Displays instructions about how to use Help.": "A Súgó használatáról szóló Súgó megjelenítése.",
	"Displays Help for areas you click on.": "Súgó megjelenítése arra a területre vonatkozóan, amelyre rákattint.",
	"Displays Help for the current task or command.": "Az aktuális feladatra vagy parancsra vonatkozó Súgó megjelenítése",
	"Centers this bitmap as the desktop wallpaper.": "Asztal tapétájaként a bitkép középre igazítása.",
	"Tiles this bitmap as the desktop wallpaper.": "Bitkép mozaik elrendezése asztal-tapétaként.",
	"Sends the selection using mail or fax.": "Kijelölt rész küldése levélként vagy faxként",
	"Prints the selection.": "A kijelölt rész nyomtatása",
	"Shows or hides the thumbnail.": "A vázlat megjelenítése vagy elrejtése",
	"Shows Paint Help.": "A Paint Súgójának megjelenítése",
	"Shows or hides the status bar.": "Az állapotsor megjelenítése vagy elrejtése.",
	"Shows or hides the tool box.": "Az eszközkészlet megjelenítése vagy elrejtése",
	"Shows or hides the color box.": "A paletta megjelenítése vagy elrejtése",
	"Only a Far East font can be used for vertical editing.": "Csak távol-keleti betűtípust lehet használni függőleges szerkesztéshez.",
	"Changes the window size.": "Az ablakméret módosítása",
	"Changes the window position.": "Az ablak helyének módosítása",
	"Reduces the window to an icon.": "Az ablak kis méretűvé tétele",
	"Enlarges the window to full size.": "Az ablak teljes méretűvé növelése",
	"Switches to the next document window.": "Váltás a következő dokumentumablakra",
	"Switches to the previous document window.": "Váltás az előző dokumentumablakra",
	"Closes the active window and asks if you want to save changes.": "Az aktív ablak bezárása, és annak megkérdezése, hogy kívánja-e menteni a módosításokat",
	"Restores the window to normal size.": "Az ablak visszaállítása eredeti méretre",
	"Activates the task list.": "A feladatlista megnyitása",
	"All Files (*.*)": "Minden fájl (*.*)",
	"Untitled": "Cím nélküli",
	"an unnamed file": "névtelen fájl",
	"&Hide": "&Elrejtés",
	"Hide": "Elrejtés",
	"No error message is available.": "Nincs hibaüzenet.",
	"An unsupported operation was attempted.": "Nem támogatott művelet végrehajtására történt kísérlet.",
	"A required resource was unavailable.": "A kért erőforrás nem érhető el.",
	"Out of memory.": "Nincs elég memória.",
	"An unknown error has occurred.": "Ismeretlen hiba történt.",
	"on %1": "Port: %1",
	"&One Page": "&Egy oldal",
	"One Page": "Egy oldal",
	"&Two Page": "&Kétoldalas",
	"Two Page": "Kétoldalas",
	"Page %u": "%u. oldal",
	"Pages %u-%u": "%u.-%u. oldal",
	"Printer Files (*.prn)|*.prn|All Files (*.*)|*.*||": "Nyomtatófájlok (*.prn)|*.prn|Minden fájl (*.*)|*.*||",
	"Print to File": "Nyomtatás fájlba",
	"to %1": "cél: %1",
	"&Update %1": "%1 &frissítése",
	"Update %1": "%1 frissítése",
	"E&xit && Return to %1": "Kilépés és &visszatérés a következőbe: %1",
	"Exit && Return to %1": "Kilépés és visszatérés a következőbe: %1",
	"Linked %s": "Csatolva: %s",
	"Unknown Type": "Ismeretlen típus",
	"Invalid filename.": "Érvénytelen fájlnév",
	"Failed to open document.": "Nem sikerült a dokumentumot megnyitni.",
	"Failed to save document.": "A dokumentum mentése nem sikerült.",
	"Save changes to %1?": "Menti %1 módosításait?",
	"Failed to create empty document.": "Nem sikerült üres dokumentumot létrehozni.",
	"The file is too large to open.": "A fájl túl nagy a megnyitáshoz.",
	"Could not start print job.": "Nem lehetett elindítani a nyomtatási feladatot.",
	"Failed to launch help.": "A Súgó indítása nem sikerült.",
	"Internal application error.": "Belső hiba az alkalmazásban.",
	"Command failed.": "A parancs végrehajtása nem sikerült.",
	"Insufficient memory to perform operation.": "Nincs elég memória a művelet végrehajtásához.",
	"System registry entries have been removed and the INI file (if any) was deleted.": "A rendszerleíróadatbázis-bejegyzések eltávolítva, az INI fájlok (ha voltak) törölve.",
	"Not all of the system registry entries (or INI file) were removed.": "Nem sikerült eltávolítani valamennyi rendszerleíróadatbázis-bejegyzést és INI fájlt.",
	"This program requires the file %s, which was not found on this system.": "A programnak szüksége van erre a fájlra: %s. Ez a fájl nem található a rendszeren.",
	"This program is linked to the missing export %s in the file %s. This machine may have an incompatible version of %s.": "Ez a program a következő fájlban található hiányzó %s exporthoz van csatolva: %s. Lehet, hogy ez a gép %s inkompatíbilis verziójával rendelkezik.",
	"Please enter an integer.": "Írjon be egy egész számot.",
	"Please enter a number.": "Adjon meg egy számot.",
	"Please enter an integer between %1 and %2.": "Adjon meg egy %1 és %2 közé eső egész számot.",
	"Please enter a number between %1 and %2.": "Adjon meg egy %1 és %2 közé eső számot.",
	"Please enter no more than %1 characters.": "Adjon meg nem több, mint %1 karaktert.",
	"Please select a button.": "Válasszon egy gombot.",
	"Please enter an integer between 0 and 255.": "Adjon meg egy 0 és 255 közötti egész számot.",
	"Please enter a positive integer.": "Adjon meg egy pozitív egész számot.",
	"Please enter a date and/or time.": "Adjon meg egy dátumot vagy egy időpontot.",
	"Please enter a currency.": "Adjon meg egy pénznemet.",
	"Unexpected file format.": "Váratlan fájlformátum.",
	"Cannot find this file.": "Ez a fájl nem található.",
	"Please verify that the correct path and file name are given.": "Ellenőrizze, hogy a helyes elérési utat és fájlnevet adta-e meg.",
	"Destination disk drive is full.": "A céllemez megtelt.",
	"Unable to read from %1, it is opened by someone else.": "A következő nem olvasható, mert valaki megnyitotta: %1.",
	"Unable to write to %1, it is read-only or opened by someone else.": "%1 írása nem lehetséges, mert az vagy írásvédett, vagy valaki más már megnyitotta.",
	"An unexpected error occurred while reading %1.": "Nem várt hiba történt %1 olvasása közben.",
	"An unexpected error occurred while writing %1.": "Nem várt hiba történt %1 írása közben.",
	"Unable to register document.": "A dokumentum nem regisztrálható.",
	"The document may already be open.": "Valószínűleg már használatban van.",
	"Update %1 before proceeding?": "Folytatás előtt frissíti a következőt: %1?",
	"Could not update client.": "Az ügyfél frissítése nem sikerült.",
	"Failed to register. ActiveX features may not work properly.": "Nem sikerült a regisztrálás. Valószínűleg nem működnek megfelelően az ActiveX funkciók.",
	"Failed to update the system registry.": "Nem sikerült a rendszerleíró adatbázis frissítése.",
	"Please try using REGEDIT.": "Próbálja meg a REGEDIT használatával.",
	"Unable to read write-only property.": "Nem lehet csak írható tulajdonságot olvasni.",
	"Unable to write read-only property.": "Nem lehet írásvédett tulajdonságot írni.",
	"Unable to load mail system support.": "A levelezőrendszert nem sikerült betölteni.",
	"Mail system DLL is invalid.": "Érvénytelen a levelezőrendszer DLL-je.",
	"Send Mail failed to send message.": "A levelezőrendszer nem tudta elküldeni az üzenetet.",
	"No error occurred.": "Nem történt hiba.",
	"An unknown error occurred while accessing %1.": "Ismeretlen hiba történt %1 használata közben.",
	"%1 was not found.": "%1 nem található.",
	"%1 contains an invalid path.": "%1 érvénytelen elérési utat tartalmaz.",
	"%1 could not be opened because there are too many open files.": "%1 nem nyitható meg, mert túl sok fájl van nyitva.",
	"Access to %1 was denied.": "A következő fájlhoz való hozzáférés megtagadva: %1.",
	"An invalid file handle was associated with %1.": "A következő fájlhoz érvénytelen leírót rendeltek: %1.",
	"%1 could not be removed because it is the current directory.": "%1 nem távolítható el, mert ez az aktuális könyvtár.",
	"%1 could not be created because the directory is full.": "%1 nem hozható létre, mert a könyvtár megtelt.",
	"Seek failed on %1": "Pozícionálási hiba a következőn: %1",
	"A hardware I/O error was reported while accessing %1.": "%1 használata során hardver I/O hiba történt.",
	"A sharing violation occurred while accessing %1.": "%1 használata közben megosztásmegsértés történt.",
	"A locking violation occurred while accessing %1.": "%1 használata közben zárolásmegsértés történt.",
	"Disk full while accessing %1.": "%1 használata közben a lemez megtelt.",
	"An attempt was made to access %1 past its end.": "%1 használatára történt kísérlet, annak megszüntetése után.",
	"An attempt was made to write to the reading %1.": "Írni próbált a következő, olvasásra megnyitott objektumba: %1.",
	"An attempt was made to read from the writing %1.": "Olvasni próbált a következő, írásra megnyitott objektumból: %1.",
	"%1 has a bad format.": "%1 formátuma hibás.",
	"%1 contained an unexpected object.": "%1 nem várt objektumot tartalmaz.",
	"%1 contains an incorrect schema.": "%1 hibás sémát tartalmaz.",
	"Selects a rectangular part of the picture to move, copy, or edit.": "A kép egy téglalappal határolt részének kijelölése áthelyezéshez, másoláshoz vagy szerkesztéshez",
	"Select": "Kijelölés",
	"Selects a free-form part of the picture to move, copy, or edit.": "A kép egy szabadkézzel határolt részének kijelölése áthelyezéshez, másoláshoz vagy szerkesztéshez",
	"Free-Form Select": "Szabadkézi kijelölés",
	"Inserts text into the picture.": "Szöveg beszúrása a képbe",
	"Fills an area with the current drawing color.": "Terület kitöltése az aktuális rajzoló színnel",
	"Fill With Color": "Kitöltés színnel",
	"Draws a straight line with the selected line width.": "Egyenes vonal rajzolása a kijelölt vonalvastagsággal",
	"Line": "Vonal",
	"Draws using an airbrush of the selected size.": "Rajzolás a kijelölt méretű festékszóróval",
	"Airbrush": "Festékszóró",
	"Draws a curved line with the selected line width.": "Görbe vonal rajzolása a kijelölt vonalvastagsággal.",
	"Curve": "Görbe",
	"Draws a polygon with the selected fill style.": "Sokszög rajzolása a kijelölt kitöltő stílussal",
	"Polygon": "Sokszög",
	"Draws a rounded rectangle with the selected fill style.": "Kerekített sarkú téglalap rajzolása a kijelölt kitöltő stílussal",
	"Rounded Rectangle": "Kerekített sarkú téglalap",
	"Draws a free-form line one pixel wide.": "Egy képpont vastagságú szabadkézi vonal húzása",
	"Pencil": "Ceruza",
	"Erases a portion of the picture, using the selected eraser shape.": "Kép törlése a kijelölt radír használatával",
	"Eraser/Color Eraser": "Radír",
	"Changes the magnification.": "A nagyítás mértékének megváltoztatása",
	"Magnifier": "Nagyító",
	"Picks up a color from the picture for drawing.": "Szín felvétele a képről a rajzoláshoz",
	"Pick Color": "Szín felvétele",
	"Draws using a brush with the selected shape and size.": "Rajzolás a kijelölt alakú és méretű ecsettel",
	"Brush": "Ecset",
	"Draws a rectangle with the selected fill style.": "Téglalap rajzolása a kijelölt kitöltő stílussal",
	"Rectangle": "Téglalap",
	"Draws a filled rectangle.": "Kitöltött téglalap rajzolása",
	"Draws an ellipse with the selected fill style.": "Ellipszis rajzolása a kijelölt kitöltő stílussal",
	"Ellipse": "Ellipszis",
	"Draws a filled ellipse.": "Kitöltött ellipszis rajzolása",
	"Makes the current selection either opaque or transparent.": "Az aktuális kijelölés átlátszatlanná vagy áttetszővé tétele",
	"Creates a new color.": "Új szín létrehozása",
	"Uses a previously saved palette of colors.": "Egy előzőleg mentett színpaletta használata",
	"Saves the current palette of colors to a file.": "A jelenlegi színpaletta mentése egy fájlba",
	"You must save the file before choosing it as Wallpaper.": "Tapétaként való kiválasztás előtt mentenie kell a fájlt.",
	"The selection is now larger than the bitmap.": "A kijelölés most nagyobb, mint a bitkép.",
	"Would you like the bitmap enlarged?": "Szeretné a bitképet megnövelni?",
	"The image in the clipboard is larger than the bitmap.": "A Vágólapon lévő kép nagyobb, mint a bitkép.",
	"The file is not in the correct format.": "A fájl nem a megfelelő formátumban van.",
	"Not enough room to paste text.": "Nincs elég hely a szöveg beillesztéséhez.",
	"Enlarge the text area and try again.": "Növelje meg a szövegterületet, majd próbálkozzon újra.",
	"Places the text.": "Szöveg elhelyezése"
});
