//
// NOTE: This is a generated file! Don't edit it directly.
// Eventually community translation will be set up on some translation platform.
// 
// Generated with: npm run update-localization
//
loaded_localizations("fr", {
	"Attributes": "Attributs",
	"&Width:": "&Largeur :",
	"Width:": "Largeur :",
	"&Height:": "&Hauteur :",
	"Height:": "Hauteur :",
	"Units": "Unités",
	"&Inches": "&Pouces",
	"Inches": "Pouces",
	"&Pixels": "Pi&xels",
	"Pixels": "Pixels",
	"Colors": "Couleurs",
	"&Black and white": "&Noir et blanc",
	"Black and white": "Noir et blanc",
	"Co&lors": "C&ouleurs",
	"Transparency": "Transparence",
	"Use &Transparent background color": "Utiliser une couleur de fond &transparente",
	"Use Transparent background color": "Utiliser une couleur de fond transparente",
	"Select &Color": "Choisir la &couleur",
	"Select Color": "Sélection d'une couleur",
	"Cancel": "Annuler",
	"&Default": "Par &défaut",
	"Default": "Par défaut",
	"Custom Zoom": "Zoom personnalisé",
	"Current zoom:": "Zoom actuel :",
	"Zoom to": "Faire un zoom de",
	"Flip and Rotate": "Retourner et faire pivoter",
	"Flip or rotate": "Retourner ou faire pivoter",
	"&Flip horizontal": "Retourner &horizontalement",
	"Flip horizontal": "Retourner horizontalement",
	"Flip &vertical": "Retourner &verticalement",
	"Flip vertical": "Retourner verticalement",
	"&Rotate by angle": "&Faire pivoter d'un angle de",
	"Rotate by angle": "Faire pivoter d'un angle de",
	"Stretch and Skew": "Étirer et incliner",
	"Stretch": "Étirement",
	"&Horizontal:": "&Horizontal :",
	"Horizontal:": "Horizontal :",
	"&Vertical:": "V&ertical :",
	"Vertical:": "Vertical :",
	"Skew": "Inclinaison",
	"H&orizontal:": "H&orizontale :",
	"Degrees": "degrés",
	"V&ertical:": "Ve&rticale :",
	"Color Table": "Table des couleurs",
	"New": "Nouveau",
	"&New ": "&Nouveau ",
	"New ": "Nouveau ",
	"&Help": "&Aide",
	"Help": "Aide",
	"Printing": "Impression en cours",
	"on the": "sur le",
	"&Print": "&Imprimer",
	"Print": "Imprimer",
	"&Next Page": "Page &suiv.",
	"Next Page": "Page suiv.",
	"Pre&v Page": "Page &préc.",
	"Prev Page": "Page préc.",
	"Zoom &In": "Zoom a&vant",
	"Zoom In": "Zoom avant",
	"Zoom &Out": "Zoom a&rrière",
	"Zoom Out": "Zoom arrière",
	"&Close": "&Fermer",
	"Close": "Fermer",
	"Grid Settings": "Paramètres de la grille",
	"&Pixel Grid": "Grille de &pixels",
	"Pixel Grid": "Grille de pixels",
	"&Tile Grid": "Grille &mosaïque",
	"Tile Grid": "Grille mosaïque",
	"H&eight:": "&Hauteur :",
	"Text": "Texte",
	"Undo": "Annuler",
	"Cut": "Couper",
	"Copy": "Copier",
	"Paste": "Coller",
	"Clear Selection": "Effacer la sélection",
	"Select All": "Sélectionner tout",
	"Text Toolbar": "Barre d'outils texte",
	"Selection": "Sélection",
	"Cu&t": "&Couper",
	"&Copy": "Co&pier",
	"&Paste": "C&oller",
	"C&lear Selection": "&Effacer la sélection",
	"Select &All": "Sélectionner &tout",
	"C&opy To": "Copier &vers",
	"Copy To": "Copier dans",
	"Paste &From": "Coller à partir &de",
	"Paste From": "Coller à partir de",
	"Flip/&Rotate": "&Retourner/Faire pivoter",
	"Flip/Rotate": "Retourner/Faire pivoter",
	"&Stretch/Skew": "Étirer/I&ncliner",
	"Stretch/Skew": "Étirer/Incliner",
	"&Invert Colors": "Inver&ser les couleurs",
	"Invert Colors": "Inverser les couleurs",
	"Thumbnail": "Miniature",
	"&File": "&Fichier",
	"File": "Fichier",
	"&New": "&Nouveau",
	"&Open": "&Ouvrir",
	"Open": "Ouvrir",
	"&Save": "&Enregistrer",
	"Save": "Enregistrer",
	"Save &As": "En&registrer sous",
	"Save As": "Enregistrer sous",
	"Print Pre&view": "&Aperçu avant impression",
	"Print Preview": "Aperçu avant impression",
	"Page Se&tup": "&Mise en page",
	"Page Setup": "Mise en page",
	"S&end": "Envo&yer",
	"Send": "Envoyer",
	"Set As &Wallpaper (Tiled)": "&Papier peint par défaut (mosaïque)",
	"Set As Wallpaper (Tiled)": "Papier peint par défaut (mosaïque)",
	"Set As Wa&llpaper (Centered)": "Papier peint par &défaut (centré)",
	"Set As Wallpaper (Centered)": "Papier peint par défaut (centré)",
	"Recent File": "Fichier récent",
	"E&xit": "&Quitter",
	"Exit": "Quitter",
	"&Edit": "&Edition",
	"Edit": "Edition",
	"&Undo": "&Annuler",
	"&Repeat": "&Répéter",
	"Repeat": "Répéter",
	"Del": "Suppr",
	"&View": "&Affichage",
	"View": "Affichage",
	"&Tool Box": "B&oîte à outils",
	"Tool Box": "Boîte à outils",
	"&Color Box": "&Palette de couleurs ",
	"Color Box": "Palette de couleurs ",
	"&Status Bar": "&Barre d'état",
	"Status Bar": "Barre d'état",
	"T&ext Toolbar": "Barr&e d'outils texte",
	"&Normal Size": "&Taille normale",
	"Normal Size": "Taille normale",
	"Ctrl+PgUp": "Ctrl+PG.PREC",
	"&Large Size": "G&rande taille",
	"Large Size": "Grande taille",
	"Ctrl+PgDn": "Ctrl+PG.SUIV",
	"C&ustom": "&Personnaliser",
	"Custom": "Personnaliser",
	"Show &Grid": "Afficher la &grille",
	"Show Grid": "Afficher la grille",
	"Show T&humbnail": "Afficher la &miniature",
	"Show Thumbnail": "Afficher la miniature",
	"&View Bitmap": "Afficher l'&image",
	"View Bitmap": "Afficher l'image",
	"&Flip/Rotate": "&Retourner/Faire pivoter",
	"&Attributes": "&Attributs",
	"&Clear Image": "E&ffacer l'image",
	"Clear Image": "Effacer l'image",
	"Ctrl+Shft+N": "Ctrl+Maj+N",
	"&Draw Opaque": "&Dessiner opaque",
	"Draw Opaque": "Dessiner opaque",
	"&Colors": "&Couleurs",
	"&Edit Colors": "&Modifier les couleurs",
	"Edit Colors": "Modification des couleurs",
	"&Help Topics": "&Rubriques d'aide",
	"Help Topics": "Rubriques d'aide",
	"&About Paint": "À &propos de Paint",
	"About Paint": "À propos de Paint",
	"&Update": "Mettre à jo&ur",
	"Update": "Mettre à jour",
	"Save Copy &As": "&Enregistrer la copie sous",
	"Save Copy As": "Enregistrer la copie sous",
	"untitled": "Sans titre",
	"Bitmap Image": "Image Bitmap",
	"Bitmap Files (*.bmp)": "Fichiers Bitmap (*.bmp)",
	"PCX Files": "Fichiers PCX",
	"Icon Files": "Fichiers icône",
	"Monochrome Bitmap (*.bmp;*.dib)": "Bitmap monochrome (*.bmp;*.dib)",
	"16 Color Bitmap (*.bmp;*.dib)": "Bitmap 16 couleurs (*.bmp;*.dib)",
	"256 Color Bitmap (*.bmp;*.dib)": "Bitmap 256 couleurs (*.bmp;*.dib)",
	"Paint cannot open this file.": "Paint ne peut pas ouvrir ce fichier.",
	"Paint cannot read this file.": "Paint ne peut pas lire ce fichier.",
	"This file is read-only.": "Ce fichier est en lecture seule.",
	"To save your changes, use a different filename.": "Pour sauvegarder vos changements, utilisez un nom différent.",
	"This file is already open.": "Ce fichier est déjà ouvert.",
	"This is not a valid .PCS file.": "Ce fichier n'est pas un fichier .PCS valide.",
	"This file is open for editing and cannot be overwritten.": "Ce fichier est ouvert pour l'édition et ne peut pas être écrasé.",
	"Use a different filename to save your changes.": "Utilisez un nom différent pour enregistrer vos changements.",
	"This is not a valid bitmap file, or its format is not currently supported.": "Ce fichier n'est pas un fichier bitmap valide, ou son format n'est pas pris en charge.",
	"This is not a valid icon.": "Cette icône n'est pas valide.",
	"This is not a valid cursor.": "Ce curseur n'est pas valide.",
	"Save was interrupted, so your file has not been saved.": "L'enregistrement a été interrompu et votre fichier n'a donc pas été enregistré.",
	"You cannot save to a read-only file.": "Impossible d'enregistrer un fichier en lecture seule.",
	"Use a different file name.": "Utilisez un nom de fichier différent.",
	"This file is already in use.": "Ce fichier est déjà utilisé.",
	"Close the program, and then try again.": "Quittez le programme, et essayez de nouveau.",
	"Paint cannot save this file.": "Paint ne peut pas enregistrer ce fichier.",
	"Paint cannot save to the same filename with a different file type.": "Le programme Paint ne peut pas enregistrer le fichier sous le même nom avec un type de fichier différent.",
	"The grid spacing must be an integer between %d and %d.": "La valeur de l'espacement de la grille doit être un entier compris entre %d et %d.",
	"There is not enough memory or resources to complete operation.": "Mémoire ou ressources insuffisantes pour terminer cette opération.",
	"Close some programs, and then try again.": "Quittez certains programmes, et essayez de nouveau.",
	"Low on memory or resources.": "Mémoire ou ressources faibles.",
	"Group error.": "Erreur de groupe.",
	"Paint was unable to print your document. Please make sure you have sufficient disk space and that your printer is working correctly.": "Paint n'a pas pu imprimer votre document. Vérifiez que l'espace disque est suffisant et que l'imprimante fonctionne.",
	"Saving into this format may cause some loss of color information.": "Si vous enregistrez dans ce format vous risquez de perdre des informations sur les couleurs.",
	"Do you want to continue?": "Voulez-vous continuer ?",
	"Converting to black and white cannot be undone.  This action affects the current file and may cause some loss of color information.": "La conversion en noir et blanc ne peut pas être annulée. Cette action affecte le fichier en cours et peut entraîner une perte de couleurs.",
	"Bitmaps must be greater than one pixel on a side.": "Les bitmaps doivent avoir une taille supérieure à un pixel de côté.",
	"Generic error.": "Erreur générique.",
	"File not found.": "Fichier introuvable.",
	"Bad path.": "Chemin d'accès incorrect.",
	"Too many open files.": "Trop de fichiers ouverts.",
	"Access denied.": "Accès refusé.",
	"Invalid file.": "Fichier non valide.",
	"Remove current folder.": "Supprimer le dossier en cours.",
	"Folder full.": "Dossier plein.",
	"Bad seek.": "Recherche incorrecte.",
	"Hard IO error.": "Erreur E/S matérielle.",
	"Sharing violation.": "Violation de partage.",
	"Lock violation.": "Violation de verrouillage.",
	"Disk full.": "Disque plein.",
	"End of file.": "Fin de fichier.",
	"Error getting the Clipboard Data!": "Erreur d'obtention des données du Presse-papiers !",
	"No Printer Found @ page setup": "Aucune imprimante à cette configuration de page",
	"24-bit Bitmap (*.bmp;*.dib)": "Bitmap 24 bits (*.bmp;*.dib)",
	"All Files": "Tous",
	"untitled.pal": "Sans titre.pal",
	"OLE 2.0 was unable to start.": "OLE 2.0 n'a pu démarrer.",
	"Make sure that you are using the correct version of the OLE libraries.": "Assurez-vous que vous utilisez la bonne version des bibliothèques OLE.",
	"Resets the text be without any attributes.": "Supprime les attributs du texte.",
	"Sets or clears the text bold attribute.": "Active ou désactive l'attribut gras du texte.",
	"Sets or clears the text italic attribute.": "Active ou désactive l'attribut italique du texte.",
	"Selects the font used by the text.": "Sélectionne la police utilisée pour le texte.",
	"Selects the point size of the text.": "Sélectionne la taille du texte en points.",
	"Sets or clears the text underline attribute.": "Active ou désactive l'attribut souligné du texte.",
	"Shows or hides the tooltips.": "Affiche ou masque les info-bulles.",
	"Show Paint Help.": "Afficher l'aide de Paint.",
	"Sends a picture by using mail or fax.": "Envoie une image en utilisant le courrier électronique ou le télécopieur.",
	"Copies the selection to a file.": "Copie la sélection dans un fichier.",
	"Pastes a file into the selection.": "Colle un fichier dans la sélection.",
	"Zooms the picture to 100%.": "Agrandit l'image à 100%.",
	"Zooms the picture to 400%.": "Agrandit l'image à 400%.",
	"Zooms the picture.": "Agrandit l'image.",
	"Displays the entire picture.": "Affiche l'image entière.",
	"Shows or hides the thumbnail view of the picture.": "Affiche ou masque la vue de la miniature dans l'image.",
	"Shows or hides the grid.": "Affiche ou masque la grille.",
	"Shows or hides the text toolbar.": "Affiche ou masque la barre d'outil du texte.",
	"Flips or rotates the picture or a selection.": "Retourne ou fait pivoter l'image ou une sélection.",
	"Stretches or skews the picture or a selection.": "Étire ou incline l'image ou la sélection.",
	"Inverts the colors of the picture or a selection.": "Inverse les couleurs de l'image ou de la sélection.",
	"Changes the attributes of the picture.": "Change les attributs de l'image.",
	"Clears the picture or selection.": "Efface l'image ou la sélection.",
	"The font size must be a numeric value.": "La taille de la police doit être une valeur numérique.",
	"Contains commands for working with the selected item(s).": "Contient les commandes pour travailler avec le ou les éléments sélectionnés.",
	"Contains commands for selecting and transferring items.": "Contient les commandes pour la sélection et le transfert des éléments.",
	"Contains commands for customizing this window.": "Contient les commandes pour personnaliser cette fenêtre.",
	"Contains commands for manipulating pictures and setting attributes.": "Contient les commandes pour la manipulation des images et la configuration des attributs.",
	"Contains commands for using custom colors and drawing options.": "Contient les commandes pour utiliser les options des couleurs personnalisées et du dessin.",
	"Contains commands for displaying Help for and information about Paint.": "Contient les commandes pour afficher l'aide et des informations à propos de Paint.",
	"Cannot save file.": "Impossible d'enregistrer le fichier.",
	"Error removing temporary file.": "Erreur de suppression du fichier temporaire.",
	"Get Colors": "Charger la palette de couleurs",
	"Save Colors": "Enregistrer la palette de couleurs",
	"File last saved:": "Dernière sauvegarde :",
	"Not Available": "Non Disponible",
	"Size on disk:": "Taille sur le disque :",
	"%s bytes": "%s octets",
	"Painting": "Peindre",
	"Fonts": "Polices",
	"Tools": "Outils",
	"All Picture Files": "Tous les fichiers images",
	"For Help, click Help Topics on the Help Menu.": "Pour obtenir de l'aide, sélectionnez l'option Rubriques d'aide du menu d'aide.",
	"Select an area on which to get Help.": "Choisissez un domaine sur lequel vous voulez de l'aide.",
	"%1 in %2": "%1 de %2",
	"Creates a new document.": "Crée un nouveau document.",
	"Opens an existing document.": "Ouvre un document existant.",
	"Closes the active document.": "Ferme le document actif.",
	"Saves the active document.": "Enregistre le document actif.",
	"Saves the active document with a new name.": "Enregistre le document actif sous un autre nom.",
	"Changes the page layout.": "Change la spécification de la page.",
	"Specifies the default printer setup.": "Spécifie la configuration de l'imprimante par défaut.",
	"Prints the active document and sets printing options.": "Imprime le document actif et définit les options d'impression.",
	"Displays full pages.": "Affiche les pages entières.",
	"Opens this document.": "Ouvre ce document.",
	"Deletes the selection.": "Supprime la sélection.",
	"Erases everything.": "Efface tout.",
	"Copies the selection and puts it on the Clipboard.": "Copie la sélection et la place dans le Presse-papiers.",
	"Cuts the selection and puts it on the Clipboard.": "Coupe la sélection et la place dans le Presse-papiers.",
	"Finds the specified text.": "Recherche le texte spécifié.",
	"Inserts the contents of the Clipboard.": "Insère le contenu du Presse-papiers.",
	"Repeats the last action.": "Répète la dernière action.",
	"Replaces specific text with different text.": "Remplace un texte par un autre.",
	"Selects everything.": "Sélectionne tout.",
	"Undoes the last action.": "Annule la dernière action.",
	"Redoes the previously undone action.": "Rétablit l'action précédemment annulée.",
	"Displays program information, version number, and copyright.": "Affiche les informations sur le programme, son numéro de version et son copyright.",
	"Quits Paint.": "Quitte Paint.",
	"Opens Paint Help.": "Ouvre l'aide de Paint.",
	"Displays instructions about how to use Help.": "Affiche le manuel d'utilisation de l'aide.",
	"Displays Help for areas you click on.": "Affiche l'aide pour les zones que vous avez sélectionnées.",
	"Displays Help for the current task or command.": "Affiche l'aide pour la tâche ou la commande en cours.",
	"Centers this bitmap as the desktop wallpaper.": "Centre ce bitmap en tant que papier peint du bureau.",
	"Tiles this bitmap as the desktop wallpaper.": "Définit ce bitmap en mode mosaïque en tant que papier peint du bureau.",
	"Sends the selection using mail or fax.": "Envoie la sélection en utilisant le courrier ou le télécopieur.",
	"Prints the selection.": "Imprime la sélection.",
	"Shows or hides the thumbnail.": "Affiche ou masque la miniature.",
	"Shows Paint Help.": "Affiche l'aide de Paint.",
	"Shows or hides the status bar.": "Affiche ou masque la barre d'état.",
	"Shows or hides the tool box.": "Affiche ou masque la boîte à outils.",
	"Shows or hides the color box.": "Affiche ou masque la palette de couleurs.",
	"Only a Far East font can be used for vertical editing.": "Seule une police extrême orientale peut être éditée à la verticale.",
	"Changes the window size.": "Modifie la taille de la fenêtre.",
	"Changes the window position.": "Modifie la position de la fenêtre.",
	"Reduces the window to an icon.": "Réduit la fenêtre à une icône.",
	"Enlarges the window to full size.": "Agrandit la fenêtre en plein écran.",
	"Switches to the next document window.": "Bascule vers la fenêtre document suivante.",
	"Switches to the previous document window.": "Bascule vers la fenêtre document précédente.",
	"Closes the active window and asks if you want to save changes.": "Ferme la fenêtre active et vous demande si vous voulez conserver vos modifications.",
	"Restores the window to normal size.": "Restaure la fenêtre à sa taille d'origine.",
	"Activates the task list.": "Active la liste des tâches.",
	"All Files (*.*)": "Tous (*.*)",
	"Untitled": "Sans titre",
	"an unnamed file": "un fichier sans nom",
	"&Hide": "&Masquer",
	"Hide": "Masquer",
	"No error message is available.": "Aucun message d'erreur disponible.",
	"An unsupported operation was attempted.": "Une opération non prise en charge a été tentée.",
	"A required resource was unavailable.": "Une ressource nécessaire n'était pas disponible.",
	"Out of memory.": "Mémoire insuffisante.",
	"An unknown error has occurred.": "Une erreur inconnue s'est produite.",
	"on %1": "sur %1",
	"&One Page": "&Une page",
	"One Page": "Une page",
	"&Two Page": "&Deux pages",
	"Two Page": "Deux pages",
	"Printer Files (*.prn)|*.prn|All Files (*.*)|*.*||": "Fichiers imprimante (*.prn)|*.prn|Tous(*.*)|*.*||",
	"Print to File": "Impression dans un fichier",
	"to %1": "vers %1",
	"&Update %1": "&Mettre %1 à jour",
	"Update %1": "Mettre %1 à jour",
	"E&xit && Return to %1": "&Quitter et revenir à %1",
	"Exit && Return to %1": "Quitter et revenir à %1",
	"Linked %s": "Lié %s",
	"Unknown Type": "Type inconnu",
	"Invalid filename.": "Nom de fichier non valide.",
	"Failed to open document.": "Impossible d'ouvrir le document.",
	"Failed to save document.": "Impossible d'enregistrer le document.",
	"Save changes to %1?": "Enregistrer les modifications vers %1 ?",
	"Failed to create empty document.": "Impossible de créer un document vide.",
	"The file is too large to open.": "Le fichier est trop grand pour être ouvert.",
	"Could not start print job.": "Impossible de démarrer le travail d'impression.",
	"Failed to launch help.": "Impossible de démarrer l'aide.",
	"Internal application error.": "Erreur interne à l'application.",
	"Command failed.": "La commande a échoué.",
	"Insufficient memory to perform operation.": "Mémoire insuffisante pour accomplir cette opération.",
	"System registry entries have been removed and the INI file (if any) was deleted.": "Les entrées du Registre système ont été supprimées et le fichier INI (s'il y en avait un) a été supprimé également.",
	"Not all of the system registry entries (or INI file) were removed.": "Certaines entrées du Registre système (ou fichiers INI) n'ont pas été supprimées.",
	"This program requires the file %s, which was not found on this system.": "Ce programme nécessite le fichier %s qui ne peut pas être trouvé sur ce système.",
	"This program is linked to the missing export %s in the file %s. This machine may have an incompatible version of %s.": "Ce programme et lié à l'export manquant %s dans le fichier %s. Cette machine peut avoir une version incompatible de %s.",
	"Please enter an integer.": "Veuillez entrer un entier.",
	"Please enter a number.": "Veuillez entrer un nombre.",
	"Please enter an integer between %1 and %2.": "Veuillez entrer un entier compris entre %1 et %2.",
	"Please enter a number between %1 and %2.": "Veuillez entrer un nombre compris entre %1 et %2.",
	"Please enter no more than %1 characters.": "Veuillez ne pas entrer plus de %1 caractères.",
	"Please select a button.": "Veuillez sélectionner un bouton.",
	"Please enter an integer between 0 and 255.": "Veuillez entrer un entier compris entre 0 et 255.",
	"Please enter a positive integer.": "Veuillez entrer un entier positif.",
	"Please enter a date and/or time.": "Veuillez entrer une date ou une heure.",
	"Please enter a currency.": "Veuillez entrer une monnaie.",
	"Unexpected file format.": "Format de fichier inattendu.",
	"Cannot find this file.": "Impossible de trouver ce fichier.",
	"Please verify that the correct path and file name are given.": "Vérifiez que le chemin d'accès et le nom de fichier sont corrects.",
	"Destination disk drive is full.": "Le disque de destination est plein.",
	"Unable to read from %1, it is opened by someone else.": "Impossible de lire depuis %1 ; il est ouvert par quelqu'un d'autre.",
	"Unable to write to %1, it is read-only or opened by someone else.": "Impossible d'écrire à partir de %1 ; il est peut-être protégé en écriture ou ouvert par un autre utilisateur.",
	"An unexpected error occurred while reading %1.": "Une erreur inattendue s'est produite durant la lecture de %1.",
	"An unexpected error occurred while writing %1.": "Une erreur inattendue s'est produite durant l'écriture de %1.",
	"Unable to register document.": "Impossible d'inscrire le document au registre.",
	"The document may already be open.": "Le document est peut-être déjà ouvert.",
	"Update %1 before proceeding?": "Souhaitez-vous mettre à jour %1 avant de continuer ?",
	"Could not update client.": "Impossible de mettre à jour le client.",
	"Failed to register. ActiveX features may not work properly.": "Échec de l'enregistrement. Il se peut que les fonctionnalités ActiveX ne fonctionnent pas correctement.",
	"Failed to update the system registry.": "Impossible de mettre à jour le Registre système.",
	"Please try using REGEDIT.": "Veuillez essayer avec REGEDIT.",
	"Unable to read write-only property.": "Impossible de lire les propriétés en écriture seule.",
	"Unable to write read-only property.": "Impossible d'écrire les propriétés en lecture seule.",
	"Unable to load mail system support.": "Impossible de charger la gestion du courrier électronique.",
	"Mail system DLL is invalid.": "La DLL système du courrier électronique n'est pas valide.",
	"Send Mail failed to send message.": "La commande Envoyer le message n'a pas pu envoyer le message.",
	"No error occurred.": "Aucune erreur ne s'est produite.",
	"An unknown error occurred while accessing %1.": "Une erreur inconnue s'est produite lors de l'accès à %1.",
	"%1 was not found.": "%1 n'a pas été trouvé.",
	"%1 contains an invalid path.": "%1 contient un chemin d'accès non valide.",
	"%1 could not be opened because there are too many open files.": "%1 n'a pas pu être ouvert car trop de fichiers sont ouverts.",
	"Access to %1 was denied.": "L'accès à %1 a été refusé.",
	"An invalid file handle was associated with %1.": "Un descripteur de fichier non valide a été associé à %1.",
	"%1 could not be removed because it is the current directory.": "%1 n'a pas pu être supprimé car il s'agit du répertoire en cours.",
	"%1 could not be created because the directory is full.": "%1 n'a pu être créé car le répertoire est plein.",
	"Seek failed on %1": "Recherche infructueuse sur %1",
	"A hardware I/O error was reported while accessing %1.": "Une erreur d'E/S matérielle a été signalée lors de l'accès à %1.",
	"A sharing violation occurred while accessing %1.": "Une violation de partage s'est produite lors de l'accès à %1.",
	"A locking violation occurred while accessing %1.": "Une violation de verrouillage s'est produite lors de l'accès à %1.",
	"Disk full while accessing %1.": "Le disque était plein lors de l'accès à %1.",
	"An attempt was made to access %1 past its end.": "Il y a eu une tentative d'accès au-delà de %1.",
	"An attempt was made to write to the reading %1.": "Il y a eu une tentative d'écriture sur %1 en lecture.",
	"An attempt was made to read from the writing %1.": "Il y a eu une tentative de lecture sur %1 en écriture.",
	"%1 has a bad format.": "%1 possède un format incorrect.",
	"%1 contained an unexpected object.": "%1 contenait un objet inattendu.",
	"%1 contains an incorrect schema.": "%1 contient un schéma incorrect.",
	"Selects a rectangular part of the picture to move, copy, or edit.": "Sélectionne une partie rectangulaire de l'image à déplacer, à copier ou à modifier.",
	"Select": "Sélection",
	"Selects a free-form part of the picture to move, copy, or edit.": "Sélectionne une partie quelconque du dessin à déplacer, à copier ou à modifier.",
	"Free-Form Select": "Sélection libre",
	"Inserts text into the picture.": "Insère du texte dans le dessin.",
	"Fills an area with the current drawing color.": "Remplit une surface avec la couleur actuelle.",
	"Fill With Color": "Remplissage",
	"Draws a straight line with the selected line width.": "Dessine une ligne droite avec l'épaisseur de trait sélectionnée.",
	"Line": "Ligne",
	"Draws using an airbrush of the selected size.": "Dessine en utilisant un aérographe de la taille sélectionnée.",
	"Airbrush": "Aérographe",
	"Draws a curved line with the selected line width.": "Dessine une courbe avec l'épaisseur de trait sélectionnée.",
	"Curve": "Courbe",
	"Draws a polygon with the selected fill style.": "Dessine un polygone avec l'épaisseur de trait et le style de remplissage sélectionnés.",
	"Polygon": "Polygone",
	"Draws a rounded rectangle with the selected fill style.": "Dessine un rectangle arrondi avec le style de remplissage sélectionné.",
	"Rounded Rectangle": "Rectangle arrondi",
	"Draws a free-form line one pixel wide.": "Dessine une ligne quelconque d'une épaisseur d'un pixel.",
	"Pencil": "Pinceau",
	"Erases a portion of the picture, using the selected eraser shape.": "Efface une partie de l'image en utilisant la forme de la gomme sélectionnée.",
	"Eraser/Color Eraser": "Gomme/Gomme une couleur",
	"Changes the magnification.": "Modifie le grossissement.",
	"Magnifier": "Loupe",
	"Picks up a color from the picture for drawing.": "Prélève la couleur à utiliser dans le dessin lui-même.",
	"Pick Color": "Prélèvement d'une couleur",
	"Draws using a brush with the selected shape and size.": "Dessine en utilisant une brosse de la forme et de la taille sélectionnées.",
	"Brush": "Brosse",
	"Draws a rectangle with the selected fill style.": "Dessine un rectangle avec l'épaisseur de trait et le style de remplissage sélectionnés.",
	"Draws a filled rectangle.": "Dessine un rectangle plein.",
	"Draws an ellipse with the selected fill style.": "Dessine une ellipse avec l'épaisseur de trait et le style de remplissage sélectionnés.",
	"Draws a filled ellipse.": "Dessine une ellipse pleine.",
	"Makes the current selection either opaque or transparent.": "Rend la sélection en cours opaque ou transparente.",
	"Creates a new color.": "Crée une nouvelle couleur.",
	"Uses a previously saved palette of colors.": "Utilise une palette de couleurs enregistrée antérieurement.",
	"Saves the current palette of colors to a file.": "Enregistre la palette de couleurs actuelle dans un fichier.",
	"You must save the file before choosing it as Wallpaper.": "Vous devez enregistrer ce fichier avant de l'utiliser en tant que papier peint.",
	"The selection is now larger than the bitmap.": "La sélection est plus grande que l'image.",
	"Would you like the bitmap enlarged?": "Voulez-vous agrandir l'image ?",
	"The image in the clipboard is larger than the bitmap.": "L'image dans le Presse-papiers est plus grande que la bitmap.",
	"The file is not in the correct format.": "Le fichier n'est pas au format correct.",
	"Not enough room to paste text.": "Espace insuffisant pour coller le texte.",
	"Enlarge the text area and try again.": "Agrandissez la zone de texte puis réessayez.",
	"Places the text.": "Place le texte."
});
