//
// NOTE: This is a generated file! Don't edit it directly.
// Eventually community translation will be set up on some translation platform.
// 
// Generated with: npm run update-localization
//
loaded_localizations("zh", {
	"Attributes": "屬性",
	"MS Shell Dlg": "新細明體",
	"&Width:": "寬度(&W):",
	"Width:": "寬度:",
	"&Height:": "高度(&H):",
	"Height:": "高度:",
	"Units": "單位",
	"&Inches": "英吋(&I)",
	"Inches": "英吋",
	"C&m": "公分(&M)",
	"Cm": "公分",
	"&Pixels": "像素(&P)",
	"Pixels": "像素",
	"Colors": "色彩",
	"&Black and white": "黑白(&B)",
	"Black and white": "黑白",
	"Co&lors": "彩色(&L)",
	"Transparency": "投影片",
	"Use &Transparent background color": "使用透明背景色彩(&T)",
	"Use Transparent background color": "使用透明背景色彩",
	"Select &Color": "選取色彩(&C)",
	"Select Color": "選取色彩",
	"OK": "確定",
	"Cancel": "取消",
	"&Default": "預設值(&D)",
	"Default": "預設值",
	"Custom Zoom": "自訂縮放",
	"Current zoom:": "目前縮放比例:",
	"Zoom to": "縮放成",
	"&100%": "100%(&1)",
	"100%": "100%",
	"&200%": "200%(&2)",
	"200%": "200%",
	"&400%": "400%(&4)",
	"400%": "400%",
	"&600%": "600%(&6)",
	"600%": "600%",
	"&800%": "800%(&8)",
	"800%": "800%",
	"Flip and Rotate": "翻轉及旋轉",
	"Flip or rotate": "翻轉或旋轉",
	"&Flip horizontal": "水平翻轉(&F)",
	"Flip horizontal": "水平翻轉",
	"Flip &vertical": "垂直翻轉(&V)",
	"Flip vertical": "垂直翻轉",
	"&Rotate by angle": "旋轉角度(&R)",
	"Rotate by angle": "旋轉角度",
	"&90°": "90 度(&9)",
	"90°": "90 度",
	"&180°": "180 度(&1)",
	"180°": "180 度",
	"&270°": "270 度(&2)",
	"270°": "270 度",
	"Stretch and Skew": "延伸及扭曲",
	"Stretch": "延伸",
	"&Horizontal:": "水平(&H):",
	"Horizontal:": "水平:",
	"&Vertical:": "垂直(&V):",
	"Vertical:": "垂直:",
	"Skew": "扭曲",
	"H&orizontal:": "水平(&O):",
	"Degrees": "度",
	"V&ertical:": "垂直(&E):",
	"Color Table": "色彩表",
	"New": "新增",
	"&New ": "新增(&N)",
	"New ": "新增",
	"&Help": "說明(&H)",
	"Help": "說明",
	"Printing": "列印",
	"on the": "從",
	"&Print": "列印(&P)",
	"Print": "列印",
	"&Next Page": "下一頁(&N)",
	"Next Page": "下一頁",
	"Pre&v Page": "上一頁(&V)",
	"Prev Page": "上一頁",
	"Zoom &In": "拉近(&I)",
	"Zoom In": "拉近",
	"Zoom &Out": "拉遠(&O)",
	"Zoom Out": "拉遠",
	"&Close": "關閉(&C)",
	"Close": "關閉",
	"Grid Settings": "格線設定",
	"                  ": "                            ",
	"&Pixel Grid": "像素格線(&P)",
	"Pixel Grid": "像素格線",
	"&Tile Grid": "並排格線(&T)",
	"Tile Grid": "並排格線",
	"pixels": "像素",
	"H&eight:": "高度(&E):",
	"Text": "文字",
	"Undo": "復原",
	"Cut": "剪下",
	"Copy": "複製",
	"Paste": "貼上",
	"Clear Selection": "清除選取範圍",
	"Select All": "全選",
	"Text Toolbar": "文字工具列",
	"Selection": "選擇",
	"Cu&t": "剪下(&T)",
	"&Copy": "複製(&C)",
	"&Paste": "貼上(&P)",
	"C&lear Selection": "清除選取範圍(&L)",
	"Select &All": "全選(&A)",
	"C&opy To": "複製到(&O)",
	"Copy To": "複製到",
	"Paste &From": "貼上來源(&F)",
	"Paste From": "貼上來源",
	"Flip/&Rotate": "翻轉/旋轉(&R)",
	"Flip/Rotate": "翻轉/旋轉",
	"&Stretch/Skew": "延伸/扭曲(&S)",
	"Stretch/Skew": "延伸/扭曲",
	"&Invert Colors": "色彩對換(&I)",
	"Invert Colors": "色彩對換",
	"Thumbnail": "縮圖",
	"&File": "檔案(&F)",
	"File": "檔案",
	"&New": "開新檔案(&N)",
	"&Open": "開啟舊檔(&O)",
	"Open": "開啟舊檔",
	"&Save": "存檔(&S)",
	"Save": "存檔",
	"Save &As": "另存新檔(&A)",
	"Save As": "另存新檔",
	"Print Pre&view": "預覽列印(&V)",
	"Print Preview": "預覽列印",
	"Page Se&tup": "版面設定(&T)",
	"Page Setup": "版面設定",
	"S&end": "傳送(&E)",
	"Send": "傳送",
	"Set As &Wallpaper (Tiled)": "設定為底色圖案 (並排)(&W)",
	"Set As Wallpaper (Tiled)": "設定為底色圖案 (並排)",
	"Set As Wa&llpaper (Centered)": "設定為底色圖案 (置於中央)(&L)",
	"Set As Wallpaper (Centered)": "設定為底色圖案 (置於中央)",
	"Recent File": "最新的檔案",
	"E&xit": "結束(&X)",
	"Exit": "結束",
	"&Edit": "編輯(&E)",
	"Edit": "編輯",
	"&Undo": "復原(&U)",
	"&Repeat": "重複(&R)",
	"Repeat": "重複",
	"&View": "檢視(&V)",
	"View": "檢視",
	"&Tool Box": "工具箱(&T)",
	"Tool Box": "工具箱",
	"&Color Box": "色塊(&C)",
	"Color Box": "色塊",
	"&Status Bar": "狀態列(&S)",
	"Status Bar": "狀態列",
	"T&ext Toolbar": "文字工具列(&E)",
	"&Zoom": "縮放(&Z)",
	"Zoom": "縮放",
	"&Normal Size": "標準大小(&N)",
	"Normal Size": "標準大小",
	"&Large Size": "放大(&L)",
	"Large Size": "放大",
	"C&ustom": "自訂(&U)",
	"Custom": "自訂",
	"Show &Grid": "顯示格線(&G)",
	"Show Grid": "顯示格線",
	"Show T&humbnail": "顯示縮圖(&H)",
	"Show Thumbnail": "顯示縮圖",
	"&View Bitmap": "檢視點陣圖(&V)",
	"View Bitmap": "檢視點陣圖",
	"&Image": "影像(&I)",
	"Image": "影像",
	"&Flip/Rotate": "翻轉/旋轉(&F)",
	"&Attributes": "屬性(&A)",
	"&Clear Image": "清除影像(&C)",
	"Clear Image": "清除影像",
	"&Draw Opaque": "不透明處理(&D)",
	"Draw Opaque": "不透明處理",
	"&Colors": "色彩(&C)",
	"&Edit Colors": "編輯色彩(&E)",
	"Edit Colors": "編輯色彩",
	"&Help Topics": "說明主題(&H)",
	"Help Topics": "說明主題",
	"&About Paint": "關於小畫家(&A)",
	"About Paint": "關於小畫家",
	"&Update": "更新(&U)",
	"Update": "更新",
	"Save Copy &As": "另存備份(&A)",
	"Save Copy As": "另存備份",
	"Paint": "小畫家",
	"untitled": "未命名",
	"Bitmap Image": "點陣圖影像",
	"Bitmap Files (*.bmp)": "點陣圖檔案(*.BMP,*.DIB)",
	"PCX Files": "PCX 檔",
	"Icon Files": "圖示檔(*.ICO)",
	"Monochrome Bitmap (*.bmp;*.dib)": "單色點陣圖 (*.bmp;*.dib)",
	"16 Color Bitmap (*.bmp;*.dib)": "16 色點陣圖 (*.bmp;*.dib)",
	"256 Color Bitmap (*.bmp;*.dib)": "256 色點陣圖 (*.bmp;*.dib)",
	"Paint cannot open this file.": "「小畫家」無法開啟這個檔案。",
	"Paint cannot read this file.": "「小畫家」無法讀取這個檔案。",
	"This file is read-only.": "這是一個唯讀檔。",
	"To save your changes, use a different filename.": "要儲存所做的變更時，請用其它的檔名。",
	"This file is already open.": "這個檔案已經開啟了。",
	"This is not a valid .PCS file.": "不是有效的 .PCS 檔。",
	"This file is open for editing and cannot be overwritten.": "這個檔案是開啟來供編輯之用，無法改寫。",
	"Use a different filename to save your changes.": "請用的不同的檔名來儲存所做的變更。",
	"This is not a valid bitmap file, or its format is not currently supported.": "這不是正確的點陣圖檔案，或是已不再支援這種格式。",
	"This is not a valid icon.": "不是有效的圖示。",
	"This is not a valid cursor.": "不是有效的游標。",
	"Save was interrupted, so your file has not been saved.": "存檔時被中斷了，所以您的檔案並未儲存。",
	"You cannot save to a read-only file.": "您無法儲存唯讀檔。",
	"Use a different file name.": "請用其它的檔名。",
	"This file is already in use.": "這個檔案已經在使用中。",
	"Close the program, and then try again.": "請關閉程式，然後重試。",
	"Paint cannot save this file.": "「小畫家」無法儲存這個檔案。",
	"Paint cannot save to the same filename with a different file type.": "「小畫家」無法用相同的檔名儲存不同的檔案類型。",
	"The grid spacing must be an integer between %d and %d.": "格線的間距必須是 %d 到 %d 之間的整數。",
	"There is not enough memory or resources to complete operation.": "記憶體或資源不足，無法完成作業。",
	"Close some programs, and then try again.": "請關閉某些程式，然後重試。",
	"Low on memory or resources.": "記憶體或資源不足。",
	"Group error.": "群組發生錯誤。",
	"Paint was unable to print your document. Please make sure you have sufficient disk space and that your printer is working correctly.": "小畫家無法列印您的文件。請確定您的磁碟空間足夠，而且印表機正常運作。",
	"Saving into this format may cause some loss of color information.": "儲存成這種格式可能會造成色彩資訊遺失。",
	"Do you want to continue?": "您還要繼續嗎?",
	"Converting to black and white cannot be undone.  This action affects the current file and may cause some loss of color information.": "無法轉換成黑白。這個動作會影響目前的檔案，而且會造成某些色彩資訊的失落。",
	"Bitmaps must be greater than one pixel on a side.": "點陣圖必須一邊大於一個像素。",
	"Generic error.": "發生同屬錯誤。",
	"File not found.": "檔案找不到。",
	"Bad path.": "路徑不正確。",
	"Too many open files.": "開啟太多檔案。",
	"Access denied.": "拒絕存取。",
	"Invalid file.": "檔案無效。",
	"Remove current folder.": "移除現有的資料夾。",
	"Folder full.": "資案夾已滿。",
	"Bad seek.": "錯誤的搜尋方式。",
	"Hard IO error.": "Hard IO 錯誤。",
	"Sharing violation.": "分享違規。",
	"Lock violation.": "鎖定違規。",
	"Disk full.": "磁碟已滿。",
	"End of file.": "檔案結尾。",
	"Error getting the Clipboard Data!": "取得剪貼簿資料發生錯誤！",
	"No Printer Found @ page setup": "找不到印表機 @ 版面設定",
	"24-bit Bitmap (*.bmp;*.dib)": "24 位元點陣圖 (*.bmp;*.dib)",
	"All Files": "所有檔案",
	"Palette|*.pal|": "色板|*.pal|",
	"OLE 2.0 was unable to start.": "無法啟動 OLE 2.0。",
	"Make sure that you are using the correct version of the OLE libraries.": "請確定是否使用正確的 OLE 程式庫版本。",
	"Resets the text be without any attributes.": "重設成沒有任何屬性的文字。",
	"Sets or clears the text bold attribute.": "設定或清除文字的粗體屬性。",
	"Sets or clears the text italic attribute.": "設定或清除文字的斜體屬性。",
	"Selects the font used by the text.": "選擇文字使用的字型。",
	"Selects the point size of the text.": "選擇文字使用的點數大小。",
	"Sets or clears the text underline attribute.": "設定或清除文字的底線屬性。",
	"Shows or hides the tooltips.": "顯示或隱藏工具提示。",
	"Show Paint Help.": "顯示「小畫家」「說明」。",
	"            ": "             ",
	"Sends a picture by using mail or fax.": "用電子郵件或傳真機傳送圖片。",
	"Copies the selection to a file.": "將選取範圍複製到檔案。",
	"Pastes a file into the selection.": "將檔案貼到選取範圍。",
	"Zooms the picture to 100%.": "將圖片放大 100%。",
	"Zooms the picture to 400%.": "將圖片放大 400%。",
	"Zooms the picture.": "縮放圖片。",
	"Displays the entire picture.": "顯示整個圖片。",
	"Shows or hides the thumbnail view of the picture.": "顯示或隱藏圖片的縮圖。",
	"Shows or hides the grid.": "顯示或隱藏格線。",
	"Shows or hides the text toolbar.": "顯示或隱藏文字工具列。",
	"Flips or rotates the picture or a selection.": "翻轉或旋轉圖片或選取範圍。",
	"Stretches or skews the picture or a selection.": "拉長或扭曲圖片或選取範圍。",
	"Inverts the colors of the picture or a selection.": "將圖片或選取範圍的顏色對調。",
	"Changes the attributes of the picture.": "變更圖片的屬性。",
	"Clears the picture or selection.": "清除圖片或選取範圍。",
	"The font size must be a numeric value.": "字型大小必須是一個數值。",
	"Contains commands for working with the selected item(s).": "內含使用選擇項目的指令。",
	"Contains commands for selecting and transferring items.": "內含選擇及轉換項目的指令。",
	"Contains commands for customizing this window.": "內含自訂這個視窗的指令。",
	"Contains commands for manipulating pictures and setting attributes.": "內含處理圖片及設定屬性的指令。",
	"Contains commands for using custom colors and drawing options.": "內含使用自訂顏色及繪圖選項的指令。",
	"Contains commands for displaying Help for and information about Paint.": "內含顯示「說明」及「小畫家」相關資訊的指令。",
	"Cannot save file.": "無法儲存檔案。",
	"Error removing temporary file.": "移除暫時檔的時候發生錯誤。",
	"Get Colors": "選取色彩",
	"Save Colors": "儲存色彩",
	"File last saved:": "上次儲存的檔案:",
	"Not Available": "無法使用",
	"Size on disk:": "磁碟大小:",
	"%s bytes": "%s 位元組",
	"Painting": "繪圖中",
	"Bitmap": "點陣圖",
	"Fonts": "字型",
	"Tools": "工具",
	" ": "    ",
	"x": "X",
	"All Picture Files": "所有圖片檔案",
	"For Help, click Help Topics on the Help Menu.": "如需說明，請按一下「說明」功能表中的「說明主題」。",
	"Select an area on which to get Help.": "選擇要取得「說明」的區域。",
	"%1 in %2": "%2 中的%1",
	"Creates a new document.": "建立新的文件。",
	"Opens an existing document.": "開啟現有的文件。",
	"Closes the active document.": "關閉目前的文件。",
	"Saves the active document.": "關閉目前的文件。",
	"Saves the active document with a new name.": "以新的名稱儲存目前的文件。",
	"Changes the page layout.": "變更版面配置。",
	"Specifies the default printer setup.": "指定預設的印表機。",
	"Prints the active document and sets printing options.": "列印目前的文件並設定列印選項。",
	"Displays full pages.": "顯示全頁。",
	"Opens this document.": "開啟這個文件。",
	"Deletes the selection.": "刪除選取範圍。",
	"Erases everything.": "全部清除。",
	"Copies the selection and puts it on the Clipboard.": "複製選取範圍，並將它放到剪貼簿中。",
	"Cuts the selection and puts it on the Clipboard.": "剪下選取範圍，並將它放到剪貼簿中。",
	"Finds the specified text.": "尋找指定的文字。",
	"Inserts the contents of the Clipboard.": "插入剪貼簿的內容。",
	"Repeats the last action.": "重複前次的動作。",
	"Replaces specific text with different text.": "以不同的文字置換指定的文字。",
	"Selects everything.": "選擇全部。",
	"Undoes the last action.": "取消前次的動作。",
	"Redoes the previously undone action.": "重做前次取消的動作。",
	"Displays program information, version number, and copyright.": "顯示程式資訊、版本號碼及著作權。",
	"Quits Paint.": "結束「小畫家」。",
	"Opens Paint Help.": "開啟「小畫家」的「說明」。",
	"Displays instructions about how to use Help.": "顯示使用「說明」的方法。",
	"Displays Help for areas you click on.": "顯示您按一下之區域的「說明」。",
	"Displays Help for the current task or command.": "顯示目前工作或指令的「說明」。",
	"Centers this bitmap as the desktop wallpaper.": "將這個圖陣圖當做底色圖案置於桌面中央。",
	"Tiles this bitmap as the desktop wallpaper.": "將這個點陣圖當成底色圖案並排在桌面上。",
	"Sends the selection using mail or fax.": "用電子郵件或傳真機傳送所選的部份。",
	"Prints the selection.": "列印選取範圍。",
	"Shows or hides the thumbnail.": "顯示或隱藏縮圖。",
	"Shows Paint Help.": "顯示「小畫家」「說明」。",
	"Shows or hides the status bar.": "顯示或隱藏狀態列。",
	"Shows or hides the tool box.": "顯示或隱藏工具箱。",
	"Shows or hides the color box.": "顯示或隱藏色塊。",
	"Only a Far East font can be used for vertical editing.": "在垂直式編輯中只能使用一種中文字型。",
	"Changes the window size.": "變更視窗大小。",
	"Changes the window position.": "變更視窗位置。",
	"Reduces the window to an icon.": "將視窗縮成一個圖示。",
	"Enlarges the window to full size.": "將視窗放到最大。",
	"Switches to the next document window.": "切換到下一個文件視窗。",
	"Switches to the previous document window.": "切換到前一個文件視窗。",
	"Closes the active window and asks if you want to save changes.": "關閉目前的視窗並詢問您要不要儲存所做的變更。",
	"Restores the window to normal size.": "將視窗復原成標準的大小。",
	"Activates the task list.": "啟動工作清單。",
	"All Files (*.*)": "所有檔案 (*.*)",
	"Untitled": "未命名",
	"an unnamed file": "未命名的檔案",
	"&Hide": "隱藏(&H)",
	"Hide": "隱藏",
	"No error message is available.": "沒有錯誤訊息。",
	"An unsupported operation was attempted.": "嘗試了一項未受支援的操作。",
	"A required resource was unavailable.": "所需的資源無法使用。",
	"Out of memory.": "記憶體不足。",
	"An unknown error has occurred.": "一個無法辨識的錯誤已發生。",
	"on %1": "於 %1",
	"&One Page": "一頁(&O)",
	"One Page": "一頁",
	"&Two Page": "兩頁(&T)",
	"Two Page": "兩頁",
	"Page %u": "第 %u 頁",
	"Pages %u-%u": "%u-%u 頁",
	"Printer Files (*.prn)|*.prn|All Files (*.*)|*.*||": "印表機檔案 (*.prn)|*.prn|所有的檔案 (*.*)|*.*||",
	"Print to File": "列印到檔案",
	"to %1": "到 %1",
	"&Update %1": "升級 %1(&U)",
	"Update %1": "升級 %1",
	"E&xit && Return to %1": "結束後回到 %1 (&X)",
	"Exit && Return to %1": "結束後回到 %1",
	"Linked %s": "已連結的 %s",
	"Unknown Type": "未知的類型",
	"Invalid filename.": "檔名無效。",
	"Failed to open document.": "開啟文件失敗。",
	"Failed to save document.": "儲存文件失敗。",
	"Save changes to %1?": "儲存變更到 %1？",
	"Failed to create empty document.": "建立空文件失敗。",
	"The file is too large to open.": "檔案太大無法開啟。",
	"Could not start print job.": "無法開始列印工作。",
	"Failed to launch help.": "啟動說明失敗。",
	"Internal application error.": "內部應用程式錯誤。",
	"Command failed.": "指令失敗。",
	"Insufficient memory to perform operation.": "記憶體不足以執行作業。",
	"System registry entries have been removed and the INI file (if any) was deleted.": "已移除系統登錄項目，且已刪除 INI 檔 (若有的話)。",
	"Not all of the system registry entries (or INI file) were removed.": "未移除所有的系統登錄項目 (或 INI 檔)。",
	"This program requires the file %s, which was not found on this system.": "這個程式需要檔案 %s，但在這個系統上找不到它。",
	"This program is linked to the missing export %s in the file %s. This machine may have an incompatible version of %s.": "這個程式連結到遺失的匯出項目 %s (在檔案 %s)。這個機器的 %s 版本可能不相容。",
	"Please enter an integer.": "請輸入整數。",
	"Please enter a number.": "請輸入數字。",
	"Please enter an integer between %1 and %2.": "請輸入介於 %1 和 %2 之間的整數。",
	"Please enter a number between %1 and %2.": "請輸入介於 %1 和 %2 之間的數字。",
	"Please enter no more than %1 characters.": "請輸入不超過 %1 個字。",
	"Please select a button.": "請選擇一個按鈕。",
	"Please enter an integer between 0 and 255.": "請輸入介於 0 和 255 之間的整數。",
	"Please enter a positive integer.": "請輸入一正整數。",
	"Please enter a date and/or time.": "請輸入一個日期及(或）時間。",
	"Please enter a currency.": "請輸入一種貨幣。",
	"Unexpected file format.": "檔案格式不正確。",
	"Cannot find this file.": "C找不到此檔案。",
	"Please verify that the correct path and file name are given.": "請確認已給正確的路徑和檔案名稱。",
	"Destination disk drive is full.": "目的地磁碟機已滿。",
	"Unable to read from %1, it is opened by someone else.": "無法讀取 %1，已被其他人開啟。",
	"Unable to write to %1, it is read-only or opened by someone else.": "無法寫入 %1，可能是唯讀或被其他人開啟。",
	"An unexpected error occurred while reading %1.": "讀取 %1 時發生無法預期的錯誤。",
	"An unexpected error occurred while writing %1.": "寫入 %1 時發生無法預期的錯誤。",
	"Unable to register document.": "無法登錄文件。",
	"The document may already be open.": "此文件可能已被開啟。",
	"Update %1 before proceeding?": "繼續下個動作前先更新 %1？",
	"Could not update client.": "無法更新用戶端。",
	"Failed to register. ActiveX features may not work properly.": "無法登錄。ActiveX 功能可能無法正確運作。",
	"Failed to update the system registry.": "更新系統登錄失敗。",
	"Please try using REGEDIT.": "請試著使用 REGEDIT。",
	"Unable to read write-only property.": "無法讀取唯寫內容。",
	"Unable to write read-only property.": "無法寫入唯讀內容。",
	"Unable to load mail system support.": "無法載入郵件系統支援",
	"Mail system DLL is invalid.": "郵件系統 DLL 不正確。",
	"Send Mail failed to send message.": "無法傳送訊息。",
	"No error occurred.": "沒有任何錯誤發生。",
	"An unknown error occurred while accessing %1.": "在存取 %1 時發生了一個無法辨識的錯誤。",
	"%1 was not found.": "找不到 %1。",
	"%1 contains an invalid path.": "%1 包含一個不正確的路徑。",
	"%1 could not be opened because there are too many open files.": "%1無法開啟，因為已經開啟太多檔案。",
	"Access to %1 was denied.": "存取 %1 被拒。",
	"An invalid file handle was associated with %1.": "一個不正確的檔案控制碼與 %1 產生關聯。",
	"%1 could not be removed because it is the current directory.": "%1無法移除，因為它是目前的目錄。",
	"%1 could not be created because the directory is full.": "%1無法建立，因為此目錄已滿。",
	"Seek failed on %1": "搜尋 %1 失敗。",
	"A hardware I/O error was reported while accessing %1.": "在存取 %1 時報告硬體 I/O 錯誤。",
	"A sharing violation occurred while accessing %1.": "在存取 %1 時發生共用違規。",
	"A locking violation occurred while accessing %1.": "在存取 %1 時發生鎖定違規。",
	"Disk full while accessing %1.": "在存取 %1 時磁碟已滿。",
	"An attempt was made to access %1 past its end.": "嘗試一次超過 %1 結尾的存取。",
	"An attempt was made to write to the reading %1.": "嘗試寫入正在讀取的 %1。",
	"An attempt was made to read from the writing %1.": "嘗試從正在寫入的 %1 讀取。",
	"%1 has a bad format.": "%1 有一個錯誤格式。",
	"%1 contained an unexpected object.": "%1 包含一個意外物件。",
	"%1 contains an incorrect schema.": "%1 包含一個不正確的架構。",
	"Selects a rectangular part of the picture to move, copy, or edit.": "選圖片的矩形部份，加以移動、複製或編輯。",
	"Select": "選擇",
	"Selects a free-form part of the picture to move, copy, or edit.": "選圖片的任何部份，加以移動、複製或編輯。",
	"Free-Form Select": "選擇任意範圍",
	"Inserts text into the picture.": "將文字貼到圖片中。",
	"Fills an area with the current drawing color.": "用目前的繪圖色彩填入某個區域",
	"Fill With Color": "填入色彩",
	"Draws a straight line with the selected line width.": "用所選的線條寬度繪製直線。",
	"Line": "直線",
	"Draws using an airbrush of the selected size.": "用所選的噴槍大小繪圖",
	"Airbrush": "噴槍",
	"Draws a curved line with the selected line width.": "用所選的線條寬度繪製曲線。",
	"Curve": "曲線",
	"Draws a polygon with the selected fill style.": "用所選的填入樣式繪製多邊形。",
	"Polygon": "多邊形",
	"Draws a rounded rectangle with the selected fill style.": "用所選的填入樣式繪製圓角矩形。",
	"Rounded Rectangle": "圓角矩形",
	"Draws a free-form line one pixel wide.": "以一個像素寬度大小繪出任意形狀的線條。",
	"Pencil": "鉛筆",
	"Erases a portion of the picture, using the selected eraser shape.": "使用所選的橡皮擦形狀，清除部份圖片。",
	"Eraser/Color Eraser": "橡皮擦/彩色橡皮擦",
	"Changes the magnification.": "變更倍率。",
	"Magnifier": "放大鏡",
	"Picks up a color from the picture for drawing.": "挑選圖片中的一種顏色用來繪圖。",
	"Pick Color": "挑選顏色",
	"Draws using a brush with the selected shape and size.": "用所選的刷子形狀及大小來繪圖。",
	"Brush": "粉刷",
	"Draws a rectangle with the selected fill style.": "用所選的填入樣式繪製矩形。",
	"Rectangle": "矩形",
	"Draws a filled rectangle.": "繪製填入樣式的矩形。",
	"Draws an ellipse with the selected fill style.": "用所選的填入樣式繪製橢圓形。",
	"Ellipse": "橢圓形",
	"Draws a filled ellipse.": "繪製內填樣式的橢圓形。",
	"Makes the current selection either opaque or transparent.": "讓目前的選取範圍變成透明或不透明。",
	"Creates a new color.": "建立新的顏色。",
	"Uses a previously saved palette of colors.": "使用以前儲存的色板。",
	"Saves the current palette of colors to a file.": "將目前的色板存到檔案中。",
	"You must save the file before choosing it as Wallpaper.": "在將它選為底色圖案之前，必須先儲存檔案。",
	"The selection is now larger than the bitmap.": "選取範圍大於點陣圖。",
	"Would you like the bitmap enlarged?": "您要放大點陣圖嗎？",
	"The image in the clipboard is larger than the bitmap.": "剪貼簿的影像大於點陣圖。",
	"The file is not in the correct format.": "檔案的格式不正確。",
	"Not enough room to paste text.": "空間不夠，無法貼上文字。",
	"Enlarge the text area and try again.": "請放大文字區域後重試。",
	"Places the text.": "置放文字。"
});
