//
// NOTE: This is a generated file! Don't edit it directly.
// Eventually community translation will be set up on some translation platform.
// 
// Generated with: npm run update-localization
//
loaded_localizations("fi", {
	"Attributes": "Määritteet",
	"&Width:": "&Leveys:",
	"Width:": "Leveys:",
	"&Height:": "&Korkeus:",
	"Height:": "Korkeus:",
	"Units": "Yksiköt",
	"&Inches": "&tuuma",
	"Inches": "tuuma",
	"C&m": "&cm",
	"Cm": "cm",
	"&Pixels": "ku&vapiste",
	"Pixels": "kuvapiste",
	"Colors": "Värit",
	"&Black and white": "&Mustavalkoinen",
	"Black and white": "Mustavalkoinen",
	"Co&lors": "V&ärit",
	"Transparency": "Kalvo",
	"Use &Transparent background color": "Käytä lä&pinäkyvää taustaväriä",
	"Use Transparent background color": "Käytä läpinäkyvää taustaväriä",
	"Select &Color": "V&alitse väri",
	"Select Color": "Valitse väri",
	"Cancel": "Peruuta",
	"&Default": "&Oletus",
	"Default": "Oletus",
	"Custom Zoom": "Oma zoomaus",
	"Current zoom:": "Nykyinen zoomaus:",
	"Zoom to": "Zoomaa",
	"&100%": "&100 %",
	"100%": "100 %",
	"&200%": "&200 %",
	"200%": "200 %",
	"&400%": "&400 %",
	"400%": "400 %",
	"&600%": "&600 %",
	"600%": "600 %",
	"&800%": "&800 %",
	"800%": "800 %",
	"Flip and Rotate": "Käännä ja kierrä",
	"Flip or rotate": "Kääntäminen tai kiertäminen",
	"&Flip horizontal": "Käännä &vaakasuunnassa",
	"Flip horizontal": "Käännä vaakasuunnassa",
	"Flip &vertical": "Käännä py&stysuunnassa",
	"Flip vertical": "Käännä pystysuunnassa",
	"&Rotate by angle": "&Kierrä kulmassa",
	"Rotate by angle": "Kierrä kulmassa",
	"Stretch and Skew": "Venytä ja viistota",
	"Stretch": "Venytä",
	"&Horizontal:": "Vaa&katasossa:",
	"Horizontal:": "Vaakatasossa:",
	"&Vertical:": "Pys&tytasossa:",
	"Vertical:": "Pystytasossa:",
	"Skew": "Viistota",
	"H&orizontal:": "V&aakatasossa:",
	"Degrees": "astetta",
	"V&ertical:": "Py&stytasossa:",
	"Color Table": "Väritaulukko",
	"New": "Uusi",
	"&New ": "&Uusi ",
	"New ": "Uusi ",
	"&Help": "&Ohje",
	"Help": "Ohje",
	"Printing": "Tulostetaan",
	"on the": "porttiin",
	"&Print": "Tul&osta",
	"Print": "Tulosta",
	"&Next Page": "Se&uraava sivu",
	"Next Page": "Seuraava sivu",
	"Pre&v Page": "&Edellinen sivu",
	"Prev Page": "Edellinen sivu",
	"Zoom &In": "&Lähennä",
	"Zoom In": "Lähennä",
	"Zoom &Out": "Loito&nna",
	"Zoom Out": "Loitonna",
	"&Close": "&Sulje",
	"Close": "Sulje",
	"Grid Settings": "Ruudukon asetukset",
	"&Pixel Grid": "&Kuvapisteruudukko",
	"Pixel Grid": "Kuvapisteruudukko",
	"&Tile Grid": "&Vierekkäinen ruudukko",
	"Tile Grid": "Vierekkäinen ruudukko",
	"pixels": "kuvapistettä",
	"H&eight:": "K&orkeus:",
	"Text": "Teksti",
	"Undo": "Kumoa",
	"Cut": "Leikkaa",
	"Copy": "Kopioi",
	"Paste": "Liitä",
	"Clear Selection": "Poista valinta",
	"Select All": "Valitse kaikki",
	"Text Toolbar": "Tekstityökalurivi",
	"Selection": "Valinta",
	"Cu&t": "&Leikkaa",
	"&Copy": "K&opioi",
	"&Paste": "L&iitä",
	"C&lear Selection": "&Poista valinta",
	"Select &All": "V&alitse kaikki",
	"C&opy To": "Kopioi &mihin",
	"Copy To": "Kopioi mihin",
	"Paste &From": "Liitä mi&stä",
	"Paste From": "Liitä mistä",
	"Flip/&Rotate": "&Käännä/kierrä",
	"Flip/Rotate": "Käännä/kierrä",
	"&Stretch/Skew": "&Venytä/viistota",
	"Stretch/Skew": "Venytä/viistota",
	"&Invert Colors": "Kää&nteiset värit",
	"Invert Colors": "Käänteiset värit",
	"Thumbnail": "Pikkukuva",
	"&File": "&Tiedosto",
	"File": "Tiedosto",
	"&New": "&Uusi",
	"&Open": "&Avaa",
	"Open": "Avaa",
	"&Save": "&Tallenna",
	"Save": "Tallenna",
	"Save &As": "Talle&nna nimellä",
	"Save As": "Tallenna nimellä",
	"Print Pre&view": "&Esikatselu",
	"Print Preview": "Esikatselu",
	"Page Se&tup": "&Sivun asetukset",
	"Page Setup": "Sivun asetukset",
	"S&end": "L&ähetä",
	"Send": "Lähetä",
	"Set As &Wallpaper (Tiled)": "Aseta taustakuvaksi (&vierekkäin)",
	"Set As Wallpaper (Tiled)": "Aseta taustakuvaksi (vierekkäin)",
	"Set As Wa&llpaper (Centered)": "Aseta taustakuvaksi (kesk&itetty)",
	"Set As Wallpaper (Centered)": "Aseta taustakuvaksi (keskitetty)",
	"Recent File": "Viimeisin tiedosto",
	"E&xit": "&Lopeta",
	"Exit": "Lopeta",
	"&Edit": "&Muokkaa",
	"Edit": "Muokkaa",
	"&Undo": "&Kumoa",
	"&Repeat": "&Tee uudelleen",
	"Repeat": "Tee uudelleen",
	"&View": "&Näytä",
	"View": "Näytä",
	"&Tool Box": "T&yökaluryhmä",
	"Tool Box": "Työkaluryhmä",
	"&Color Box": "&Värivalikoima",
	"Color Box": "Värivalikoima",
	"&Status Bar": "&Tilarivi",
	"Status Bar": "Tilarivi",
	"T&ext Toolbar": "T&ekstityökalurivi",
	"&Zoom": "&Zoomaa",
	"Zoom": "Zoomaa",
	"&Normal Size": "&Normaali koko",
	"Normal Size": "Normaali koko",
	"&Large Size": "&Suuri koko",
	"Large Size": "Suuri koko",
	"C&ustom": "&Mukauta",
	"Custom": "Mukauta",
	"Show &Grid": "N&äytä ruudukko",
	"Show Grid": "Näytä ruudukko",
	"Show T&humbnail": "Näytä &pikkukuva",
	"Show Thumbnail": "Näytä pikkukuva",
	"&View Bitmap": "&Näytä bittikartta",
	"View Bitmap": "Näytä bittikartta",
	"&Image": "&Kuva",
	"Image": "Kuva",
	"&Flip/Rotate": "&Käännä/kierrä",
	"&Attributes": "&Määritteet",
	"&Clear Image": "Poi&sta kuva",
	"Clear Image": "Poista kuva",
	"Ctrl+Shft+N": "Ctrl+Vaihto+N",
	"&Draw Opaque": "&Piirrä peittäen",
	"Draw Opaque": "Piirrä peittäen",
	"&Colors": "&Värit",
	"&Edit Colors": "&Muokkaa värit",
	"Edit Colors": "Muokkaa värit",
	"&Help Topics": "&Ohjeen aiheet",
	"Help Topics": "Ohjeen aiheet",
	"&About Paint": "&Tietoja Paintista",
	"About Paint": "Tietoja Paintista",
	"&Update": "&Päivitä",
	"Update": "Päivitä",
	"Save Copy &As": "T&allenna kopio nimellä",
	"Save Copy As": "Tallenna kopio nimellä",
	"untitled": "nimetön",
	"Bitmap Image": "Bittikartta",
	"Bitmap Files (*.bmp)": "Bittikarttatiedostot (*.bmp)",
	"PCX Files": "PCX-tiedostot",
	"Icon Files": "Kuvaketiedostot",
	"Monochrome Bitmap (*.bmp;*.dib)": "Yksivärinen bittikartta (*.bmp;*.dib)",
	"16 Color Bitmap (*.bmp;*.dib)": "16-värinen bittikartta (*.bmp;*.dib)",
	"256 Color Bitmap (*.bmp;*.dib)": "256-värinen bittikartta (*.bmp;*.dib)",
	"Paint cannot open this file.": "Paint ei voi avata tätä tiedostoa.",
	"Paint cannot read this file.": "Paint ei voi lukea tätä tiedostoa.",
	"This file is read-only.": "Tämä tiedosto on vain luku -tyyppiä.",
	"To save your changes, use a different filename.": "Tallenna muutokset toisella tiedostonimellä.",
	"This file is already open.": "Tiedosto on jo avoinna.",
	"This is not a valid .PCS file.": "Tämä ei ole kelvollinen .PCS-tiedosto.",
	"This file is open for editing and cannot be overwritten.": "Tiedosto on avoinna muokkausta varten eikä sitä voi korvata.",
	"Use a different filename to save your changes.": "Tallenna muutokset toisella tiedostonimellä.",
	"This is not a valid bitmap file, or its format is not currently supported.": "Tämä ei ole kelvollinen bittikarttatiedosto tai sen muotoa ei tueta.",
	"This is not a valid icon.": "Tämä ei ole kelvollinen kuvake.",
	"This is not a valid cursor.": "Tämä ei ole kelvollinen kohdistin.",
	"Save was interrupted, so your file has not been saved.": "Tallentaminen keskeytetty. Tiedostoa ei ole tallennettu.",
	"You cannot save to a read-only file.": "Vain luku -tiedostoon ei voi tallentaa.",
	"Use a different file name.": "Käytä toista tiedostonimeä.",
	"This file is already in use.": "Tiedosto on jo käytössä.",
	"Close the program, and then try again.": "Sulje ohjelma ja yritä uudelleen.",
	"Paint cannot save this file.": "Paint ei voi tallentaa tätä tiedostoa.",
	"Paint cannot save to the same filename with a different file type.": "Paint ei voi tallentaa samalla tiedostonimellä eri tiedostotyyppiä.",
	"The grid spacing must be an integer between %d and %d.": "Ruudukon välin on oltava kokonaisluku %d - %d.",
	"There is not enough memory or resources to complete operation.": "Liian vähän muistia tai resursseja tämän toiminnon suorittamiseksi.",
	"Close some programs, and then try again.": "Sulje ohjelmia ja yritä uudelleen.",
	"Low on memory or resources.": "Vähän muistia ja resursseja.",
	"Group error.": "Ryhmävirhe.",
	"Paint was unable to print your document. Please make sure you have sufficient disk space and that your printer is working correctly.": "Paint ei pystynyt tulostamaan asiakirjaasi. Varmista että Sinulla on riittävästi kiintolevytilaa ja että kirjoittimesi toimii oikein.",
	"Saving into this format may cause some loss of color information.": "Tähän muotoon tallentaminen voi aiheuttaa joidenkin väritietojen menettämisen.",
	"Do you want to continue?": " Jatketaanko?",
	"Converting to black and white cannot be undone.  This action affects the current file and may cause some loss of color information.": "Muuntamista mustavalkoiseksi ei voi kumota. Tämä toiminto vaikuttaa nykyiseen tiedostoon ja voi aiheuttaa väritietojen häviämistä.",
	"Bitmaps must be greater than one pixel on a side.": "Bittikartassa on oltava enemmän kuin yksi kuvapiste.",
	"Generic error.": "Yleisvirhe.",
	"File not found.": "Tiedostoa ei löydy.",
	"Bad path.": "Polku ei ole kelvollinen.",
	"Too many open files.": "Liian monta avointa tiedostoa.",
	"Access denied.": "Käyttö estetty.",
	"Invalid file.": "Tiedosto ei ole kelvollinen.",
	"Remove current folder.": "Poista nykyinen kansio.",
	"Folder full.": "Kansio on täynnä.",
	"Bad seek.": "Etsintä ei ole kelvollinen.",
	"Hard IO error.": "Laitteiston IO-virhe.",
	"Sharing violation.": "Yhteiskäyttövirhe.",
	"Lock violation.": "Lukitusvirhe.",
	"Disk full.": "Levy on täynnä.",
	"End of file.": "Tiedoston loppu.",
	"Error getting the Clipboard Data!": "Virhe Leikepöydän tietojen saamisessa.",
	"No Printer Found @ page setup": "Kirjoitinta ei löydy @ sivun asetuksilla",
	"24-bit Bitmap (*.bmp;*.dib)": "24-bittinen bittikartta (*.bmp;*.dib)",
	"All Files": "Kaikki tiedostot",
	"Palette|*.pal|": "Valikoima|*.pal|",
	"untitled.pal": "nimetön.pal",
	"OLE 2.0 was unable to start.": "OLE:a ei voi käynnistää.",
	"Make sure that you are using the correct version of the OLE libraries.": "Varmista, että käytät oikeita versioita OLE-kirjastoista.",
	"Resets the text be without any attributes.": "Poistaa tekstin kaikki määritteet.",
	"Sets or clears the text bold attribute.": "Asettaa tai poistaa tekstin lihavointi -määritteen.",
	"Sets or clears the text italic attribute.": "Asettaa tai poistaa tekstin kursivointi -määritteen.",
	"Selects the font used by the text.": "Valitsee tekstin käyttämän fontin.",
	"Selects the point size of the text.": "Valitsee tekstin pistekoon.",
	"Sets or clears the text underline attribute.": "Asettaa tai poistaa tekstin alleviivaus -määritteen.",
	"Shows or hides the tooltips.": "Näyttää tai piilottaa työkaluvihjeet.",
	"Show Paint Help.": "Näyttää Paintin Ohjeen.",
	"Sends a picture by using mail or fax.": "Lähettää kuvan sähköpostina tai faksilla.",
	"Copies the selection to a file.": "Kopioi valinnan tiedostoon.",
	"Pastes a file into the selection.": "Liittää tiedoston valintaan.",
	"Zooms the picture to 100%.": "Zoomaa kuvan 100 %:n kokoon.",
	"Zooms the picture to 400%.": "Zoomaa kuva 400 %:n kokoon.",
	"Zooms the picture.": "Zoomaa kuvan.",
	"Displays the entire picture.": "Näyttää koko kuvan.",
	"Shows or hides the thumbnail view of the picture.": "Näyttää tai piilottaa pikkukuvan.",
	"Shows or hides the grid.": "Näyttää tai piilottaa ruudukon.",
	"Shows or hides the text toolbar.": "Näyttää tai piilottaa tekstityökalurivin.",
	"Flips or rotates the picture or a selection.": "Kääntää tai kiertää kuvaa tai valintaa.",
	"Stretches or skews the picture or a selection.": "Venyttää tai viistottaa kuvaa tai valintaa.",
	"Inverts the colors of the picture or a selection.": "Muuttaa kuvan tai valinnan värit käänteisiksi.",
	"Changes the attributes of the picture.": "Muuttaa kuvan määritteitä.",
	"Clears the picture or selection.": "Poistaa kuvan tai valinnan.",
	"The font size must be a numeric value.": "Fonttikoon on oltava luku.",
	"Contains commands for working with the selected item(s).": "Komennot, joilla käsitellään valittua kohdetta.",
	"Contains commands for selecting and transferring items.": "Komennot, joilla valitaan ja siirretään kohteita.",
	"Contains commands for customizing this window.": "Komennot, joilla mukautetaan tätä ikkunaa.",
	"Contains commands for manipulating pictures and setting attributes.": "Komennot, joilla muokataan kuvia ja muutetaan määritteitä.",
	"Contains commands for using custom colors and drawing options.": "Komennot, joilla käytetään mukautettuja värejä ja piirtoasetuksia.",
	"Contains commands for displaying Help for and information about Paint.": "Komennot, joilla näytetään Ohje ja tietoja Paintista.",
	"Cannot save file.": "Tiedostoa ei voi tallentaa.",
	"Error removing temporary file.": "Virhe poistettaessa tilapäistiedostoa.",
	"Get Colors": "Hae värit",
	"Save Colors": "Tallenna värit",
	"File last saved:": "Viimeisin tallennus:",
	"Not Available": "Ei tietoa",
	"Size on disk:": "Koko levylle tallennettuna:",
	"%s bytes": "%s tavua",
	"Painting": "Maalaus",
	"Fonts": "Fontit",
	"Tools": "Työkalut",
	"All Picture Files": "Kaikki kuvatiedostot",
	"For Help, click Help Topics on the Help Menu.": "Valitse Ohjeen aiheet Ohje-valikosta, jos haluat lisätietoja.",
	"Select an area on which to get Help.": "Valitse alue, josta haluat Ohjeita",
	"%1 in %2": "%1 kohteessa %2",
	"Creates a new document.": "Luo uuden tiedoston.",
	"Opens an existing document.": "Avaa aiemmin luodun tiedoston.",
	"Closes the active document.": "Sulkee aktiivisen tiedoston.",
	"Saves the active document.": "Tallentaa aktiivisen tiedoston.",
	"Saves the active document with a new name.": "Tallentaa aktiivisen tiedoston uudella nimellä.",
	"Changes the page layout.": "Muuttaa sivun asettelua.",
	"Specifies the default printer setup.": "Määrittää kirjoittimen oletusasetukset.",
	"Prints the active document and sets printing options.": "Tulostaa aktiivisen tiedoston ja asettaa tulostusasetukset.",
	"Displays full pages.": "Näyttää koko sivun.",
	"Opens this document.": "Avaa tämän tiedoston.",
	"Deletes the selection.": "Poistaa valinnan.",
	"Erases everything.": "Pyyhkii kaiken.",
	"Copies the selection and puts it on the Clipboard.": "Kopioi valinnan ja sijoittaa sen Leikepöydälle",
	"Cuts the selection and puts it on the Clipboard.": "Leikkaa valinnan ja sijoittaa sen Leikepöydälle.",
	"Finds the specified text.": "Etsii määritetyn tekstin.",
	"Inserts the contents of the Clipboard.": "Lisää Leikepöydän sisällön.",
	"Repeats the last action.": "Toistaa viimeisimmän toiminnon.",
	"Replaces specific text with different text.": "Korvaa määritetyn tekstin toisella tekstillä.",
	"Selects everything.": "Valitsee kaiken.",
	"Undoes the last action.": "Kumoaa viimeisimmän toiminnon.",
	"Redoes the previously undone action.": "Tekee uudelleen aikaisemmin kumotun toiminnon.",
	"Displays program information, version number, and copyright.": "Näyttää tietoja ohjelmasta, versionumeron ja tekijänoikeustiedot.",
	"Quits Paint.": "Lopettaa Paintin.",
	"Opens Paint Help.": "Avaa Paintin Ohjeen.",
	"Displays instructions about how to use Help.": "Näyttää tietoja Ohjeen käyttämisestä.",
	"Displays Help for areas you click on.": "Näyttää Ohjeen valitsemastasi alueesta.",
	"Displays Help for the current task or command.": "Näyttää Ohjeen nykyisestä tehtävästä tai komennosta.",
	"Centers this bitmap as the desktop wallpaper.": "Keskittää tämän bittikartan työpöydän taustakuvaksi.",
	"Tiles this bitmap as the desktop wallpaper.": "Asettaa tämän bittikartan vierekkäiseksi työpöydän taustakuvaksi.",
	"Sends the selection using mail or fax.": "Lähettää valinnan sähköpostina tai faksilla.",
	"Prints the selection.": "Tulostaa valinnan.",
	"Shows or hides the thumbnail.": "Näyttää tai piilottaa pikkukuvan.",
	"Shows Paint Help.": "Näyttää Paintin Ohjeen.",
	"Shows or hides the status bar.": "Näyttää tai piilottaa tilarivin.",
	"Shows or hides the tool box.": "Näyttää tai piilottaa työkaluruudun.",
	"Shows or hides the color box.": "Näyttää tai piilottaa väriruudun.",
	"Only a Far East font can be used for vertical editing.": "Vain Far East -fonttia voidaan käyttää pystysuoraan muokkaukseen.",
	"Changes the window size.": "Muuttaa ikkunan kokoa.",
	"Changes the window position.": "Muuttaa ikkunan paikkaa.",
	"Reduces the window to an icon.": "Pienentää ikkunan kuvakkeeksi.",
	"Enlarges the window to full size.": "Suurentaa ikkunan täyteen kokoon.",
	"Switches to the next document window.": "Vaihtaa seuraavaan tiedostoikkunaan.",
	"Switches to the previous document window.": "Vaihtaa edelliseen tiedostoikkunaan.",
	"Closes the active window and asks if you want to save changes.": "Sulkee aktiivisen ikkunan ja pyytää tallentamaan muutokset.",
	"Restores the window to normal size.": "Palauttaa ikkunan normaaliin kokoon.",
	"Activates the task list.": "Aktivoi tehtäväluettelon.",
	"All Files (*.*)": "Kaikki tiedostot (*.*)",
	"Untitled": "Nimetön",
	"an unnamed file": "Nimeämätön tiedosto",
	"&Hide": "&Piilota",
	"Hide": "Piilota",
	"No error message is available.": "Virhesanomaa ei ole käytettävissä.",
	"An unsupported operation was attempted.": "Yritettiin suorittaa  toiminto, jota ei tueta.",
	"A required resource was unavailable.": "Tarvittava resurssi ei ole käytettävissä.",
	"Out of memory.": "Muisti ei riitä.",
	"An unknown error has occurred.": "Tuntematon virhe.",
	"on %1": "kohteessa %1",
	"&One Page": "&Yksi sivu",
	"One Page": "Yksi sivu",
	"&Two Page": "&Kaksi sivua",
	"Two Page": "Kaksi sivua",
	"Page %u": "Sivu %u",
	"Pages %u-%u": "Sivut %u-%u",
	"Printer Files (*.prn)|*.prn|All Files (*.*)|*.*||": "Kirjoitintiedostot (*.prn)|*.prn|Kaikki tiedostot (*.*)|*.*||",
	"Print to File": "Tulosta tiedostoon",
	"to %1": "tiedostoon %1",
	"&Update %1": "&Päivitä %1",
	"Update %1": "Päivitä %1",
	"E&xit && Return to %1": "&Lopeta ja palaa kohteeseen %1",
	"Exit && Return to %1": "Lopeta ja palaa kohteeseen %1",
	"Linked %s": "Linkitetty %s",
	"Unknown Type": "Tuntematon tyyppi",
	"Invalid filename.": "Tiedostonimi ei kelpaa.",
	"Failed to open document.": "Tiedoston avaaminen epäonnistui.",
	"Failed to save document.": "Tiedoston tallentaminen epäonnistui.",
	"Save changes to %1?": "Tallennetaanko tiedoston %1 muutokset?",
	"Failed to create empty document.": "Tyhjän tiedoston luominen epäonnistui.",
	"The file is too large to open.": "Tiedosto on liian suuri avattavaksi.",
	"Could not start print job.": "Tulostustyötä ei voi aloittaa.",
	"Failed to launch help.": "Ohjeen käynnistäminen epäonnistui.",
	"Internal application error.": "Sisäinen sovellusvirhe.",
	"Command failed.": "Komento epäonnistui.",
	"Insufficient memory to perform operation.": "Liian vähän muistia toiminnon suorittamiseen.",
	"System registry entries have been removed and the INI file (if any) was deleted.": "Järjestelmän rekisteritietueet ja mahdollinen INI -tiedosto on poistettu.",
	"Not all of the system registry entries (or INI file) were removed.": "Kaikkia järjestelmän rekisteritietueita tai INI -tiedostoa ei ole poistettu.",
	"This program requires the file %s, which was not found on this system.": "Ohjelman vaatimaa tiedostoa %s ei löytynyt järjestelmästä.",
	"This program is linked to the missing export %s in the file %s. This machine may have an incompatible version of %s.": "Ohjelma on yhdistetty puuttuvaan vientiin %s tiedostossa %s. Tietokoneen versio %s voi olla yhteensopimaton.",
	"Please enter an integer.": "Anna kokonaisluku.",
	"Please enter a number.": "Anna luku.",
	"Please enter an integer between %1 and %2.": "Anna kokonaisluku %1 - %2.",
	"Please enter a number between %1 and %2.": "Anna luku %1 - %2.",
	"Please enter no more than %1 characters.": "Anna enintään %1 merkkiä.",
	"Please select a button.": "Valitse painike.",
	"Please enter an integer between 0 and 255.": "Anna kokonaisluku 0 - 255.",
	"Please enter a positive integer.": "Anna positiivinen kokonaisluku.",
	"Please enter a date and/or time.": "Anna päivämäärä tai aika.",
	"Please enter a currency.": "Anna valuutta.",
	"Unexpected file format.": "Odottamaton tiedostomuoto.",
	"Cannot find this file.": "Tiedostoa ei löydy.",
	"Please verify that the correct path and file name are given.": "Varmista, että polku ja tiedostonimi ovat oikein.",
	"Destination disk drive is full.": "Kohdelevyasema on täynnä.",
	"Unable to read from %1, it is opened by someone else.": "Tiedostoa %1 ei voi lukea, koska joku toinen on avannut sen.",
	"Unable to write to %1, it is read-only or opened by someone else.": "Tiedostoon %1 ei voi kirjoittaa, koska se on vain luku -tyyppiä tai joku toinen on avannut sen.",
	"An unexpected error occurred while reading %1.": "Odottamaton virhe luettaessa tiedostoa %1.",
	"An unexpected error occurred while writing %1.": "Odottamaton virhe kirjoitettaessa tiedostoon %1.",
	"Unable to register document.": "Tiedostoa ei voi rekisteröidä.",
	"The document may already be open.": "Tiedosto voi olla jo avoinna.",
	"Update %1 before proceeding?": "Päivitetäänkö %1 ennen jatkamista?",
	"Could not update client.": "Asiakasta ei voi päivittää.",
	"Failed to register. ActiveX features may not work properly.": "Rekisteröinti epäonnistui. ActiveX-ominaisuudet eivät ehkä toimi oikein.",
	"Failed to update the system registry.": "Järjestelmärekisteriä ei voitu päivittää.",
	"Please try using REGEDIT.": "Yritä uudelleen käyttämällä Regedit-ohjelmaa.",
	"Unable to read write-only property.": "Vain kirjoitus -ominaisuutta ei voi lukea.",
	"Unable to write read-only property.": "Vain luku -ominaisuuteen ei voi kirjoittaa.",
	"Unable to load mail system support.": "Sähköpostijärjestelmän tukea ei voi ladata.",
	"Mail system DLL is invalid.": "Sähköpostijärjestelmän DLL ei kelpaa.",
	"Send Mail failed to send message.": "Sähköpostin lähettäminen ei onnistu.",
	"No error occurred.": "Ei virheitä.",
	"An unknown error occurred while accessing %1.": "Tuntematon virhe  käytettäessä: %1.",
	"%1 was not found.": "%1 ei löydy.",
	"%1 contains an invalid path.": "%1 sisältää epäkelvon polun.",
	"%1 could not be opened because there are too many open files.": "Tiedostoa %1 ei voi avata, koska avoimia tiedostoja on liikaa.",
	"Access to %1 was denied.": "Kohteen %1 käyttö estetty.",
	"An invalid file handle was associated with %1.": "Kohteeseen %1 liitetty epäkelpo tiedostokahva.",
	"%1 could not be removed because it is the current directory.": "Hakemistoa %1 ei voida poistaa, koska se on nykyinen hakemisto.",
	"%1 could not be created because the directory is full.": "%1 ei voi luoda, koska hakemisto on täynnä.",
	"Seek failed on %1": "Etsintä hakemistossa %1 epäonnistui",
	"A hardware I/O error was reported while accessing %1.": "Laitteiston I/O-virhe käsiteltäessä kohdetta %1.",
	"A sharing violation occurred while accessing %1.": "Yhteiskäyttövirhe käytettäessä kohdetta %1.",
	"A locking violation occurred while accessing %1.": "Lukitusvirhe käytettäessä kohdetta %1.",
	"Disk full while accessing %1.": "Levyn täyttyminen käytettäessä kohdetta %1.",
	"An attempt was made to access %1 past its end.": "Yritys käyttää kohdetta %1 sen lopun jälkeen.",
	"An attempt was made to write to the reading %1.": "Yritys kirjoittaa luettavaan kohteeseen %1.",
	"An attempt was made to read from the writing %1.": "Yritys lukea kirjoitettavaan kohteesta %1.",
	"%1 has a bad format.": "%1 on väärää muotoa.",
	"%1 contained an unexpected object.": "%1 sisältää odottamattoman objektin.",
	"%1 contains an incorrect schema.": "%1 sisältää väärän mallin.",
	"Selects a rectangular part of the picture to move, copy, or edit.": "Valitsee suorakulmion muotoisen kuvan osan siirrettäväksi, kopioitavaksi tai muokattavaksi.",
	"Select": "Valinta",
	"Selects a free-form part of the picture to move, copy, or edit.": "Valitsee vapaamuotoisen alueen siirrettäväksi, kopioitavaksi tai muokattavaksi.",
	"Free-Form Select": "Vapaa valinta",
	"Inserts text into the picture.": "Liittää tekstin kuvaan.",
	"Fills an area with the current drawing color.": "Täyttää alueen nykyisellä piirtovärillä.",
	"Fill With Color": "Täytä värillä",
	"Draws a straight line with the selected line width.": "Piirtää valitun levyisen suoran viivan.",
	"Line": "Viiva",
	"Draws using an airbrush of the selected size.": "Piirtää valitun kokoisella ruiskulla.",
	"Airbrush": "Ruisku",
	"Draws a curved line with the selected line width.": "Piirtää valitun levyisen käyrän viivan.",
	"Curve": "Käyrä",
	"Draws a polygon with the selected fill style.": "Piirtää valitun värisen täytetyn monikulmion.",
	"Polygon": "Monikulmio",
	"Draws a rounded rectangle with the selected fill style.": "Piirtää pyöristetyn suorakulmion käyttäen valittua täyttötyyliä.",
	"Rounded Rectangle": "Pyöristetty suorakulmio",
	"Draws a free-form line one pixel wide.": "Piirtää yhden kuvapisteen levyisen vapaan viivan.",
	"Pencil": "Kynä",
	"Erases a portion of the picture, using the selected eraser shape.": "Pyyhkii osan kuvasta käyttäen valittua pyyhkimen muotoa.",
	"Eraser/Color Eraser": "Pyyhin",
	"Changes the magnification.": "Muuttaa suurennusta.",
	"Magnifier": "Suurennus",
	"Picks up a color from the picture for drawing.": "Valitsee piirrettävän kuvan värin.",
	"Pick Color": "Värin valinta",
	"Draws using a brush with the selected shape and size.": "Piirtää käyttäen valitun muotoista ja kokoista sivellintä.",
	"Brush": "Sivellin",
	"Draws a rectangle with the selected fill style.": "Piirtää suorakulmion käyttäen valittua täyttötyyliä.",
	"Rectangle": "Suorakulmio",
	"Draws a filled rectangle.": "Piirtää täytetyn suorakulmion.",
	"Draws an ellipse with the selected fill style.": "Piirtää ellipsin käyttäen valittua täyttötyyliä.",
	"Ellipse": "Ellipsi",
	"Draws a filled ellipse.": "Piirtää täytetyn ellipsin.",
	"Makes the current selection either opaque or transparent.": "Tekee nykyisestä valinnasta joko peittävän tai läpinäkyvän.",
	"Creates a new color.": "Luo uuden piirtovärin.",
	"Uses a previously saved palette of colors.": "Käyttää aikaisemmin tallennettua värivalikoimaa.",
	"Saves the current palette of colors to a file.": "Tallentaa nykyisen värivalikoiman tiedostoon.",
	"You must save the file before choosing it as Wallpaper.": "Tallenna tiedosto ennen sen valitsemista taustakuvaksi.",
	"The selection is now larger than the bitmap.": "Valinta on nyt suurempi kuin bittikartta.",
	"Would you like the bitmap enlarged?": "Haluatko suurentaa bittikarttaa?",
	"The image in the clipboard is larger than the bitmap.": "Leikepöydän kuva on suurempi kuin bittikartta.",
	"The file is not in the correct format.": "Tiedosto ei ole oikeassa muodossa.",
	"Not enough room to paste text.": "Liian vähän tilaa tekstin liittämiseen.",
	"Enlarge the text area and try again.": "Suurenna tekstialuetta ja yritä uudelleen.",
	"Places the text.": "Sijoittaa tekstin."
});
