//
// NOTE: This is a generated file! Don't edit it directly.
// Eventually community translation will be set up on some translation platform.
// 
// Generated with: npm run update-localization
//
loaded_localizations("es", {
	"Attributes": "Atributos",
	"&Width:": "&Ancho:",
	"Width:": "Ancho:",
	"&Height:": "A&lto:",
	"Height:": "Alto:",
	"Units": "Unidades",
	"&Inches": "P&ulgadas",
	"Inches": "Pulgadas",
	"C&m": "&cm",
	"Cm": "cm",
	"&Pixels": "Pí&xeles",
	"Pixels": "Píxeles",
	"Colors": "Colores",
	"&Black and white": "&Blanco y negro",
	"Black and white": "Blanco y negro",
	"Co&lors": "C&olores",
	"Transparency": "Transparencia",
	"Use &Transparent background color": "Usar un color &transparente de fondo",
	"Use Transparent background color": "Usar un color transparente de fondo",
	"Select &Color": "&Seleccionar color",
	"Select Color": "Seleccione un color",
	"OK": "Aceptar",
	"Cancel": "Cancelar",
	"&Default": "&Predeterminado",
	"Default": "Predeterminado",
	"Custom Zoom": "Zoom personalizado",
	"Current zoom:": "Zoom actual:",
	"Zoom to": "Zoom",
	"Flip and Rotate": "Voltear y rotar",
	"Flip or rotate": "Voltear o rotar",
	"&Flip horizontal": "Voltear &horizontalmente",
	"Flip horizontal": "Voltear horizontalmente",
	"Flip &vertical": "Voltear &verticalmente",
	"Flip vertical": "Voltear verticalmente",
	"&Rotate by angle": "&Rotar",
	"Rotate by angle": "Rotar",
	"Stretch and Skew": "Expandir y contraer",
	"Stretch": "Expandir",
	"Skew": "Contraer",
	"H&orizontal:": "Hori&zontal:",
	"Horizontal:": "Horizontal:",
	"Degrees": "grados",
	"Color Table": "Tabla de colores",
	"New": "Nuevo",
	"&New ": "&Nuevo ",
	"New ": "Nuevo ",
	"&Help": "Ay&uda",
	"Help": "Ayuda",
	"Printing": "Imprimiendo",
	"on the": "en",
	"&Print": "I&mprimir",
	"Print": "Imprimir",
	"&Next Page": "&Pág. sig.",
	"Next Page": "Pág. sig.",
	"Pre&v Page": "Pág. ante&rior",
	"Prev Page": "Pág. anterior",
	"Zoom &In": "&Acercar",
	"Zoom In": "Acercar",
	"Zoom &Out": "A&lejar",
	"Zoom Out": "Alejar",
	"&Close": "&Cerrar",
	"Close": "Cerrar",
	"Grid Settings": "Configuración de la cuadrícula",
	"&Pixel Grid": "Cuadrícula de pí&xeles",
	"Pixel Grid": "Cuadrícula de píxeles",
	"&Tile Grid": "Cuadrícula de &mosaico",
	"Tile Grid": "Cuadrícula de mosaico",
	"pixels": "píxeles",
	"H&eight:": "Alt&o:",
	"Text": "Texto",
	"Undo": "Deshacer",
	"Cut": "Cortar",
	"Copy": "Copiar",
	"Paste": "Pegar",
	"Clear Selection": "Borrar selección",
	"Select All": "Seleccionar todo",
	"Text Toolbar": "Barra de herramientas de texto",
	"Selection": "Selección",
	"Cu&t": "C&ortar",
	"&Copy": "&Copiar",
	"&Paste": "&Pegar",
	"C&lear Selection": "&Borrar selección",
	"Select &All": "Seleccionar &todo",
	"C&opy To": "Copi&ar a",
	"Copy To": "Copiar a",
	"Paste &From": "P&egar desde",
	"Paste From": "Pegar desde",
	"Flip/&Rotate": "&Voltear o rotar",
	"Flip/Rotate": "Voltear o rotar",
	"&Stretch/Skew": "E&xpandir o contraer",
	"Stretch/Skew": "Expandir o contraer",
	"&Invert Colors": "I&nvertir colores",
	"Invert Colors": "Invertir colores",
	"Thumbnail": "Vista en miniatura",
	"&File": "&Archivo",
	"File": "Archivo",
	"&New": "&Nuevo",
	"&Open": "&Abrir",
	"Open": "Abrir",
	"Ctrl+O": "Ctrl+A",
	"&Save": "&Guardar",
	"Save": "Guardar",
	"Ctrl+S": "Ctrl+G",
	"Save &As": "Guardar co&mo",
	"Save As": "Guardar como",
	"Print Pre&view": "&Vista preliminar",
	"Print Preview": "Vista preliminar",
	"Page Se&tup": "&Configurar página",
	"Page Setup": "Configurar página",
	"S&end": "&Enviar",
	"Send": "Enviar",
	"Set As &Wallpaper (Tiled)": "Establecer como papel tapiz (m&osaico)",
	"Set As Wallpaper (Tiled)": "Establecer como papel tapiz (mosaico)",
	"Set As Wa&llpaper (Centered)": "Estab&lecer como papel tapiz (centrado)",
	"Set As Wallpaper (Centered)": "Establecer como papel tapiz (centrado)",
	"Recent File": "Archivo reciente",
	"E&xit": "&Salir",
	"Exit": "Salir",
	"&Edit": "&Edición",
	"Edit": "Edición",
	"&Undo": "&Deshacer",
	"&Repeat": "&Repetir",
	"Repeat": "Repetir",
	"Del": "Supr",
	"Ctrl+A": "Ctrl+E",
	"&View": "&Ver",
	"View": "Ver",
	"&Tool Box": "Cuadro de &herramientas",
	"Tool Box": "Cuadro de herramientas",
	"Ctrl+T": "Ctrl+H",
	"&Color Box": "Cua&dro de colores",
	"Color Box": "Cuadro de colores",
	"Ctrl+L": "Ctrl+D",
	"&Status Bar": "Barra d&e estado",
	"Status Bar": "Barra de estado",
	"T&ext Toolbar": "&Barra de herramientas de texto",
	"&Normal Size": "&Tamaño normal",
	"Normal Size": "Tamaño normal",
	"Ctrl+PgUp": "Ctrl+Re Pág",
	"&Large Size": "T&amaño grande",
	"Large Size": "Tamaño grande",
	"Ctrl+PgDn": "Ctrl+Av Pág",
	"C&ustom": "&Personalizado",
	"Custom": "Personalizado",
	"Show &Grid": "Most&rar cuadrícula",
	"Show Grid": "Mostrar cuadrícula",
	"Ctrl+G": "Ctrl+M",
	"Show T&humbnail": "Mostrar página en &miniatura",
	"Show Thumbnail": "Mostrar página en miniatura",
	"&View Bitmap": "&Ver mapa de bits",
	"View Bitmap": "Ver mapa de bits",
	"Ctrl+F": "Ctrl+B",
	"&Image": "&Imagen",
	"Image": "Imagen",
	"&Flip/Rotate": "&Voltear o rotar",
	"&Attributes": "&Atributos",
	"Ctrl+E": "Ctrl+Mayús+E",
	"&Clear Image": "&Borrar imagen",
	"Clear Image": "Borrar imagen",
	"Ctrl+Shft+N": "Ctrl+Mayús+N",
	"&Draw Opaque": "&Dibujar figuras opacas",
	"Draw Opaque": "Dibujar figuras opacas",
	"&Colors": "C&olores",
	"&Edit Colors": "&Modificar colores",
	"Edit Colors": "Modificar colores",
	"&Help Topics": "&Temas de Ayuda",
	"Help Topics": "Temas de Ayuda",
	"&About Paint": "&Acerca de Paint",
	"About Paint": "Acerca de Paint",
	"&Update": "Act&ualizar",
	"Update": "Actualizar",
	"Save Copy &As": "&Guardar copia como",
	"Save Copy As": "Guardar copia como",
	"untitled": "Dibujo",
	"Bitmap Image": "Imagen de mapa de bits",
	"Bitmap Files (*.bmp)": "Archivos de mapa de bits (*.bmp)",
	"PCX Files": "Archivos PCX",
	"Icon Files": "Archivos de icono",
	"Monochrome Bitmap (*.bmp;*.dib)": "Mapa de bits monocromo (*.bmp;*.dib)",
	"16 Color Bitmap (*.bmp;*.dib)": "Mapa de bits de 16 colores (*.bmp;*.dib)",
	"256 Color Bitmap (*.bmp;*.dib)": "Mapa de bits de 256 colores (*.bmp;*.dib)",
	"Paint cannot open this file.": "Paint no puede abrir este archivo.",
	"Paint cannot read this file.": "Paint no puede leer este archivo.",
	"This file is read-only.": "Este archivo es de sólo lectura.",
	"To save your changes, use a different filename.": "Para guardar los cambios, utilice un nombre de archivo diferente.",
	"This file is already open.": "Este archivo ya está abierto.",
	"This is not a valid .PCS file.": "No es un archivo .PCS válido.",
	"This file is open for editing and cannot be overwritten.": "Este archivo está abierto para edición y no puede sobrescribirse.",
	"Use a different filename to save your changes.": "Utilice un nombre de archivo diferente para guardar los cambios.",
	"This is not a valid bitmap file, or its format is not currently supported.": "Este archivo no es un archivo de mapa de bits válido o su formato no es compatible.",
	"This is not a valid icon.": "No es un icono válido.",
	"This is not a valid cursor.": "No es un cursor válido.",
	"Save was interrupted, so your file has not been saved.": "El proceso de  guardar fue interrumpido. El archivo no se ha guardado.",
	"You cannot save to a read-only file.": "No se puede guardar un archivo de sólo lectura.",
	"Use a different file name.": "Utilice un nombre de archivo diferente.",
	"This file is already in use.": "Este archivo ya está en uso.",
	"Close the program, and then try again.": "Cierre el programa e intente de nuevo.",
	"Paint cannot save this file.": "Paint no puede guardar este archivo.",
	"Paint cannot save to the same filename with a different file type.": "Paint no puede guardar un archivo de nombre idéntico con un tipo de archivo diferente.",
	"The grid spacing must be an integer between %d and %d.": "El espaciado de la cuadrícula debe ser un entero entre %d y %d.",
	"There is not enough memory or resources to complete operation.": "No hay recursos o memoria suficientes para completar la operación.",
	"Close some programs, and then try again.": "Cierre algunos programas e intente de nuevo.",
	"Low on memory or resources.": "Memoria o recursos insuficientes.",
	"Group error.": "Error de grupo.",
	"Paint was unable to print your document. Please make sure you have sufficient disk space and that your printer is working correctly.": "Paint no puede imprimir su documento. Asegúrese de que existe suficiente espacio en el disco y de que su impresora funciona correctamente.",
	"Saving into this format may cause some loss of color information.": "Guardar en este formato puede causar pérdida de información de color.",
	"Do you want to continue?": "¿Desea continuar?",
	"Converting to black and white cannot be undone.  This action affects the current file and may cause some loss of color information.": "No se puede deshacer la operación de convertir en blanco y negro. Esto afecta al archivo actual y puede causar la pérdida de información de color.",
	"Bitmaps must be greater than one pixel on a side.": "Los mapas de bits deben ser mayores de un píxel en un lado.",
	"Generic error.": "Error genérico.",
	"File not found.": "Archivo no encontrado.",
	"Bad path.": "Ruta errónea.",
	"Too many open files.": "Demasiados archivos abiertos.",
	"Access denied.": "Acceso denegado.",
	"Invalid file.": "Archivo no válido.",
	"Remove current folder.": "Quitar carpeta actual.",
	"Folder full.": "Carpeta llena.",
	"Bad seek.": "Búsqueda errónea.",
	"Hard IO error.": "Error de hardware de E/S.",
	"Sharing violation.": "Infracción al compartir.",
	"Lock violation.": "Infracción de bloqueo.",
	"Disk full.": "Disco lleno.",
	"End of file.": "Final de archivo.",
	"Error getting the Clipboard Data!": "Error al obtener información del Portapapeles",
	"No Printer Found @ page setup": "No se encontró impresora en Configuración de página",
	"24-bit Bitmap (*.bmp;*.dib)": "Mapa de bits de 24 bits (*.bmp;*.dib)",
	"All Files": "Todos los archivos",
	"Palette|*.pal|": "Paleta|*.pal|",
	"untitled.pal": "Dibujo.pal",
	"OLE 2.0 was unable to start.": "OLE 2.0 no se puede iniciar.",
	"Make sure that you are using the correct version of the OLE libraries.": "Asegúrese de que está utilizando la versión correcta de las bibliotecas OLE.",
	"Resets the text be without any attributes.": "Restablece el texto sin ningún atributo.",
	"Sets or clears the text bold attribute.": "Aplica o quita el formato de negrita.",
	"Sets or clears the text italic attribute.": "Aplica o quita el formato de cursiva.",
	"Selects the font used by the text.": "Selecciona la fuente utilizada por el texto.",
	"Selects the point size of the text.": "Selecciona el tamaño en puntos del texto.",
	"Sets or clears the text underline attribute.": "Establece o quita el atributo subrayado del texto.",
	"Shows or hides the tooltips.": "Muestra u oculta la información sobre herramientas.",
	"Show Paint Help.": "Muestra la Ayuda de Paint.",
	"Sends a picture by using mail or fax.": "Envía una imagen utilizando correo o fax.",
	"Copies the selection to a file.": "Copia la selección a un archivo.",
	"Pastes a file into the selection.": "Pega un archivo en la selección.",
	"Zooms the picture to 100%.": "Amplía la imagen a 100%.",
	"Zooms the picture to 400%.": "Amplía la imagen a 400%.",
	"Zooms the picture.": "Amplía la imagen.",
	"Displays the entire picture.": "Muestra toda la imagen.",
	"Shows or hides the thumbnail view of the picture.": "Muestra u oculta la vista en miniatura de la imagen.",
	"Shows or hides the grid.": "Muestra u oculta la cuadrícula.",
	"Shows or hides the text toolbar.": "Muestra u oculta la barra de herramientas de texto.",
	"Flips or rotates the picture or a selection.": "Voltea o rota el dibujo o una selección.",
	"Stretches or skews the picture or a selection.": "Extiende o contrae la imagen o la selección.",
	"Inverts the colors of the picture or a selection.": "Invierte los colores de la imagen o de una selección.",
	"Changes the attributes of the picture.": "Cambia los atributos de la imagen.",
	"Clears the picture or selection.": "Borra la imagen o selección.",
	"The font size must be a numeric value.": "El tamaño de fuente debe ser un valor numérico.",
	"Contains commands for working with the selected item(s).": "Contiene comandos para trabajar con los elementos seleccionados.",
	"Contains commands for selecting and transferring items.": "Contiene comandos para seleccionar y transferir elementos.",
	"Contains commands for customizing this window.": "Contiene comandos para personalizar esta ventana.",
	"Contains commands for manipulating pictures and setting attributes.": "Contiene comandos para manipular imágenes y establecer atributos.",
	"Contains commands for using custom colors and drawing options.": "Contiene comandos para utilizar colores personalizados y opciones de dibujo.",
	"Contains commands for displaying Help for and information about Paint.": "Contiene comandos para mostrar la Ayuda e información acerca de Paint.",
	"Cannot save file.": "No se puede guardar el archivo.",
	"Error removing temporary file.": "Error al quitar el archivo temporal.",
	"Get Colors": "Cargar colores",
	"Save Colors": "Guardar colores",
	"File last saved:": "Último archivo guardado:",
	"Not Available": "No disponible",
	"Size on disk:": "Tamaño en disco:",
	"Painting": "Pintando",
	"Bitmap": "Mapa de bits",
	"Fonts": "Fuentes",
	"Tools": "Herramientas",
	"All Picture Files": "Todos los archivos de imagen",
	"For Help, click Help Topics on the Help Menu.": "Para obtener Ayuda, haga clic en Temas de Ayuda en el menú Ayuda.",
	"Select an area on which to get Help.": "Seleccione un área sobre la que desee obtener Ayuda.",
	"%1 in %2": "%1 en %2",
	"Creates a new document.": "Crea un nuevo documento.",
	"Opens an existing document.": "Abre un documento existente.",
	"Closes the active document.": "Cierra el documento activo.",
	"Saves the active document.": "Guarda el documento activo.",
	"Saves the active document with a new name.": "Guarda el documento activo con un nuevo nombre.",
	"Changes the page layout.": "Cambia la distribución de la página.",
	"Specifies the default printer setup.": "Especifica la configuración de la  impresora predeterminada.",
	"Prints the active document and sets printing options.": "Imprime el documento activo y establece las opciones de impresión.",
	"Displays full pages.": "Muestra páginas enteras.",
	"Opens this document.": "Abre este documento.",
	"Deletes the selection.": "Elimina la selección.",
	"Erases everything.": "Borra todo.",
	"Copies the selection and puts it on the Clipboard.": "Copia la selección y la pone en el Portapapeles.",
	"Cuts the selection and puts it on the Clipboard.": "Corta la selección y la pone en el Portapapeles.",
	"Finds the specified text.": "Busca el texto especificado.",
	"Inserts the contents of the Clipboard.": "Inserta el contenido del Portapapeles.",
	"Repeats the last action.": "Repite la última acción.",
	"Replaces specific text with different text.": "Reemplaza un texto determinado con texto diferente.",
	"Selects everything.": "Selecciona todo.",
	"Undoes the last action.": "Deshace la última acción.",
	"Redoes the previously undone action.": "Rehace la acción previamente deshecha.",
	"Displays program information, version number, and copyright.": "Muestra la información del programa, número de versión, y copyright.",
	"Quits Paint.": "Sale de Paint.",
	"Opens Paint Help.": "Abre la Ayuda de Paint.",
	"Displays instructions about how to use Help.": "Muestra instrucciones acerca del uso de la Ayuda.",
	"Displays Help for areas you click on.": "Muestra Ayuda para las áreas en las que haga clic.",
	"Displays Help for the current task or command.": "Muestra Ayuda para la tarea o el comando actual.",
	"Centers this bitmap as the desktop wallpaper.": "Centra este mapa de bits como el papel tapiz del escritorio.",
	"Tiles this bitmap as the desktop wallpaper.": "Pone en mosaico este mapa de bits como papel tapiz del escritorio.",
	"Sends the selection using mail or fax.": "Envía la selección utilizando correo electrónico o fax.",
	"Prints the selection.": "Imprime la selección.",
	"Shows or hides the thumbnail.": "Muestra u oculta vistas en miniatura.",
	"Shows Paint Help.": "Muestra la Ayuda de Paint.",
	"Shows or hides the status bar.": "Muestra u oculta la barra de estado.",
	"Shows or hides the tool box.": "Muestra u oculta el cuadro de herramientas.",
	"Shows or hides the color box.": "Muestra u oculta el cuadro de colores.",
	"Only a Far East font can be used for vertical editing.": "Sólo se puede usar una fuente del Lejano Oriente para edición vertical.",
	"Changes the window size.": "Cambia el tamaño de la ventana.",
	"Changes the window position.": "Cambia la posición de la ventana.",
	"Reduces the window to an icon.": "Reduce la ventana a un icono.",
	"Enlarges the window to full size.": "Amplía la ventana a tamaño completo.",
	"Switches to the next document window.": "Cambia a la siguiente ventana de documento.",
	"Switches to the previous document window.": "Cambia a la anterior ventana de documento.",
	"Closes the active window and asks if you want to save changes.": "Cierra la ventana activa y pregunta si se desea guardar los cambios.",
	"Restores the window to normal size.": "Restaura la ventana a su tamaño normal.",
	"Activates the task list.": "Activa la lista de tareas.",
	"All Files (*.*)": "Todos los archivos (*.*)",
	"Untitled": "Sin título",
	"an unnamed file": "un archivo sin nombre",
	"&Hide": "&Ocultar",
	"Hide": "Ocultar",
	"No error message is available.": "No hay ningún mensaje de error disponible.",
	"An unsupported operation was attempted.": "Intento de realizar una operación incompatible.",
	"A required resource was unavailable.": "No se encuentra disponible un recurso necesario.",
	"Out of memory.": "Memoria insuficiente.",
	"An unknown error has occurred.": "Error desconocido.",
	"on %1": "en %1",
	"&One Page": "&Una página",
	"One Page": "Una página",
	"&Two Page": "&Dos páginas",
	"Two Page": "Dos páginas",
	"Page %u": "Página %u",
	"Pages %u-%u": "Páginas %u-%u",
	"Output.prn": "Salida.prn",
	"Printer Files (*.prn)|*.prn|All Files (*.*)|*.*||": "Archivos de impresora (*.prn)|*.prn|Todos los archivos (*.*)|*.*||",
	"Print to File": "Imprimir a un archivo",
	"to %1": "a %1",
	"&Update %1": "Act&ualizar %1",
	"Update %1": "Actualizar %1",
	"E&xit && Return to %1": "&Salir y regresar a %1",
	"Exit && Return to %1": "Salir y regresar a %1",
	"Linked %s": "%s vinculado",
	"Unknown Type": "Tipo desconocido",
	"Invalid filename.": "Nombre de archivo no válido.",
	"Failed to open document.": "Error al abrir documento.",
	"Failed to save document.": "Error al guardar documento.",
	"Save changes to %1?": "¿Desea guardar los cambios en %1?",
	"Failed to create empty document.": "Error al crear un documento vacío.",
	"The file is too large to open.": "No se puede abrir el archivo porque es demasiado grande.",
	"Could not start print job.": "No se puede iniciar el trabajo de impresión.",
	"Failed to launch help.": "Error al iniciar la Ayuda.",
	"Internal application error.": "Error interno de la aplicación.",
	"Command failed.": "Error al ejecutar comando.",
	"Insufficient memory to perform operation.": "Memoria insuficiente para realizar la operación.",
	"System registry entries have been removed and the INI file (if any) was deleted.": "Se han quitado las entradas del Registro del sistema y se ha eliminado el archivo INI (si existe).",
	"Not all of the system registry entries (or INI file) were removed.": "No se han quitado todas las entradas del Registro del sistema (o el archivo INI).",
	"This program requires the file %s, which was not found on this system.": "Este programa requiere el archivo %s, que no se encontró en este sistema.",
	"This program is linked to the missing export %s in the file %s. This machine may have an incompatible version of %s.": "Este programa está vinculado a la exportación ausente %s en el archivo %s. Es posible que este equipo tenga una versión incompatible de %s.",
	"Please enter an integer.": "Escriba un número entero.",
	"Please enter a number.": "Escriba un número.",
	"Please enter an integer between %1 and %2.": "Escriba un número entero entre  %1 y %2.",
	"Please enter a number between %1 and %2.": "Escriba un número entre %1 y %2.",
	"Please enter no more than %1 characters.": "No escriba más de %1 caracteres.",
	"Please select a button.": "Seleccione un botón.",
	"Please enter an integer between 0 and 255.": "Escriba un número entero entre 0 y 255.",
	"Please enter a positive integer.": "Escriba un número entero positivo.",
	"Please enter a date and/or time.": "Escriba una fecha, una hora o ambas.",
	"Please enter a currency.": "Escriba una moneda.",
	"Unexpected file format.": "Formato de archivo inesperado.",
	"Cannot find this file.": "No se encuentra el archivo.",
	"Please verify that the correct path and file name are given.": "Compruebe si el nombre de archivo y la ruta son correctos.",
	"Destination disk drive is full.": "La unidad de disco de destino está llena.",
	"Unable to read from %1, it is opened by someone else.": "No se puede leer %1, está abierto por otra persona.",
	"Unable to write to %1, it is read-only or opened by someone else.": "No se puede escribir en %1: es de sólo lectura o alguien lo ha abierto.",
	"An unexpected error occurred while reading %1.": "Error inesperado al leer %1.",
	"An unexpected error occurred while writing %1.": "Error inesperado al escribir %1.",
	"Unable to register document.": "No se puede registrar el documento.",
	"The document may already be open.": "Puede que ya esté abierto.",
	"Update %1 before proceeding?": "¿Desea actualizar %1 antes de continuar?",
	"Could not update client.": "No se puede actualizar el cliente.",
	"Failed to register. ActiveX features may not work properly.": "Error al registrar. Es posible que las características ActiveX no funcionen correctamente.",
	"Failed to update the system registry.": "Error al actualizar el Registro de sistema.",
	"Please try using REGEDIT.": "Inténtelo utilizando REGEDIT.",
	"Unable to read write-only property.": "No se puede leer la propiedad de sólo escritura.",
	"Unable to write read-only property.": "No se puede escribir la propiedad de sólo lectura.",
	"Unable to load mail system support.": "No se puede cargar sistema de correo.",
	"Mail system DLL is invalid.": "DLL del sistema de correo no válida.",
	"Send Mail failed to send message.": "No se puede enviar el mensaje.",
	"No error occurred.": "Sin errores.",
	"An unknown error occurred while accessing %1.": "Error desconocido al tener acceso a %1.",
	"%1 was not found.": "No se encuentra %1.",
	"%1 contains an invalid path.": "%1 contiene una ruta de acceso no válida.",
	"%1 could not be opened because there are too many open files.": "No se puede abrir %1 porque hay demasiados archivos abiertos.",
	"Access to %1 was denied.": "Se ha denegado el acceso a %1.",
	"An invalid file handle was associated with %1.": "Se asoció con %1 un manipulador de archivo no válido.",
	"%1 could not be removed because it is the current directory.": "No se puede quitar %1 porque es el directorio actual.",
	"%1 could not be created because the directory is full.": "No se puede crear %1 porque el directorio está lleno.",
	"Seek failed on %1": "Error de búsqueda en %1",
	"A hardware I/O error was reported while accessing %1.": "Se ha notificado un error de E/S de hardware al tener acceso a %1.",
	"A sharing violation occurred while accessing %1.": "Infracción de recurso compartido al tener acceso a %1.",
	"A locking violation occurred while accessing %1.": "Infracción de bloqueo al tener acceso a %1.",
	"Disk full while accessing %1.": "El disco se llenó al tener acceso a %1.",
	"An attempt was made to access %1 past its end.": "Intento de acceso a %1 más allá de su término.",
	"An attempt was made to write to the reading %1.": "Se ha intentado escribir en la lectura %1.",
	"An attempt was made to read from the writing %1.": "Se ha intentado leer en la escritura %1.",
	"%1 has a bad format.": "%1 tiene un formato incorrecto.",
	"%1 contained an unexpected object.": "%1 contenía un objeto inesperado.",
	"%1 contains an incorrect schema.": "%1 contiene un esquema incorrecto.",
	"Selects a rectangular part of the picture to move, copy, or edit.": "Selecciona una zona rectangular de la imagen para moverla, copiarla o modificarla.",
	"Select": "Selección",
	"Selects a free-form part of the picture to move, copy, or edit.": "Selecciona una zona de forma libre para moverla, copiarla o modificarla.",
	"Free-Form Select": "Selección de forma libre",
	"Inserts text into the picture.": "Inserta texto dentro de la imagen.",
	"Fills an area with the current drawing color.": "Rellena un área con el color del dibujo actual.",
	"Fill With Color": "Relleno con color",
	"Draws a straight line with the selected line width.": "Dibuja una línea recta de la anchura seleccionada.",
	"Line": "Línea",
	"Draws using an airbrush of the selected size.": "Dibuja utilizando un aerógrafo del tamaño seleccionado.",
	"Airbrush": "Aerógrafo",
	"Draws a curved line with the selected line width.": "Dibuja una línea curva de la anchura seleccionada.",
	"Curve": "Curva",
	"Draws a polygon with the selected fill style.": "Dibuja un polígono con el estilo de relleno seleccionado.",
	"Polygon": "Polígono",
	"Draws a rounded rectangle with the selected fill style.": "Dibuja un rectángulo de esquinas redondeadas con el estilo de relleno seleccionado.",
	"Rounded Rectangle": "Rectángulo redondeado",
	"Draws a free-form line one pixel wide.": "Dibuja una línea de forma libre de un píxel de ancho.",
	"Pencil": "Lápiz",
	"Erases a portion of the picture, using the selected eraser shape.": "Borra una parte de la imagen utilizando la forma de borrador seleccionada.",
	"Eraser/Color Eraser": "Borrador/Borrador de color",
	"Changes the magnification.": "Cambia la ampliación.",
	"Magnifier": "Ampliación",
	"Picks up a color from the picture for drawing.": "Selecciona un color de la imagen para dibujar.",
	"Pick Color": "Seleccionar color",
	"Draws using a brush with the selected shape and size.": "Dibuja utilizando un pincel de la forma y tamaño seleccionados.",
	"Brush": "Pincel",
	"Draws a rectangle with the selected fill style.": "Dibuja un rectángulo con el estilo de relleno seleccionado.",
	"Rectangle": "Rectángulo",
	"Draws a filled rectangle.": "Dibuja un rectángulo lleno.",
	"Draws an ellipse with the selected fill style.": "Dibuja una elipse con el estilo de relleno seleccionado.",
	"Ellipse": "Elipse",
	"Draws a filled ellipse.": "Dibuja una elipse llena.",
	"Makes the current selection either opaque or transparent.": "Hace la actual selección opaca o transparente.",
	"Creates a new color.": "Crea un nuevo color.",
	"Uses a previously saved palette of colors.": "Utiliza una paleta de colores guardada previamente.",
	"Saves the current palette of colors to a file.": "Guarda en un archivo la paleta de colores actual.",
	"You must save the file before choosing it as Wallpaper.": "Debe guardar el archivo antes de elegirlo como Papel tapiz.",
	"The selection is now larger than the bitmap.": "La selección es ahora más grande que el mapa de bits.",
	"Would you like the bitmap enlarged?": "¿Desea ampliar el mapa de bits?",
	"The image in the clipboard is larger than the bitmap.": "La imagen en el portapapeles es mayor  que el mapa de bits.",
	"The file is not in the correct format.": "El archivo no tiene el formato correcto.",
	"Not enough room to paste text.": "Espacio insuficiente para pegar el texto.",
	"Enlarge the text area and try again.": "Amplíe el área de texto y repita la operación.",
	"Places the text.": "Coloca el texto."
});
