//
// NOTE: This is a generated file! Don't edit it directly.
// Eventually community translation will be set up on some translation platform.
// 
// Generated with: npm run update-localization
//
loaded_localizations("ar", {
	"Attributes": "السمات",
	"&Width:": "ال&عرض:",
	"Width:": "العرض:",
	"&Height:": "الار&تفاع:",
	"Height:": "الارتفاع:",
	"Units": "الوحدة",
	"&Inches": "بو&صة",
	"Inches": "بوصة",
	"C&m": "&سم",
	"Cm": "سم",
	"&Pixels": "ب&كسل",
	"Pixels": "بكسل",
	"Colors": "‏‏ألوان",
	"&Black and white": "أسو&د وأبيض",
	"Black and white": "أسود وأبيض",
	"Co&lors": "ألو&ان",
	"Transparency": "الشفافية",
	"Use &Transparent background color": "استخدام لون خلفية &شفاف",
	"Use Transparent background color": "استخدام لون خلفية شفاف",
	"Select &Color": "تحديد &لون",
	"Select Color": "‏‏تحديد لون",
	"OK": "موافق",
	"Cancel": "إلغاء الأمر",
	"&Default": "افترا&ضي",
	"Default": "افتراضي",
	"Custom Zoom": "تكبير/تصغير مخصص",
	"Current zoom:": "التكبير/التصغير الحالي:",
	"Zoom to": "تكبير/تصغير إلى",
	"Flip and Rotate": "الانعكاس والاستدارة",
	"Flip or rotate": "الانعكاس أو الاستدارة",
	"&Flip horizontal": "&انعكاس أفقي",
	"Flip horizontal": "انعكاس أفقي",
	"Flip &vertical": "ا&نعكاس عمودي",
	"Flip vertical": "انعكاس عمودي",
	"&Rotate by angle": "ا&ستدارة بزاوية",
	"Rotate by angle": "استدارة بزاوية",
	"Stretch and Skew": "التمدد والانحراف",
	"Stretch": "التمدد",
	"&Horizontal:": "أف&قياً:",
	"Horizontal:": "أفقياً:",
	"&Vertical:": "&عمودياً:",
	"Vertical:": "عمودياً:",
	"Skew": "الانحراف",
	"H&orizontal:": "أ&فقياً:",
	"Degrees": "درجة",
	"V&ertical:": "ع&مودياً:",
	"Color Table": "جدول الألوان",
	"New": "جديد",
	"&New ": "&جديد",
	"New ": "جديد",
	"&Help": "&تعليمات",
	"Help": "تعليمات",
	"Printing": "طباعة",
	"on the": "على",
	"&Print": "&طباعة",
	"Print": "طباعة",
	"&Next Page": "الصفحة ال&تالية",
	"Next Page": "الصفحة التالية",
	"Pre&v Page": "الصفحة ال&سابقة",
	"Prev Page": "الصفحة السابقة",
	"Zoom &In": "ت&كبير",
	"Zoom In": "تكبير",
	"Zoom &Out": "ت&صغير",
	"Zoom Out": "تصغير",
	"&Close": "إ&غلاق",
	"Close": "إغلاق",
	"Grid Settings": "إعدادات الشبكة",
	"&Pixel Grid": "شب&كة بكسل",
	"Pixel Grid": "شبكة بكسل",
	"&Tile Grid": "&شبكة تجانب",
	"Tile Grid": "شبكة تجانب",
	"pixels": "بكسل",
	"H&eight:": "الار&تفاع:",
	"Text": "نص",
	"Undo": "تراجع",
	"Cut": "قص",
	"Copy": "نسخ",
	"Paste": "لصق",
	"Clear Selection": "مسح التحديد",
	"Select All": "تحديد الكل",
	"Text Toolbar": "شريط أدوات نص",
	"Selection": "التحديد",
	"Cu&t": "&قص",
	"&Copy": "ن&سخ",
	"&Paste": "&لصق",
	"C&lear Selection": "&مسح التحديد",
	"Select &All": "تحديد ال&كل",
	"C&opy To": "&نسخ إلى",
	"Copy To": "‏‏نسخ إلى",
	"Paste &From": "ل&صق من",
	"Paste From": "‏‏لصق من",
	"Flip/&Rotate": "&انعكاس/استدارة",
	"Flip/Rotate": "انعكاس/استدارة",
	"&Stretch/Skew": "&تمدد/انحراف",
	"Stretch/Skew": "تمدد/انحراف",
	"&Invert Colors": "&عكس الألوان",
	"Invert Colors": "عكس الألوان",
	"Thumbnail": "مصغرة",
	"&File": "&ملف",
	"File": "ملف",
	"&New": "&جديد",
	"&Open": "&فتح",
	"Open": "فتح",
	"&Save": "&حفظ",
	"Save": "حفظ",
	"Save &As": "حفظ &باسم",
	"Save As": "حفظ باسم",
	"Print Pre&view": "&معاينة قبل الطباعة",
	"Print Preview": "معاينة قبل الطباعة",
	"Page Se&tup": "إ&عداد الصفحة",
	"Page Setup": "إعداد الصفحة",
	"S&end": "إرس&ال",
	"Send": "إرسال",
	"Set As &Wallpaper (Tiled)": "تعيين كخلفية للشاشة (متجانب)",
	"Set As Wallpaper (Tiled)": "تعيين كخلفية للشاشة (متجانب)",
	"Set As Wa&llpaper (Centered)": "تعيين كخلفية للشاشة (موسّط)",
	"Set As Wallpaper (Centered)": "تعيين كخلفية للشاشة (موسّط)",
	"Recent File": "الملف الأخير",
	"E&xit": "إن&هاء",
	"Exit": "إنهاء",
	"&Edit": "ت&حرير",
	"Edit": "تحرير",
	"&Undo": "ترا&جع",
	"&Repeat": "&تكرار",
	"Repeat": "تكرار",
	"&View": "&عرض",
	"View": "عرض",
	"&Tool Box": "مربع الأ&دوات",
	"Tool Box": "مربع الأدوات",
	"&Color Box": "&مربع الألوان",
	"Color Box": "مربع الألوان",
	"&Status Bar": "شريط المع&لومات",
	"Status Bar": "شريط المعلومات",
	"T&ext Toolbar": "شريط أدوات ال&نص",
	"&Zoom": "تكبير/ت&صغير",
	"Zoom": "تكبير/تصغير",
	"&Normal Size": "&حجم عادي",
	"Normal Size": "حجم عادي",
	"&Large Size": "حجم &كبير",
	"Large Size": "حجم كبير",
	"C&ustom": "م&خصص",
	"Custom": "مخصص",
	"Show &Grid": "إظهار ال&شبكة",
	"Show Grid": "إظهار الشبكة",
	"Show T&humbnail": "إظهار الم&صغّرة",
	"Show Thumbnail": "إظهار المصغّرة",
	"&View Bitmap": "&عرض صورة نقطية",
	"View Bitmap": "عرض صورة نقطية",
	"&Image": "&صورة",
	"Image": "صورة",
	"&Flip/Rotate": "&انعكاس/استدارة",
	"&Attributes": "&سمات",
	"&Clear Image": "&مسح الصورة",
	"Clear Image": "مسح الصورة",
	"&Draw Opaque": "&رسم كامد",
	"Draw Opaque": "رسم كامد",
	"&Colors": "أ&لوان",
	"&Edit Colors": "&تحرير الألوان",
	"Edit Colors": "‏‏تحرير الألوان",
	"&Help Topics": "&مواضيع التعليمات",
	"Help Topics": "مواضيع التعليمات",
	"&About Paint": "&حول الرسام",
	"About Paint": "حول الرسام",
	"&Update": "&تحديث",
	"Update": "تحديث",
	"Save Copy &As": "&حفظ نسخة باسم",
	"Save Copy As": "حفظ نسخة باسم",
	"Paint": "الرسام",
	"untitled": "بدون عنوان",
	"Bitmap Image": "صورة نقطية",
	"Bitmap Files (*.bmp)": "ملفات صور نقطية (*.bmp)",
	"Paint.Picture": "صورة الرسام",
	"PCX Files": "ملفات PCX",
	"Icon Files": "ملفات رموز",
	"Monochrome Bitmap (*.bmp;*.dib)": "صورة نقطية أحادية اللون (*.bmp,*.dib)",
	"16 Color Bitmap (*.bmp;*.dib)": "صورة نقطية 16 لون (*.bmp,*.dib)",
	"256 Color Bitmap (*.bmp;*.dib)": "صورة نقطية 256 لون (*.bmp,*.dib)",
	"Paint cannot open this file.": "‏‏لا يستطيع الرسام فتح هذا الملف.",
	"Paint cannot read this file.": "‏‏لا يستطيع الرسام قراءة هذا الملف.",
	"This file is read-only.": "‏‏هذا الملف للقراءة فقط.",
	"To save your changes, use a different filename.": "استخدم اسم ملف آخر لحفظ تعديلاتك.",
	"This file is already open.": "‏‏هذا الملف مفتوح مسبقاً.",
	"This is not a valid .PCS file.": "‏‏هذا ليس ملف .PCS صالحاً.",
	"This file is open for editing and cannot be overwritten.": "‏‏هذا الملف مفتوح للتحرير ولا يمكن الكتابة فوقه.",
	"Use a different filename to save your changes.": "استخدم اسم ملف آخر لحفظ تعديلاتك.",
	"This is not a valid bitmap file, or its format is not currently supported.": "‏‏هذا الملف ملف صورة نقطية غير صالح أو أن تنسيقه غير معتمد حالياً.",
	"This is not a valid icon.": "‏‏هذا الرمز غير صالح.",
	"This is not a valid cursor.": "‏‏رأس المؤشر هذا غير صالح.",
	"Save was interrupted, so your file has not been saved.": "‏‏تمت مقاطعة عملية الحفظ، لذا لم يتم حفظ ملفك.",
	"You cannot save to a read-only file.": "‏‏لا يمكنك الحفظ في ملف قراءة فقط.",
	"Use a different file name.": "استخدم اسم ملف آخر.",
	"This file is already in use.": "‏‏هذا الملف مستخدم مسبقاً.",
	"Close the program, and then try again.": "أغلق البرنامج وحاول ثانيةً.",
	"Paint cannot save this file.": "‏‏لا يستطيع الرسام حفظ هذا الملف.",
	"Paint cannot save to the same filename with a different file type.": "‏‏لا يمكن للرسام أن يحفظ في اسم الملف نفسه مستخدماً نوع ملف مختلفاً.",
	"The grid spacing must be an integer between %d and %d.": "‏‏يجب أن يكون تباعد الشبكة رقماً صحيحاً بين %d و %d.",
	"There is not enough memory or resources to complete operation.": "‏‏لا توجد ذاكرة أو مصادر كافية لإتمام العملية.",
	"Close some programs, and then try again.": "أغلق بعض البرامج ثم حاول ثانيةً.",
	"Low on memory or resources.": "‏‏نقص في الذاكرة أو المصادر.",
	"Group error.": "‏‏خطأ مجموعة.",
	"Paint was unable to print your document. Please make sure you have sufficient disk space and that your printer is working correctly.": "‏‏لم يتمكن الرسام من طباعة وثيقتك. يرجى التأكد من وجود مساحة كافية على القرص وأن الطابعة تعمل بشكل صحيح.",
	"Saving into this format may cause some loss of color information.": "‏‏يؤدي الحفظ بهذا التنسيق إلى فقدان بعض معلومات اللون.",
	"Do you want to continue?": "هل تريد المتابعة؟",
	"Converting to black and white cannot be undone.  This action affects the current file and may cause some loss of color information.": "‏‏لا يمكن التراجع عن عملية التحويل إلى أسود وأبيض. يؤدي هذا إلى التأثير على الملف الحالي وقد يؤدي إلى فقدان بعض معلومات اللون.",
	"Bitmaps must be greater than one pixel on a side.": "‏‏يجب أن تكون الصور النقطية أكبر من نقطة واحدة في الطرف.",
	"Generic error.": "‏‏خطأ عام.",
	"File not found.": "‏‏الملف غير موجود.",
	"Bad path.": "‏‏مسار غير صالح.",
	"Too many open files.": "‏‏عدد كبير من الملفات المفتوحة.",
	"Access denied.": "‏‏لم يسمح بالوصول.",
	"Invalid file.": "‏‏ملف غير صالح.",
	"Remove current folder.": "‏‏أزل المجلد الحالي.",
	"Folder full.": "‏‏المجلد ممتلئ.",
	"Bad seek.": "‏‏إيجاد خاطئ.",
	"Hard IO error.": "‏‏خطأ إدخال/إخراج في التجهيزات.",
	"Sharing violation.": "‏‏انتهاك في المشاركة.",
	"Lock violation.": "‏‏انتهاك التأمين.",
	"Disk full.": "‏‏القرص ممتلئ.",
	"End of file.": "‏‏نهاية الملف.",
	"Error getting the Clipboard Data!": "‏‏خطأ في إحضار بيانات الحافظة!",
	"No Printer Found @ page setup": "‏‏لا توجد طابعة @ إعداد الصفحة",
	"24-bit Bitmap (*.bmp;*.dib)": "صورة نقطية 24 بت (*.bmp,*.dib)",
	"All Files": "كافة الملفات",
	"Palette|*.pal|": "لوح ألوان|*.pal|",
	"OLE 2.0 was unable to start.": "‏‏فشل في تهيئة OLE 2.0. ",
	"Make sure that you are using the correct version of the OLE libraries.": "تأكد من أنك تستخدم الإصدارالصحيح لمكتبات OLE",
	"Resets the text be without any attributes.": "‏‏إعادة تعيين النص ليكون دون أية سمات.",
	"Sets or clears the text bold attribute.": "‏‏تعيين أو إلغاء سمة النص الأسود العريض.",
	"Sets or clears the text italic attribute.": "‏‏تعيين أو إلغاء سمة النص المائل.",
	"Selects the font used by the text.": "‏‏تحديد الخط المستخدَم للنص.",
	"Selects the point size of the text.": "‏‏تحديد حجم النقطة للنص.",
	"Sets or clears the text underline attribute.": "‏‏تعيين أو إلغاء سمة النص المسطّر.",
	"Shows or hides the tooltips.": "‏‏إظهار تعريفات الأدوات أو إخفاؤها.",
	"Show Paint Help.": "‏‏إظهار تعليمات الرسام.",
	"Sends a picture by using mail or fax.": "‏‏إرسال صورة عن طريق البريد أو الفاكس.",
	"Copies the selection to a file.": "‏‏نسخ التحديد إلى ملف.",
	"Pastes a file into the selection.": "‏‏لصق ملف إلى التحديد.",
	"Zooms the picture to 100%.": "‏‏تكبير/تصغير الصورة إلى 100%.",
	"Zooms the picture to 400%.": "‏‏تكبير/تصغير الصورة إلى 400%.",
	"Zooms the picture.": "‏‏تكبير/تصغير الصورة .",
	"Displays the entire picture.": "‏‏إظهار الصورة بالكامل.",
	"Shows or hides the thumbnail view of the picture.": "‏‏إظهار مصغرة الصورة أو إخفاؤها.",
	"Shows or hides the grid.": "‏‏إظهار الشبكة أو إخفاؤها.",
	"Shows or hides the text toolbar.": "‏‏إظهار شريط أدوات النص أو إخفاؤه.",
	"Flips or rotates the picture or a selection.": "‏‏عكس أو تدوير الصورة أو التحديد.",
	"Stretches or skews the picture or a selection.": "‏‏تمديد أو حرف الصورة أو التحديد.",
	"Inverts the colors of the picture or a selection.": "‏‏عكس ألوان الصورة أو التحديد.",
	"Changes the attributes of the picture.": "‏‏تغيير سمات الصورة.",
	"Clears the picture or selection.": "‏‏مسح الصورة أو التحديد.",
	"The font size must be a numeric value.": "‏‏يجب أن يكون حجم الخط قيمة عددية.",
	"Contains commands for working with the selected item(s).": "‏‏يتضمن أوامر للعمل بالعنصر أو العناصر المختارة.",
	"Contains commands for selecting and transferring items.": "‏‏يتضمن أوامر لتحديد العناصر أو نقلها.",
	"Contains commands for customizing this window.": "‏‏يتضمن أوامر لتخصيص هذا الإطار.",
	"Contains commands for manipulating pictures and setting attributes.": "‏‏يتضمن أوامر لمعالجة الصور وتعيين السمات.",
	"Contains commands for using custom colors and drawing options.": "‏‏يتضمن أوامر لاستخدام ألوان مخصصة وخيارات الرسم.",
	"Contains commands for displaying Help for and information about Paint.": "‏‏يتضمن أوامر لإظهار تعليمات ومعلومات حول الرسام.",
	"Cannot save file.": "‏‏غير قادر على حفظ الملف.",
	"Error removing temporary file.": "‏‏خطأ في إزالة الملف المؤقت.",
	"Get Colors": "‏‏إحضار الألوان",
	"Save Colors": "‏‏حفظ الألوان",
	"File last saved:": "‏‏آخر حفظ للملف:",
	"Not Available": "غير متوفر",
	"Size on disk:": "‏‏الحجم على القرص:",
	"%s bytes": "%s بايت",
	"Painting": "‏‏الرسم",
	"Bitmap": "‏‏صورة نقطية",
	"Fonts": "‏‏خطوط",
	"Tools": "‏‏أدوات",
	"All Picture Files": "‏‏كافة ملفات الصور",
	"For Help, click Help Topics on the Help Menu.": "‏‏للحصول على التعليمات؛ انقر \"مواضيع التعليمات\" في لائحة \"تعليمات\".",
	"Select an area on which to get Help.": "‏‏حدد المنطقة التي تريد تعليمات حولها.",
	"%1 in %2": "‏‏%1 في %2",
	"%1 - %2": "‏‏%1 - %2",
	"Creates a new document.": "‏‏إنشاء مستند جديد.",
	"Opens an existing document.": "‏‏فتح مستند موجود.",
	"Closes the active document.": "‏‏إغلاق المستند النشط.",
	"Saves the active document.": "‏‏حفظ المستند النشط.",
	"Saves the active document with a new name.": "‏‏حفظ المستند النشط باسم جديد.",
	"Changes the page layout.": "‏‏تغيير تخطيط الصفحة.",
	"Specifies the default printer setup.": "‏‏تحديد إعداد الطابعة الافتراضي.",
	"Prints the active document and sets printing options.": "‏‏طباعة المستند النشط وتعيين خيارات الطباعة.",
	"Displays full pages.": "‏‏إظهار صفحات كاملة.",
	"Opens this document.": "‏‏فتح هذا المستند.",
	"Deletes the selection.": "‏‏حذف التحديد.",
	"Erases everything.": "‏‏مسح كل شيء.",
	"Copies the selection and puts it on the Clipboard.": "‏‏نسخ التحديد ووضعه في الحافظة.",
	"Cuts the selection and puts it on the Clipboard.": "‏‏قص التحديد ووضعه في الحافظة.",
	"Finds the specified text.": "‏‏العثور على النص المعين.",
	"Inserts the contents of the Clipboard.": "‏‏إدراج محتويات الحافظة.",
	"Repeats the last action.": "‏‏إعادة آخر إجراء.",
	"Replaces specific text with different text.": "‏‏تبديل نص معين بنص آخر.",
	"Selects everything.": "‏‏تحديد كل شيء.",
	"Undoes the last action.": "‏‏التراجع عن آخر إجراء.",
	"Redoes the previously undone action.": "إعادة آخر إجراء تم التراجع عنه.",
	"Displays program information, version number, and copyright.": "إظهار معلومات البرنامج ورقم الإصدار وحقوق النشر.",
	"Quits Paint.": "إنهاء الرسام.",
	"Opens Paint Help.": "فتح تعليمات الرسام.",
	"Displays instructions about how to use Help.": "إظهار إرشادات حول استخدام التعليمات.",
	"Displays Help for areas you click on.": "إظهار تعليمات عن المناطق التي تنقر فوقها.",
	"Displays Help for the current task or command.": "إظهار تعليمات المهمة أو الأمر الحاليين.",
	"Centers this bitmap as the desktop wallpaper.": "توسيط هذه الصورة النقطية  كخلفية لسطح المكتب.",
	"Tiles this bitmap as the desktop wallpaper.": "تجانُب هذه الصورة النقطية كخلفية لسطح المكتب.",
	"Sends the selection using mail or fax.": "إرسال التحديد عن طريق البريد أو الفاكس.",
	"Prints the selection.": "طباعة التحديد.",
	"Shows or hides the thumbnail.": "إظهار المصغرات أو إخفاؤها.",
	"Shows Paint Help.": "إظهار تعليمات الرسام.",
	"Shows or hides the status bar.": "إظهار شريط الحالة أو إخفاؤه.",
	"Shows or hides the tool box.": "إظهار مربع الأدوات أو إخفاؤه.",
	"Shows or hides the color box.": "إظهار مربع الألوان أو إخفاؤه.",
	"Only a Far East font can be used for vertical editing.": "‏‏يمكن فقط استخدام خط من خطوط الشرق الأقصى للتحرير الشاقولي.",
	"Changes the window size.": "تغيير حجم الإطار.",
	"Changes the window position.": "تغيير موضع الإطار.",
	"Reduces the window to an icon.": "تصغير الإطار إلى رمز.",
	"Enlarges the window to full size.": "تكبير الإطار إلى الحجم الكامل.",
	"Switches to the next document window.": "تبديل إلى إطار المستند التالي.",
	"Switches to the previous document window.": "تبديل إلى إطار المستند السابق.",
	"Closes the active window and asks if you want to save changes.": "إغلاق الإطار النشط والسؤال عن الرغبة في حفظ التعديلات.",
	"Restores the window to normal size.": "ستعادة الإطار إلى الحجم العادي.",
	"Activates the task list.": "تنشيط قائمة المهام.",
	"All Files (*.*)": "كافة الملفات (*.*)",
	"Untitled": "بلا عنوان",
	"an unnamed file": "ملف غير مسمى",
	"&Hide": "إ&خفاء",
	"Hide": "إخفاء",
	"No error message is available.": "‏‏لا تتوفر رسالة خطأ.",
	"An unsupported operation was attempted.": "‏‏جرت محاولة للقيام بعملية غير معتمدة.",
	"A required resource was unavailable.": "‏‏هناك مورد مطلوب لم يكن متوفراً.",
	"Out of memory.": "‏‏نفدت الذاكرة.",
	"An unknown error has occurred.": "‏‏حدث خطأ غير معروف.",
	"on %1": "‏‏على %1",
	"&One Page": "‏‏&صفحة واحدة",
	"One Page": "‏‏صفحة واحدة",
	"&Two Page": "‏‏&صفحتان",
	"Two Page": "‏‏صفحتان",
	"Page %u": "‏‏صفحة %u",
	"Pages %u-%u": "الصفحات %u-%u",
	"Printer Files (*.prn)|*.prn|All Files (*.*)|*.*||": "ملفات الطابعة (*.prn)|*.prn|كافة الملفات (*.*)|*.*||",
	"Print to File": "طباعة إلى ملف",
	"to %1": "إلى %1",
	"&Update %1": "&تحديث %1",
	"Update %1": "تحديث %1",
	"E&xit && Return to %1": "&خروج وعودة إلى %1",
	"Exit && Return to %1": "خروج وعودة إلى %1",
	"Linked %s": "%s مرتبط",
	"Unknown Type": "‏‏نوع غير معروف",
	"Invalid filename.": "‏‏اسم ملف غير صالح.",
	"Failed to open document.": "‏‏فشل فتح المستند.",
	"Failed to save document.": "‏‏فشل حفظ المستند.",
	"Save changes to %1?": "‏‏حفظ التغييرات في %1؟",
	"Failed to create empty document.": "‏‏فشل إنشاء مستند فارغ.",
	"The file is too large to open.": "‏‏الملف كبير جداً بحيث لا يمكن فتحه.",
	"Could not start print job.": "‏‏تعذّر بدء مهمة الطباعة.",
	"Failed to launch help.": "‏‏فشل بدء تشغيل التعليمات.",
	"Internal application error.": "‏‏خطأ داخلي في التطبيق.",
	"Command failed.": "‏‏فشل الأمر.",
	"Insufficient memory to perform operation.": "‏‏لا تكفي الذاكرة لإنجاز العملية.",
	"System registry entries have been removed and the INI file (if any) was deleted.": "‏‏تمت إزالة إدخالات تسجيل النظام وحذف ملف INI (إن وجد).",
	"Not all of the system registry entries (or INI file) were removed.": "‏‏لم تتم إزالة كافة إدخالات تسجيل النظام (أو ملف INI).",
	"This program requires the file %s, which was not found on this system.": "‏‏يحتاج هذا البرنامج إلى الملف %s الذي لم يتم العثور عليه في النظام.",
	"This program is linked to the missing export %s in the file %s. This machine may have an incompatible version of %s.": "‏‏هذا البرنامج مرتبط بالتصدير المفقود %s في الملف %s. ربما يوجد في هذا الجهاز إصدار غير متوافق من %s.",
	"Please enter an integer.": "‏‏أدخل عدداً صحيحاً.",
	"Please enter a number.": "‏‏أدخل رقماً.",
	"Please enter an integer between %1 and %2.": "‏‏أدخل عدداً صحيحاً بين 1% و 2%.",
	"Please enter a number between %1 and %2.": "‏‏أدخل رقماً بين 1% و 2%.",
	"Please enter no more than %1 characters.": "‏‏أدخل ما لا يزيد عن 1% حرف.",
	"Please select a button.": "‏‏حدد زراً.",
	"Please enter an integer between 0 and 255.": "‏‏أدخل عدداً صحيحاً بين 0 و 255.",
	"Please enter a positive integer.": "‏‏أدخل عدداً صحيحاً موجباً.",
	"Please enter a date and/or time.": "‏‏أدخل تاريخاً أو وقتاً.",
	"Please enter a currency.": "‏‏أدخل عملة.",
	"Unexpected file format.": "‏‏تنسيق ملف غير متوقع.",
	"%1": "‏‏%1",
	"Cannot find this file.": "تعذر العثور على هذا الملف.",
	"Please verify that the correct path and file name are given.": "تحقق من أن المسار واسم الملف الصحيحين مدخلان.",
	"Destination disk drive is full.": "‏‏محرك القرص الوجهة ممتلئ.",
	"Unable to read from %1, it is opened by someone else.": "‏‏غير قادر على القراءة من 1%، لأنه مفتوح من قبل شخص آخر.",
	"Unable to write to %1, it is read-only or opened by someone else.": "‏‏غير قادر على الكتابة في %1، لأنه للقراءة فقط أو مفتوح من قبل شخص آخر.",
	"An unexpected error occurred while reading %1.": "‏‏حدث خطأ غير متوقع أثناء قراءة 1%.",
	"An unexpected error occurred while writing %1.": "‏‏حدث خطأ غير متوقع أثناء كتابة 1%.",
	"Unable to register document.": "غير قادر على تسجيل المستند.",
	"The document may already be open.": "قد يكون المستند مفتوحاً مسبقاً.",
	"Update %1 before proceeding?": "‏‏هل تريد تحديث %1 قبل المتابعة؟",
	"Could not update client.": "‏‏تعذّر تحديث العميل.",
	"Failed to register. ActiveX features may not work properly.": "‏‏فشل التسجيل. قد لا تعمل ميزات ActiveX بشكل صحيح.",
	"Failed to update the system registry.": "‏‏فشل تحديث تسجيل النظام.",
	"Please try using REGEDIT.": "الرجاء المحاولة باستخدام REGEDIT.",
	"Unable to read write-only property.": "‏‏تعذرت قراءة خاصية الكتابة فقط.",
	"Unable to write read-only property.": "‏‏تعذرت كتابة خاصية القراءة فقط.",
	"Unable to load mail system support.": "‏‏تعذر تحميل دعم نظام البريد.",
	"Mail system DLL is invalid.": "‏‏DLL نظام البريد غير صالح.",
	"Send Mail failed to send message.": "‏‏فشل 'إرسال البريد' في إرسال الرسالة.",
	"No error occurred.": "‏‏لم يحدث أي خطأ.",
	"An unknown error occurred while accessing %1.": "‏‏حدث خطأ غير معروف أثناء الوصول إلى %1.",
	"%1 was not found.": "‏‏تعذر العثور على %1.",
	"%1 contains an invalid path.": "‏‏يحتوي %1 على مسار غير صالح.",
	"%1 could not be opened because there are too many open files.": "‏‏تعذّر فتح %1 لوجود عدد كبير من الملفات المفتوحة.",
	"Access to %1 was denied.": "‏‏تم رفض الوصول إلى %1.",
	"An invalid file handle was associated with %1.": "‏‏اقتران مؤشر غير صالح للملف مع %1.",
	"%1 could not be removed because it is the current directory.": "‏‏تعذّرت إزالة %1 لأنه الدليل الحالي.",
	"%1 could not be created because the directory is full.": "‏‏تعذّر إنشاء %1 بسبب امتلاء الدليل.",
	"Seek failed on %1": "‏‏فشل إيجاد %1",
	"A hardware I/O error was reported while accessing %1.": "‏‏تم الإعلام عن خطأ إدخال/إخراج في الجهاز أثناء الوصول إلى %1.",
	"A sharing violation occurred while accessing %1.": "‏‏حدث انتهاك في المشاركة أثناء الوصول إلى %1.",
	"A locking violation occurred while accessing %1.": "‏‏حدث انتهاك في التأمين أثناء الوصول إلى %1.",
	"Disk full while accessing %1.": "‏‏امتلاء القرص أثناء الوصول إلى %1.",
	"An attempt was made to access %1 past its end.": "‏‏جرت محاولة للوصول إلى %1 مع تجاوز نهايته.",
	"An attempt was made to write to the reading %1.": "‏‏جرت محاولة للكتابة من %1 للقراءة.",
	"An attempt was made to read from the writing %1.": "‏‏جرت محاولة للقراءة من %1 للكتابة.",
	"%1 has a bad format.": "‏‏تنسيق غير صحيح في %1.",
	"%1 contained an unexpected object.": "‏‏احتوى %1 كائناً غير متوقع.",
	"%1 contains an incorrect schema.": "‏‏يحتوي %1 على مخطط غير صحيح.",
	"Selects a rectangular part of the picture to move, copy, or edit.": "‏‏تحديد جزء مستطيل من الصورة لنقله أو نسخه أو تعديله.",
	"Select": "تحديد",
	"Selects a free-form part of the picture to move, copy, or edit.": "‏‏تحديد جزء حر من الصورة لنقله أو نسخه أو تعديله.",
	"Free-Form Select": "تحديد حر",
	"Inserts text into the picture.": "‏‏إدراج نص في الصورة.",
	"Fills an area with the current drawing color.": "‏‏ملء منطقة بلون الرسم الحالي.",
	"Fill With Color": "ملء باللون",
	"Draws a straight line with the selected line width.": "‏‏رسم خط مستقيم بالعرض المحدد.",
	"Line": "خط",
	"Draws using an airbrush of the selected size.": "‏‏رسم باستخدام مرشة بالحجم المحدد.",
	"Airbrush": "مرشة",
	"Draws a curved line with the selected line width.": "‏‏رسم خط منحنٍ بالعرض المحدد.",
	"Curve": "منحن",
	"Draws a polygon with the selected fill style.": "‏‏رسم مضلع بنمط التعبئة المحدد.",
	"Polygon": "مضلع",
	"Draws a rounded rectangle with the selected fill style.": "‏‏رسم مستطيل مستدير الزوايا بنمط التعبئة المحدد.",
	"Rounded Rectangle": "مستطيل مستدير الزوايا",
	"Draws a free-form line one pixel wide.": "‏‏رسم خط حر بعرض نقطة واحدة.",
	"Pencil": "قلم",
	"Erases a portion of the picture, using the selected eraser shape.": "‏‏مسح جزء من الصورة باستخدام الشكل المحدد للممحاة.",
	"Eraser/Color Eraser": "ممحاة/ممحاة لون",
	"Changes the magnification.": "‏‏تغيير التكبير.",
	"Magnifier": "مكبر",
	"Picks up a color from the picture for drawing.": "‏‏انتقاء لون للرسم من الصورة.",
	"Pick Color": "انتقاء لون",
	"Draws using a brush with the selected shape and size.": "‏‏رسم باستخدام فرشاة بالشكل والحجم المحددين.",
	"Brush": "فرشاة",
	"Draws a rectangle with the selected fill style.": "‏‏رسم مستطيل بنمط التعبئة المحدد.",
	"Rectangle": "مستطيل",
	"Draws a filled rectangle.": "رسم مستطيل ممتلئ.",
	"Draws an ellipse with the selected fill style.": "رسم قطع ناقص بنمط التعبئة المحدد.",
	"Ellipse": "قطع ناقص",
	"Draws a filled ellipse.": "رسم قطع ناقص ممتلئ.",
	"Makes the current selection either opaque or transparent.": "‏‏جعل التحديد الحالي كامداً أو شفافاً.",
	"Creates a new color.": "‏‏إنشاء لون جديد.",
	"Uses a previously saved palette of colors.": "‏‏استخدام لوح ألوان محفوظ سابقاً.",
	"Saves the current palette of colors to a file.": "‏‏حفظ لوح الألوان الحالي في ملف.",
	"You must save the file before choosing it as Wallpaper.": "‏‏يجب حفظ الملف قبل اختياره كخلفية للشاشة.",
	"The selection is now larger than the bitmap.": "‏‏التحديد الآن أكبر من الصورة النقطية.",
	"Would you like the bitmap enlarged?": "هل ترغب في تكبير الصورة النقطية؟",
	"The image in the clipboard is larger than the bitmap.": "‏‏الصورة في الحافظة أكبر من الصورة النقطية.",
	"The file is not in the correct format.": "‏‏تنسيق الملف غير صحيح.",
	"Not enough room to paste text.": "‏‏لا يوجد حيز كاف للصق النص.",
	"Enlarge the text area and try again.": "كبِّر منطقة النص وحاول ثانيةً.",
	"Places the text.": "توضيع النص."
});
