//
// NOTE: This is a generated file! Don't edit it directly.
// Eventually community translation will be set up on some translation platform.
// 
// Generated with: npm run update-localization
//
loaded_localizations("ru", {
	"Attributes": "Атрибуты",
	"&Width:": "&Ширина:",
	"Width:": "Ширина:",
	"&Height:": "&Высота:",
	"Height:": "Высота:",
	"Units": "Единицы",
	"&Inches": "Д&юймы",
	"Inches": "Дюймы",
	"C&m": "С&м",
	"Cm": "См",
	"&Pixels": "Т&очки",
	"Pixels": "Точки",
	"Colors": "Палитра",
	"&Black and white": "&Черно-белая",
	"Black and white": "Черно-белая",
	"Co&lors": "Цв&етная",
	"Transparency": "Прозрачность",
	"Use &Transparent background color": "Использовать про&зрачный цвет фона",
	"Use Transparent background color": "Использовать прозрачный цвет фона",
	"Select &Color": "Выбор цве&та",
	"Select Color": "Выбор цвета",
	"OK": "ОК",
	"Cancel": "Отмена",
	"&Default": "По умо&лчанию",
	"Default": "По умолчанию",
	"Custom Zoom": "Масштаб",
	"Current zoom:": "Текущий масштаб:",
	"Zoom to": "Варианты",
	"Flip and Rotate": "Отражение и поворот",
	"Flip or rotate": "Действие",
	"&Flip horizontal": "Отразить с&лева направо",
	"Flip horizontal": "Отразить слева направо",
	"Flip &vertical": "Отразить с&верху вниз",
	"Flip vertical": "Отразить сверху вниз",
	"&Rotate by angle": "&Повернуть на угол",
	"Rotate by angle": "Повернуть на угол",
	"Stretch and Skew": "Растяжение и наклон",
	"Stretch": "Растянуть",
	"&Horizontal:": "По &горизонтали:",
	"Horizontal:": "По горизонтали:",
	"&Vertical:": "По &вертикали:",
	"Vertical:": "По вертикали:",
	"Skew": "Наклонить",
	"H&orizontal:": "По г&оризонтали:",
	"Degrees": "градусов",
	"V&ertical:": "По в&ертикали:",
	"Color Table": "Таблица цветов",
	"New": "Новый документ",
	"&New ": "&Новый",
	"New ": "Новый",
	"&Help": "&Справка",
	"Help": "Справка",
	"Printing": "Печать",
	"on the": "на",
	"&Print": "&Печать",
	"Print": "Печать",
	"&Next Page": "&Следующая",
	"Next Page": "Следующая",
	"Pre&v Page": "Пр&едыдущая",
	"Prev Page": "Предыдущая",
	"Zoom &In": "&Увеличить",
	"Zoom In": "Увеличить",
	"Zoom &Out": "У&меньшить",
	"Zoom Out": "Уменьшить",
	"&Close": "&Закрыть",
	"Close": "Закрыть",
	"Grid Settings": "Настройка сетки",
	"                  ": "                                         ",
	"&Pixel Grid": "Ш&аг в 1 точку",
	"Pixel Grid": "Шаг в 1 точку",
	"&Tile Grid": "&Параметры сетки",
	"Tile Grid": "Параметры сетки",
	"pixels": "точек",
	"H&eight:": "&Высота ячейки:",
	"Text": "Текст",
	"Undo": "Отменить",
	"Cut": "Вырезать",
	"Copy": "Копировать",
	"Paste": "Вставить",
	"Clear Selection": "Очистить выделение",
	"Select All": "Выделить все",
	"Text Toolbar": "Панель атрибутов текста",
	"Selection": "Выделение",
	"Cu&t": "&Вырезать",
	"&Copy": "&Копировать",
	"&Paste": "Вст&авить",
	"C&lear Selection": "О&чистить выделение",
	"Select &All": "Выделить в&се",
	"C&opy To": "Ко&пировать в файл",
	"Copy To": "Копирование в файл",
	"Paste &From": "Вставить из &файла",
	"Paste From": "Вставка из файла",
	"Flip/&Rotate": "&Отразить/повернуть",
	"Flip/Rotate": "Отразить/повернуть",
	"&Stretch/Skew": "&Растянуть/наклонить",
	"Stretch/Skew": "Растянуть/наклонить",
	"&Invert Colors": "О&братить цвета",
	"Invert Colors": "Обратить цвета",
	"Thumbnail": "Эскиз",
	"&File": "&Файл",
	"File": "Файл",
	"&New": "Созд&ать",
	"&Open": "&Открыть",
	"Open": "Открыть",
	"&Save": "&Сохранить",
	"Save": "Сохранить",
	"Save &As": "Сохранить &как",
	"Save As": "Сохранить как",
	"Print Pre&view": "Пред&варительный просмотр",
	"Print Preview": "Предварительный просмотр",
	"Page Se&tup": "&Макет страницы",
	"Page Setup": "Макет страницы",
	"S&end": "Отправит&ь",
	"Send": "Отправить",
	"Set As &Wallpaper (Tiled)": "&Замостить рабочий стол Windows",
	"Set As Wallpaper (Tiled)": "Замостить рабочий стол Windows",
	"Set As Wa&llpaper (Centered)": "В ц&ентр рабочего стола Windows",
	"Set As Wallpaper (Centered)": "В центр рабочего стола Windows",
	"Recent File": "Последний файл",
	"E&xit": "В&ыход",
	"Exit": "Выход",
	"&Edit": "&Правка",
	"Edit": "Правка",
	"&Undo": "&Отменить",
	"&Repeat": "Пов&торить",
	"Repeat": "Повторить",
	"&View": "&Вид",
	"View": "Вид",
	"&Tool Box": "Набор &инструментов",
	"Tool Box": "Набор инструментов",
	"&Color Box": "Па&литра",
	"Color Box": "Палитра",
	"&Status Bar": "&Строка состояния",
	"Status Bar": "Строка состояния",
	"T&ext Toolbar": "Панель &атрибутов текста",
	"&Zoom": "Мас&штаб",
	"Zoom": "Масштаб",
	"&Normal Size": "&Обычный",
	"Normal Size": "Обычный",
	"&Large Size": "&Крупный",
	"Large Size": "Крупный",
	"C&ustom": "&Другой",
	"Custom": "Другой",
	"Show &Grid": "Показать се&тку",
	"Show Grid": "Показать сетку",
	"Show T&humbnail": "&Показать эскиз",
	"Show Thumbnail": "Показать эскиз",
	"&View Bitmap": "&Просмотреть рисунок",
	"View Bitmap": "Просмотреть рисунок",
	"&Image": "&Рисунок",
	"Image": "Рисунок",
	"&Flip/Rotate": "&Отразить/повернуть",
	"&Attributes": "&Атрибуты",
	"&Clear Image": "О&чистить",
	"Clear Image": "Очистить",
	"&Draw Opaque": "&Непрозрачный фон",
	"Draw Opaque": "Непрозрачный фон",
	"&Colors": "П&алитра",
	"&Edit Colors": "&Изменить палитру",
	"Edit Colors": "Изменение палитры",
	"&Help Topics": "&Вызов справки",
	"Help Topics": "Вызов справки",
	"&About Paint": "&О программе",
	"About Paint": "О программе",
	"&Update": "О&бновить",
	"Update": "Обновить",
	"Save Copy &As": "Сохранить копию &как",
	"Save Copy As": "Сохранить копию как",
	"untitled": "Безымянный",
	"Bitmap Image": "Точечный рисунок",
	"Bitmap Files (*.bmp)": "Точечные рисунки (*.bmp)",
	"PCX Files": "Файлы PCX",
	"Icon Files": "Файлы значков (*.ico)",
	"Monochrome Bitmap (*.bmp;*.dib)": "Монохромный рисунок (*.bmp;*.dib)",
	"16 Color Bitmap (*.bmp;*.dib)": "16-цветный рисунок (*.bmp;*.dib)",
	"256 Color Bitmap (*.bmp;*.dib)": "256-цветный рисунок (*.bmp;*.dib)",
	"Paint cannot open this file.": "Не удается открыть файл.",
	"Paint cannot read this file.": "Не удается прочитать файл.",
	"This file is read-only.": "Файл доступен только для чтения.",
	"To save your changes, use a different filename.": "Чтобы сохранить его, укажите другое имя.",
	"This file is already open.": "Файл уже открыт.",
	"This is not a valid .PCS file.": "Файл не является файлом .PCS.",
	"This file is open for editing and cannot be overwritten.": "Файл открыт для редактирования и не может быть заменен.",
	"Use a different filename to save your changes.": "Сохраните изменения под другим именем.",
	"This is not a valid bitmap file, or its format is not currently supported.": "Файл не является правильным точечным рисунком (BMP), или этот формат не поддерживается.",
	"This is not a valid icon.": "Файл не является значком (ICO).",
	"This is not a valid cursor.": "Файл не является указателем (CUR).",
	"Save was interrupted, so your file has not been saved.": "Операция сохранения была прервана. Файл не сохранен.",
	"You cannot save to a read-only file.": "Нельзя сохранить файл, доступный только для чтения.",
	"Use a different file name.": "Укажите другое имя.",
	"This file is already in use.": "Файл уже используется.",
	"Close the program, and then try again.": "Закройте программу и повторите попытку.",
	"Paint cannot save this file.": "Не удается сохранить файл.",
	"Paint cannot save to the same filename with a different file type.": "Нельзя использовать то же самое имя для файла другого типа.",
	"The grid spacing must be an integer between %d and %d.": "Шаг сетки должен быть целым числом в пределах между %d и %d.",
	"There is not enough memory or resources to complete operation.": "Недостаточно памяти или ресурсов для выполнения операции.",
	"Close some programs, and then try again.": "Закройте несколько программ и повторите попытку.",
	"Low on memory or resources.": "Недостаточно памяти или ресурсов.",
	"Group error.": "Групповая ошибка.",
	"Paint was unable to print your document. Please make sure you have sufficient disk space and that your printer is working correctly.": "Не удалось напечатать документ. Проверьте, достаточно ли свободного места на диске и правильно ли настроена программа управления печатью.",
	"Saving into this format may cause some loss of color information.": "Сохранение документа в данном формате может привести к частичной потере данных о цвете. ",
	"Do you want to continue?": "Подтверждаете выполнение сохранения?",
	"Converting to black and white cannot be undone.  This action affects the current file and may cause some loss of color information.": "Преобразование цветного рисунка в черно-белый вызовет потерю сведений о цвете, после чего восстановление исходного рисунка будет невозможно.",
	"Bitmaps must be greater than one pixel on a side.": "Каждый из размеров рисунка должен быть не менее 1 точку.",
	"Generic error.": "Ошибка.",
	"File not found.": "Файл не найден.",
	"Bad path.": "Неверно указан путь.",
	"Too many open files.": "Открыто слишком много файлов.",
	"Access denied.": "Нет доступа.",
	"Invalid file.": "Неправильный файл.",
	"Remove current folder.": "Удаление текущей папки.",
	"Folder full.": "Папка заполнена.",
	"Bad seek.": "Неудачный поиск.",
	"Hard IO error.": "Ошибка ввода/вывода.",
	"Sharing violation.": "Попытка доступа к занятому файлу.",
	"Lock violation.": "Нарушение блокировки.",
	"Disk full.": "Диск заполнен.",
	"End of file.": "Конец файла.",
	"Error getting the Clipboard Data!": "Ошибка при чтении данных из буфера обмена.",
	"No Printer Found @ page setup": "Принтер не найден @",
	"24-bit Bitmap (*.bmp;*.dib)": "24-разрядный рисунок (*.bmp;*.dib)",
	"All Files": "Все файлы",
	"Palette|*.pal|": "Палитра|*.pal|",
	"OLE 2.0 was unable to start.": "Не удалось запустить OLE 2.0.",
	"Make sure that you are using the correct version of the OLE libraries.": "Проверьте, установлена ли правильная версия библиотек OLE.",
	"Resets the text be without any attributes.": "Сброс атрибутов текста.",
	"Sets or clears the text bold attribute.": "Использование или отмена полужирного шрифта.",
	"Sets or clears the text italic attribute.": "Использование или отмена курсива.",
	"Selects the font used by the text.": "Выбор шрифта для надписи.",
	"Selects the point size of the text.": "Выбор размера символов надписи.",
	"Sets or clears the text underline attribute.": "Превращение шрифта в подчеркнутый и обратно.",
	"Shows or hides the tooltips.": "Вывод и скрытие всплывающих подсказок.",
	"Show Paint Help.": "Вызов справки по Paint.",
	"Sends a picture by using mail or fax.": "Отправка рисунка по электронной почте или факсу.",
	"Copies the selection to a file.": "Копирование выделенного фрагмента в файл.",
	"Pastes a file into the selection.": "Вставка содержимого буфера обмена.",
	"Zooms the picture to 100%.": "Возврат к масштабу 100%.",
	"Zooms the picture to 400%.": "Установка масштаба 400%.",
	"Zooms the picture.": "Установка масштаба.",
	"Displays the entire picture.": "Просмотр рисунка целиком.",
	"Shows or hides the thumbnail view of the picture.": "Вывод и скрытие окна просмотра в масштабе 100%.",
	"Shows or hides the grid.": "Вывод и скрытие сетки.",
	"Shows or hides the text toolbar.": "Вывод и скрытие панели атрибутов текста.",
	"Flips or rotates the picture or a selection.": "Отражение и поворот рисунка целиком или его фрагмента.",
	"Stretches or skews the picture or a selection.": "Растяжение и наклон рисунка целиком или его фрагмента.",
	"Inverts the colors of the picture or a selection.": "Обращение цветов для рисунка целиком или его фрагмента.",
	"Changes the attributes of the picture.": "Изменение параметров рисунка.",
	"Clears the picture or selection.": "Очистка рисунка целиком или его фрагмента.",
	"The font size must be a numeric value.": "Размер шрифта должен быть числом.",
	"Contains commands for working with the selected item(s).": "Команды для работы с выбранными объектами.",
	"Contains commands for selecting and transferring items.": "Команды выделения и перемещения объектов.",
	"Contains commands for customizing this window.": "Команды управления окном.",
	"Contains commands for manipulating pictures and setting attributes.": "Команды работы с рисунками и установки атрибутов.",
	"Contains commands for using custom colors and drawing options.": "Команды работы с палитрами и выбора параметров настройки.",
	"Contains commands for displaying Help for and information about Paint.": "Команды вывода справки и сведений о программе.",
	"Cannot save file.": "Не удается сохранить файл.",
	"Error removing temporary file.": "Ошибка при удалении временного файла.",
	"Get Colors": "Загрузка палитры",
	"Save Colors": "Сохранение палитры",
	"File last saved:": "Файл сохранен:",
	"Not Available": "нет данных",
	"Size on disk:": "Размер файла:",
	"%s bytes": "%s байт",
	"Painting": "Рисование",
	"Fonts": "Шрифты",
	"Tools": "Панель",
	"All Picture Files": "Все файлы рисунков",
	"For Help, click Help Topics on the Help Menu.": "Для получения справки выберите команду \"Вызов справки\" из меню \"Справка\".",
	"Select an area on which to get Help.": "Выберите интересующий объект.",
	"%1 in %2": "%1 в %2",
	"Creates a new document.": "Создание нового документа.",
	"Opens an existing document.": "Открытие существующего документа.",
	"Closes the active document.": "Закрытие активного документа.",
	"Saves the active document.": "Сохранение активного документа.",
	"Saves the active document with a new name.": "Сохранение активного документа под другим именем.",
	"Changes the page layout.": "Изменение макета страницы.",
	"Specifies the default printer setup.": "Выбор принтера и параметров печати",
	"Prints the active document and sets printing options.": "Печать активного документа и выбор параметров печати.",
	"Displays full pages.": "Отображает страницы целиком.",
	"Opens this document.": "Открытие этого документа.",
	"Deletes the selection.": "Удаление выделенного фрагмента.",
	"Erases everything.": "Удаление рисунка целиком.",
	"Copies the selection and puts it on the Clipboard.": "Копирование выделенного фрагмента в буфер обмена.",
	"Cuts the selection and puts it on the Clipboard.": "Удаление выделенного фрагмента в буфер обмена.",
	"Finds the specified text.": "Поиск заданного текста.",
	"Inserts the contents of the Clipboard.": "Вставка в документ содержимого буфера обмена.",
	"Repeats the last action.": "Повтор последнего действия.",
	"Replaces specific text with different text.": "Замена одного текста другим.",
	"Selects everything.": "Выделение всего документа целиком.",
	"Undoes the last action.": "Отмена последнего выполненного действия.",
	"Redoes the previously undone action.": "Возврат результатов отмененного действия.",
	"Displays program information, version number, and copyright.": "Вывод сведений о программе, ее версии и авторских правах.",
	"Quits Paint.": "Завершение работы с приложением.",
	"Opens Paint Help.": "Открытие справочной системы Paint.",
	"Displays instructions about how to use Help.": "Вывод инструкций по использованию встроенной справки.",
	"Displays Help for areas you click on.": "Вывод контекстной справки по выбранным объектам.",
	"Displays Help for the current task or command.": "Вывод справки по текущему действию или команде.",
	"Centers this bitmap as the desktop wallpaper.": "Размещение рисунка в центре рабочего стола.",
	"Tiles this bitmap as the desktop wallpaper.": "Заполнение рабочего стола копиями рисунка.",
	"Sends the selection using mail or fax.": "Отправка выделенного фрагмента по электронной почте или факсу.",
	"Prints the selection.": "Печать выделенного фрагмента.",
	"Shows or hides the thumbnail.": "Вывод и скрытие окна просмотра в масштабе 100%.",
	"Shows Paint Help.": "Открытие справочной системы Paint.",
	"Shows or hides the status bar.": "Вывод и скрытие строки состояния.",
	"Shows or hides the tool box.": "Вывод и скрытие набора инструментов.",
	"Shows or hides the color box.": "Вывод и скрытие цветовой палитры.",
	"Only a Far East font can be used for vertical editing.": "Для вертикального написания текста можно использовать только шрифты Дальнего Востока.",
	"Changes the window size.": "Изменение размеров окна.",
	"Changes the window position.": "Изменение положения окна.",
	"Reduces the window to an icon.": "Свертывание окна в значок.",
	"Enlarges the window to full size.": "Развертывание окна до максимального размера.",
	"Switches to the next document window.": "Переход в окно следующего документа.",
	"Switches to the previous document window.": "Переход в окно предыдущего документа.",
	"Closes the active window and asks if you want to save changes.": "Закрытие активного окна с запросом на сохранение документов.",
	"Restores the window to normal size.": "Восстановление исходных размеров окна.",
	"Activates the task list.": "Активизация списка задач.",
	"All Files (*.*)": "Все файлы (*.*)",
	"Untitled": "Безымянный",
	"an unnamed file": "безымянный файл",
	"&Hide": "&Скрыть",
	"Hide": "Скрыть",
	"No error message is available.": "Отсутствует сообщение об ошибке.",
	"An unsupported operation was attempted.": "Попытка выполнить недопустимую операцию.",
	"A required resource was unavailable.": "Запрашиваемый ресурс недоступен.",
	"Out of memory.": "Недостаточно памяти.",
	"An unknown error has occurred.": "Неопознанная ошибка.",
	"on %1": "на \"%1\"",
	"&One Page": "&Одна страница",
	"One Page": "Одна страница",
	"&Two Page": "&Две страницы",
	"Two Page": "Две страницы",
	"Page %u": "Страница %u",
	"Pages %u-%u": "Страницы %u-%u",
	"Printer Files (*.prn)|*.prn|All Files (*.*)|*.*||": "Файлы печати (*.prn)|*.prn|Все файлы (*.*)|*.*||",
	"Print to File": "Печать в файл",
	"to %1": "в %1",
	"&Update %1": "&Обновить %1",
	"Update %1": "Обновить %1",
	"E&xit && Return to %1": "В&ыход и возврат к %1",
	"Exit && Return to %1": "Выход и возврат к %1",
	"Linked %s": "Связанный %s",
	"Unknown Type": "Неизвестный тип",
	"Invalid filename.": "Неправильное имя файла.",
	"Failed to open document.": "Не удалось открыть документ.",
	"Failed to save document.": "Не удалось сохранить документ.",
	"Save changes to %1?": "Сохранить изменения в файле \"%1\"?",
	"Failed to create empty document.": "Не удалось создать новый документ.",
	"The file is too large to open.": "Не удалось открыть слишком большой файл.",
	"Could not start print job.": "Не удалось запустить задание на печать.",
	"Failed to launch help.": "Не удалось вызвать встроенную справку.",
	"Internal application error.": "Внутренняя ошибка приложения.",
	"Command failed.": "Ошибка при выполнении команды.",
	"Insufficient memory to perform operation.": "Недостаточно памяти для выполнения операции.",
	"System registry entries have been removed and the INI file (if any) was deleted.": "Элементы системного реестра были удалены, и INI-файл (если таковой существовал) также был удален.",
	"Not all of the system registry entries (or INI file) were removed.": "Не все элементы системного реестра (или INI-файлы) были удалены.",
	"This program requires the file %s, which was not found on this system.": "Этой программе нужен файл \"%s\", который не найден на этом компьютере.",
	"This program is linked to the missing export %s in the file %s. This machine may have an incompatible version of %s.": "Программа связана с отсутствующей функцией %s в файле \"%s\". На компьютере может быть установлена несовместимая версия %s.",
	"Please enter an integer.": "Введите целое число.",
	"Please enter a number.": "Введите числовое значение.",
	"Please enter an integer between %1 and %2.": "Введите целое число в диапазоне от %1 до %2.",
	"Please enter a number between %1 and %2.": "Введите числовое значение в диапазоне от %1 до %2.",
	"Please enter no more than %1 characters.": "Введите не более %1 знаков.",
	"Please select a button.": "Нажмите одну из кнопок.",
	"Please enter an integer between 0 and 255.": "Введите целое число в диапазоне от 0 до 255.",
	"Please enter a positive integer.": "Введите положительное целое число.",
	"Please enter a date and/or time.": "Введите дату и время.",
	"Please enter a currency.": "Введите денежную единицу.",
	"Unexpected file format.": "Непредусмотренный формат файла.",
	"Cannot find this file.": "Не удается найти файл.",
	"Please verify that the correct path and file name are given.": "Проверьте правильность указания пути и имени файла.",
	"Destination disk drive is full.": "Диск назначения заполнен.",
	"Unable to read from %1, it is opened by someone else.": "Не удается прочесть данные из файла \"%1\", он открыт другим пользователем.",
	"Unable to write to %1, it is read-only or opened by someone else.": "Не удается записать данные в файл \"%1\", он предназначен только для чтения или открыт другим пользователем.",
	"An unexpected error occurred while reading %1.": "Непредусмотренная ошибка при чтении файла \"%1\".",
	"An unexpected error occurred while writing %1.": "Непредусмотренная ошибка при записи файла \"%1\".",
	"Unable to register document.": "Не удается зарегистрировать документ.",
	"The document may already be open.": "Возможно, он уже открыт.",
	"Update %1 before proceeding?": "Обновить %1 перед продолжением?",
	"Could not update client.": "Не удается обновить клиента.",
	"Failed to register. ActiveX features may not work properly.": "Не удалось зарегистрировать. Возможны неполадки при использовании ActiveX.",
	"Failed to update the system registry.": "Не удалось обновить системный реестр.",
	"Please try using REGEDIT.": "Попробуйте использовать программу REGEDIT.",
	"Unable to read write-only property.": "Не удалось прочесть - свойство только для записи.",
	"Unable to write read-only property.": "Не удалось записать - свойство только для чтения.",
	"Unable to load mail system support.": "Не удалось загрузить поддержку почтовой системы.",
	"Mail system DLL is invalid.": "Неправильная библиотека DLL почтовой системы.",
	"Send Mail failed to send message.": "Команда \"Отправить\" не смогла отправить сообщение.",
	"No error occurred.": "Нет ошибки.",
	"An unknown error occurred while accessing %1.": "Произошла неизвестная ошибка во время доступа к \"%1\".",
	"%1 was not found.": "Файл \"%1\" не найден.",
	"%1 contains an invalid path.": "\"%1\" содержит неправильный путь.",
	"%1 could not be opened because there are too many open files.": "Не удается открыть \"%1\", поскольку уже открыто слишком много файлов.",
	"Access to %1 was denied.": "Нет доступа к \"%1\".",
	"An invalid file handle was associated with %1.": "С файлом \"%1\" связан неправильный дескриптор файла.",
	"%1 could not be removed because it is the current directory.": "Не удается удалить \"%1\", поскольку это текущая папка.",
	"%1 could not be created because the directory is full.": "Невозможно создать \"%1\", поскольку данная папка заполнена.",
	"Seek failed on %1": "Ошибка поиска в \"%1\"",
	"A hardware I/O error was reported while accessing %1.": "Аппаратная ошибка ввода/вывода при доступе к \"%1\".",
	"A sharing violation occurred while accessing %1.": "Нарушение совместного использования при доступе к \"%1\".",
	"A locking violation occurred while accessing %1.": "Нарушение блокировки при доступе к \"%1\".",
	"Disk full while accessing %1.": "Нет места на диске при доступе к \"%1\".",
	"An attempt was made to access %1 past its end.": "Попытка доступа к \"%1\" за пределами файла.",
	"An attempt was made to write to the reading %1.": "Попытка выполнить операцию записи при чтении \"%1\".",
	"An attempt was made to read from the writing %1.": "Попытка выполнить операцию чтения при записи \"%1\".",
	"%1 has a bad format.": "\"%1\" имеет неправильный формат.",
	"%1 contained an unexpected object.": "\"%1\" содержит неподдерживаемый объект.",
	"%1 contains an incorrect schema.": "\"%1\" содержит неправильную схему.",
	"Selects a rectangular part of the picture to move, copy, or edit.": "Выделение прямоугольного элемента рисунка.",
	"Select": "Выделение",
	"Selects a free-form part of the picture to move, copy, or edit.": "Выделение произвольного фрагмента рисунка.",
	"Free-Form Select": "Выделение произвольной области",
	"Inserts text into the picture.": "Создание надписи.",
	"Fills an area with the current drawing color.": "Заполнение области одним из двух текущих цветов.",
	"Fill With Color": "Заливка",
	"Draws a straight line with the selected line width.": "Проведение прямой линии выбранной толщины.",
	"Line": "Линия",
	"Draws using an airbrush of the selected size.": "Рисование с помощью выбранного распылителя.",
	"Airbrush": "Распылитель",
	"Draws a curved line with the selected line width.": "Проведение кривой линии выбранной толщины.",
	"Curve": "Кривая",
	"Draws a polygon with the selected fill style.": "Рисование многоугольника с заданным типом заливки.",
	"Polygon": "Многоугольник",
	"Draws a rounded rectangle with the selected fill style.": "Рисование скругленного прямоугольника с заданным типом заливки.",
	"Rounded Rectangle": "Скругленный прямоугольник",
	"Draws a free-form line one pixel wide.": "Проведение произвольной линии толщиной в 1 точку.",
	"Pencil": "Карандаш",
	"Erases a portion of the picture, using the selected eraser shape.": "Стирание части рисунка с помощью ластика выбранного типа.",
	"Eraser/Color Eraser": "Ластик/Цветной ластик",
	"Changes the magnification.": "Изменение масштаба.",
	"Magnifier": "Масштаб",
	"Picks up a color from the picture for drawing.": "Выбор текущих цветов из имеющихся на рисунке.",
	"Pick Color": "Выбор цветов",
	"Draws using a brush with the selected shape and size.": "Рисование с помощью кисти выбранных формы и размера.",
	"Brush": "Кисть",
	"Draws a rectangle with the selected fill style.": "Рисование прямоугольника с заданным типом заливки.",
	"Rectangle": "Прямоугольник",
	"Draws a filled rectangle.": "Рисование заполненного прямоугольника.",
	"Draws an ellipse with the selected fill style.": "Рисование эллипса с заданным типом заливки.",
	"Ellipse": "Эллипс",
	"Draws a filled ellipse.": "Рисование заполненного эллипса.",
	"Makes the current selection either opaque or transparent.": "Превращение выделенного фрагмента в прозрачный либо непрозрачный.",
	"Creates a new color.": "Создание нового цвета.",
	"Uses a previously saved palette of colors.": "Загрузка созданной ранее палитры.",
	"Saves the current palette of colors to a file.": "Сохранение палитры в файле.",
	"You must save the file before choosing it as Wallpaper.": "Для размещение рисунка на рабочем столе его следует сохранить.",
	"The selection is now larger than the bitmap.": "Выделенный фрагмент превосходит рисунок по размерам.",
	"Would you like the bitmap enlarged?": "Увеличить рисунок?",
	"The image in the clipboard is larger than the bitmap.": "Фрагмент, находящийся в буфере, превосходит рисунок по размерам.",
	"The file is not in the correct format.": "Файл имеет неверный формат.",
	"Not enough room to paste text.": "Недостаточно места для вставки текста.",
	"Enlarge the text area and try again.": "Увеличьте надпись и повторите попытку.",
	"Places the text.": "Размещение текста."
});
