//
// NOTE: This is a generated file! Don't edit it directly.
// Eventually community translation will be set up on some translation platform.
// 
// Generated with: npm run update-localization
//
loaded_localizations("ja", {
	"Attributes": "キャンバスの色とサイズ",
	"MS Shell Dlg": "MS UI Gothic",
	"&Width:": "幅(&W):",
	"Width:": "幅:",
	"&Height:": "高さ(&H):",
	"Height:": "高さ:",
	"Units": "単位",
	"&Inches": "インチ(&I)",
	"Inches": "インチ",
	"C&m": "センチ(&M)",
	"Cm": "センチ",
	"&Pixels": "ピクセル(&P)",
	"Pixels": "ピクセル",
	"Colors": "色",
	"&Black and white": "白黒(&B)",
	"Black and white": "白黒",
	"Co&lors": "カラー(&L)",
	"Transparency": "透明フィルム",
	"Use &Transparent background color": "背景色に透明を使用(&T)",
	"Use Transparent background color": "背景色に透明を使用",
	"Select &Color": "色の選択(&C)",
	"Select Color": "色の選択",
	"Cancel": "キャンセル",
	"&Default": "既定値(&D)",
	"Default": "既定値",
	"Custom Zoom": "拡大率の指定",
	"Current zoom:": "現在の拡大率:",
	"Zoom to": "拡大率",
	"&100%": "100%(&1)",
	"100%": "100%",
	"&200%": "200%(&2)",
	"200%": "200%",
	"&400%": "400%(&4)",
	"400%": "400%",
	"&600%": "600%(&6)",
	"600%": "600%",
	"&800%": "800%(&8)",
	"800%": "800%",
	"Flip and Rotate": "反転と回転",
	"Flip or rotate": "反転/回転",
	"&Flip horizontal": "水平方向(&F)",
	"Flip horizontal": "水平方向",
	"Flip &vertical": "垂直方向(&V)",
	"Flip vertical": "垂直方向",
	"&Rotate by angle": "角度を指定(&R)",
	"Rotate by angle": "角度を指定",
	"&90°": "90 度(&9)",
	"90°": "90 度",
	"&180°": "180 度(&1)",
	"180°": "180 度",
	"&270°": "270 度(&2)",
	"270°": "270 度",
	"Stretch and Skew": "伸縮と傾き",
	"Stretch": "伸縮",
	"&Horizontal:": "水平方向(&H):",
	"Horizontal:": "水平方向:",
	"&Vertical:": "垂直方向(&V):",
	"Vertical:": "垂直方向:",
	"Skew": "傾き",
	"H&orizontal:": "水平方向(&O):",
	"Degrees": "度",
	"V&ertical:": "垂直方向(&E):",
	"Color Table": "カラー テーブル",
	"New": "新規作成",
	"&New ": "新規(&N) ",
	"New ": "新規 ",
	"&Help": "ヘルプ(&H)",
	"Help": "ヘルプ",
	"Printing": "印刷中",
	"on the": "を",
	"&Print": "印刷(&P)",
	"Print": "印刷",
	"&Next Page": "次のページ(&N)",
	"Next Page": "次のページ",
	"Pre&v Page": "前のページ(&V)",
	"Prev Page": "前のページ",
	"Zoom &In": "拡大(&I)",
	"Zoom In": "拡大",
	"Zoom &Out": "縮小(&O)",
	"Zoom Out": "縮小",
	"&Close": "閉じる(&C)",
	"Close": "閉じる",
	"Grid Settings": "グリッドの設定",
	"&Pixel Grid": "点で表示(&P)",
	"Pixel Grid": "点で表示",
	"&Tile Grid": "線で表示(&T)",
	"Tile Grid": "線で表示",
	"pixels": "ピクセル",
	"H&eight:": "高さ(&E):",
	"Text": "テキスト",
	"Undo": "元に戻す",
	"Cut": "切り取り",
	"Copy": "コピー",
	"Paste": "貼り付け",
	"Clear Selection": "選択範囲のクリア",
	"Select All": "すべて選択",
	"Text Toolbar": "書式バー",
	"Selection": "選択",
	"Cu&t": "切り取り(&T)",
	"&Copy": "コピー(&C)",
	"&Paste": "貼り付け(&P)",
	"C&lear Selection": "選択範囲のクリア(&L)",
	"Select &All": "すべて選択(&A)",
	"C&opy To": "ファイルへコピー(&O)",
	"Copy To": "コピー先",
	"Paste &From": "ファイルから貼り付け(&F)",
	"Paste From": "ファイルから貼り付け",
	"Flip/&Rotate": "反転と回転(&R)",
	"Flip/Rotate": "反転と回転",
	"&Stretch/Skew": "伸縮と傾き(&S)",
	"Stretch/Skew": "伸縮と傾き",
	"&Invert Colors": "色の反転(&I)",
	"Invert Colors": "色の反転",
	"Thumbnail": "実寸表示",
	"&File": "ファイル(&F)",
	"File": "ファイル",
	"&New": "新規作成(&N)",
	"&Open": "開く(&O)",
	"Open": "開く",
	"&Save": "上書き保存(&S)",
	"Save": "上書き保存",
	"Save &As": "名前を付けて保存(&A)",
	"Save As": "名前を付けて保存",
	"Print Pre&view": "印刷プレビュー(&V)",
	"Print Preview": "印刷プレビュー",
	"Page Se&tup": "ページ設定(&T)",
	"Page Setup": "ページ設定",
	"S&end": "送信(&E)",
	"Send": "送信",
	"Set As &Wallpaper (Tiled)": "壁紙に設定 (並べて表示) (&W)",
	"Set As Wallpaper (Tiled)": "壁紙に設定 (並べて表示)",
	"Set As Wa&llpaper (Centered)": "壁紙に設定 (中央に表示) (&L)",
	"Set As Wallpaper (Centered)": "壁紙に設定 (中央に表示)",
	"Recent File": "最新のファイル",
	"E&xit": "ペイントの終了(&X)",
	"Exit": "ペイントの終了",
	"&Edit": "編集(&E)",
	"Edit": "編集",
	"&Undo": "元に戻す(&U)",
	"&Repeat": "やり直し(&R)",
	"Repeat": "やり直し",
	"&View": "表示(&V)",
	"View": "表示",
	"&Tool Box": "ツール ボックス(&T)",
	"Tool Box": "ツール ボックス",
	"&Color Box": "カラー ボックス(&C)",
	"Color Box": "カラー ボックス",
	"&Status Bar": "ステータス バー(&S)",
	"Status Bar": "ステータス バー",
	"T&ext Toolbar": "書式バー(&E)",
	"&Zoom": "拡大(&Z)",
	"Zoom": "拡大",
	"&Normal Size": "標準に戻す(&N)",
	"Normal Size": "標準に戻す",
	"&Large Size": "拡大する(&L)",
	"Large Size": "拡大する",
	"C&ustom": "拡大率の指定(&U)",
	"Custom": "拡大率の指定",
	"Show &Grid": "グリッドを表示(&G)",
	"Show Grid": "グリッドを表示",
	"Show T&humbnail": "実寸表示(&H)",
	"Show Thumbnail": "実寸表示",
	"&View Bitmap": "ビットマップ表示(&V)",
	"View Bitmap": "ビットマップ表示",
	"&Image": "変形(&I)",
	"Image": "変形",
	"&Flip/Rotate": "反転と回転(&F)",
	"&Attributes": "キャンバスの色とサイズ(&A)",
	"&Clear Image": "すべてクリア(&C)",
	"Clear Image": "すべてクリア",
	"Ctrl+Shft+N": "Ctrl+Shift+N",
	"&Draw Opaque": "背景色を不透明にする(&D)",
	"Draw Opaque": "背景色を不透明にする",
	"&Colors": "色(&C)",
	"&Edit Colors": "色の編集(&E)",
	"Edit Colors": "色の編集",
	"&Help Topics": "トピックの検索(&H)",
	"Help Topics": "トピックの検索",
	"&About Paint": "バージョン情報(&A)",
	"About Paint": "バージョン情報",
	"&Update": "更新(&U)",
	"Update": "更新",
	"Save Copy &As": "名前を付けて保存(&A)",
	"Save Copy As": "名前を付けて保存",
	"Paint": "ペイント",
	"untitled": "無題",
	"Bitmap Image": "ビットマップの絵",
	"Bitmap Files (*.bmp)": "ビットマップ ファイル (*.bmp)",
	"PCX Files": "PCX ファイル",
	"Icon Files": "アイコン ファイル",
	"Monochrome Bitmap (*.bmp;*.dib)": "白黒ビットマップ (*.bmp;*.dib)",
	"16 Color Bitmap (*.bmp;*.dib)": "16 色ビットマップ (*.bmp;*.dib)",
	"256 Color Bitmap (*.bmp;*.dib)": "256 色ビットマップ (*.bmp;*.dib)",
	"Paint cannot open this file.": "このファイルは開けません。",
	"Paint cannot read this file.": "このファイルは読み取れません。",
	"This file is read-only.": "このファイルは読み取り専用です。",
	"To save your changes, use a different filename.": "変更を保存するには、別のファイル名を使ってください。",
	"This file is already open.": "このファイルは既に開かれています。",
	"This is not a valid .PCS file.": "この PCS ファイルは無効です。",
	"This file is open for editing and cannot be overwritten.": "このファイルには上書きできません。",
	"Use a different filename to save your changes.": "別のファイル名で保存してください。",
	"This is not a valid bitmap file, or its format is not currently supported.": "このビットマップ ファイルは無効であるか、または現在サポートされていない形式です。",
	"This is not a valid icon.": "このアイコンは無効です。",
	"This is not a valid cursor.": "このポインタは無効です。",
	"Save was interrupted, so your file has not been saved.": "保存が中断されたので、ファイルは保存されませんでした。",
	"You cannot save to a read-only file.": "読み取り専用ファイルには保存できません。",
	"Use a different file name.": "別のファイル名にしてください。",
	"This file is already in use.": "このファイルは既に使われています。",
	"Close the program, and then try again.": "アプリケーションを終了して、やり直してください。",
	"Paint cannot save this file.": "このファイルは保存できません。",
	"Paint cannot save to the same filename with a different file type.": "ファイルの種類が違うため、同じファイル名では保存できません。",
	"The grid spacing must be an integer between %d and %d.": "グリッドの間隔には、%d から %d の間の整数を指定してください。",
	"There is not enough memory or resources to complete operation.": "メモリまたはリソースが足りないため、作業を完了できません。",
	"Close some programs, and then try again.": "いくつかのアプリケーションを終了して、もう一度やり直してください。",
	"Low on memory or resources.": "メモリまたはリソースが足りません。",
	"Group error.": "グループ エラーです。",
	"Paint was unable to print your document. Please make sure you have sufficient disk space and that your printer is working correctly.": "ドキュメントを印刷できませんでした。十分なディスク領域があることと、プリンタが正しく動作していることを確認してください。",
	"Saving into this format may cause some loss of color information.": "この形式に保存すると、カラー情報のいくつかが失われる可能性があります。",
	"Do you want to continue?": "続行しますか?",
	"Converting to black and white cannot be undone.  This action affects the current file and may cause some loss of color information.": "白黒への変換は元に戻せません。この操作を行うと現在のファイルに影響を及ぼし、色の情報が失われる可能性があります。",
	"Bitmaps must be greater than one pixel on a side.": "ビットマップは、1 辺あたり 1 ピクセルより大きくなければなりません。",
	"Generic error.": "エラーです。",
	"File not found.": "ファイルが見つかりません。",
	"Bad path.": "パスが違っています。",
	"Too many open files.": "開いているファイルの数が多すぎます。",
	"Access denied.": "アクセスは拒否されました。",
	"Invalid file.": "無効なファイルです。",
	"Remove current folder.": "現在のフォルダを削除します。",
	"Folder full.": "フォルダがいっぱいです。",
	"Bad seek.": "シーク エラーです。",
	"Hard IO error.": "ハードウェア I/O エラーです。",
	"Sharing violation.": "共有違反です。",
	"Lock violation.": "ロック違反です。",
	"Disk full.": "ディスクがいっぱいです。",
	"End of file.": "ファイルの終わりです。",
	"Error getting the Clipboard Data!": "クリップボードのエラーです。",
	"No Printer Found @ page setup": "プリンタが見つかりません。",
	"24-bit Bitmap (*.bmp;*.dib)": "24 ビット ビットマップ (*.bmp;*.dib)",
	"All Files": "すべてのファイル",
	"Palette|*.pal|": "パレット|*.pal|",
	"untitled.pal": "無題.pal",
	"OLE 2.0 was unable to start.": "OLE 2.0 を起動できませんでした。",
	"Make sure that you are using the correct version of the OLE libraries.": "OLE ライブラリのバージョンが合っているかどうか確認してください。",
	"Resets the text be without any attributes.": "テキストを元の状態に戻します。",
	"Sets or clears the text bold attribute.": "テキストの太字設定を切り替えます。",
	"Sets or clears the text italic attribute.": "テキストの斜体設定を切り替えます。",
	"Selects the font used by the text.": "テキストで使うフォントを選びます。",
	"Selects the point size of the text.": "テキストで使うフォント サイズを選びます。",
	"Sets or clears the text underline attribute.": "テキストの下線設定を切り替えます。",
	"Shows or hides the tooltips.": "ツールのヒントの表示/非表示を切り替えます。",
	"Show Paint Help.": "ペイントのヘルプを表示します。",
	"Sends a picture by using mail or fax.": "メールまたは FAX で絵を送信します。",
	"Copies the selection to a file.": "選択範囲をファイルにコピーします。",
	"Pastes a file into the selection.": "選択範囲にファイルを貼り付けます。",
	"Zooms the picture to 100%.": "絵を 100% に戻します。",
	"Zooms the picture to 400%.": "絵を 4 倍に拡大します。",
	"Zooms the picture.": "絵を拡大します。",
	"Displays the entire picture.": "絵を画面全体に表示します。",
	"Shows or hides the thumbnail view of the picture.": "実寸の表示/非表示を切り替えます。",
	"Shows or hides the grid.": "グリッドの表示/非表示を切り替えます。",
	"Shows or hides the text toolbar.": "書式バーの表示/非表示を切り替えます。",
	"Flips or rotates the picture or a selection.": "絵または選択範囲を反転/回転させます。",
	"Stretches or skews the picture or a selection.": "絵または選択範囲を伸縮/傾斜させます。",
	"Inverts the colors of the picture or a selection.": "絵または選択範囲の色を反転させます。",
	"Changes the attributes of the picture.": "キャンバスの色とサイズを変更します。",
	"Clears the picture or selection.": "絵または選択範囲をクリアします。",
	"The font size must be a numeric value.": "フォント サイズは数字で指定してください。",
	"Contains commands for working with the selected item(s).": "選択したオブジェクトを操作するコマンドです。",
	"Contains commands for selecting and transferring items.": "オブジェクトを選択したり転送するコマンドです。",
	"Contains commands for customizing this window.": "このウィンドウを設定するコマンドです。",
	"Contains commands for manipulating pictures and setting attributes.": "絵を操作したりキャンバスの設定を変えるコマンドです。",
	"Contains commands for using custom colors and drawing options.": "色やオプションを設定するコマンドです。",
	"Contains commands for displaying Help for and information about Paint.": "ペイントのヘルプやバージョン情報を表示するコマンドです。",
	"Cannot save file.": "ファイルを保存できません。",
	"Error removing temporary file.": "一時ファイルを削除できません。",
	"Get Colors": "パレットの交換",
	"Save Colors": "パレットの保存",
	"File last saved:": "ファイルの最終保存:",
	"Not Available": "利用できません",
	"Size on disk:": "ディスク上のサイズ:",
	"%s bytes": "%s バイト",
	"Painting": "絵",
	"Bitmap": "ビットマップ",
	"Fonts": "書式設定",
	"Tools": "ツール",
	"All Picture Files": "すべてのピクチャ ファイル",
	"For Help, click Help Topics on the Help Menu.": "ヘルプを見るには、[ヘルプ] メニューの [トピックの検索] を選んでください。",
	"Select an area on which to get Help.": "ヘルプを見る項目を選んでください。",
	"%1 in %2": "%2 の %1",
	"Creates a new document.": "新しいファイルを作成します。",
	"Opens an existing document.": "既存のファイルを開きます。",
	"Closes the active document.": "現在のファイルを閉じます。",
	"Saves the active document.": "現在のファイルを保存します。",
	"Saves the active document with a new name.": "現在のファイルを新しい名前で保存します。",
	"Changes the page layout.": "ページ レイアウトの設定を変更します。",
	"Specifies the default printer setup.": "通常使うプリンタの設定を指定します。",
	"Prints the active document and sets printing options.": "印刷オプションを設定し、現在のファイルを印刷します。",
	"Displays full pages.": "ページ全体を表示します。",
	"Opens this document.": "このファイルを開きます。",
	"Deletes the selection.": "選択範囲を削除します。",
	"Erases everything.": "すべてクリアします。",
	"Copies the selection and puts it on the Clipboard.": "選択範囲をクリップボードにコピーします。",
	"Cuts the selection and puts it on the Clipboard.": "選択範囲を切り取ってクリップボードに移動します。",
	"Finds the specified text.": "指定された文字列を検索します。",
	"Inserts the contents of the Clipboard.": "クリップボードの内容を挿入します。",
	"Repeats the last action.": "直前に行った操作をやり直します。",
	"Replaces specific text with different text.": "指定された文字列をほかの文字列に置き換えます。",
	"Selects everything.": "すべての範囲を選択します。",
	"Undoes the last action.": "直前に行った操作を取り消します。",
	"Redoes the previously undone action.": "取り消した操作をやり直します。",
	"Displays program information, version number, and copyright.": "プログラム情報、バージョン、著作権を表示します。",
	"Quits Paint.": "ペイントを終了します。",
	"Opens Paint Help.": "ペイントのヘルプを開きます。",
	"Displays instructions about how to use Help.": "ヘルプの使い方を表示します。",
	"Displays Help for areas you click on.": "クリックした項目のヘルプを表示します。",
	"Displays Help for the current task or command.": "ヘルプ トピックを表示します。",
	"Centers this bitmap as the desktop wallpaper.": "このビットマップを壁紙として使用し、中央に表示します。",
	"Tiles this bitmap as the desktop wallpaper.": "このビットマップを壁紙として使用し、並べて表示します。",
	"Sends the selection using mail or fax.": "メールまたは FAX で選択範囲を送信します。",
	"Prints the selection.": "選択範囲を印刷します。",
	"Shows or hides the thumbnail.": "実寸の表示/非表示を切り替えます。",
	"Shows Paint Help.": "ペイントのヘルプを表示します。",
	"Shows or hides the status bar.": "ステータス バーの表示/非表示を切り替えます。",
	"Shows or hides the tool box.": "ツール ボックスの表示/非表示を切り替えます。",
	"Shows or hides the color box.": "カラー ボックスの表示/非表示を切り替えます。",
	"Only a Far East font can be used for vertical editing.": "極東アジア言語のフォントを使用する場合のみ縦書き編集が可能です。",
	"Changes the window size.": "このウィンドウのサイズを変更します。",
	"Changes the window position.": "このウィンドウを画面の別の位置に移動します。",
	"Reduces the window to an icon.": "このウィンドウを最小化します。",
	"Enlarges the window to full size.": "このウィンドウを画面いっぱいに拡大します。",
	"Switches to the next document window.": "次のドキュメント ウィンドウに切り替えます。",
	"Switches to the previous document window.": "前のドキュメント ウィンドウに切り替えます。",
	"Closes the active window and asks if you want to save changes.": "変更の保存を確認してから、アクティブ ウィンドウを閉じます。",
	"Restores the window to normal size.": "ウィンドウを通常の大きさに戻します。",
	"Activates the task list.": "タクス リストを表示します。",
	"All Files (*.*)": "すべてのファイル (*.*)",
	"Untitled": "無題",
	"an unnamed file": "無題のファイル",
	"&Hide": "非表示(&H)",
	"Hide": "非表示",
	"No error message is available.": "エラー メッセージはありません。",
	"An unsupported operation was attempted.": "サポートされていない操作を実行しました。",
	"A required resource was unavailable.": "必要なリソースを利用できませんでした。",
	"Out of memory.": "メモリが不足しています。",
	"An unknown error has occurred.": "不明なエラーが発生しました。",
	"on %1": "%1 へ出力中",
	"&One Page": "1 ページ(&O)",
	"One Page": "1 ページ",
	"&Two Page": "2 ページ(&T)",
	"Two Page": "2 ページ",
	"Page %u": "ページ %u",
	"Pages %u-%u": "ページ %u-%u",
	"Printer Files (*.prn)|*.prn|All Files (*.*)|*.*||": "プリンタ ファイル (*.prn)|*.prn|すべてのファイル (*.*)|*.*||",
	"Print to File": "ファイルへ出力",
	"to %1": "%1 へ",
	"&Update %1": "%1 を更新(&U)",
	"Update %1": "%1 を更新",
	"E&xit && Return to %1": "終了して %1 に戻る(&X)",
	"Exit && Return to %1": "終了して %1 に戻る",
	"Linked %s": "%s をリンクしました。",
	"Unknown Type": "不明な型です。",
	"Invalid filename.": "無効なファイル名です。",
	"Failed to open document.": "ドキュメントを開くことに失敗しました。",
	"Failed to save document.": "ドキュメントの保存に失敗しました。",
	"Save changes to %1?": "%1 への変更を保存しますか?",
	"Failed to create empty document.": "空のドキュメントの作成に失敗しました。",
	"The file is too large to open.": "ファイルが大きすぎて開けません。",
	"Could not start print job.": "印刷ジョブを開始できませんでした。",
	"Failed to launch help.": "ヘルプの起動に失敗しました。",
	"Internal application error.": "アプリケーションの内部エラーです。",
	"Command failed.": "コマンドの実行に失敗しました。",
	"Insufficient memory to perform operation.": "メモリ不足のため実行できません。",
	"System registry entries have been removed and the INI file (if any) was deleted.": "システム レジストリ エントリは削除されています。また、INI ファイルがある場合は、 INI ファイルも削除されました。",
	"Not all of the system registry entries (or INI file) were removed.": "一部のシステム レジストリ エントリ (または INI ファイル) は削除されませんでした。",
	"This program requires the file %s, which was not found on this system.": "このプログラムにはファイル %s が必要ですがこのシステム上に見つかりませんでした。",
	"This program is linked to the missing export %s in the file %s. This machine may have an incompatible version of %s.": "このプログラムは欠落エクスポート %s にファイル %s 内でリンクされています。このコンピュータは互換性のないバージョンの %s を含んでいる可能性があります。",
	"Please enter an integer.": "整数を入力してください。",
	"Please enter a number.": "数字を入力してください。",
	"Please enter an integer between %1 and %2.": "%1 から %2 までの整数を入力してください。",
	"Please enter a number between %1 and %2.": "%1 から %2 までの数字を入力してください。",
	"Please enter no more than %1 characters.": "%1 文字以内で入力してください。",
	"Please select a button.": "ボタンを選択してください。",
	"Please enter an integer between 0 and 255.": "0 から 255 までの整数を入力してください。",
	"Please enter a positive integer.": "正の整数を入力してください。",
	"Please enter a date and/or time.": "日付/時刻を入力してください。",
	"Please enter a currency.": "通貨型を入力してください。",
	"Unexpected file format.": "予期しないファイル形式です。",
	"Cannot find this file.": "このファイルが見つかりません。",
	"Please verify that the correct path and file name are given.": "パスとファイル名が正しいかどうか確認してください。",
	"Destination disk drive is full.": "受け側のディスク ドライブがいっぱいです。",
	"Unable to read from %1, it is opened by someone else.": "%1 は使用中のため、読み取れません。",
	"Unable to write to %1, it is read-only or opened by someone else.": "%1 は使用中、または読み取り専用のため、書き込めません。",
	"An unexpected error occurred while reading %1.": "%1 の読み取り中に予期しないエラーが発生しました。",
	"An unexpected error occurred while writing %1.": "%1 の書き込み中に予期しないエラーが発生しました。",
	"Unable to register document.": "ドキュメントを登録できません。",
	"The document may already be open.": "ドキュメントは既に開かれている可能性があります。",
	"Update %1 before proceeding?": "先に %1 を更新しますか?",
	"Could not update client.": "クライアントを更新できませんでした。",
	"Failed to register. ActiveX features may not work properly.": "登録に失敗しました。ActiveX の機能は正しく動作しない可能性があります。",
	"Failed to update the system registry.": "システム レジストリの更新に失敗しました。",
	"Please try using REGEDIT.": "REGEDIT を使って更新してください。",
	"Unable to read write-only property.": "書き込み専用プロパティからは読み取れません。",
	"Unable to write read-only property.": "読み取り専用プロパティには書き込めません。",
	"Unable to load mail system support.": "メール システム サポートを読み込めません。",
	"Mail system DLL is invalid.": "メール システム DLL が無効です。",
	"Send Mail failed to send message.": "メールの送信に失敗しました。",
	"No error occurred.": "エラーはありませんでした。",
	"An unknown error occurred while accessing %1.": "%1 へのアクセス中に不明なエラーが発生しました。",
	"%1 was not found.": "%1 が見つかりませんでした。",
	"%1 contains an invalid path.": "%1 には無効なパスが含まれています。",
	"%1 could not be opened because there are too many open files.": "開いているファイルが多すぎるため、%1 を開けませんでした。",
	"Access to %1 was denied.": "%1 へのアクセスは拒否されました。",
	"An invalid file handle was associated with %1.": "%1 へ無効なファイル ハンドルが関連付けられていました。",
	"%1 could not be removed because it is the current directory.": "現在のディレクトリ %1 は削除できませんでした。",
	"%1 could not be created because the directory is full.": " %1 を作成できませんでした。そのディレクトリはいっぱいです。",
	"Seek failed on %1": "%1 のシークに失敗しました",
	"A hardware I/O error was reported while accessing %1.": "%1 へのアクセス中にハードウェア I/O エラーが報告されました。",
	"A sharing violation occurred while accessing %1.": "%1 へのアクセス中に共有違反が発生しました。",
	"A locking violation occurred while accessing %1.": "%1 へのアクセス中にロック違反が発生しました。",
	"Disk full while accessing %1.": "%1 へのアクセス中にディスクがいっぱいになりました。",
	"An attempt was made to access %1 past its end.": "%1 の末尾以降にアクセスしようとしました。",
	"An attempt was made to write to the reading %1.": "%1 の読み取り中に書き込もうとしました。",
	"An attempt was made to read from the writing %1.": "%1 へ書き込み中に読み取ろうとしました。",
	"%1 has a bad format.": "%1 の形式が正しくありません。",
	"%1 contained an unexpected object.": "%1 は予期しないオブジェクトを含んでいます。",
	"%1 contains an incorrect schema.": "%1 は不正なスキーマを含んでいます。",
	"Selects a rectangular part of the picture to move, copy, or edit.": "絵の一部を四角形で選択して、移動、コピー、または編集します。",
	"Select": "選択",
	"Selects a free-form part of the picture to move, copy, or edit.": "絵の一部を選択して、移動、コピー、または編集します。",
	"Free-Form Select": "自由選択",
	"Inserts text into the picture.": "絵の中にテキストを貼り付けます。",
	"Fills an area with the current drawing color.": "現在の色で領域を塗りつぶします。",
	"Fill With Color": "塗りつぶし",
	"Draws a straight line with the selected line width.": "選択された太さの線で、直線を引きます。",
	"Line": "直線",
	"Draws using an airbrush of the selected size.": "選択されたサイズのエアブラシで描きます。",
	"Airbrush": "エアブラシ",
	"Draws a curved line with the selected line width.": "選択された太さの線で、曲線を引きます。",
	"Curve": "曲線",
	"Draws a polygon with the selected fill style.": "選択された塗りつぶし形式で、多角形を描きます。",
	"Polygon": "多角形",
	"Draws a rounded rectangle with the selected fill style.": "選択された塗りつぶし形式で、角の丸い四角形を描きます。",
	"Rounded Rectangle": "角丸四角形",
	"Draws a free-form line one pixel wide.": "1 ピクセル幅の線を引きます。",
	"Pencil": "鉛筆",
	"Erases a portion of the picture, using the selected eraser shape.": "選択された消しゴムで、絵の一部を消します。",
	"Eraser/Color Eraser": "消しゴム/カラー消しゴム",
	"Changes the magnification.": "拡大または縮小します。",
	"Magnifier": "拡大と縮小",
	"Picks up a color from the picture for drawing.": "絵の中から、色を選択します。",
	"Pick Color": "色の選択",
	"Draws using a brush with the selected shape and size.": "選択された形や幅のブラシで描きます。",
	"Brush": "ブラシ",
	"Draws a rectangle with the selected fill style.": "選択された塗りつぶし形式で、四角形を描きます。",
	"Rectangle": "四角形",
	"Draws a filled rectangle.": "塗りつぶし四角形を描きます。",
	"Draws an ellipse with the selected fill style.": "選択された塗りつぶし形式で、楕円を描きます。",
	"Ellipse": "楕円",
	"Draws a filled ellipse.": "塗りつぶし楕円を描きます。",
	"Makes the current selection either opaque or transparent.": "選択範囲の背景色を不透明または透明にします。",
	"Creates a new color.": "新しい色を作成します。",
	"Uses a previously saved palette of colors.": "以前に保存したパレットを使用します。",
	"Saves the current palette of colors to a file.": "現在のパレットをファイルに保存します。",
	"You must save the file before choosing it as Wallpaper.": "壁紙に指定する前に、ファイルを保存しなければなりません。",
	"The selection is now larger than the bitmap.": "選択範囲はビットマップより大きいです。",
	"Would you like the bitmap enlarged?": "ビットマップを大きくしますか?",
	"The image in the clipboard is larger than the bitmap.": "クリップボードの絵はビットマップより大きいです。",
	"The file is not in the correct format.": "ファイルの形式が正しくありません。",
	"Not enough room to paste text.": "テキストを貼り付けるスペースがありません。",
	"Enlarge the text area and try again.": "テキスト領域を広げて、やり直してください。",
	"Places the text.": "テキストを配置します。"
});
