//
// NOTE: This is a generated file! Don't edit it directly.
// Eventually community translation will be set up on some translation platform.
// 
// Generated with: npm run update-localization
//
loaded_localizations("no", {
	"Attributes": "Attributter",
	"&Width:": "&Bredde:",
	"Width:": "Bredde:",
	"&Height:": "&Høyde:",
	"Height:": "Høyde:",
	"Units": "Enheter",
	"&Inches": "&Tommer",
	"Inches": "Tommer",
	"C&m": "&Cm",
	"Cm": "Cm",
	"&Pixels": "&Piksler",
	"Pixels": "Piksler",
	"Colors": "Farger",
	"&Black and white": "S&vart-hvitt",
	"Black and white": "Svart-hvitt",
	"Co&lors": "&Farger",
	"Transparency": "Gjennomsiktighet",
	"Use &Transparent background color": "Br&uk gjennomsiktig bakgrunnsfarge",
	"Use Transparent background color": "Bruk gjennomsiktig bakgrunnsfarge",
	"Select &Color": "V&elg farge",
	"Select Color": "Velg farge",
	"Cancel": "Avbryt",
	"&Default": "&Standard",
	"Default": "Standard",
	"Custom Zoom": "Egendefinert zoom",
	"Current zoom:": "Gjeldende zoom:",
	"Zoom to": "Zoom til",
	"&100%": "&100 %",
	"100%": "100 %",
	"&200%": "&200 %",
	"200%": "200 %",
	"&400%": "&400 %",
	"400%": "400 %",
	"&600%": "&600 %",
	"600%": "600 %",
	"&800%": "&800 %",
	"800%": "800 %",
	"Flip and Rotate": "Vend og roter",
	"Flip or rotate": "Vend eller roter",
	"&Flip horizontal": "&Vend vannrett",
	"Flip horizontal": "Vend vannrett",
	"Flip &vertical": "V&end loddrett",
	"Flip vertical": "Vend loddrett",
	"&Rotate by angle": "&Roter",
	"Rotate by angle": "Roter",
	"Stretch and Skew": "Strekk og forskyv bilde",
	"Stretch": "Strekk",
	"&Horizontal:": "&Vannrett:",
	"Horizontal:": "Vannrett:",
	"%": " %",
	"&Vertical:": "&Loddrett:",
	"Vertical:": "Loddrett:",
	"Skew": "Forskyv",
	"H&orizontal:": "V&annrett:",
	"Degrees": "grader",
	"V&ertical:": "L&oddrett:",
	"Color Table": "Fargetabell",
	"New": "Ny",
	"&New ": "&Ny ",
	"New ": "Ny ",
	"&Help": "&Hjelp",
	"Help": "Hjelp",
	"Printing": "Skriver ut",
	"on the": "på",
	"&Print": "Skriv &ut",
	"Print": "Skriv ut",
	"&Next Page": "&Neste side",
	"Next Page": "Neste side",
	"Pre&v Page": "&Forrige side",
	"Prev Page": "Forrige side",
	"Zoom &In": "&Zoom inn",
	"Zoom In": "Zoom inn",
	"Zoom &Out": "Z&oom ut",
	"Zoom Out": "Zoom ut",
	"&Close": "&Lukk",
	"Close": "Lukk",
	"Grid Settings": "Innstillinger for rutenett",
	"&Pixel Grid": "&Pikselrutenett",
	"Pixel Grid": "Pikselrutenett",
	"&Tile Grid": "&Rutenett",
	"Tile Grid": "Rutenett",
	"pixels": "piksler",
	"H&eight:": "&Høyde:",
	"Text": "Tekst",
	"Undo": "Angre",
	"Cut": "Klipp ut",
	"Copy": "Kopier",
	"Paste": "Lim inn",
	"Clear Selection": "Fjern utvalg",
	"Select All": "Merk alt",
	"Text Toolbar": "Tekstverktøylinje",
	"Selection": "Merket område",
	"Cu&t": "Klipp &ut",
	"&Copy": "&Kopier",
	"&Paste": "&Lim inn",
	"C&lear Selection": "&Fjern utvalg",
	"Select &All": "&Merk alt",
	"C&opy To": "K&opier til",
	"Copy To": "Kopier til",
	"Paste &From": "Lim &inn fra",
	"Paste From": "Lim inn fra",
	"Flip/&Rotate": "&Vend/roter",
	"Flip/Rotate": "Vend/roter",
	"&Stretch/Skew": "&Strekk/forskyv",
	"Stretch/Skew": "Strekk/forskyv",
	"&Invert Colors": "Inv&erter farger",
	"Invert Colors": "Inverter farger",
	"Thumbnail": "Miniatyr",
	"&File": "&Fil",
	"File": "Fil",
	"&New": "&Ny",
	"&Open": "Å&pne",
	"Open": "Åpne",
	"&Save": "La&gre",
	"Save": "Lagre",
	"Save &As": "Lagre &som",
	"Save As": "Lagre som",
	"Print Pre&view": "Forhånds&visning",
	"Print Preview": "Forhåndsvisning",
	"Page Se&tup": "Utskr&iftsformat",
	"Page Setup": "Utskriftsformat",
	"S&end": "Sen&d",
	"Send": "Send",
	"Set As &Wallpaper (Tiled)": "&Bruk som bakgrunn (side ved side)",
	"Set As Wallpaper (Tiled)": "Bruk som bakgrunn (side ved side)",
	"Set As Wa&llpaper (Centered)": "B&ruk som bakgrunn (midtstilt)",
	"Set As Wallpaper (Centered)": "Bruk som bakgrunn (midtstilt)",
	"Recent File": "Nylig brukt fil",
	"E&xit": "&Avslutt",
	"Exit": "Avslutt",
	"&Edit": "&Rediger",
	"Edit": "Rediger",
	"&Undo": "&Angre",
	"&Repeat": "&Gjenta",
	"Repeat": "Gjenta",
	"Del": "DEL",
	"&View": "&Vis",
	"View": "Vis",
	"&Tool Box": "&Verktøykasse",
	"Tool Box": "Verktøykasse",
	"&Color Box": "&Fargeboks",
	"Color Box": "Fargeboks",
	"&Status Bar": "Stat&uslinje",
	"Status Bar": "Statuslinje",
	"T&ext Toolbar": "&Tekstverktøylinje",
	"&Normal Size": "&Normal størrelse",
	"Normal Size": "Normal størrelse",
	"&Large Size": "&Stor størrelse",
	"Large Size": "Stor størrelse",
	"C&ustom": "&Egendefinert",
	"Custom": "Egendefinert",
	"Show &Grid": "&Vis rutenett",
	"Show Grid": "Vis rutenett",
	"Show T&humbnail": "Vis &miniatyr",
	"Show Thumbnail": "Vis miniatyr",
	"&View Bitmap": "&Punktgrafikk",
	"View Bitmap": "Punktgrafikk",
	"Ctrl+F": "Ctrl+H",
	"&Image": "&Bilde",
	"Image": "Bilde",
	"&Flip/Rotate": "&Vend/roter",
	"&Attributes": "&Attributter",
	"&Clear Image": "&Fjern bilde",
	"Clear Image": "Fjern bilde",
	"Ctrl+Shft+N": "Ctrl+Skift+N",
	"&Draw Opaque": "&Tegn ugjennomsiktig",
	"Draw Opaque": "Tegn ugjennomsiktig",
	"&Colors": "F&arger",
	"&Edit Colors": "&Rediger farger",
	"Edit Colors": "Rediger farger",
	"&Help Topics": "&Emner i Hjelp",
	"Help Topics": "Emner i Hjelp",
	"&About Paint": "&Om Paint",
	"About Paint": "Om Paint",
	"&Update": "&Oppdater",
	"Update": "Oppdater",
	"Save Copy &As": "Lagre kopi &som",
	"Save Copy As": "Lagre kopi som",
	"untitled": "Uten navn",
	"Bitmap Image": "Punktgrafikk",
	"Bitmap Files (*.bmp)": "Punktgrafikkfiler (bmp)",
	"Paint.Picture": "Paint.Bilde",
	"PCX Files": "PCX-filer",
	"Icon Files": "Ikonfiler",
	"Monochrome Bitmap (*.bmp;*.dib)": "Monokrom punktgrafikk (*.bmp, *.dib)",
	"16 Color Bitmap (*.bmp;*.dib)": "16-fargers punktgrafikk (*.bmp, *.dib)",
	"256 Color Bitmap (*.bmp;*.dib)": "256-fargers punktgrafikk (*.bmp, *.dib)",
	"Paint cannot open this file.": "Kan ikke åpne denne filen.",
	"Paint cannot read this file.": "Kan ikke lese denne filen.",
	"This file is read-only.": "Filen er skrivebeskyttet.",
	"To save your changes, use a different filename.": "Bruk et annet filnavn for å lagre endringene.",
	"This file is already open.": "Filen er allerede åpen.",
	"This is not a valid .PCS file.": "Dette er ikke en gyldig PCS-fil.",
	"This file is open for editing and cannot be overwritten.": "Denne filen er åpen for redigering, og kan ikke overskrives.",
	"Use a different filename to save your changes.": "Bruk et annet filnavn for å lagre endringene.",
	"This is not a valid bitmap file, or its format is not currently supported.": "Dette er ikke en gyldig punktgrafikkfil, eller formatet på filen støttes ikke.",
	"This is not a valid icon.": "Dette er ikke et gyldig ikon.",
	"This is not a valid cursor.": "Dette er ikke en gyldig markør.",
	"Save was interrupted, so your file has not been saved.": "Lagringen ble avbrutt. Filen ble ikke lagret.",
	"You cannot save to a read-only file.": "Du kan ikke lagre en skrivebeskyttet fil.",
	"Use a different file name.": "Bruk et annet filnavn.",
	"This file is already in use.": "Filen er allerede i bruk.",
	"Close the program, and then try again.": "Lukk programmet, og prøv på nytt.",
	"Paint cannot save this file.": "Kan ikke lagre denne filen.",
	"Paint cannot save to the same filename with a different file type.": "Kan ikke lagre det samme filnavnet med en annen filtype.",
	"The grid spacing must be an integer between %d and %d.": "Rutenettmellomrommet må være et heltall mellom %d og %d.",
	"There is not enough memory or resources to complete operation.": "Ikke nok minne eller ressurser til å fullføre operasjonen.",
	"Close some programs, and then try again.": "Lukk noen programmer, og prøv på nytt.",
	"Low on memory or resources.": "Lite minne eller systemressurser.",
	"Group error.": "Gruppefeil.",
	"Paint was unable to print your document. Please make sure you have sufficient disk space and that your printer is working correctly.": "Paint kan ikke skrive ut dokumentet. Kontroller at du har nok diskplass og at skriveren fungerer korrekt.",
	"Saving into this format may cause some loss of color information.": "Noe fargeinformasjon kan gå tapt hvis du lagrer filen i dette formatet.",
	"Do you want to continue?": "Vil du fortsette?",
	"Converting to black and white cannot be undone.  This action affects the current file and may cause some loss of color information.": "Du kan ikke angre konvertering til svart/hvitt. Denne handlingen påvirker gjeldende fil, og kan medføre tap av fargeinformasjon.",
	"Bitmaps must be greater than one pixel on a side.": "Punktgrafikk må ha mer enn en piksel på hver side.",
	"Generic error.": "Generell feil.",
	"File not found.": "Finner ikke filen.",
	"Bad path.": "Ugyldig bane.",
	"Too many open files.": "For mange åpne filer.",
	"Access denied.": "Ingen tilgang.",
	"Invalid file.": "Ugyldig fil.",
	"Remove current folder.": "Fjern gjeldende mappe.",
	"Folder full.": "Mappen er full.",
	"Bad seek.": "Ugyldig søk.",
	"Hard IO error.": "I/U-feil i maskinvaren.",
	"Sharing violation.": "Brudd på delingstillatelse.",
	"Lock violation.": "Brudd på låsetillatelse.",
	"Disk full.": "Disken er full.",
	"End of file.": "Slutt på filen.",
	"Error getting the Clipboard Data!": "Kan ikke hente data fra utklippstavlen.",
	"No Printer Found @ page setup": "Finner ingen skriver @ utskriftsformat.",
	"24-bit Bitmap (*.bmp;*.dib)": "24-biters punktgrafikk (*.bmp, *.dib)",
	"All Files": "Alle filer",
	"Palette|*.pal|": "Palett|*.PAL|",
	"OLE 2.0 was unable to start.": "Kan ikke starte OLE 2.0.",
	"Make sure that you are using the correct version of the OLE libraries.": "Kontroller at du bruker riktig versjon av OLE-bibliotekene.",
	"Resets the text be without any attributes.": "Tilbakestiller teksten slik at den ikke har noen attributter",
	"Sets or clears the text bold attribute.": "Aktiverer eller deaktiverer attributtet for fet tekst",
	"Sets or clears the text italic attribute.": "Aktiverer eller deaktiverer attributtet for kursiv tekst",
	"Selects the font used by the text.": "Velger skriften som brukes på teksten",
	"Selects the point size of the text.": "Velger punktstørrelsen for teksten",
	"Sets or clears the text underline attribute.": "Aktiverer eller deaktiverer attributtet for understreket tekst",
	"Shows or hides the tooltips.": "Viser eller skjuler verktøytips",
	"Show Paint Help.": "Viser Hjelp for Paint",
	"Sends a picture by using mail or fax.": "Sender et bilde via e-post eller telefaks",
	"Copies the selection to a file.": "Kopierer det merkede området til en fil",
	"Pastes a file into the selection.": "Limer inn en fil i det merkede området",
	"Zooms the picture to 100%.": "Zoomer bildet til 100 %",
	"Zooms the picture to 400%.": "Zoomer bildet til 400 %",
	"Zooms the picture.": "Zoomer bildet",
	"Displays the entire picture.": "Viser hele bildet",
	"Shows or hides the thumbnail view of the picture.": "Viser eller skjuler miniatyren",
	"Shows or hides the grid.": "Viser eller skjuler rutenettet",
	"Shows or hides the text toolbar.": "Viser eller skjuler tekstverktøylinjen",
	"Flips or rotates the picture or a selection.": "Vender eller roterer bildet eller det merkede området",
	"Stretches or skews the picture or a selection.": "Strekker eller forskyver bildet eller det merkede området",
	"Inverts the colors of the picture or a selection.": "Inverterer fargene i bildet eller i det merkede området",
	"Changes the attributes of the picture.": "Endrer attributtene til dette bildet",
	"Clears the picture or selection.": "Fjerner bildet eller det merkede området",
	"The font size must be a numeric value.": "Skriftstørrelsen må være en numerisk verdi.",
	"Contains commands for working with the selected item(s).": "Inneholder kommandoer for å arbeide med valgt(e) element(er)",
	"Contains commands for selecting and transferring items.": "Inneholder kommandoer for å merke og flytte elementer",
	"Contains commands for customizing this window.": "Inneholder kommandoer for å tilpasse vinduet",
	"Contains commands for manipulating pictures and setting attributes.": "Inneholder kommandoer for å endre bilder og angi attributter",
	"Contains commands for using custom colors and drawing options.": "Inneholder kommandoer for å bruke egendefinerte farger og tegnealternativer",
	"Contains commands for displaying Help for and information about Paint.": "Inneholder kommandoer for å vise Hjelp for og informasjon om Paint",
	"Cannot save file.": "Kan ikke lagre filen",
	"Error removing temporary file.": "Feil under fjerning av midlertidig fil.",
	"Get Colors": "Hent farger",
	"Save Colors": "Lagre farger",
	"File last saved:": "Fil sist lagret:",
	"Size on disk:": "Størrelse på disk:",
	"Not Available": "Ikke tilgjengelig",
	"%s bytes": "%s byte",
	"Painting": "Maleri",
	"Fonts": "Skrifter",
	"Tools": "Verktøy",
	"All Picture Files": "Alle bildefiler",
	"For Help, click Help Topics on the Help Menu.": "Velg Emner i Hjelp på Hjelp-menyen hvis du vil ha mer informasjon.",
	"Select an area on which to get Help.": "Merker et emne som du vil vise Hjelp for.",
	"%1 in %2": "%1 i %2",
	"Creates a new document.": "Oppretter et nytt dokument",
	"Opens an existing document.": "Åpner et eksisterende dokument",
	"Closes the active document.": "Lukker det aktive dokumentet",
	"Saves the active document.": "Lagrer det aktive dokumentet",
	"Saves the active document with a new name.": "Lagrer det aktive dokumentet med et nytt navn.",
	"Changes the page layout.": "Endrer sideoppsettet",
	"Specifies the default printer setup.": "Angir standard skriveroppsett",
	"Prints the active document and sets printing options.": "Skriver ut det aktive dokumentet og angir utskriftsalternativer",
	"Displays full pages.": "Viser hele sider",
	"Opens this document.": "Åpner dette dokumentet",
	"Deletes the selection.": "Sletter det merkede området",
	"Erases everything.": "Sletter alt",
	"Copies the selection and puts it on the Clipboard.": "Kopierer det merkede området til utklippstavlen",
	"Cuts the selection and puts it on the Clipboard.": "Klipper ut det merkede området og flytter det til utklippstavlen",
	"Finds the specified text.": "Søker etter den angitte teksten",
	"Inserts the contents of the Clipboard.": "Setter inn innholdet på utklippstavlen",
	"Repeats the last action.": "Gjentar siste handling",
	"Replaces specific text with different text.": "Erstatter angitt tekst med en annen tekst",
	"Selects everything.": "Merker alt",
	"Undoes the last action.": "Angrer siste handling",
	"Redoes the previously undone action.": "Gjør om siste angret handling",
	"Displays program information, version number, and copyright.": "Viser programinformasjon, versjonsnummer og opphavsrett.",
	"Quits Paint.": "Avslutter Paint",
	"Opens Paint Help.": "Åpner Hjelp for Paint",
	"Displays instructions about how to use Help.": "Viser informasjon om hvordan du bruker Hjelp",
	"Displays Help for areas you click on.": "Viser hjelp til områder du klikker",
	"Displays Help for the current task or command.": "Viser hjelp for gjeldende oppgave eller kommando",
	"Centers this bitmap as the desktop wallpaper.": "Bruker dette bildet som bakgrunn på skrivebordet (midtstilt)",
	"Tiles this bitmap as the desktop wallpaper.": "Bruker dette bildet som bakgrunn på skrivebordet (side ved side)",
	"Sends the selection using mail or fax.": "Sender det merkede området via av e-post eller telefaks",
	"Prints the selection.": "Skriver ut det merkede området",
	"Shows or hides the thumbnail.": "Viser eller skjuler miniatyren",
	"Shows Paint Help.": "Viser Hjelp for Paint",
	"Shows or hides the status bar.": "Viser eller skjuler statuslinjen",
	"Shows or hides the tool box.": "Viser eller skjuler verktøykassen",
	"Shows or hides the color box.": "Viser eller skjuler fargeboksen",
	"Only a Far East font can be used for vertical editing.": "Bare skrifter fra Fjerne østen kan brukes til loddrett redigering.",
	"Changes the window size.": "Endrer vindusstørrelsen",
	"Changes the window position.": "Endrer vindusplasseringen",
	"Reduces the window to an icon.": "Minimerer vinduet til et ikon",
	"Enlarges the window to full size.": "Forstørrer vinduet til full størrelse",
	"Switches to the next document window.": "Bytter til det neste dokumentvinduet",
	"Switches to the previous document window.": "Bytter til det forrige dokumentvinduet",
	"Closes the active window and asks if you want to save changes.": "Lukker det aktive vinduet, og spør om du vil lagre eventuelle endringer",
	"Restores the window to normal size.": "Gjenoppretter vinduet til normal størrelse",
	"Activates the task list.": "Aktiverer oppgavelisten",
	"All Files (*.*)": "Alle filer (*.*)",
	"Untitled": "Uten navn",
	"an unnamed file": "en fil uten navn",
	"&Hide": "&Skjul",
	"Hide": "Skjul",
	"No error message is available.": "Ingen feilmelding er tilgjengelig.",
	"An unsupported operation was attempted.": "Forsøkte å utføre en operasjon som ikke støttes.",
	"A required resource was unavailable.": "En nødvendig ressurs var ikke tilgjengelig.",
	"Out of memory.": "Ikke nok minne.",
	"An unknown error has occurred.": "Det har oppstått en ukjent feil.",
	"on %1": "på %1",
	"&One Page": "&En side",
	"One Page": "En side",
	"&Two Page": "&To sider",
	"Two Page": "To sider",
	"Page %u": "Side %u",
	"Pages %u-%u": "Side %u-%u",
	"Printer Files (*.prn)|*.prn|All Files (*.*)|*.*||": "Skriverfiler (*.prn)|*.prn|Alle filer (*.*)|*.*||",
	"Print to File": "Skriv til fil",
	"to %1": "til %1",
	"&Update %1": "&Oppdater %1",
	"Update %1": "Oppdater %1",
	"E&xit && Return to %1": "&Avslutt og gå til %1",
	"Exit && Return to %1": "Avslutt og gå til %1",
	"Linked %s": "Koblet %s",
	"Unknown Type": "Ukjent type",
	"Invalid filename.": "Ugyldig filnavn.",
	"Failed to open document.": "Kan ikke åpne dokumentet.",
	"Failed to save document.": "Kan ikke lagre dokumentet.",
	"Save changes to %1?": "Lagre endringer i %1?",
	"Failed to create empty document.": "Kan ikke opprette tomt dokument.",
	"The file is too large to open.": "Filen er for stor til å kunne åpnes.",
	"Could not start print job.": "Kan ikke starte utskriftsjobben.",
	"Failed to launch help.": "Kan ikke starte Hjelp.",
	"Internal application error.": "Intern programfeil.",
	"Command failed.": "Kommandoen mislyktes.",
	"Insufficient memory to perform operation.": "Ikke nok minne til å utføre operasjonen.",
	"System registry entries have been removed and the INI file (if any) was deleted.": "Oppføringer i systemregistret er fjernet og INI-filen (hvis det fantes noen) er slettet.",
	"Not all of the system registry entries (or INI file) were removed.": "Ikke alle oppføringene i systemregistret (eller INI-filen) ble fjernet.",
	"This program requires the file %s, which was not found on this system.": "Dette programmet krever filen %s. Filen finnes ikke på dette systemet.",
	"This program is linked to the missing export %s in the file %s. This machine may have an incompatible version of %s.": "Dette programmet er koblet til den manglende eksporten %s i filen %s. Denne datamaskinen har kanskje en versjon av %s som ikke er kompatibel.",
	"Please enter an integer.": "Angi et heltall.",
	"Please enter a number.": "Angi et tall.",
	"Please enter an integer between %1 and %2.": "Angi et heltall mellom %1 og %2.",
	"Please enter a number between %1 and %2.": "Angi et tall mellom %1 og %2.",
	"Please enter no more than %1 characters.": "Ikke skriv inn mer enn %1 tegn.",
	"Please select a button.": "Trykk en knapp.",
	"Please enter an integer between 0 and 255.": "Angi et heltall mellom 0 og 255.",
	"Please enter a positive integer.": "Angi et positivt heltall.",
	"Please enter a date and/or time.": "Angi en dato og/eller klokkeslett.",
	"Please enter a currency.": "Angi en valuta.",
	"Unexpected file format.": "Uventet filformat.",
	"Cannot find this file.": "Finner ikke filen.",
	"Please verify that the correct path and file name are given.": "Kontroller at riktig bane og filnavn er angitt.",
	"Destination disk drive is full.": "Måldisken er full.",
	"Unable to read from %1, it is opened by someone else.": "Kan ikke lese fra %1. Den er åpnet av en annen bruker.",
	"Unable to write to %1, it is read-only or opened by someone else.": "Kan ikke skrive til %1. Den er skrivebeskyttet eller åpnet av andre.",
	"An unexpected error occurred while reading %1.": "Det oppstod en uventet feil under lesing av %1.",
	"An unexpected error occurred while writing %1.": "Det oppstod en uventet feil under skriving til %1.",
	"Unable to register document.": "kan ikke registrere dokumentet.",
	"The document may already be open.": "Det kan allerede være åpnet.",
	"Update %1 before proceeding?": "Vil du oppdatere %1 før du går videre?",
	"Could not update client.": "Kan ikke oppdatere klienten.",
	"Failed to register. ActiveX features may not work properly.": "Kan ikke registrere. ActiveX-funksjoner vil kanskje ikke fungere.",
	"Failed to update the system registry.": "Kan ikke oppdatere systemregistret.",
	"Please try using REGEDIT.": "Prøv med REGEDIT.",
	"Unable to read write-only property.": "Kan ikke lese lesebeskyttet egenskap.",
	"Unable to write read-only property.": "Kan ikke skrive til skrivebeskyttet egenskap.",
	"Unable to load mail system support.": "Kan ikke laste støtte for e-postsystemer.",
	"Mail system DLL is invalid.": "Ugyldig DLL for e-postsystem.",
	"Send Mail failed to send message.": "Meldingen ble ikke sendt.",
	"No error occurred.": "Ingen feil oppstod.",
	"An unknown error occurred while accessing %1.": "Det oppstod en ukjent feil under tilgang til %1.",
	"%1 was not found.": "Fant ikke %1.",
	"%1 contains an invalid path.": "%1 inneholder en ugyldig bane.",
	"%1 could not be opened because there are too many open files.": "%1 kunne ikke åpnes fordi det er for mange åpne filer.",
	"Access to %1 was denied.": "Ingen tilgang til %1.",
	"An invalid file handle was associated with %1.": "En ugyldig filreferanse ble knyttet til %1.",
	"%1 could not be removed because it is the current directory.": "%1 kunne ikke fjernes fordi det er gjeldende katalog.",
	"%1 could not be created because the directory is full.": "%1 kunne ikke opprettes fordi katalogen er full.",
	"Seek failed on %1": "Søk mislyktes på %1",
	"A hardware I/O error was reported while accessing %1.": "En I/U-feil på maskinvaren ble rapportert under tilgang til %1.",
	"A sharing violation occurred while accessing %1.": "Det oppstod brudd på delingstillatelse under tilgang til %1.",
	"A locking violation occurred while accessing %1.": "Det oppstod brudd på låsetillatelse under tilgang til %1.",
	"Disk full while accessing %1.": "Full disk ved tilgang til %1.",
	"An attempt was made to access %1 past its end.": "Forsøkte å få tilgang til %1 etter dens slutt.",
	"An attempt was made to write to the reading %1.": "Det ble forsøkt å skrive til %1, som er skrivebeskyttet.",
	"An attempt was made to read from the writing %1.": "Det ble forsøkt å lese fra %1, som er lesebeskyttet.",
	"%1 has a bad format.": "%1 har feil format.",
	"%1 contained an unexpected object.": "%1 inneholdt et uventet objekt.",
	"%1 contains an incorrect schema.": "%1 inneholder et ugyldig skjema.",
	"Selects a rectangular part of the picture to move, copy, or edit.": "Merker en rektangulær del av bildet som kan flyttes, kopieres eller redigeres",
	"Select": "Merk",
	"Selects a free-form part of the picture to move, copy, or edit.": "Merker en frihåndsdel av bildet som kan flyttes, kopieres eller redigeres",
	"Free-Form Select": "Frihåndsmerking",
	"Inserts text into the picture.": "Setter inn tekst i bildet",
	"Fills an area with the current drawing color.": "Fyller et område med gjeldende tegnefarge.",
	"Fill With Color": "Fyll med farge",
	"Draws a straight line with the selected line width.": "Tegner en rett strek med den valgte bredden",
	"Line": "Strek",
	"Draws using an airbrush of the selected size.": "Spraymaler med den valgte størrelsen",
	"Airbrush": "Spraymaling",
	"Draws a curved line with the selected line width.": "Tegner en bue med den valgte strektykkelsen",
	"Curve": "Bue",
	"Draws a polygon with the selected fill style.": "Tegner en polygon med den valgte fylltypen",
	"Draws a rounded rectangle with the selected fill style.": "Tegner et avrundet rektangel med det valgte fyllmønsteret",
	"Rounded Rectangle": "Avrundet rektangel",
	"Draws a free-form line one pixel wide.": "Tegner en frihåndslinje som er en piksel tykk",
	"Pencil": "Blyant",
	"Erases a portion of the picture, using the selected eraser shape.": "Sletter en del av bildet med den valgte formen på viskelæret",
	"Eraser/Color Eraser": "Viskelær",
	"Changes the magnification.": "Endrer forstørrelsen",
	"Magnifier": "Forstørrelseglass",
	"Picks up a color from the picture for drawing.": "Henter en farge som det skal tegnes med, fra bildet",
	"Pick Color": "Hent farge",
	"Draws using a brush with the selected shape and size.": "Tegner med en kost i valgt størrelse og form.",
	"Brush": "Kost",
	"Draws a rectangle with the selected fill style.": "Tegner et rektangel med det valgte fyllmønsteret",
	"Rectangle": "Rektangel",
	"Draws a filled rectangle.": "Tegner et fylt rektangel",
	"Draws an ellipse with the selected fill style.": "Tegner en ellipse med det valgte fyllmønsteret",
	"Draws a filled ellipse.": "Tegner en fylt ellipse",
	"Makes the current selection either opaque or transparent.": "Gjør det merkede området gjennomsiktig eller ugjennomsiktig",
	"Creates a new color.": "Lager en ny farge",
	"Uses a previously saved palette of colors.": "Bruker en tidligere lagret fargepalett",
	"Saves the current palette of colors to a file.": "Lagrer gjeldende fargepalett i en fil",
	"You must save the file before choosing it as Wallpaper.": "Du må lagre filen før den kan velges som bakgrunn.",
	"The selection is now larger than the bitmap.": "Det merkede området er nå større enn punktgrafikkbildet.",
	"Would you like the bitmap enlarged?": "Vil du forstørre bildet?",
	"The image in the clipboard is larger than the bitmap.": "Bildet på utklippstavlen er større enn punktgrafikkbildet.",
	"The file is not in the correct format.": "Filen har ikke riktig format.",
	"Not enough room to paste text.": "Ikke nok plass til å lime inn tekst.",
	"Enlarge the text area and try again.": "Gjør tekstområdet større og prøv på nytt.",
	"Places the text.": "Plasserer teksten"
});
