//
// NOTE: This is a generated file! Don't edit it directly.
// Eventually community translation will be set up on some translation platform.
// 
// Generated with: npm run update-localization
//
loaded_localizations("da", {
	"Attributes": "Attributter",
	"&Width:": "&Bredde:",
	"Width:": "Bredde:",
	"&Height:": "H&øjde:",
	"Height:": "Højde:",
	"Units": "Måleenhed",
	"&Inches": "&Tommer",
	"Inches": "Tommer",
	"C&m": "&Cm",
	"Cm": "Cm",
	"&Pixels": "&Pixel",
	"Pixels": "Pixel",
	"Colors": "Farver",
	"&Black and white": "Sort-&hvid",
	"Black and white": "Sort-hvid",
	"Co&lors": "&Farver",
	"Transparency": "Gennemsigtighed",
	"Use &Transparent background color": "Br&ug gennemsigtig baggrundsfarve",
	"Use Transparent background color": "Brug gennemsigtig baggrundsfarve",
	"Select &Color": "&Vælg farve",
	"Select Color": "Vælg farve",
	"Cancel": "Annuller",
	"&Default": "&Standard",
	"Default": "Standard",
	"Custom Zoom": "Brugerdefineret zoom",
	"Current zoom:": "Aktuel zoomprocent:",
	"Zoom to": "Zoom til",
	"Flip and Rotate": "Vend og roter",
	"Flip or rotate": "Spejlvend eller roter",
	"&Flip horizontal": "&Spejlvend vandret",
	"Flip horizontal": "Spejlvend vandret",
	"Flip &vertical": "Sp&ejlvend lodret",
	"Flip vertical": "Spejlvend lodret",
	"&Rotate by angle": "&Roter efter vinkel",
	"Rotate by angle": "Roter efter vinkel",
	"Stretch and Skew": "Stræk og vrid",
	"Stretch": "Stræk",
	"&Horizontal:": "&Vandret:",
	"Horizontal:": "Vandret:",
	"&Vertical:": "&Lodret:",
	"Vertical:": "Lodret:",
	"Skew": "Vrid",
	"H&orizontal:": "Va&ndret:",
	"Degrees": "grader",
	"V&ertical:": "Lodr&et:",
	"Color Table": "Farvetabel",
	"New": "Ny",
	"&New ": "&Ny ",
	"New ": "Ny ",
	"&Help": "&Hjælp",
	"Help": "Hjælp",
	"Printing": "Udskriver",
	"on the": "på",
	"&Print": "&Udskriv",
	"Print": "Udskriv",
	"&Next Page": "N&æste side",
	"Next Page": "Næste side",
	"Pre&v Page": "&Forrige side",
	"Prev Page": "Forrige side",
	"Zoom &In": "Zoom &ind",
	"Zoom In": "Zoom ind",
	"Zoom &Out": "Zoo&m ud",
	"Zoom Out": "Zoom ud",
	"&Close": "&Luk",
	"Close": "Luk",
	"Grid Settings": "Gitterindstillinger",
	"&Pixel Grid": "&Pixelgitter",
	"Pixel Grid": "Pixelgitter",
	"&Tile Grid": "&Arranger gitter",
	"Tile Grid": "Arranger gitter",
	"pixels": "pixel",
	"H&eight:": "&Højde:",
	"Text": "Tekst",
	"Undo": "Fortryd",
	"Cut": "Klip",
	"Copy": "Kopier",
	"Paste": "Sæt ind",
	"Clear Selection": "Slet markering",
	"Select All": "Marker alt",
	"Text Toolbar": "Værktøjslinjen Tekst",
	"Selection": "Markering",
	"Cu&t": "&Klip",
	"&Copy": "K&opier",
	"&Paste": "Sæt i&nd",
	"C&lear Selection": "&Slet markering",
	"Select &All": "&Marker alt",
	"C&opy To": "Kopier &til",
	"Copy To": "Kopier til",
	"Paste &From": "Sæt in&d fra",
	"Paste From": "Sæt ind fra",
	"Flip/&Rotate": "&Vend/roter",
	"Flip/Rotate": "Vend/roter",
	"&Stretch/Skew": "St&ræk/vrid",
	"Stretch/Skew": "Stræk/vrid",
	"&Invert Colors": "&Inverter farver",
	"Invert Colors": "Inverter farver",
	"Thumbnail": "Miniature",
	"&File": "&Filer",
	"File": "Filer",
	"&New": "&Ny",
	"&Open": "Å&bn",
	"Open": "Åbn",
	"&Save": "&Gem",
	"Save": "Gem",
	"Save &As": "Ge&m som",
	"Save As": "Gem som",
	"Print Pre&view": "&Vis udskrift",
	"Print Preview": "Vis udskrift",
	"Page Se&tup": "S&ideopsætning",
	"Page Setup": "Sideopsætning",
	"S&end": "&Send",
	"Send": "Send",
	"Set As &Wallpaper (Tiled)": "Anven&d som tapet (side om side)",
	"Set As Wallpaper (Tiled)": "Anvend som tapet (side om side)",
	"Set As Wa&llpaper (Centered)": "Anvend som &tapet (centreret)",
	"Set As Wallpaper (Centered)": "Anvend som tapet (centreret)",
	"Recent File": "Seneste fil",
	"E&xit": "&Afslut",
	"Exit": "Afslut",
	"&Edit": "&Rediger",
	"Edit": "Rediger",
	"&Undo": "Fo&rtryd",
	"&Repeat": "&Gentag",
	"Repeat": "Gentag",
	"&View": "&Vis",
	"View": "Vis",
	"&Tool Box": "&Værktøjskasse",
	"Tool Box": "Værktøjskasse",
	"&Color Box": "&Farveboks",
	"Color Box": "Farveboks",
	"&Status Bar": "&Statuslinje",
	"Status Bar": "Statuslinje",
	"T&ext Toolbar": "Værktøjslinjen Skrift&typer",
	"&Normal Size": "&Normal størrelse",
	"Normal Size": "Normal størrelse",
	"&Large Size": "&Stor størrelse",
	"Large Size": "Stor størrelse",
	"C&ustom": "Bruger&defineret",
	"Custom": "Brugerdefineret",
	"Show &Grid": "V&is gitter",
	"Show Grid": "Vis gitter",
	"Show T&humbnail": "&Vis miniature",
	"Show Thumbnail": "Vis miniature",
	"&View Bitmap": "Vis &bitmap",
	"View Bitmap": "Vis bitmap",
	"Ctrl+F": "Ctrl+B",
	"&Image": "&Billede",
	"Image": "Billede",
	"&Flip/Rotate": "&Vend/roter",
	"&Attributes": "&Attributter",
	"&Clear Image": "&Ryd billede",
	"Clear Image": "Ryd billede",
	"&Draw Opaque": "&Tegn uigennemsigtigt",
	"Draw Opaque": "Tegn uigennemsigtigt",
	"&Colors": "F&arver",
	"&Edit Colors": "&Rediger farver",
	"Edit Colors": "Rediger farver",
	"&Help Topics": "Emner i &Hjælp",
	"Help Topics": "Emner i Hjælp",
	"&About Paint": "&Om Paint",
	"About Paint": "Om Paint",
	"&Update": "Op&dater",
	"Update": "Opdater",
	"Save Copy &As": "Gem &kopi som",
	"Save Copy As": "Gem kopi som",
	"untitled": "Ikke-navngivet",
	"Bitmap Image": "Bitmapbillede",
	"Bitmap Files (*.bmp)": "Bitmapfiler (*.bmp)",
	"PCX Files": "PCX-filer",
	"Icon Files": "Ikonfiler",
	"Monochrome Bitmap (*.bmp;*.dib)": "Monokrom bitmap (*.bmp,*.dib)",
	"16 Color Bitmap (*.bmp;*.dib)": "16-farvers bitmap (*.bmp,*.dip)",
	"256 Color Bitmap (*.bmp;*.dib)": "256-farvers bitmap (*.bmp,*.dip)",
	"Paint cannot open this file.": "Paint kan ikke åbne denne fil.",
	"Paint cannot read this file.": "Paint kan ikke læse denne fil.",
	"This file is read-only.": "Filen er skrivebeskyttet.",
	"To save your changes, use a different filename.": "Hvis du vil gemme ændringerne, skal du benytte et andet filnavn.",
	"This file is already open.": "Filen er allerede åben.",
	"This is not a valid .PCS file.": "Dette er ikke en gyldig .PCS-fil.",
	"This file is open for editing and cannot be overwritten.": "Denne fil er åbnet til redigering og kan ikke overskrives.",
	"Use a different filename to save your changes.": "Hvis du vil gemme ændringerne, skal du benytte et andet filnavn.",
	"This is not a valid bitmap file, or its format is not currently supported.": "Enten er dette ikke en gyldig bitmap-fil eller også understøttes formatet ikke.",
	"This is not a valid icon.": "Dette er ikke et gyldigt ikon.",
	"This is not a valid cursor.": "Dette er ikke en gyldig markør.",
	"Save was interrupted, so your file has not been saved.": "Lagringen blev afbrudt, så filen er ikke blevet gemt.",
	"You cannot save to a read-only file.": "Du kan ikke gemme i en skrivebeskyttet fil.",
	"Use a different file name.": "Benyt et andet filnavn.",
	"This file is already in use.": "Filen er i brug.",
	"Close the program, and then try again.": "Luk programmet, og prøv igen.",
	"Paint cannot save this file.": "Paint kan ikke gemme denne fil.",
	"Paint cannot save to the same filename with a different file type.": "Filen kan ikke gemmes under samme filnavn, men med et andet filtypenavn.",
	"The grid spacing must be an integer between %d and %d.": "Gitterafstanden skal være et heltal mellem %d og %d.",
	"There is not enough memory or resources to complete operation.": "Der er ikke tilstrækkelig hukommelse eller tilstrækkelige ressourcer til at udføre handlingen.",
	"Close some programs, and then try again.": "Luk nogle programmer, og prøv igen.",
	"Low on memory or resources.": "Der er næsten ikke mere hukommelse eller næsten ikke flere ressourcer.",
	"Group error.": "Gruppefejl.",
	"Paint was unable to print your document. Please make sure you have sufficient disk space and that your printer is working correctly.": "Paint kunne ikke udskrive dit dokument. Kontroller, at der er tilstrækkelig plads på harddisken og at printeren fungerer korrekt.",
	"Saving into this format may cause some loss of color information.": "Hvis du gemmer i dette format, kan visse farveoplysninger gå tabt.",
	"Do you want to continue?": "Vil du fortsætte?",
	"Converting to black and white cannot be undone.  This action affects the current file and may cause some loss of color information.": "Konverteringen til sort-hvid kan ikke annulleres. Denne handling påvirker den aktuelle fil og kan medføre tab af farveoplysninger.",
	"Bitmaps must be greater than one pixel on a side.": "Bitmaps skal være større end én pixel på hver led.",
	"Generic error.": "Standardfejl.",
	"File not found.": "Filen blev ikke fundet.",
	"Bad path.": "Forkert sti.",
	"Too many open files.": "Der er for mange filer åbne.",
	"Access denied.": "Adgang nægtet.",
	"Invalid file.": "Filen er ugyldig.",
	"Remove current folder.": "Fjern den aktuelle mappe.",
	"Folder full.": "Mappen er fuld.",
	"Bad seek.": "Forkert søgning.",
	"Hard IO error.": "IO-harddiskfejl.",
	"Sharing violation.": "Fildelingsfejl.",
	"Lock violation.": "Låsningsfejl.",
	"Disk full.": "Disken er fuld.",
	"End of file.": "Slut på fil.",
	"Error getting the Clipboard Data!": "Fejl under hentning af data fra Udklipsholder.",
	"No Printer Found @ page setup": "Ingen printer fundet @ sideopsætning",
	"24-bit Bitmap (*.bmp;*.dib)": "24-bit bitmap (*.bmp,*.dip)",
	"All Files": "Alle filer",
	"Palette|*.pal|": "Palet|*.pal|",
	"untitled.pal": "udennavn.pal",
	"OLE 2.0 was unable to start.": "OLE 2.0 kunne ikke startes.",
	"Make sure that you are using the correct version of the OLE libraries.": "Kontroller, at du anvender den rigtige version af OLE-bibliotekerne.",
	"Resets the text be without any attributes.": "Nulstiller teksten uden attributter",
	"Sets or clears the text bold attribute.": "Slår skriftattributten Fed fra eller til",
	"Sets or clears the text italic attribute.": "Slår skriftattributten Kursiv fra eller til",
	"Selects the font used by the text.": "Vælger den skrifttype, der bruges i teksten",
	"Selects the point size of the text.": "Vælger skriftstørrelse i teksten",
	"Sets or clears the text underline attribute.": "Slår skriftattributten Understreget fra eller til",
	"Shows or hides the tooltips.": "Viser eller skjuler værktøjstip",
	"Show Paint Help.": "Viser Hjælp til Paint",
	"Sends a picture by using mail or fax.": "Sender et billede med elektronisk post eller fax",
	"Copies the selection to a file.": "Kopierer markeringen til en fil",
	"Pastes a file into the selection.": "Indsætter en fil i markeringen",
	"Zooms the picture to 100%.": "Zoomer billedet med 100%",
	"Zooms the picture to 400%.": "Zoomer billedet med 400%",
	"Zooms the picture.": "Zoomer billedet",
	"Displays the entire picture.": "Viser hele billedet",
	"Shows or hides the thumbnail view of the picture.": "Viser eller skjuler miniaturen",
	"Shows or hides the grid.": "Viser eller skjuler gitteret",
	"Shows or hides the text toolbar.": "Viser eller skjuler værktøjslinjen Tekst",
	"Flips or rotates the picture or a selection.": "Spejlvender eller roterer billedet eller en markering",
	"Stretches or skews the picture or a selection.": "Strækker eller vrider billedet eller en markering",
	"Inverts the colors of the picture or a selection.": "Inverterer farverne på billedet eller en markering",
	"Changes the attributes of the picture.": "Ændrer billedets egenskaber",
	"Clears the picture or selection.": "Sletter billedet eller markeringen",
	"The font size must be a numeric value.": "Skriftstørrelsen skal være en numerisk værdi.",
	"Contains commands for working with the selected item(s).": "Indeholder kommandoer til arbejde med det eller de markerede elementer",
	"Contains commands for selecting and transferring items.": "Indeholder kommandoer til markering og overførsel af elementer",
	"Contains commands for customizing this window.": "Indeholder kommandoer til tilpasning af vinduet",
	"Contains commands for manipulating pictures and setting attributes.": "Indeholder kommandoer til håndtering af billeder og indstilling af attributter",
	"Contains commands for using custom colors and drawing options.": "Indeholder kommandoer til brug af brugerdefinerede farver og tegneindstillinger",
	"Contains commands for displaying Help for and information about Paint.": "Indeholder kommandoer til visning af Hjælp til og oplysninger om Paint",
	"Cannot save file.": "Filen kan ikke gemmes.",
	"Error removing temporary file.": "Fejl under fjernelse af midlertidig fil.",
	"Get Colors": "Hent farver",
	"Save Colors": "Gem farver",
	"File last saved:": "Filen blev sidst gemt:",
	"Not Available": "Ikke tilgængelig",
	"Size on disk:": "Størrelse på disk:",
	"%s bytes": "%s byte",
	"Painting": "Maler",
	"Fonts": "Skrifttyper",
	"Tools": "Funktioner",
	"All Picture Files": "Alle billedfiler",
	"For Help, click Help Topics on the Help Menu.": "Klik på Emner i Hjælp i menuen Hjælp for at få hjælp",
	"Select an area on which to get Help.": "Marker et område, som du vil have hjælp til.",
	"%1 in %2": "%1 i %2",
	"Creates a new document.": "Opretter et nyt dokument",
	"Opens an existing document.": "Åbner et eksisterende dokument",
	"Closes the active document.": "Lukker det aktive dokument",
	"Saves the active document.": "Gemmer det aktive dokument",
	"Saves the active document with a new name.": "Gemmer det aktive dokument under et nyt navn",
	"Changes the page layout.": "Ændrer sideopsætningen",
	"Specifies the default printer setup.": "Angiver standardindstillinger for printeren",
	"Prints the active document and sets printing options.": "Udskriver det aktive dokument og definerer udskriftsindstillinger",
	"Displays full pages.": "Viser hele sider",
	"Opens this document.": "Åbner dokumentet",
	"Deletes the selection.": "Sletter markeringen",
	"Erases everything.": "Sletter alt",
	"Copies the selection and puts it on the Clipboard.": "Kopierer markeringen og placerer den i Udklipsholder",
	"Cuts the selection and puts it on the Clipboard.": "Klipper markeringen ud og placerer den i Udklipsholder",
	"Finds the specified text.": "Søger efter den angivne tekst",
	"Inserts the contents of the Clipboard.": "Indsætter indholdet af Udklipsholder",
	"Repeats the last action.": "Gentager den sidste handling",
	"Replaces specific text with different text.": "Erstatter bestemt tekst med anden tekst",
	"Selects everything.": "Markerer hele dokumentet",
	"Undoes the last action.": "Fortryder den sidste handling",
	"Redoes the previously undone action.": "Annullerer fortrydelsen af den tidligere fortrudte handling",
	"Displays program information, version number, and copyright.": "Viser programoplysninger, versionsnummer og copyright",
	"Quits Paint.": "Afslutter Paint",
	"Opens Paint Help.": "Åbner Paint Hjælp",
	"Displays instructions about how to use Help.": "Viser instruktioner om brugen af Hjælp",
	"Displays Help for areas you click on.": "Viser hjælp til områder, som du klikker på",
	"Displays Help for the current task or command.": "Viser hjælp til den aktuelle opgave eller kommando",
	"Centers this bitmap as the desktop wallpaper.": "Centrerer bitmappen som tapet bag skrivebordet",
	"Tiles this bitmap as the desktop wallpaper.": "Arrangerer bitmappen som tapet bag skrivebordet",
	"Sends the selection using mail or fax.": "Sender markeringen med elektronisk post eller fax",
	"Prints the selection.": "Udskriver markeringen",
	"Shows or hides the thumbnail.": "Viser eller skjuler miniaturen",
	"Shows Paint Help.": "Viser Paint Hjælp",
	"Shows or hides the status bar.": "Viser eller skjuler statuslinjen",
	"Shows or hides the tool box.": "Viser eller skjuler værktøjskassen",
	"Shows or hides the color box.": "Viser eller skjuler farveboksen",
	"Only a Far East font can be used for vertical editing.": "Kun en fjernøstlig skrifttype kan bruges til lodret redigering.",
	"Changes the window size.": "Ændrer vinduesstørrelsen",
	"Changes the window position.": "Ændrer vinduesplaceringen",
	"Reduces the window to an icon.": "Formindsker vinduet til et ikon",
	"Enlarges the window to full size.": "Forstørrer vinduet til fuld størrelse",
	"Switches to the next document window.": "Skifter til næste dokumentvindue",
	"Switches to the previous document window.": "Skifter til det forrige dokumentvindue",
	"Closes the active window and asks if you want to save changes.": "Lukker det aktive vindue og spørger, om du vil gemme dokumenterne",
	"Restores the window to normal size.": "Gendanner vinduet til normal størrelse",
	"Activates the task list.": "Aktiverer Jobliste",
	"All Files (*.*)": "Alle filer (*.*)",
	"Untitled": "Ikke-navngivet",
	"an unnamed file": "en ikke-navngivet fil",
	"&Hide": "&Skjul",
	"Hide": "Skjul",
	"No error message is available.": "Der er ingen fejlmeddelelse tilgængelig.",
	"An unsupported operation was attempted.": "Det blev forsøgt at udføre en ikke-understøttet handling.",
	"A required resource was unavailable.": "En krævet ressource var ikke tilgængelig.",
	"Out of memory.": "Der er ikke mere hukommelse.",
	"An unknown error has occurred.": "Der er opstået en ukendt fejl.",
	"on %1": "tilsluttet %1",
	"&One Page": "&En side",
	"One Page": "En side",
	"&Two Page": "&To sider",
	"Two Page": "To sider",
	"Page %u": "Side %u",
	"Pages %u-%u": "Sider %u-%u",
	"Printer Files (*.prn)|*.prn|All Files (*.*)|*.*||": "Printerfiler (*.prn)|*.prn|Alle filer (*.*)|*.*||",
	"Print to File": "Skriv til fil",
	"to %1": "til %1",
	"&Update %1": "&Opdater %1",
	"Update %1": "Opdater %1",
	"E&xit && Return to %1": "A&fslut, og vend tilbage til %1",
	"Exit && Return to %1": "Afslut, og vend tilbage til %1",
	"Linked %s": "Sammenkædet %s",
	"Unknown Type": "Ukendt type",
	"Invalid filename.": "Ugyldigt filnavn.",
	"Failed to open document.": "Dokumentet kunne ikke åbnes.",
	"Failed to save document.": "Dokumentet kunne ikke gemmes.",
	"Save changes to %1?": "Skal ændringerne i %1 gemmes?",
	"Failed to create empty document.": "Der kunne ikke oprettes et tomt dokument.",
	"The file is too large to open.": "Filen er for stor til at åbne.",
	"Could not start print job.": "Udskriftsjob kunne ikke startes.",
	"Failed to launch help.": "Hjælp kunne ikke startes.",
	"Internal application error.": "Intern programfejl.",
	"Command failed.": "Kommandoen mislykkedes.",
	"Insufficient memory to perform operation.": "Der er ikke tilstrækkelig hukommelse til at udføre handlingen.",
	"System registry entries have been removed and the INI file (if any) was deleted.": "Systemposter i registreringsdatabasen er blevet fjernet, og INI-filen (hvis der var en) er blevet slettet.",
	"Not all of the system registry entries (or INI file) were removed.": "Nogle af systemposterne i registreringsdatabasen eller INI-filen blev ikke fjernet.",
	"This program requires the file %s, which was not found on this system.": "Dette program kræver filen %s, som ikke blev fundet på dette system.",
	"This program is linked to the missing export %s in the file %s. This machine may have an incompatible version of %s.": "Dette program er kædet til den manglende eksport %s i filen %s. Denne computer har muligvis en ikke-kompatibel version af %s.",
	"Please enter an integer.": "Indtast et heltal.",
	"Please enter a number.": "Indtast et tal.",
	"Please enter an integer between %1 and %2.": "Indtast et heltal mellem %1 og %2.",
	"Please enter a number between %1 and %2.": "Indtast et tal mellem %1 og %2.",
	"Please enter no more than %1 characters.": "Indtast højst %1 tegn.",
	"Please select a button.": "Vælg en knap.",
	"Please enter an integer between 0 and 255.": "Skriv et heltal mellem 0 og 255.",
	"Please enter a positive integer.": "Skriv et positivt heltal.",
	"Please enter a date and/or time.": "Indtast dato og/eller klokkeslæt.",
	"Please enter a currency.": "Angiv en valuta.",
	"Unexpected file format.": "Uventet filformat.",
	"Cannot find this file.": "Denne fil kan ikke findes.",
	"Please verify that the correct path and file name are given.": "Kontroller, at sti og filnavn er korrekt.",
	"Destination disk drive is full.": "Destinationsdrevet er fuldt.",
	"Unable to read from %1, it is opened by someone else.": "Der kan ikke læses fra %1. Filen er åbnet af en anden bruger.",
	"Unable to write to %1, it is read-only or opened by someone else.": "Der kan ikke skrives til %1. Filen er skrivebeskyttet eller åbnet af en anden bruger.",
	"An unexpected error occurred while reading %1.": "Der opstod en uventet fejl under indlæsning af %1.",
	"An unexpected error occurred while writing %1.": "Der opstod en uventet fejl under skrivning til %1.",
	"Unable to register document.": "Dokumentet kunne ikke registreres.",
	"The document may already be open.": "Dokumentet er muligvis allerede åbnet.",
	"Update %1 before proceeding?": "Skal %1 opdateres, inden der fortsættes?",
	"Could not update client.": "Klientprogrammet kunne ikke opdateres.",
	"Failed to register. ActiveX features may not work properly.": "Der kan ikke registreres. ActiveX-funktioner virker måske ikke korrekt.",
	"Failed to update the system registry.": "Kan ikke opdatere systemregistreringsdatabasen.",
	"Please try using REGEDIT.": "Benyt REGEDIT.",
	"Unable to read write-only property.": "En læsebeskyttet egenskab kan ikke læses.",
	"Unable to write read-only property.": "En skrivebeskyttet egenskab kan ikke skrives.",
	"Unable to load mail system support.": "Der kan ikke indlæses understøttelse af postsystem.",
	"Mail system DLL is invalid.": "DLL-filen til e-mail-system er ugyldig.",
	"Send Mail failed to send message.": "Send post kunne ikke sende meddelelsen.",
	"No error occurred.": "Der opstod ingen fejl.",
	"An unknown error occurred while accessing %1.": "Der opstod en ukendt fejl ved adgang til %1.",
	"%1 was not found.": "%1 blev ikke fundet.",
	"%1 contains an invalid path.": "%1 indeholder en ugyldig sti.",
	"%1 could not be opened because there are too many open files.": "%1 kunne ikke åbnes, fordi der er for mange åbne filer.",
	"Access to %1 was denied.": "Adgang til %1 nægtet.",
	"An invalid file handle was associated with %1.": "En ugyldig fil-handle blev associeret med %1.",
	"%1 could not be removed because it is the current directory.": "%1 kunne ikke fjernes, da den er den aktive mappe.",
	"%1 could not be created because the directory is full.": "%1 kunne ikke oprettes, fordi mappen er fuld.",
	"Seek failed on %1": "Søgning på %1 mislykkedes",
	"A hardware I/O error was reported while accessing %1.": "Der opstod en hardware I/O-fejl ved adgang til %1.",
	"A sharing violation occurred while accessing %1.": "Der opstod en delingsfejl ved adgang til %1.",
	"A locking violation occurred while accessing %1.": "Der opstod en låsefejl ved adgang til %1.",
	"Disk full while accessing %1.": "Disken blev fuld ved adgang til %1.",
	"An attempt was made to access %1 past its end.": "Det blev forsøgt at få adgang til %1 efter dens afslutning.",
	"An attempt was made to write to the reading %1.": "Det blev forsøgt at skrive til %1, som var i færd med at læse.",
	"An attempt was made to read from the writing %1.": "Det blev forsøgt at læse fra %1, som i øjeblikket er ved at skrive.",
	"%1 has a bad format.": "%1 har et ugyldigt format.",
	"%1 contained an unexpected object.": "%1 indeholdt et uventet objekt.",
	"%1 contains an incorrect schema.": "%1 indeholder et ugyldigt skema.",
	"Selects a rectangular part of the picture to move, copy, or edit.": "Markerer et firkantet område af billedet, som kan flyttes, kopieres eller redigeres ",
	"Select": "Marker",
	"Selects a free-form part of the picture to move, copy, or edit.": "Markerer et frihåndsudsnit af billedet, som kan flyttes, kopieres eller redigeres ",
	"Free-Form Select": "Frihåndsmarkering",
	"Inserts text into the picture.": "Indsætter tekst i billedet ",
	"Fills an area with the current drawing color.": "Udfylder et område med den aktuelle tegnefarve ",
	"Fill With Color": "Udfyld med farve",
	"Draws a straight line with the selected line width.": "Tegner en lige streg med den valgte stregtykkelse ",
	"Line": "Streger",
	"Draws using an airbrush of the selected size.": "Tegner med en airbrush af den markerede størrelse.",
	"Draws a curved line with the selected line width.": "Tegner en kurvet streg med den valgte stregtykkelse ",
	"Curve": "Kurver",
	"Draws a polygon with the selected fill style.": "Tegner en polygon med den valgte stregtykkelse og fyldtype ",
	"Polygon": "Polygoner",
	"Draws a rounded rectangle with the selected fill style.": "Tegner et afrundet rektangel med den valgte stregtykkelse og fyldtype ",
	"Rounded Rectangle": "Afrundet rektangel",
	"Draws a free-form line one pixel wide.": "Tegner en frihåndsstreg, som er én pixel bred ",
	"Pencil": "Blyant",
	"Erases a portion of the picture, using the selected eraser shape.": "Sletter en del af billedet med den markerede viskelæderform ",
	"Eraser/Color Eraser": "Viskelæder/Farveviskelæder",
	"Changes the magnification.": "Ændrer forstørrelsen ",
	"Magnifier": "Forstørrelsesglas",
	"Picks up a color from the picture for drawing.": "Samler en farve op fra billedet til at tegne med ",
	"Pick Color": "Vælg farve",
	"Draws using a brush with the selected shape and size.": "Tegner med en pensel med den valgte facon og størrelse ",
	"Brush": "Pensel",
	"Draws a rectangle with the selected fill style.": "Tegner et rektangel med den valgte stregtykkelse og det valgte fyldmønster ",
	"Rectangle": "Rektangel",
	"Draws a filled rectangle.": "Tegner et udfyldt rektangel",
	"Draws an ellipse with the selected fill style.": "Tegner en ellipse med den valgte stregtykkelse og det valgte fyldmønster ",
	"Draws a filled ellipse.": "Tegner en udfyldt ellipse",
	"Makes the current selection either opaque or transparent.": "Gør markeringen uigennemsigtigt eller gennemsigtigt",
	"Creates a new color.": "Opretter en ny farve",
	"Uses a previously saved palette of colors.": "Benytter en tidligere gemt farvepalet",
	"Saves the current palette of colors to a file.": "Gemmer den aktuelle farvepalet i en fil",
	"You must save the file before choosing it as Wallpaper.": "Du skal gemme filen, inden du vælger den som tapet.",
	"The selection is now larger than the bitmap.": "Det markerede område er større end bitmappen.",
	"Would you like the bitmap enlarged?": "Skal bitmappen forstørres?",
	"The image in the clipboard is larger than the bitmap.": "Billedet i Udklipsholder er større end bitmappen.",
	"The file is not in the correct format.": "Filen har ikke det rigtige format.",
	"Not enough room to paste text.": "Der er ikke plads nok til at indsætte tekst.",
	"Enlarge the text area and try again.": "Gør tekstområdet større, og prøv igen.",
	"Places the text.": "Placerer teksten"
});
