//
// NOTE: This is a generated file! Don't edit it directly.
// Eventually community translation will be set up on some translation platform.
// 
// Generated with: npm run update-localization
//
loaded_localizations("cs", {
	"Attributes": "Atributy",
	"&Width:": "Šíř&ka:",
	"Width:": "Šířka:",
	"&Height:": "Výšk&a:",
	"Height:": "Výška:",
	"Units": "Jednotky",
	"&Inches": "Pa&lce",
	"Inches": "Palce",
	"C&m": "&Cm",
	"Cm": "Cm",
	"&Pixels": "&Pixely",
	"Pixels": "Pixely",
	"Colors": "Barvy",
	"&Black and white": "Černo&bíle",
	"Black and white": "Černobíle",
	"Co&lors": "Ba&rvy",
	"Transparency": "Průhlednost",
	"Use &Transparent background color": "Použít prů&hlednou barvu pozadí",
	"Use Transparent background color": "Použít průhlednou barvu pozadí",
	"Select &Color": "V&ybrat barvu",
	"Select Color": "Vybrat barvu",
	"Cancel": "Storno",
	"&Default": "&Výchozí",
	"Default": "Výchozí",
	"Custom Zoom": "Vlastní měřítko",
	"Current zoom:": "Aktuální měřítko:",
	"Zoom to": "Měřítko",
	"Flip and Rotate": "Převrátit či otočit",
	"Flip or rotate": "Převrátit či otočit",
	"&Flip horizontal": "Převrátit vo&dorovně",
	"Flip horizontal": "Převrátit vodorovně",
	"Flip &vertical": "Převrátit &svisle",
	"Flip vertical": "Převrátit svisle",
	"&Rotate by angle": "O&točit o",
	"Rotate by angle": "Otočit o",
	"Stretch and Skew": "Roztáhnout či zkosit",
	"Stretch": "Roztáhnout",
	"&Horizontal:": "&Vodorovně:",
	"Horizontal:": "Vodorovně:",
	"&Vertical:": "&Svisle:",
	"Vertical:": "Svisle:",
	"Skew": "Zkosit",
	"H&orizontal:": "V&odorovně:",
	"Degrees": "stupňů",
	"V&ertical:": "Sv&isle:",
	"Color Table": "Tabulka barev",
	"New": "Nový",
	"&New ": "&Nový ",
	"New ": "Nový ",
	"&Help": "Nápo&věda",
	"Help": "Nápověda",
	"Printing": "Probíhá tisk",
	"on the": "na tiskárně",
	"&Print": "&Tisk",
	"Print": "Tisk",
	"&Next Page": "&Další",
	"Next Page": "Další",
	"Pre&v Page": "&Předchozí",
	"Prev Page": "Předchozí",
	"Zoom &In": "Při&blížit",
	"Zoom In": "Přiblížit",
	"Zoom &Out": "&Oddálit",
	"Zoom Out": "Oddálit",
	"&Close": "&Zavřít",
	"Close": "Zavřít",
	"Grid Settings": "Nastavení mřížky",
	"&Pixel Grid": "&Mřížka pixelů",
	"Pixel Grid": "Mřížka pixelů",
	"&Tile Grid": "Mřížka &obdélníků",
	"Tile Grid": "Mřížka obdélníků",
	"pixels": "pixelů",
	"H&eight:": "&Výška:",
	"Undo": "Zpět",
	"Cut": "Vyjmout",
	"Copy": "Kopírovat",
	"Paste": "Vložit",
	"Clear Selection": "Vymazat výběr",
	"Select All": "Vybrat vše",
	"Text Toolbar": "Panel nástrojů Text",
	"Selection": "Výběr",
	"Cu&t": "&Vyjmout",
	"&Copy": "&Kopírovat",
	"&Paste": "V&ložit",
	"C&lear Selection": "Vy&mazat výběr",
	"Select &All": "Vybr&at vše",
	"C&opy To": "Zkopírovat &do",
	"Copy To": "Zkopírovat do",
	"Paste &From": "Vloži&t z",
	"Paste From": "Vložit z",
	"Flip/&Rotate": "&Převrátit či otočit",
	"Flip/Rotate": "Převrátit či otočit",
	"&Stretch/Skew": "&Roztáhnout či zkosit",
	"Stretch/Skew": "Roztáhnout či zkosit",
	"&Invert Colors": "&Invertovat barvy",
	"Invert Colors": "Invertovat barvy",
	"Thumbnail": "Miniatura",
	"&File": "&Soubor",
	"File": "Soubor",
	"&New": "&Nový",
	"&Open": "&Otevřít",
	"Open": "Otevřít",
	"&Save": "&Uložit",
	"Save": "Uložit",
	"Save &As": "Uložit j&ako",
	"Save As": "Uložit jako",
	"Print Pre&view": "Ná&hled",
	"Print Preview": "Náhled",
	"Page Se&tup": "Vzhled &stránky",
	"Page Setup": "Vzhled stránky",
	"S&end": "O&deslat",
	"Send": "Odeslat",
	"Set As &Wallpaper (Tiled)": "Nastavit jako tapetu &vedle sebe",
	"Set As Wallpaper (Tiled)": "Nastavit jako tapetu vedle sebe",
	"Set As Wa&llpaper (Centered)": "Nastavit jako tapetu up&rostřed",
	"Set As Wallpaper (Centered)": "Nastavit jako tapetu uprostřed",
	"Recent File": "Minulý soubor",
	"E&xit": "&Konec",
	"Exit": "Konec",
	"&Edit": "Úpr&avy",
	"Edit": "Úpravy",
	"&Undo": "&Zpět",
	"&Repeat": "&Opakovat",
	"Repeat": "Opakovat",
	"&View": "&Zobrazit",
	"View": "Zobrazit",
	"&Tool Box": "Panel &nástrojů",
	"Tool Box": "Panel nástrojů",
	"&Color Box": "Panel &barev",
	"Color Box": "Panel barev",
	"&Status Bar": "&Stavový řádek",
	"Status Bar": "Stavový řádek",
	"T&ext Toolbar": "&Panel nástrojů Text",
	"&Zoom": "&Lupa",
	"Zoom": "Lupa",
	"&Normal Size": "&Normální velikost",
	"Normal Size": "Normální velikost",
	"&Large Size": "V&elká velikost",
	"Large Size": "Velká velikost",
	"C&ustom": "&Vlastní",
	"Custom": "Vlastní",
	"Show &Grid": "&Zobrazit mřížku",
	"Show Grid": "Zobrazit mřížku",
	"Show T&humbnail": "Zobrazit &miniaturu",
	"Show Thumbnail": "Zobrazit miniaturu",
	"&View Bitmap": "&Celá obrazovka",
	"View Bitmap": "Celá obrazovka",
	"&Image": "&Obraz",
	"Image": "Obraz",
	"&Flip/Rotate": "&Převrátit či otočit",
	"&Attributes": "&Atributy",
	"&Clear Image": "Vy&mazat",
	"Clear Image": "Vymazat",
	"Ctrl+Shft+N": "Ctrl+Shift+N",
	"&Draw Opaque": "&Kreslit neprůhledně",
	"Draw Opaque": "Kreslit neprůhledně",
	"&Colors": "&Barvy",
	"&Edit Colors": "&Upravit barvy",
	"Edit Colors": "Upravit barvy",
	"&Help Topics": "&Témata nápovědy",
	"Help Topics": "Témata nápovědy",
	"&About Paint": "&O aplikaci Malování",
	"About Paint": "O aplikaci Malování",
	"&Update": "&Aktualizovat",
	"Update": "Aktualizovat",
	"Save Copy &As": "&Uložit kopii jako",
	"Save Copy As": "Uložit kopii jako",
	"Paint": "Malování",
	"untitled": "Bez_názvu",
	"Bitmap Image": "Rastrový obraz",
	"Bitmap Files (*.bmp)": "Rastrové soubory (*.bmp)",
	"Paint.Picture": "Obraz programu Malování",
	"PCX Files": "Soubory PCX",
	"Icon Files": "Soubory ikon",
	"Monochrome Bitmap (*.bmp;*.dib)": "Černobílý rastr (*.bmp;*.dib)",
	"16 Color Bitmap (*.bmp;*.dib)": "16barevný rastr (*.bmp;*.dib)",
	"256 Color Bitmap (*.bmp;*.dib)": "256barevný rastr (*.bmp;*.dib)",
	"Paint cannot open this file.": "Program Malování nemůže otevřít tento soubor.",
	"Paint cannot read this file.": "Program Malování nemůže přečíst tento soubor.",
	"This file is read-only.": "Tento soubor je jen pro čtení.",
	"To save your changes, use a different filename.": "Chcete-li změny uložit, zadejte jiný název souboru.",
	"This file is already open.": "Tento soubor je již otevřen.",
	"This is not a valid .PCS file.": "Toto není platný soubor typu .PCS.",
	"This file is open for editing and cannot be overwritten.": "Soubor je otevřen pro úpravy a nelze ho přepsat.",
	"Use a different filename to save your changes.": "Chcete-li změny uložit, zadejte jiný název souboru.",
	"This is not a valid bitmap file, or its format is not currently supported.": "Toto není platný soubor s rastrovým obrázkem nebo jeho formát není nyní podporován.",
	"This is not a valid icon.": "Toto není platná ikona.",
	"This is not a valid cursor.": "Toto není platný kurzor.",
	"Save was interrupted, so your file has not been saved.": "Ukládání bylo přerušeno, soubor není uložen.",
	"You cannot save to a read-only file.": "Nelze uložit soubor, který je jen pro čtení.",
	"Use a different file name.": "Zadejte jiný název souboru.",
	"This file is already in use.": "Tento soubor je již používán.",
	"Close the program, and then try again.": "Program zavřete a akci zopakujte.",
	"Paint cannot save this file.": "Program Malování nemůže tento soubor uložit.",
	"Paint cannot save to the same filename with a different file type.": "Program Malování nemůže uložit pod stejným názvem soubor jiného typu.",
	"The grid spacing must be an integer between %d and %d.": "Hustota mřížky se zadává jako celé číslo hodnoty %d až %d.",
	"There is not enough memory or resources to complete operation.": "K dokončení operace není dost paměti nebo prostředků.",
	"Close some programs, and then try again.": "Zavřete některé programy a akci zopakujte.",
	"Low on memory or resources.": "Nedostatek paměti nebo prostředků.",
	"Group error.": "Chyba skupiny.",
	"Paint was unable to print your document. Please make sure you have sufficient disk space and that your printer is working correctly.": "Program Malování nemůže dokument vytisknout. Přesvědčte se, zda je na disku dostatek místa a zda tiskárna pracuje správně.",
	"Saving into this format may cause some loss of color information.": "Uložení v tomto formátu může způsobit ztrátu některých informací o barvě.",
	"Do you want to continue?": "Chcete pokračovat?",
	"Converting to black and white cannot be undone.  This action affects the current file and may cause some loss of color information.": "Převod na černobílý obrázek nelze vzít zpět. Tato akce upraví aktivní soubor a může způsobit ztrátu informací o barvách.",
	"Bitmaps must be greater than one pixel on a side.": "Velikost strany rastru musí být větší než jeden pixel.",
	"Generic error.": "Došlo k obecné chybě.",
	"File not found.": "Soubor nebyl nalezen.",
	"Bad path.": "Chybná cesta.",
	"Too many open files.": "Je otevřeno příliš mnoho souborů.",
	"Access denied.": "Přístup odepřen.",
	"Invalid file.": "Neplatný soubor.",
	"Remove current folder.": "Odstranit aktuální složku.",
	"Folder full.": "Složka je plná.",
	"Bad seek.": "Chybné hledání.",
	"Hard IO error.": "Došlo k závažné vstupně-výstupní chybě.",
	"Sharing violation.": "Byla narušeno sdílení.",
	"Lock violation.": "Bylo narušeno uzamčení.",
	"Disk full.": "Disk je plný.",
	"End of file.": "Konec souboru.",
	"Error getting the Clipboard Data!": "Při získávání dat ze schránky došlo k chybě.",
	"No Printer Found @ page setup": "Nebyla nalezena tiskárna pro nastavení stránky",
	"24-bit Bitmap (*.bmp;*.dib)": "24bitový rastr (*.bmp;*.dib)",
	"All Files": "Všechny soubory",
	"Palette|*.pal|": "Paleta|*.pal|",
	"untitled.pal": "bez_názvu.pal",
	"OLE 2.0 was unable to start.": "OLE 2.0 nelze spustit.",
	"Make sure that you are using the correct version of the OLE libraries.": "Ujistěte se, zda používáte správnou verzi knihoven OLE.",
	"Resets the text be without any attributes.": "Zruší všechny atributy textu.",
	"Sets or clears the text bold attribute.": "Zapne nebo vypne tučné písmo.",
	"Sets or clears the text italic attribute.": "Zapne nebo vypne kurzívu.",
	"Selects the font used by the text.": "Vybere písmo pro psaní textu.",
	"Selects the point size of the text.": "Vybere výšku textu (v bodech).",
	"Sets or clears the text underline attribute.": "Zapne nebo vypne podtržení písma.",
	"Shows or hides the tooltips.": "Zobrazí nebo skryje tipy panelů.",
	"Show Paint Help.": "Zobrazí nápovědu programu Malování.",
	"Sends a picture by using mail or fax.": "Odešle obrázek poštou nebo faxem.",
	"Copies the selection to a file.": "Zkopíruje vybranou část do souboru.",
	"Pastes a file into the selection.": "Vloží soubor do vybrané části.",
	"Zooms the picture to 100%.": "Nastaví měřítko na 100%.",
	"Zooms the picture to 400%.": "Nastaví měřítko na 400%.",
	"Zooms the picture.": "Přiblíží obrázek.",
	"Displays the entire picture.": "Zobrazí celý obrázek.",
	"Shows or hides the thumbnail view of the picture.": "Zobrazí nebo skryje miniaturu.",
	"Shows or hides the grid.": "Zobrazí nebo skryje mřížku.",
	"Shows or hides the text toolbar.": "Zobrazí nebo skryje panel nástrojů Text.",
	"Flips or rotates the picture or a selection.": "Převrátí nebo otočí obrázek nebo vybranou část.",
	"Stretches or skews the picture or a selection.": "Roztáhne nebo zkosí obrázek nebo vybranou část.",
	"Inverts the colors of the picture or a selection.": "Invertuje barvy obrázku nebo vybrané části.",
	"Changes the attributes of the picture.": "Změní atributy obrázku.",
	"Clears the picture or selection.": "Vymaže obrázek nebo vybranou část.",
	"The font size must be a numeric value.": "Velikost písma musí být číslo.",
	"Contains commands for working with the selected item(s).": "Obsahuje příkazy pro práci s vybranými položkami.",
	"Contains commands for selecting and transferring items.": "Obsahuje příkazy pro výběr a přenos položek.",
	"Contains commands for customizing this window.": "Obsahuje příkazy pro přizpůsobení vzhledu okna.",
	"Contains commands for manipulating pictures and setting attributes.": "Obsahuje příkazy pro manipulaci s obrázkem a pro nastavení atributů.",
	"Contains commands for using custom colors and drawing options.": "Obsahuje příkazy pro práci s barvami a pro nastavení možností kreslení.",
	"Contains commands for displaying Help for and information about Paint.": "Obsahuje příkazy pro zobrazení nápovědy a informací o programu Malování.",
	"Cannot save file.": "Soubor nelze uložit.",
	"Error removing temporary file.": "Při odstraňování dočasného souboru došlo k chybě.",
	"Get Colors": "Převzít barvy",
	"Save Colors": "Uložit barvy",
	"File last saved:": "Naposledy uložený soubor:",
	"Not Available": "Není k dispozici",
	"Size on disk:": "Místo na disku:",
	"%s bytes": "%s bajtů",
	"Painting": "Kreslení",
	"Fonts": "Písma",
	"Tools": "Nástroje",
	"All Picture Files": "Všechny soubory obrázků",
	"For Help, click Help Topics on the Help Menu.": "Nápovědu získáte klepnutím na položku Témata nápovědy v nabídce Nápověda.",
	"Select an area on which to get Help.": "Klepněte na oblast obrazovky, ke které chcete nápovědu.",
	"%1 in %2": "%1 v %2",
	"Creates a new document.": "Vytvoří nový dokument.",
	"Opens an existing document.": "Otevře dříve vytvořený dokument.",
	"Closes the active document.": "Zavře aktivní dokument.",
	"Saves the active document.": "Uloží aktivní dokument.",
	"Saves the active document with a new name.": "Uloží aktivní dokument pod novým názvem.",
	"Changes the page layout.": "Změní vzhled tiskové stránky.",
	"Specifies the default printer setup.": "Nastaví výchozí tiskárnu.",
	"Prints the active document and sets printing options.": "Vytiskne aktivní dokument a určí způsob tisku.",
	"Displays full pages.": "Zobrazí tiskové stránky.",
	"Opens this document.": "Otevře tento dokument.",
	"Deletes the selection.": "Odstraní vybranou část.",
	"Erases everything.": "Vymaže všechno.",
	"Copies the selection and puts it on the Clipboard.": "Zkopíruje výběr do schránky.",
	"Cuts the selection and puts it on the Clipboard.": "Vyjme výběr a vloží ho do schránky.",
	"Finds the specified text.": "Hledá zadaný text.",
	"Inserts the contents of the Clipboard.": "Vloží obsah schránky.",
	"Repeats the last action.": "Zopakuje předchozí akci.",
	"Replaces specific text with different text.": "Nahradí zadaný text jiným textem.",
	"Selects everything.": "Vybere všechno.",
	"Undoes the last action.": "Vrátí zpět poslední akci.",
	"Redoes the previously undone action.": "Znovu provede vrácenou akci.",
	"Displays program information, version number, and copyright.": "Zobrazí informace o programu, verzi a o autorských právech.",
	"Quits Paint.": "Ukončí program Malování.",
	"Opens Paint Help.": "Otevře nápovědu programu Malování.",
	"Displays instructions about how to use Help.": "Zobrazí návod k práci s nápovědou.",
	"Displays Help for areas you click on.": "Zobrazí nápovědu k místům, na která klepnete.",
	"Displays Help for the current task or command.": "Zobrazí nápovědu k úkolu nebo příkazu.",
	"Centers this bitmap as the desktop wallpaper.": "Použije vycentrovaný obrázek jako tapetu pracovní plochy.",
	"Tiles this bitmap as the desktop wallpaper.": "Opakováním obrázku vytvoří tapetu pracovní plochy.",
	"Sends the selection using mail or fax.": "Odešle výběr poštou nebo faxem.",
	"Prints the selection.": "Vytiskne výběr.",
	"Shows or hides the thumbnail.": "Zobrazí nebo skryje miniaturu.",
	"Shows Paint Help.": "Zobrazí nápovědu programu Malování.",
	"Shows or hides the status bar.": "Zobrazí nebo skryje stavový řádek.",
	"Shows or hides the tool box.": "Zobrazí nebo skryje panel nástrojů.",
	"Shows or hides the color box.": "Zobrazí nebo skryje panel barev.",
	"Only a Far East font can be used for vertical editing.": "V režimu svislých úprav může být použito pouze písmo pro Vzdálený východ.",
	"Changes the window size.": "Změní velikost okna.",
	"Changes the window position.": "Změní polohu okna.",
	"Reduces the window to an icon.": "Zmenší okno do ikony.",
	"Enlarges the window to full size.": "Zvětší okno na plnou velikost.",
	"Switches to the next document window.": "Přepne do dalšího okna dokumentu.",
	"Switches to the previous document window.": "Přepne do předchozího okna dokumentu.",
	"Closes the active window and asks if you want to save changes.": "Zavře aktivní okno a dotáže se na uložení změn.",
	"Restores the window to normal size.": "Obnoví normální velikost okna.",
	"Activates the task list.": "Aktivuje seznam úkolů.",
	"All Files (*.*)": "Všechny soubory (*.*)",
	"Untitled": "Bez názvu",
	"an unnamed file": "Soubor bez názvu",
	"&Hide": "&Skrýt",
	"Hide": "Skrýt",
	"No error message is available.": "Není dostupná žádná chybová zpráva.",
	"An unsupported operation was attempted.": "Byl učiněn pokus o nepodporovanou operaci.",
	"A required resource was unavailable.": "Požadovaný zdroj nebyl dostupný.",
	"Out of memory.": "Nedostatek paměti.",
	"An unknown error has occurred.": "Došlo k neznámé chybě.",
	"on %1": "Na %1",
	"&One Page": "&Jedna stránka",
	"One Page": "Jedna stránka",
	"&Two Page": "&Dvě stránky",
	"Two Page": "Dvě stránky",
	"Page %u": "Stránka %u",
	"Pages %u-%u": "stránky %u-%u",
	"Printer Files (*.prn)|*.prn|All Files (*.*)|*.*||": "Soubory tiskárny (*.prn)|*.prn|Všechny soubory (*.*)|*.*||",
	"Print to File": "Tisk do souboru",
	"to %1": "do %1",
	"&Update %1": "&Aktualizovat %1",
	"Update %1": "Aktualizovat %1",
	"E&xit && Return to %1": "&Ukončit a návrat do %1",
	"Exit && Return to %1": "Ukončit a návrat do %1",
	"Linked %s": "Připojený objekt %s",
	"Unknown Type": "Neznámý typ",
	"Invalid filename.": "Neplatný název souboru.",
	"Failed to open document.": "Dokument se nepodařilo otevřít.",
	"Failed to save document.": "Dokument se nepodařilo uložit.",
	"Save changes to %1?": "Chcete uložit změny v dokumentu %1?",
	"Failed to create empty document.": "Nepodařilo se vytvořit prázdný dokument.",
	"The file is too large to open.": "Soubor je pro otevření příliš veliký.",
	"Could not start print job.": "Tiskovou úlohu nelze zahájit.",
	"Failed to launch help.": "Nepodařilo se spustit nápovědu.",
	"Internal application error.": "Došlo k vnitřní chybě aplikace.",
	"Command failed.": "Došlo k chybě příkazu.",
	"Insufficient memory to perform operation.": "K provedení operace není dostatek paměti.",
	"System registry entries have been removed and the INI file (if any) was deleted.": "Položky systémového registru byly odebrány a soubor INI, pokud existoval, byl odstraněn.",
	"Not all of the system registry entries (or INI file) were removed.": "Nebyly odebrány všechny položky registru nebo soubor INI.",
	"This program requires the file %s, which was not found on this system.": "Tento program vyžaduje soubor %s, který ve vašem systému nebyl nalezen.",
	"This program is linked to the missing export %s in the file %s. This machine may have an incompatible version of %s.": "Tento program je propojen s nenalezeným exportem %s v souboru %s. Tento počítač může obsahovat nekompatibilní verzi %s.",
	"Please enter an integer.": "Zadejte celé číslo.",
	"Please enter a number.": "Zadejte číslo.",
	"Please enter an integer between %1 and %2.": "Zadejte celé číslo od %1 do %2.",
	"Please enter a number between %1 and %2.": "Zadejte číslo od %1 do %2.",
	"Please enter no more than %1 characters.": "Zadejte maximálně %1 znaků.",
	"Please select a button.": "Klepněte na tlačítko.",
	"Please enter an integer between 0 and 255.": "Zadejte celé číslo od 0 do 255.",
	"Please enter a positive integer.": "Zadejte celé kladné číslo.",
	"Please enter a date and/or time.": "Zadejte datum nebo čas.",
	"Please enter a currency.": "Zadejte měnu.",
	"Unexpected file format.": "Neočekávaný formát souboru.",
	"Cannot find this file.": "Tento soubor nelze najít.",
	"Please verify that the correct path and file name are given.": "Zkontrolujte zadanou cestu a název souboru.",
	"Destination disk drive is full.": "Cílový disk je zaplněn.",
	"Unable to read from %1, it is opened by someone else.": "%1 nelze otevřít; je otevřen jiným programem.",
	"Unable to write to %1, it is read-only or opened by someone else.": "%1 nelze uložit; je jen pro čtení nebo je otevřen jiným programem.",
	"An unexpected error occurred while reading %1.": "Došlo k neočekávané chybě během čtení souboru %1.",
	"An unexpected error occurred while writing %1.": "Došlo k neočekávané chybě během zápisu do souboru %1.",
	"Unable to register document.": "Dokument nelze zaregistrovat.",
	"The document may already be open.": "Možná je již otevřen.",
	"Update %1 before proceeding?": "Chcete %1 před pokračováním zaktualizovat?",
	"Could not update client.": "Klienta nelze zaktualizovat.",
	"Failed to register. ActiveX features may not work properly.": "Při registraci došlo k chybě. Funkce ActiveX nemusí pracovat správně.",
	"Failed to update the system registry.": "Nepodařilo se zaktualizovat systémový registr.",
	"Please try using REGEDIT.": "Zkuste použít program REGEDIT.",
	"Unable to read write-only property.": "Nelze přečíst vlastnost, která je jen pro zápis.",
	"Unable to write read-only property.": "Nelze zapsat vlastnost, která je jen pro čtení.",
	"Unable to load mail system support.": "Nelze načíst systémovou podporu pošty.",
	"Mail system DLL is invalid.": "Systémová dynamická knihovna pošty není platná.",
	"Send Mail failed to send message.": "Modul Send Mail nemohl odeslat zprávu.",
	"No error occurred.": "Nedošlo k žádné chybě.",
	"An unknown error occurred while accessing %1.": "Při přístupu k %1 došlo k neznámé chybě.",
	"%1 was not found.": "%1 nebyl nalezen.",
	"%1 contains an invalid path.": "%1 obsahuje neplatnou cestu.",
	"%1 could not be opened because there are too many open files.": "%1 nemohl být otevřen, protože je otevřeno příliš mnoho souborů.",
	"Access to %1 was denied.": "Přístup k %1 byl odepřen.",
	"An invalid file handle was associated with %1.": "K %1 byl přidružen neplatný souborový manipulátor.",
	"%1 could not be removed because it is the current directory.": "%1 nemohl být odstraněn, protože to je aktuální adresář.",
	"%1 could not be created because the directory is full.": "%1 nemohl být vytvořen, protože adresář je plný.",
	"Seek failed on %1": "Hledání selhalo na %1",
	"A hardware I/O error was reported while accessing %1.": "Při přístupu k %1 byla ohlášena vstupně-výstupní chyba hardwaru.",
	"A sharing violation occurred while accessing %1.": "Při přístupu k %1 došlo k porušení sdílení.",
	"A locking violation occurred while accessing %1.": "Při přístupu k %1 došlo k porušení uzamčení.",
	"Disk full while accessing %1.": "Při přístupu k %1 došlo k zaplnění disku.",
	"An attempt was made to access %1 past its end.": "Byl učiněn pokus přistoupit k %1 po jeho ukončení.",
	"An attempt was made to write to the reading %1.": "Byl učiněn pokus zapsat při čtení %1.",
	"An attempt was made to read from the writing %1.": "Byl učiněn pokus číst při zápisu do %1.",
	"%1 has a bad format.": "%1 má chybný formát.",
	"%1 contained an unexpected object.": "%1 obsahoval neočekávaný objekt.",
	"%1 contains an incorrect schema.": "%1 obsahuje nesprávné schéma.",
	"Selects a rectangular part of the picture to move, copy, or edit.": "Vybere pravoúhlou část obrázku, která může být přesouvána, kopírována nebo upravována.",
	"Select": "Výběr",
	"Selects a free-form part of the picture to move, copy, or edit.": "Ohraničením vybere část obrázku, která může být přesouvána, kopírována nebo upravována.",
	"Free-Form Select": "Výběr libovolného tvaru",
	"Inserts text into the picture.": "Zapíše text do obrázku.",
	"Fills an area with the current drawing color.": "Vyplní oblast aktuální barvou pera.",
	"Fill With Color": "Plechovka",
	"Draws a straight line with the selected line width.": "Nakreslí úsečku zvolené tloušťky.",
	"Line": "Úsečka",
	"Draws using an airbrush of the selected size.": "Maluje sprejem zvolené velikosti.",
	"Airbrush": "Sprej",
	"Draws a curved line with the selected line width.": "Kreslí křivku zvolené tloušťky.",
	"Curve": "Křivka",
	"Draws a polygon with the selected fill style.": "Kreslí mnohoúhelník se zvolenou výplní.",
	"Polygon": "Mnohoúhelník",
	"Draws a rounded rectangle with the selected fill style.": "Kreslí zaoblený obdélník se zvolenou výplní.",
	"Rounded Rectangle": "Zaoblený obdélník",
	"Draws a free-form line one pixel wide.": "Kreslí od ruky čáru tloušťky 1 bod.",
	"Pencil": "Tužka",
	"Erases a portion of the picture, using the selected eraser shape.": "Vymaže část obrázku zvoleným tvarem gumy.",
	"Eraser/Color Eraser": "Guma a barevná guma",
	"Changes the magnification.": "Změní měřítko zobrazení.",
	"Magnifier": "Lupa",
	"Picks up a color from the picture for drawing.": "Nabere z obrázku barvu do pera.",
	"Pick Color": "Kapátko",
	"Draws using a brush with the selected shape and size.": "Maluje štětcem zvoleného tvaru a tloušťky.",
	"Brush": "Štětec",
	"Draws a rectangle with the selected fill style.": "Kreslí obdélník se zvolenou výplní.",
	"Rectangle": "Obdélník",
	"Draws a filled rectangle.": "Kreslí plný obdélník.",
	"Draws an ellipse with the selected fill style.": "Kreslí elipsu se zvolenou výplní.",
	"Ellipse": "Elipsa",
	"Draws a filled ellipse.": "Kreslí plnou elipsu.",
	"Makes the current selection either opaque or transparent.": "Změní aktuální výběr na neprůhledný nebo průhledný.",
	"Creates a new color.": "Připraví novou barvu.",
	"Uses a previously saved palette of colors.": "Použije dříve uloženou paletu barev.",
	"Saves the current palette of colors to a file.": "Uloží tuto barevnou paletu do souboru.",
	"You must save the file before choosing it as Wallpaper.": "Než obrázek použijete jako tapetu, musíte ho uložit.",
	"The selection is now larger than the bitmap.": "Vybraná část je nyní větší než rastr.",
	"Would you like the bitmap enlarged?": "Chcete rastr zvětšit?",
	"The image in the clipboard is larger than the bitmap.": "Obraz ve schránce je větší než rastr.",
	"The file is not in the correct format.": "Formát souboru není správný.",
	"Not enough room to paste text.": "K vložení textu není dost místa.",
	"Enlarge the text area and try again.": "Zvětšete oblast pro text a akci zopakujte.",
	"Places the text.": "Umístí text."
});
