//
// NOTE: This is a generated file! Don't edit it directly.
// Eventually community translation will be set up on some translation platform.
// 
// Generated with: npm run update-localization
//
loaded_localizations("nl", {
	"Attributes": "Kenmerken",
	"&Width:": "&Breedte:",
	"Width:": "Breedte:",
	"&Height:": "&Hoogte:",
	"Height:": "Hoogte:",
	"Units": "Eenheden",
	"C&m": "&Cm",
	"Cm": "Cm",
	"Colors": "Kleuren",
	"&Black and white": "&Zwart-wit",
	"Black and white": "Zwart-wit",
	"Co&lors": "&Kleuren",
	"Transparency": "Doorzichtigheid",
	"Use &Transparent background color": "&Doorzichtige achtergrondkleur gebruiken",
	"Use Transparent background color": "Doorzichtige achtergrondkleur gebruiken",
	"Select &Color": "Kl&eur kiezen",
	"Select Color": "Kleur selecteren",
	"Cancel": "Annuleren",
	"&Default": "&Standaard",
	"Default": "Standaard",
	"Custom Zoom": "In-/uitzoomen aanpassen",
	"Current zoom:": "Huidig in-/uitzoomniveau:",
	"Zoom to": "In-/uitzoomen naar",
	"Flip and Rotate": "Spiegelen en draaien",
	"Flip or rotate": "Spiegelen of draaien",
	"&Flip horizontal": "&Horizontaal spiegelen",
	"Flip horizontal": "Horizontaal spiegelen",
	"Flip &vertical": "&Verticaal spiegelen",
	"Flip vertical": "Verticaal spiegelen",
	"&Rotate by angle": "&Draaihoek",
	"Rotate by angle": "Draaihoek",
	"Stretch and Skew": "Uitrekken en hellen",
	"Stretch": "Uitrekken",
	"&Horizontal:": "&Horizontaal:",
	"Horizontal:": "Horizontaal:",
	"&Vertical:": "&Verticaal:",
	"Vertical:": "Verticaal:",
	"Skew": "Hellen",
	"H&orizontal:": "H&orizontaal:",
	"Degrees": "Graden",
	"V&ertical:": "V&erticaal:",
	"Color Table": "Kleurentabel",
	"New": "Nieuw",
	"&New ": "&Nieuw ",
	"New ": "Nieuw ",
	"Printing": "Bezig met afdrukken van",
	"on the": "op",
	"&Print": "Af&drukken",
	"Print": "Afdrukken",
	"&Next Page": "Vo&lgende pagina",
	"Next Page": "Volgende pagina",
	"Pre&v Page": "Vo&rige pagina",
	"Prev Page": "Vorige pagina",
	"Zoom &In": "&Inzoomen",
	"Zoom In": "Inzoomen",
	"Zoom &Out": "&Uitzoomen",
	"Zoom Out": "Uitzoomen",
	"&Close": "&Sluiten",
	"Close": "Sluiten",
	"Grid Settings": "Rasterinstellingen",
	"&Pixel Grid": "&Pixels",
	"Pixel Grid": "Pixels",
	"&Tile Grid": "B&lokken",
	"Tile Grid": "Blokken",
	"H&eight:": "&Hoogte:",
	"Text": "Tekst",
	"Undo": "Ongedaan maken",
	"Cut": "Knippen",
	"Copy": "Kopiëren",
	"Paste": "Plakken",
	"Clear Selection": "Selectie wissen",
	"Select All": "Alles selecteren",
	"Text Toolbar": "Werkbalk Tekst",
	"Selection": "Selectie",
	"Cu&t": "K&nippen",
	"&Copy": "&Kopiëren",
	"&Paste": "&Plakken",
	"C&lear Selection": "Se&lectie wissen",
	"Select &All": "&Alles selecteren",
	"C&opy To": "K&opiëren naar",
	"Copy To": "Kopiëren naar",
	"Paste &From": "Plakken &uit",
	"Paste From": "Plakken uit",
	"Flip/&Rotate": "&Spiegelen/draaien",
	"Flip/Rotate": "Spiegelen/draaien",
	"&Stretch/Skew": "Uit&rekken/hellen",
	"Stretch/Skew": "Uitrekken/hellen",
	"&Invert Colors": "Nega&tief",
	"Invert Colors": "Negatief",
	"Thumbnail": "Schets",
	"&File": "&Bestand",
	"File": "Bestand",
	"&New": "&Nieuw",
	"&Open": "&Openen",
	"Open": "Openen",
	"&Save": "O&pslaan",
	"Save": "Opslaan",
	"Save &As": "Ops&laan als",
	"Save As": "Opslaan als",
	"Print Pre&view": "A&fdrukvoorbeeld",
	"Print Preview": "Afdrukvoorbeeld",
	"Page Se&tup": "Pag&ina-instelling",
	"Page Setup": "Pagina-instelling",
	"S&end": "Bericht &verzenden",
	"Send": "Bericht verzenden",
	"Set As &Wallpaper (Tiled)": "Ins&tellen als achtergrond (naast elkaar)",
	"Set As Wallpaper (Tiled)": "Instellen als achtergrond (naast elkaar)",
	"Set As Wa&llpaper (Centered)": "In&stellen als achtergrond (gecentreerd)",
	"Set As Wallpaper (Centered)": "Instellen als achtergrond (gecentreerd)",
	"Recent File": "Recent bestand",
	"E&xit": "&Afsluiten",
	"Exit": "Afsluiten",
	"&Edit": "Be&werken",
	"Edit": "Bewerken",
	"&Undo": "&Ongedaan maken",
	"&Repeat": "&Herhalen",
	"Repeat": "Herhalen",
	"&View": "Beel&d",
	"View": "Beeld",
	"&Tool Box": "&Werkset",
	"Tool Box": "Werkset",
	"&Color Box": "&Kleurenset",
	"Color Box": "Kleurenset",
	"&Status Bar": "&Statusbalk",
	"Status Bar": "Statusbalk",
	"T&ext Toolbar": "W&erkbalk Tekst",
	"&Zoom": "In-/uit&zoomen",
	"Zoom": "In-/uitzoomen",
	"&Normal Size": "&Normaal formaat",
	"Normal Size": "Normaal formaat",
	"&Large Size": "&Groot formaat",
	"Large Size": "Groot formaat",
	"C&ustom": "&Aanpassen",
	"Custom": "Aanpassen",
	"Show &Grid": "&Raster weergeven",
	"Show Grid": "Raster weergeven",
	"Show T&humbnail": "&Schets weergeven",
	"Show Thumbnail": "Schets weergeven",
	"&View Bitmap": "&Bitmap weergeven",
	"View Bitmap": "Bitmap weergeven",
	"&Image": "&Afbeelding",
	"Image": "Afbeelding",
	"&Flip/Rotate": "&Spiegelen/draaien",
	"&Attributes": "&Kenmerken",
	"&Clear Image": "&Afbeelding wissen",
	"Clear Image": "Afbeelding wissen",
	"&Draw Opaque": "On&doorzichtig tekenen",
	"Draw Opaque": "Ondoorzichtig tekenen",
	"&Colors": "&Kleuren",
	"&Edit Colors": "Kleuren &bewerken",
	"Edit Colors": "Kleuren bewerken",
	"&Help Topics": "&Help-onderwerpen",
	"Help Topics": "Help-onderwerpen",
	"&About Paint": "&Info",
	"About Paint": "Info",
	"&Update": "&Bijwerken",
	"Update": "Bijwerken",
	"Save Copy &As": "K&opie opslaan als",
	"Save Copy As": "Kopie opslaan als",
	"untitled": "naamloos",
	"Bitmap Image": "Bitmapafbeelding",
	"Bitmap Files (*.bmp)": "Bitmapbestanden (*.bmp)",
	"PCX Files": "PCX-bestanden",
	"Icon Files": "Pictogrambestanden",
	"Monochrome Bitmap (*.bmp;*.dib)": "Monochrome bitmap (*.bmp;*.dib)",
	"16 Color Bitmap (*.bmp;*.dib)": "16-kleuren bitmap (*.bmp;*.dib)",
	"256 Color Bitmap (*.bmp;*.dib)": "256-kleuren bitmap (*.bmp;*.dib)",
	"Paint cannot open this file.": "Paint kan dit bestand niet openen.",
	"Paint cannot read this file.": "Paint kan dit bestand niet lezen.",
	"This file is read-only.": "Dit is een alleen-lezenbestand.",
	"To save your changes, use a different filename.": "Om wijzigingen op te slaan moet u een andere bestandsnaam gebruiken.",
	"This file is already open.": "Het bestand is al geopend.",
	"This is not a valid .PCS file.": "Dit is geen geldig .PCS-bestand.",
	"This file is open for editing and cannot be overwritten.": "Dit bestand wordt momenteel bewerkt en kan daarom niet worden overschreven.",
	"Use a different filename to save your changes.": "Gebruik een andere bestandsnaam om uw wijzigingen op te slaan.",
	"This is not a valid bitmap file, or its format is not currently supported.": "Dit is geen geldig bitmapbestand, of deze opmaak wordt niet ondersteund.",
	"This is not a valid icon.": "Dit is geen geldig pictogram.",
	"This is not a valid cursor.": "Dit is geen geldige cursor.",
	"Save was interrupted, so your file has not been saved.": "Opslaan is afgebroken. Het bestand is niet opgeslagen.",
	"You cannot save to a read-only file.": "Opslaan naar een alleen-lezenbestand is niet mogelijk.",
	"Use a different file name.": "Gebruik een andere bestandsnaam.",
	"This file is already in use.": "Het bestand is al in gebruik.",
	"Close the program, and then try again.": "Sluit de toepassing af en probeer het opnieuw.",
	"Paint cannot save this file.": "Paint kan dit bestand niet opslaan.",
	"Paint cannot save to the same filename with a different file type.": "Paint kan een ander bestandstype niet met dezelfde bestandsnaam opslaan.",
	"The grid spacing must be an integer between %d and %d.": "De rasterafstand moet een geheel getal zijn tussen %d en %d.",
	"There is not enough memory or resources to complete operation.": "Onvoldoende geheugen of bronnen om de bewerking te voltooien.",
	"Close some programs, and then try again.": "Sluit enkele programma's af en probeer het opnieuw.",
	"Low on memory or resources.": "Onvoldoende vrij geheugen of vrije bronnen.",
	"Group error.": "Groepsfout.",
	"Paint was unable to print your document. Please make sure you have sufficient disk space and that your printer is working correctly.": "Paint kan het document niet afdrukken. Controleer of er voldoende schijfruimte is, en de printer aan staat.",
	"Saving into this format may cause some loss of color information.": "Als u in dit formaat opslaat, kunnen kleurgegevens verloren gaan.",
	"Do you want to continue?": "Wilt u toch doorgaan?",
	"Converting to black and white cannot be undone.  This action affects the current file and may cause some loss of color information.": "Een conversie naar zwart-wit kan niet ongedaan worden gemaakt. Deze actie heeft gevolgen voor het actieve bestand en kan tot verlies van kleurinformatie lijden.",
	"Bitmaps must be greater than one pixel on a side.": "Bitmaps moeten groter zijn dan 1 x 1 pixel.",
	"Generic error.": "Algemene fout.",
	"File not found.": "Het bestand is niet gevonden.",
	"Bad path.": "Ongeldig pad.",
	"Too many open files.": "Er zijn te veel geopende bestanden.",
	"Access denied.": "De toegang is geweigerd.",
	"Invalid file.": "Ongeldig bestand.",
	"Remove current folder.": "Actieve map verwijderen.",
	"Folder full.": "Map vol.",
	"Bad seek.": "Ongeldige zoekactie.",
	"Hard IO error.": "Hardwarematige I/O-fout.",
	"Sharing violation.": "Fout bij delen.",
	"Lock violation.": "Fout bij vergrendelen.",
	"Disk full.": "De schijf is vol.",
	"End of file.": "Einde van bestand.",
	"Error getting the Clipboard Data!": "Fout bij ophalen van Klembord-gegevens.",
	"No Printer Found @ page setup": "Geen printer gevonden bij pagina-instelling",
	"24-bit Bitmap (*.bmp;*.dib)": "24-bits bitmap (*.bmp;*.dib)",
	"All Files": "Alle bestanden",
	"Palette|*.pal|": "Palet|*.pal|",
	"OLE 2.0 was unable to start.": "Opstarten van OLE 2.0 niet gelukt.",
	"Make sure that you are using the correct version of the OLE libraries.": "Zorg ervoor dat u de juiste versie van de OLE-bibliotheken gebruikt.",
	"Resets the text be without any attributes.": "Alle tekstkenmerken wissen",
	"Sets or clears the text bold attribute.": "Het tekstkenmerk Vet instellen of wissen",
	"Sets or clears the text italic attribute.": "Het tekstkenmerk Cursief instellen of wissen",
	"Selects the font used by the text.": "Het lettertype voor de tekst selecteren",
	"Selects the point size of the text.": "De puntgrootte van de tekst selecteren",
	"Sets or clears the text underline attribute.": "Het tekstkenmerk Onderstrepen instellen of wissen",
	"Shows or hides the tooltips.": "De Knopinfo weergeven of verbergen",
	"Show Paint Help.": "Help voor Paint weergeven",
	"Sends a picture by using mail or fax.": "Een figuur verzenden via Mail of Fax",
	"Copies the selection to a file.": "De selectie naar een bestand kopiëren",
	"Pastes a file into the selection.": "Een bestand in de selectie plakken",
	"Zooms the picture to 100%.": "Een figuur in-/uitzoomen tot 100%",
	"Zooms the picture to 400%.": "Een figuur in-/uitzoomen tot 400%",
	"Zooms the picture.": "Een figuur in-/uitzoomen",
	"Displays the entire picture.": "De hele figuur weergeven",
	"Shows or hides the thumbnail view of the picture.": "De schets van de figuur weergeven of verbergen",
	"Shows or hides the grid.": "Het raster weergeven of verbergen",
	"Shows or hides the text toolbar.": "De werkbalk Tekst weergeven of verbergen",
	"Flips or rotates the picture or a selection.": "De figuur of selectie spiegelen of draaien",
	"Stretches or skews the picture or a selection.": "De figuur of selectie uitrekken of hellen",
	"Inverts the colors of the picture or a selection.": "Kleuren van de figuur of van een selectie omkeren",
	"Changes the attributes of the picture.": "Kenmerken van de figuur wijzigen",
	"Clears the picture or selection.": "De figuur of selectie wissen",
	"The font size must be a numeric value.": "De tekengrootte moet een numerieke waarde zijn.",
	"Contains commands for working with the selected item(s).": "Opdrachten voor het werken met geselecteerde items",
	"Contains commands for selecting and transferring items.": "Opdrachten voor het selecteren en overbrengen van items",
	"Contains commands for customizing this window.": "Opdrachten voor het aanpassen van dit venster",
	"Contains commands for manipulating pictures and setting attributes.": "Opdrachten voor het werken met figuren en het instellen van kenmerken",
	"Contains commands for using custom colors and drawing options.": "Opdrachten voor het gebruik van aangepaste kleuren en tekenopties",
	"Contains commands for displaying Help for and information about Paint.": "Opdrachten voor de weergave van Help en informatie over Paint",
	"Cannot save file.": "Kan het bestand niet opslaan.",
	"Error removing temporary file.": "Fout bij verwijderen van tijdelijk bestand.",
	"Get Colors": "Kleuren ophalen",
	"Save Colors": "Kleuren opslaan",
	"File last saved:": "Voor het laatst opgeslagen:",
	"Not Available": "niet beschikbaar",
	"Size on disk:": "Bestandsgrootte:",
	"Painting": "Schilderen",
	"Fonts": "Lettertypen",
	"Tools": "Extra",
	"All Picture Files": "Alle figuurbestanden",
	"For Help, click Help Topics on the Help Menu.": "Klik op Help-onderwerpen in het menu Help als u Help wilt weergeven",
	"Select an area on which to get Help.": "Selecteer een gebied waarover u Help wilt weergeven",
	"Creates a new document.": "Een nieuw document maken",
	"Opens an existing document.": "Een bestaand document openen",
	"Closes the active document.": "Het actieve document sluiten",
	"Saves the active document.": "Het actieve document opslaan",
	"Saves the active document with a new name.": "Het actieve document opslaan met een andere naam",
	"Changes the page layout.": "De pagina-indeling wijzigen",
	"Specifies the default printer setup.": "De instellingen voor de standaardprinter",
	"Prints the active document and sets printing options.": "Het actieve document afdrukken en afdrukopties instellen",
	"Displays full pages.": "Volledige pagina's weergeven",
	"Opens this document.": "Dit document openen",
	"Deletes the selection.": "De selectie verwijderen",
	"Erases everything.": "Alles wissen",
	"Copies the selection and puts it on the Clipboard.": "De selectie naar het Klembord kopiëren",
	"Cuts the selection and puts it on the Clipboard.": "De selectie knippen en naar het Klembord verplaatsen",
	"Finds the specified text.": "De opgegeven tekst zoeken",
	"Inserts the contents of the Clipboard.": "De inhoud van het Klembord invoegen",
	"Repeats the last action.": "De laatste actie herhalen",
	"Replaces specific text with different text.": "De opgegeven tekst vervangen",
	"Selects everything.": "Alles selecteren",
	"Undoes the last action.": "De laatste actie ongedaan maken",
	"Redoes the previously undone action.": "De laatst ongedaan gemaakte actie opnieuw uitvoeren",
	"Displays program information, version number, and copyright.": "Programma-informatie, versienummer en copyright weergeven",
	"Quits Paint.": "Paint afsluiten",
	"Opens Paint Help.": "Help voor Paint weergeven",
	"Displays instructions about how to use Help.": "Help weergeven voor gebieden waarop u klikt",
	"Displays Help for areas you click on.": "Help weergeven voor de huidige taak of opdracht",
	"Displays Help for the current task or command.": "Help weergeven voor de huidige taak of opdracht",
	"Centers this bitmap as the desktop wallpaper.": "Deze bitmap centreren als achtergrond voor het bureaublad",
	"Tiles this bitmap as the desktop wallpaper.": "Kopieën van deze bitmap naast elkaar plaatsen als bureaubladachtergrond",
	"Sends the selection using mail or fax.": "De selectie verzenden via Mail of Fax",
	"Prints the selection.": "De selectie afdrukken",
	"Shows or hides the thumbnail.": "De schets weergeven of verbergen",
	"Shows Paint Help.": "Help voor Paint weergeven",
	"Shows or hides the status bar.": "De statusbalk weergeven of verbergen",
	"Shows or hides the tool box.": "De werkset weergeven of verbergen",
	"Shows or hides the color box.": "De kleurenset weergeven of verbergen",
	"Only a Far East font can be used for vertical editing.": "Verticaal bewerken kan alleen met een lettertype uit het verre oosten.",
	"Changes the window size.": "De venstergrootte wijzigen",
	"Changes the window position.": "De vensterpositie wijzigen",
	"Reduces the window to an icon.": "Het venster verkleinen tot pictogram",
	"Enlarges the window to full size.": "Het venster vergroten tot volledig scherm",
	"Switches to the next document window.": "Het volgende documentvenster activeren",
	"Switches to the previous document window.": "Het vorige documentvenster activeren",
	"Closes the active window and asks if you want to save changes.": "Het werkvenster sluiten en wijzigingen al of niet opslaan",
	"Restores the window to normal size.": "Het formaat van het venster herstellen",
	"Activates the task list.": "De taaklijst activeren",
	"All Files (*.*)": "Alle bestanden (*.*)",
	"Untitled": "Naamloos",
	"an unnamed file": "een bestand zonder naam",
	"&Hide": "&Verbergen",
	"Hide": "Verbergen",
	"No error message is available.": "Er is geen foutbericht beschikbaar.",
	"An unsupported operation was attempted.": "Er is een poging gedaan tot een niet-ondersteunde bewerking.",
	"A required resource was unavailable.": "Een vereiste bron was niet beschikbaar.",
	"Out of memory.": "Er is onvoldoende geheugen beschikbaar.",
	"An unknown error has occurred.": "Er is een onbekende fout opgetreden.",
	"on %1": "op %1",
	"&One Page": "&Een pagina",
	"One Page": "Een pagina",
	"&Two Page": "&Twee pagina's",
	"Two Page": "Twee pagina's",
	"Page %u": "Pagina %u",
	"Pages %u-%u": "Pagina's %u-%u",
	"Printer Files (*.prn)|*.prn|All Files (*.*)|*.*||": "Printerbestanden (*.prn)|*.prn|Alle bestanden (*.*)|*.*||",
	"Print to File": "Naar bestand",
	"to %1": "naar %1",
	"&Update %1": "%1 &bijwerken",
	"Update %1": "%1 bijwerken",
	"E&xit && Return to %1": "&Afsluiten en terugkeren naar %1",
	"Exit && Return to %1": "Afsluiten en terugkeren naar %1",
	"Linked %s": "Gekoppeld(e) %s",
	"Unknown Type": "Onbekend type",
	"Invalid filename.": "De bestandsnaam is ongeldig.",
	"Failed to open document.": "Kan document niet openen.",
	"Failed to save document.": "Kan document niet opslaan.",
	"Save changes to %1?": "Wijzigingen in %1 opslaan?",
	"Failed to create empty document.": "Kan geen leeg document maken.",
	"The file is too large to open.": "Het bestand is te groot om te openen.",
	"Could not start print job.": "Kan de afdruktaak niet starten.",
	"Failed to launch help.": "Kan Help niet starten.",
	"Internal application error.": "Interne toepassingsfout.",
	"Command failed.": "De opdracht is mislukt.",
	"Insufficient memory to perform operation.": "Er is onvoldoende geheugen om de bewerking uit te voeren.",
	"System registry entries have been removed and the INI file (if any) was deleted.": "Ingangen in het systeemregister zijn verwijderd en het INI-bestand (indien aanwezig) is verwijderd.",
	"Not all of the system registry entries (or INI file) were removed.": "Niet alle ingangen in het systeemregister (of INI-bestand) zijn verwijderd.",
	"This program requires the file %s, which was not found on this system.": "Dit programma vereist het bestand %s. Dit bestand is niet op het systeem gevonden.",
	"This program is linked to the missing export %s in the file %s. This machine may have an incompatible version of %s.": "Dit programma is gekoppeld aan de ontbrekende uitvoer %s in het bestand %s. Deze computer heeft misschien een incompatibele versie van %s.",
	"Please enter an integer.": "Geef een geheel getal op.",
	"Please enter a number.": "Geef een getal op.",
	"Please enter an integer between %1 and %2.": "Geef een geheel getal tussen %1 en %2 op.",
	"Please enter a number between %1 and %2.": "Geef een getal tussen %1 en %2 op.",
	"Please enter no more than %1 characters.": "Geef maximaal %1 tekens op.",
	"Please select a button.": "Selecteer een knop.",
	"Please enter an integer between 0 and 255.": "Geef een geheel getal tussen 0 en 255 op.",
	"Please enter a positive integer.": "Geef een positief geheel getal op.",
	"Please enter a date and/or time.": "Voer een datum en/of tijd in.",
	"Please enter a currency.": "Voer een valuta in.",
	"Unexpected file format.": "Onverwachte bestandsindeling.",
	"Cannot find this file.": "Kan dit bestand niet vinden.",
	"Please verify that the correct path and file name are given.": "Controleer of het pad en de bestandsnaam juist zijn.",
	"Destination disk drive is full.": "Bestemmingsstation is vol.",
	"Unable to read from %1, it is opened by someone else.": "Kan niet van %1 lezen, het is door iemand anders geopend.",
	"Unable to write to %1, it is read-only or opened by someone else.": "Kan niet naar %1 schrijven, het is een alleen-lezenbestand of het is door iemand anders geopend.",
	"An unexpected error occurred while reading %1.": "Onverwachte fout bij het lezen van %1.",
	"An unexpected error occurred while writing %1.": "Onverwachte fout bij het schrijven van %1.",
	"Unable to register document.": "Kan het document niet registreren.",
	"The document may already be open.": "Het document is mogelijk al geopend.",
	"Update %1 before proceeding?": "Wilt u %1 bijwerken voordat u doorgaat?",
	"Could not update client.": "Kan de client niet bijwerken.",
	"Failed to register. ActiveX features may not work properly.": "Kan niet registreren. ActiveX-functies werken niet juist.",
	"Failed to update the system registry.": "Kan het systeemregister niet bijwerken.",
	"Please try using REGEDIT.": "Probeer het met REGEDIT.",
	"Unable to read write-only property.": "Kan alleen-schrijvenkenmerk niet lezen.",
	"Unable to write read-only property.": "Kan alleen-lezenkenmerk niet schrijven.",
	"Unable to load mail system support.": "Kan ondersteuning voor mailsysteem niet laden.",
	"Mail system DLL is invalid.": "DLL-bestand voor mailsysteem is ongeldig.",
	"Send Mail failed to send message.": "Mail versturen kan het bericht niet versturen.",
	"No error occurred.": "Er is geen fout opgetreden.",
	"An unknown error occurred while accessing %1.": "Onbekende fout tijdens de toegang tot %1.",
	"%1 was not found.": "%1 is niet gevonden.",
	"%1 contains an invalid path.": "%1 bevat een ongeldig pad.",
	"%1 could not be opened because there are too many open files.": "%1 kan niet worden geopend omdat er te veel geopende bestanden zijn.",
	"Access to %1 was denied.": "Toegang tot %1 is geweigerd.",
	"An invalid file handle was associated with %1.": "Er is een ongeldige bestandsingang gekoppeld aan %1.",
	"%1 could not be removed because it is the current directory.": "%1 kan niet worden verwijderd omdat het de actieve map is.",
	"%1 could not be created because the directory is full.": "%1 kan niet worden gemaakt omdat de map vol is.",
	"Seek failed on %1": "Zoekopdracht mislukt op %1.",
	"A hardware I/O error was reported while accessing %1.": "Bij het openen van %1 wordt een I/O-fout gemeld in de hardware.",
	"A sharing violation occurred while accessing %1.": "Er is een fout bij het delen opgetreden tijdens de toegang tot %1.",
	"A locking violation occurred while accessing %1.": "Er is een vergrendelingsfout opgetreden tijdens de toegang tot %1.",
	"Disk full while accessing %1.": "Onvoldoende schijfruimte tijdens de toegang tot %1.",
	"An attempt was made to access %1 past its end.": "Er is een poging gedaan tot toegang tot %1 voorbij het eindpunt.",
	"An attempt was made to write to the reading %1.": "Er is een poging gedaan om te lezen van %1 terwijl deze bezig was met schrijven.",
	"An attempt was made to read from the writing %1.": "Er is een poging gedaan om te schrijven naar %1 terwijl deze bezig was met lezen.",
	"%1 has a bad format.": "%1 heeft een onjuiste indeling.",
	"%1 contained an unexpected object.": "%1 bevat een onverwacht object.",
	"%1 contains an incorrect schema.": "%1 bevat een onjuist schema.",
	"Selects a rectangular part of the picture to move, copy, or edit.": "Een rechthoekig gedeelte selecteren om te verplaatsen, kopiëren of bewerken",
	"Select": "Selecteren",
	"Selects a free-form part of the picture to move, copy, or edit.": "Een vrije-vormgedeelte selecteren om te verplaatsen, kopiëren of bewerken",
	"Free-Form Select": "Vrije vorm selecteren",
	"Inserts text into the picture.": "Tekst invoegen in de figuur",
	"Fills an area with the current drawing color.": "Een gebied opvullen met de huidige tekenkleur",
	"Fill With Color": "Opvullen",
	"Draws a straight line with the selected line width.": "Een rechte lijn tekenen met de gekozen lijndikte",
	"Line": "Lijn",
	"Draws using an airbrush of the selected size.": "Tekenen met een verfspuit van het gekozen formaat",
	"Airbrush": "Verfspuit",
	"Draws a curved line with the selected line width.": "Een gebogen lijn tekenen met de gekozen lijndikte",
	"Curve": "Boog",
	"Draws a polygon with the selected fill style.": "Een veelhoek tekenen met de gekozen opvulstijl",
	"Polygon": "Veelhoek",
	"Draws a rounded rectangle with the selected fill style.": "Een afgeronde rechthoek tekenen met de gekozen opvulstijl",
	"Rounded Rectangle": "Afgeronde rechthoek",
	"Draws a free-form line one pixel wide.": "Een vrije-vormlijn tekenen van één pixel breed",
	"Pencil": "Potlood",
	"Erases a portion of the picture, using the selected eraser shape.": "Een gedeelte van de figuur uitgummen met de geselecteerde gumvorm",
	"Eraser/Color Eraser": "Gum/Kleurengum",
	"Changes the magnification.": "De vergroting wijzigen",
	"Magnifier": "Vergroten",
	"Picks up a color from the picture for drawing.": "Een kleur uit de figuur selecteren om mee te tekenen",
	"Pick Color": "Kleur selecteren",
	"Draws using a brush with the selected shape and size.": "Tekenen met een kwast van de gewenste vorm en dikte",
	"Brush": "Kwast",
	"Draws a rectangle with the selected fill style.": "Een rechthoek tekenen met de gekozen opvulstijl",
	"Rectangle": "Rechthoek",
	"Draws a filled rectangle.": "Een opgevulde rechthoek tekenen",
	"Draws an ellipse with the selected fill style.": "Een ovaal tekenen met de gekozen opvulstijl",
	"Ellipse": "Ovaal",
	"Draws a filled ellipse.": "Een opgevuld ovaal tekenen",
	"Makes the current selection either opaque or transparent.": "De huidige selectie ondoorzichtig of doorzichtig maken",
	"Creates a new color.": "Een nieuwe kleur maken",
	"Uses a previously saved palette of colors.": "Een eerder opgeslagen kleurenpalet gebruiken",
	"Saves the current palette of colors to a file.": "Het huidige kleurenpalet opslaan in een bestand",
	"You must save the file before choosing it as Wallpaper.": "U moet het bestand opslaan voordat u het als achtergrond kunt gebruiken.",
	"The selection is now larger than the bitmap.": "De selectie is groter dan de bitmap.",
	"Would you like the bitmap enlarged?": "Wilt u de bitmap vergroten?",
	"The image in the clipboard is larger than the bitmap.": "De afbeelding op het Klembord is groter dan de bitmap.",
	"The file is not in the correct format.": "Het bestand heeft niet de juiste indeling.",
	"Not enough room to paste text.": "Onvoldoende ruimte om de tekst te plakken.",
	"Enlarge the text area and try again.": "Vergroot het tekstgebied en probeer het opnieuw.",
	"Places the text.": "Tekst plaatsen"
});
