//
// NOTE: This is a generated file! Don't edit it directly.
// Eventually community translation will be set up on some translation platform.
// 
// Generated with: npm run update-localization
//
loaded_localizations("he", {
	"Attributes": "תכונות",
	"MS Shell Dlg": "MS Sans Serif",
	"&Width:": "&רוחב:",
	"Width:": "רוחב:",
	"&Height:": "&גובה:",
	"Height:": "גובה:",
	"Units": "יחידות",
	"&Inches": "אי&נץ'",
	"Inches": "אינץ'",
	"C&m": "&ס\"מ",
	"Cm": "ס\"מ",
	"&Pixels": "&פיקסלים",
	"Pixels": "פיקסלים",
	"Colors": "צבעים",
	"&Black and white": "&שחור-לבן",
	"Black and white": "שחור-לבן",
	"Co&lors": "&צבעים",
	"Transparency": "שקיפות",
	"Use &Transparent background color": "&השתמש בצבע רקע שקוף",
	"Use Transparent background color": "השתמש בצבע רקע שקוף",
	"Select &Color": "&בחירת צבע",
	"Select Color": "בחירת צבע",
	"OK": "אישור",
	"Cancel": "ביטול",
	"&Default": "ברירת &מחדל",
	"Default": "ברירת מחדל",
	"Custom Zoom": "התאמה אישית של מרחק מתצוגה",
	"Current zoom:": "מרחק נוכחי מתצוגה:",
	"Zoom to": "שנה ל- ",
	"Flip and Rotate": "היפוך וסיבוב",
	"Flip or rotate": "הפוך או סובב",
	"&Flip horizontal": "הפוך או&פקית",
	"Flip horizontal": "הפוך אופקית",
	"Flip &vertical": "הפוך א&נכית",
	"Flip vertical": "הפוך אנכית",
	"&Rotate by angle": "&סובב בזווית",
	"Rotate by angle": "סובב בזווית",
	"Stretch and Skew": "מתיחה והטיה",
	"Stretch": "מתיחה",
	"&Horizontal:": "או&פקית:",
	"Horizontal:": "אופקית:",
	"&Vertical:": "א&נכית:",
	"Vertical:": "אנכית:",
	"Skew": "הטיה",
	"H&orizontal:": "&אופקית:",
	"Degrees": "מעלות",
	"V&ertical:": "אנ&כית:",
	"Color Table": "טבלת צבעים",
	"New": "חדש",
	"&New ": "&חדש ",
	"New ": "חדש ",
	"&Help": "ע&זרה",
	"Help": "עזרה",
	"Printing": "מדפיס",
	"on the": "ב-",
	"&Print": "&הדפסה",
	"Print": "הדפסה",
	"&Next Page": "העמוד ה&בא",
	"Next Page": "העמוד הבא",
	"Pre&v Page": "ה&עמוד הקודם",
	"Prev Page": "העמוד הקודם",
	"Zoom &In": "&קרב",
	"Zoom In": "קרב",
	"Zoom &Out": "ה&רחק",
	"Zoom Out": "הרחק",
	"&Close": "&סגור",
	"Close": "סגור",
	"Grid Settings": "הגדרות רשת",
	"&Pixel Grid": "&רשת פיקסלים",
	"Pixel Grid": "רשת פיקסלים",
	"&Tile Grid": "רשת &פרישה",
	"Tile Grid": "רשת פרישה",
	"pixels": "פיקסלים",
	"H&eight:": "&גובה:",
	"Text": "טקסט",
	"Undo": "בטל",
	"Cut": "גזור",
	"Copy": "העתק",
	"Paste": "הדבק",
	"Clear Selection": "בטל בחירה",
	"Select All": "בחר הכל",
	"Text Toolbar": "סרגל הכלים טקסט",
	"Selection": "בחירה",
	"Cu&t": "&גזור",
	"&Copy": "ה&עתק",
	"&Paste": "ה&דבק",
	"C&lear Selection": "&נקה בחירה",
	"Select &All": "&בחר הכל",
	"C&opy To": "העתקה &אל",
	"Copy To": "העתקה אל",
	"Paste &From": "הדבקה &מתוך",
	"Paste From": "הדבקה מתוך",
	"Flip/&Rotate": "&היפוך/סיבוב",
	"Flip/Rotate": "היפוך/סיבוב",
	"&Stretch/Skew": "מ&תיחה/הטיה",
	"Stretch/Skew": "מתיחה/הטיה",
	"&Invert Colors": "הפוך &צבעים",
	"Invert Colors": "הפוך צבעים",
	"Thumbnail": "תמונה ממוזערת",
	"&File": "&קובץ",
	"File": "קובץ",
	"&New": "&חדש",
	"&Open": "&פתיחה",
	"Open": "פתיחה",
	"&Save": "&שמור",
	"Save": "שמור",
	"Save &As": "שמירה &בשם",
	"Save As": "שמירה בשם",
	"Print Pre&view": "הצג &לפני הדפסה",
	"Print Preview": "הצג לפני הדפסה",
	"Page Se&tup": "הגדרת &עמוד",
	"Page Setup": "הגדרת עמוד",
	"S&end": "של&יחה",
	"Send": "שליחה",
	"Set As &Wallpaper (Tiled)": "קבע כטפט (פר&וש)",
	"Set As Wallpaper (Tiled)": "קבע כטפט (פרוש)",
	"Set As Wa&llpaper (Centered)": "קבע כטפט (ב&מרכז)",
	"Set As Wallpaper (Centered)": "קבע כטפט (במרכז)",
	"Recent File": "קובץ אחרון",
	"E&xit": "י&ציאה",
	"Exit": "יציאה",
	"&Edit": "&עריכה",
	"Edit": "עריכה",
	"&Undo": "&בטל",
	"&Repeat": "&חזור על",
	"Repeat": "חזור על",
	"Ctrl+A": "Ctrl+L",
	"&View": "&תצוגה",
	"View": "תצוגה",
	"&Tool Box": "תיבת &כלים",
	"Tool Box": "תיבת כלים",
	"&Color Box": "תיבת &צבעים",
	"Color Box": "תיבת צבעים",
	"Ctrl+L": "Ctrl+A",
	"&Status Bar": "שורת &מצב",
	"Status Bar": "שורת מצב",
	"T&ext Toolbar": "סרגל הכלים &טקסט",
	"&Zoom": "מ&רחק מתצוגה",
	"Zoom": "מרחק מתצוגה",
	"&Normal Size": "&גודל רגיל",
	"Normal Size": "גודל רגיל",
	"&Large Size": "&תצוגה מוגדלת",
	"Large Size": "תצוגה מוגדלת",
	"C&ustom": "&התאמה אישית",
	"Custom": "התאמה אישית",
	"Show &Grid": "הצג &רשת",
	"Show Grid": "הצג רשת",
	"Show T&humbnail": "הצג תמונה ממו&זערת",
	"Show Thumbnail": "הצג תמונה ממוזערת",
	"&View Bitmap": "&הצג מפת סיביות",
	"View Bitmap": "הצג מפת סיביות",
	"&Image": "ת&מונה",
	"Image": "תמונה",
	"&Flip/Rotate": "&היפוך/סיבוב",
	"&Attributes": "&תכונות",
	"&Clear Image": "&נקה תמונה",
	"Clear Image": "נקה תמונה",
	"&Draw Opaque": "צייר &אטום",
	"Draw Opaque": "צייר אטום",
	"&Colors": "&צבעים",
	"&Edit Colors": "&עריכת צבעים",
	"Edit Colors": "עריכת צבעים",
	"&Help Topics": "&נושאי עזרה",
	"Help Topics": "נושאי עזרה",
	"&About Paint": "&אודות צייר",
	"About Paint": "אודות צייר",
	"&Update": "עד&כן",
	"Update": "עדכן",
	"Save Copy &As": "שמירת עותק &בשם",
	"Save Copy As": "שמירת עותק בשם",
	"Paint": "צייר",
	"untitled": "ללא שם",
	"Bitmap Image": "תמונת מפת סיביות",
	"Bitmap Files (*.bmp)": "קבצי מפת סיביות (‎*.bmp)",
	"PCX Files": "קבצי PCX",
	"Icon Files": "קבצי סמלים",
	"Monochrome Bitmap (*.bmp;*.dib)": "מפת סיביות חד-צבעית (‎*.bmp;‎*.dib)",
	"16 Color Bitmap (*.bmp;*.dib)": "מפת סיביות של 16 צבעים (‎*.bmp;‎*.dib)",
	"256 Color Bitmap (*.bmp;*.dib)": "מפת סיביות של 256 צבעים (‎*.bmp;‎*.dib)",
	"Paint cannot open this file.": "‏‏אין אפשרות לפתוח קובץ זה בצייר.",
	"Paint cannot read this file.": "‏‏אין אפשרות לקרוא קובץ זה בצייר.",
	"This file is read-only.": "‏‏זהו קובץ לקריאה בלבד.",
	"To save your changes, use a different filename.": "לשמירת השינויים שביצעת השתמש בשם קובץ שונה.",
	"This file is already open.": "‏‏קובץ זה פתוח כבר.",
	"This is not a valid .PCS file.": "‏‏קובץ זה אינו קובץ ‎.PCS חוקי.",
	"This file is open for editing and cannot be overwritten.": "‏‏קובץ זה פתוח לעריכה ואין אפשרות לכתוב עליו.",
	"Use a different filename to save your changes.": "השתמש בשם קובץ שונה לשמירת השינויים שביצעת.",
	"This is not a valid bitmap file, or its format is not currently supported.": "‏‏קובץ זה אינו קובץ מפת סיביות חוקי או שהתבנית שלו אינה נתמכת כעת.",
	"This is not a valid icon.": "‏‏סמל זה אינו חוקי.",
	"This is not a valid cursor.": "‏‏סמן זה אינו חוקי.",
	"Save was interrupted, so your file has not been saved.": "‏‏השמירה הופסקה, ולכן הקובץ שלך לא נשמר.",
	"You cannot save to a read-only file.": "‏‏אין אפשרות לשמור קובץ לקריאה בלבד.",
	"Use a different file name.": "השתמש בשם קובץ שונה.",
	"This file is already in use.": "‏‏קובץ זה נמצא כבר בשימוש.",
	"Close the program, and then try again.": "סגור את התוכנית ולאחר מכן נסה שנית.",
	"Paint cannot save this file.": "‏‏אין אפשרות לשמור קובץ זה בצייר.",
	"Paint cannot save to the same filename with a different file type.": "‏‏בצייר אין אפשרות לשמור סוג קובץ שונה תחת שם קובץ זהה.",
	"The grid spacing must be an integer between %d and %d.": "‏‏על מרווח הרשת להיות מספר שלם בטווח שבין %d ל- %d.",
	"There is not enough memory or resources to complete operation.": "‏‏אין די זיכרון או משאבים להשלמת הפעולה.",
	"Close some programs, and then try again.": "סגור מספר תוכניות ולאחר מכן נסה שנית.",
	"Low on memory or resources.": "‏‏אין די זיכרון או משאבים.",
	"Group error.": "‏‏שגיאת קבוצה.",
	"Paint was unable to print your document. Please make sure you have sufficient disk space and that your printer is working correctly.": "‏‏אין אפשרות להדפיס את המסמך בצייר. ודא כי קיים די שטח דיסק והמדפסת פועלת כראוי.",
	"Saving into this format may cause some loss of color information.": "‏‏שמירה לתבנית זו עלולה לגרום לאובדן של חלק מהמידע אודות צבעים.",
	"Do you want to continue?": "האם ברצונך להמשיך?",
	"Converting to black and white cannot be undone.  This action affects the current file and may cause some loss of color information.": "‏‏אין אפשרות לבטל את ביצוע ההמרה לשחור-לבן. פעולה זו משפיעה על הקובץ הנוכחי ועלולה לגרום לאובדן של חלק מהמידע אודות צבעים.",
	"Bitmaps must be greater than one pixel on a side.": "‏‏מפות סיביות חייבות להיות גדולות יותר מפיקסל אחד בכל צד.",
	"Generic error.": "‏‏שגיאה כללית.",
	"File not found.": "‏‏הקובץ לא נמצא.",
	"Bad path.": "‏‏נתיב שגוי.",
	"Too many open files.": "‏‏קבצים רבים מדי פתוחים.",
	"Access denied.": "‏‏הגישה נדחתה.",
	"Invalid file.": "‏‏קובץ לא חוקי.",
	"Remove current folder.": "‏‏הסר את התיקיה הנוכחית.",
	"Folder full.": "‏‏התיקיה מלאה.",
	"Bad seek.": "‏‏חיפוש שגוי.",
	"Hard IO error.": "‏‏שגיאת קלט/פלט קשה.",
	"Sharing violation.": "‏‏הפרת זכויות גישה.",
	"Lock violation.": "‏‏הפרת נעילה.",
	"Disk full.": "‏‏הדיסק מלא.",
	"End of file.": "‏‏סוף הקובץ.",
	"Error getting the Clipboard Data!": "‏‏שגיאה בקבלת נתוני הלוח!",
	"No Printer Found @ page setup": "‏‏לא נמצאה מדפסת @ הגדרת עמוד",
	"24-bit Bitmap (*.bmp;*.dib)": "מפת סיביות של 24 סיביות (‎*.bmp;‎*.dib)",
	"All Files": "כל הקבצים",
	"Palette|*.pal|": "לוח צבעים|‎*.pal|",
	"OLE 2.0 was unable to start.": "‏‏הפעלת OLE 2.0 לא הצליחה.",
	"Make sure that you are using the correct version of the OLE libraries.": "ודא כי אתה משתמש בגירסה הנכונה של ספריות OLE.",
	"Resets the text be without any attributes.": "הסרת כל התכונות מהטקסט.",
	"Sets or clears the text bold attribute.": "קביעה או הסרה של התכונה הדגשת טקסט.",
	"Sets or clears the text italic attribute.": "קביעה או הסרה של התכונה הטיית טקסט.",
	"Selects the font used by the text.": "בחירת הגופן לשימוש בטקסט.",
	"Selects the point size of the text.": "בחירת הגודל בנקודות של הטקסט.",
	"Sets or clears the text underline attribute.": "קביעה או הסרה של התכונה קו תחתון.",
	"Shows or hides the tooltips.": "הצגה או הסתרה של תיאורי הכלים.",
	"Show Paint Help.": "הצגת העזרה לצייר.",
	"Sends a picture by using mail or fax.": "שליחת תמונה באמצעות דואר או פקס.‏",
	"Copies the selection to a file.": "העתקת הקטע הנבחר לקובץ.",
	"Pastes a file into the selection.": "הדבקת קובץ לתוך הקטע הנבחר.",
	"Zooms the picture to 100%.": "שינוי המרחק מהתמונה ל- ‎100%‎.",
	"Zooms the picture to 400%.": "שינוי המרחק מהתמונה ל- ‎400%‎.",
	"Zooms the picture.": "שינוי המרחק מהתמונה.",
	"Displays the entire picture.": "הצגת התמונה כולה.",
	"Shows or hides the thumbnail view of the picture.": "הצגה או הסתרה של תצוגת התמונה הממוזערת.",
	"Shows or hides the grid.": "הצגה או הסתרה של הרשת.",
	"Shows or hides the text toolbar.": "הצגה או הסתרה של סרגל הכלים טקסט.",
	"Flips or rotates the picture or a selection.": "היפוך או סיבוב של התמונה או הקטע הנבחר.",
	"Stretches or skews the picture or a selection.": "מתיחה או הטיה של התמונה או הקטע הנבחר.",
	"Inverts the colors of the picture or a selection.": "היפוך הצבעים של התמונה או הקטע הנבחר.",
	"Changes the attributes of the picture.": "שינוי התכונות של התמונה.",
	"Clears the picture or selection.": "ניקוי התמונה או הקטע הנבחר.",
	"The font size must be a numeric value.": "‏‏על גודל הגופן להיות ערך מספרי.",
	"Contains commands for working with the selected item(s).": "מכיל פקודות לעבודה עם הפריטים הנבחרים.",
	"Contains commands for selecting and transferring items.": "מכיל פקודות לבחירה והעברה של פריטים.",
	"Contains commands for customizing this window.": "מכיל פקודות להתאמה אישית של חלון זה.",
	"Contains commands for manipulating pictures and setting attributes.": "מכיל פקודות לטיפול בתמונות והגדרת תכונות.",
	"Contains commands for using custom colors and drawing options.": "מכיל פקודות לשימוש בצבעים מותאמים אישית ובאפשרויות ציור.",
	"Contains commands for displaying Help for and information about Paint.": "מכיל פקודות להצגת עזרה ומידע אודות צייר.",
	"Cannot save file.": "‏‏אין אפשרות לשמור את הקובץ.",
	"Error removing temporary file.": "‏‏שגיאה בהסרת הקובץ הזמני.",
	"Get Colors": "קבלת צבעים",
	"Save Colors": "שמירת צבעים",
	"File last saved:": "הקובץ נשמר לאחרונה:",
	"Not Available": "לא זמין",
	"Size on disk:": "גודל בדיסק:",
	"%s bytes": "%s בתים",
	"Painting": "ציור",
	"Bitmap": "מפת סיביות",
	"Fonts": "גופנים",
	"Tools": "כלים",
	"All Picture Files": "כל קבצי התמונה",
	"For Help, click Help Topics on the Help Menu.": "לקבלת עזרה, לחץ על נושאי עזרה בתפריט עזרה.",
	"Select an area on which to get Help.": "בחר אזור לשם קבלת עזרה אודותיו.",
	"%1 in %2": "%1 ב- %2",
	"Creates a new document.": "יצירת מסמך חדש.",
	"Opens an existing document.": "פתיחת מסמך קיים.",
	"Closes the active document.": "סגירת המסמך הפעיל.",
	"Saves the active document.": "שמירת המסמך הפעיל.",
	"Saves the active document with a new name.": "שמירת המסמך הפעיל תחת שם חדש.",
	"Changes the page layout.": "שינוי עיצוב העמוד.",
	"Specifies the default printer setup.": "ציון הגדרת מדפסת ברירת המחדל.",
	"Prints the active document and sets printing options.": "הדפסת המסמך הפעיל וקביעת אפשרויות הדפסה.",
	"Displays full pages.": "הצגת עמודים מלאים.",
	"Opens this document.": "פתיחת מסמך זה.",
	"Deletes the selection.": "מחיקת הקטע הנבחר.",
	"Erases everything.": "מחיקת הכל.",
	"Copies the selection and puts it on the Clipboard.": "העתקת הקטע הנבחר ומיקומו בלוח.",
	"Cuts the selection and puts it on the Clipboard.": "גזירת הקטע הנבחר ומיקומו בלוח.",
	"Finds the specified text.": "חיפוש הטקסט שצויין.",
	"Inserts the contents of the Clipboard.": "הוספת תוכן הלוח.",
	"Repeats the last action.": "חזרה על הפעולה האחרונה.",
	"Replaces specific text with different text.": "החלפת טקסט ספציפי בטקסט אחר.",
	"Selects everything.": "בחירת הכל.",
	"Undoes the last action.": "ביטול הפעולה האחרונה.",
	"Redoes the previously undone action.": "ביצוע מחדש של הפעולה שבוטלה קודם לכן.",
	"Displays program information, version number, and copyright.": "הצגת מידע אודות התוכנית, מספר גירסה וזכויות יוצרים.",
	"Quits Paint.": "יציאה מצייר.",
	"Opens Paint Help.": "פתיחת העזרה לצייר.",
	"Displays instructions about how to use Help.": "הצגת הוראות אודות אופן השימוש בעזרה.",
	"Displays Help for areas you click on.": "הצגת עזרה עבור אזורים עליהם אתה לוחץ.",
	"Displays Help for the current task or command.": "הצגת עזרה עבור המשימה או הפקודה הנוכחית.",
	"Centers this bitmap as the desktop wallpaper.": "מרכוז מפת סיביות זו כטפט שולחן העבודה.",
	"Tiles this bitmap as the desktop wallpaper.": "פרישת מפת סיביות זו כטפט שולחן העבודה.",
	"Sends the selection using mail or fax.": "שליחת הקטע הנבחר באמצעות דואר או פקס.",
	"Prints the selection.": "הדפסת הקטע הנבחר.",
	"Shows or hides the thumbnail.": "הצגה או הסתרה של התמונה הממוזערת.",
	"Shows Paint Help.": "הצגת העזרה לצייר.",
	"Shows or hides the status bar.": "הצגה או הסתרה של שורת המצב.",
	"Shows or hides the tool box.": "הצגה או הסתרה של תיבת הכלים.",
	"Shows or hides the color box.": "הצגה או הסתרה של תיבת הצבעים.",
	"Only a Far East font can be used for vertical editing.": "ניתן להשתמש רק בגופן של המזרח הרחוק עבור עריכה אנכית.",
	"Changes the window size.": "שינוי גודל החלון.",
	"Changes the window position.": "שינוי מיקום החלון.",
	"Reduces the window to an icon.": "הקטנת החלון לסמל.",
	"Enlarges the window to full size.": "הגדלת החלון לגודל מלא.",
	"Switches to the next document window.": "מעבר לחלון המסמך הבא.",
	"Switches to the previous document window.": "מעבר לחלון המסמך הקודם.",
	"Closes the active window and asks if you want to save changes.": "סגירת החלון הפעיל והצגת שאלה אם ברצונך לשמור שינויים.",
	"Restores the window to normal size.": "החזרת החלון לגודל הרגיל.",
	"Activates the task list.": "הפעלת רשימת המשימות.",
	"All Files (*.*)": "כל הקבצים (*.*)",
	"Untitled": "ללא שם",
	"an unnamed file": "קובץ ללא שם",
	"&Hide": "ה&סתר",
	"Hide": "הסתר",
	"No error message is available.": "‏‏אין הודעת שגיאה זמינה.",
	"An unsupported operation was attempted.": "‏‏בוצע ניסיון לבצע פעולה שאינה נתמכת.",
	"A required resource was unavailable.": "‏‏משאב נחוץ לא היה זמין.",
	"Out of memory.": "‏‏אין זיכרון פנוי.",
	"An unknown error has occurred.": "‏‏אירעה שגיאה לא מוכרת.",
	"on %1": "ב- %1",
	"&One Page": "עמוד &אחד",
	"One Page": "עמוד אחד",
	"&Two Page": "&שני עמודים",
	"Two Page": "שני עמודים",
	"Page %u": "עמוד %u",
	"Pages %u-%u": "עמודים %u-%u",
	"Printer Files (*.prn)|*.prn|All Files (*.*)|*.*||": "קבצי מדפסת (*.prn)|*.prn|כל הקבצים (*.*)|*.*||",
	"Print to File": "הדפסה לקובץ",
	"to %1": "ל- %1",
	"&Update %1": "&עדכן את %1",
	"Update %1": "עדכן את %1",
	"E&xit && Return to %1": "י&ציאה וחזרה אל %1",
	"Exit && Return to %1": "יציאה וחזרה אל %1",
	"Linked %s": "%s מקושר",
	"Unknown Type": "‏‏סוג לא מוכר",
	"Invalid filename.": "‏‏שם קובץ לא חוקי.",
	"Failed to open document.": "‏‏פתיחת המסמך נכשלה.",
	"Failed to save document.": "‏‏שמירת המסמך נכשלה.",
	"Save changes to %1?": "‏‏האם לשמור שינויים ב- %1?",
	"Failed to create empty document.": "‏‏יצירת מסמך ריק נכשלה.",
	"The file is too large to open.": "‏‏הקובץ גדול מכדי שניתן יהיה לפתוח אותו.",
	"Could not start print job.": "‏‏הפעלת עבודת הדפסה לא הצליחה.",
	"Failed to launch help.": "‏‏הפעלת עזרה נכשלה.",
	"Internal application error.": "‏‏שגיאה פנימית ביישום.",
	"Command failed.": "‏‏הפקודה נכשלה.",
	"Insufficient memory to perform operation.": "‏‏אין די זיכרון לביצוע הפעולה.",
	"System registry entries have been removed and the INI file (if any) was deleted.": "‏‏ערכי רישום המערכת הוסרו וקובץ ה- INI (אם קיים) נמחק.",
	"Not all of the system registry entries (or INI file) were removed.": "‏‏לא כל ערכי רישום המערכת (או קובץ INI) הוסרו.",
	"This program requires the file %s, which was not found on this system.": "‏‏לתוכנית זו נחוץ הקובץ %s שלא נמצא במערכת זו.",
	"This program is linked to the missing export %s in the file %s. This machine may have an incompatible version of %s.": "‏‏תוכנית זו מקושרת ל- %s של הייצוא החסר בקובץ %s. ייתכן כי במחשב זה קיימת גירסה לא תואמת של %s.",
	"Please enter an integer.": "‏‏הזן מספר שלם.",
	"Please enter a number.": "‏‏הזן מספר.",
	"Please enter an integer between %1 and %2.": "‏‏הזן מספר שלם בטווח שבין %1 ל- %2.",
	"Please enter a number between %1 and %2.": "‏‏הזן מספר שלם בטווח שבין %1 ל- %2.",
	"Please enter no more than %1 characters.": "‏‏אל תזין יותר מ- %1 תווים.",
	"Please select a button.": "‏‏בחר לחצן.",
	"Please enter an integer between 0 and 255.": "‏‏הזן מספר שלם בטווח שבין 0  ל-255.",
	"Please enter a positive integer.": "‏‏הזן מספר שלם חיובי.",
	"Please enter a date and/or time.": "‏‏הזן תאריך ו/שעה.",
	"Please enter a currency.": "‏‏הזן מטבע.",
	"Unexpected file format.": "‏‏תבנית קובץ לא צפויה.",
	"%1": "‏‏%1",
	"Cannot find this file.": "קובץ זה לא נמצא.",
	"Please verify that the correct path and file name are given.": "ודא כי הנתיב ושם הקובץ הנתונים נכונים.",
	"Destination disk drive is full.": "‏‏כונן הדיסקים המשמש כיעד מלא.",
	"Unable to read from %1, it is opened by someone else.": "‏‏אין אפשרות לקרוא מתוך %1, הפריט פתוח על-ידי משתמש אחר.",
	"Unable to write to %1, it is read-only or opened by someone else.": "‏‏אין אפשרות לכתוב אל %1, הפריט לקריאה בלבד או פתוח על-ידי משתמש אחר.",
	"An unexpected error occurred while reading %1.": "‏‏אירעה שגיאה לא צפויה בעת קריאת %1.",
	"An unexpected error occurred while writing %1.": "‏‏אירעה שגיאה לא צפויה בעת כתיבת %1.",
	"Unable to register document.": "אין אפשרות לרשום את המסמך.",
	"The document may already be open.": "ייתכן כי המסמך כבר פתוח.",
	"Update %1 before proceeding?": "‏‏האם לעדכן את %1 לפני המשך העבודה?",
	"Could not update client.": "‏‏עדכון הלקוח לא הצליח.",
	"Failed to register. ActiveX features may not work properly.": "‏‏הרישום נכשל. ייתכן כי תכונות ActiveX אינן פועלות כראוי.",
	"Failed to update the system registry.": "‏‏עדכון רישום המערכת נכשל.",
	"Please try using REGEDIT.": "נסה להשתמש ב- REGEDIT.",
	"Unable to read write-only property.": "‏‏אין אפשרות לקרוא מאפיין לכתיבה בלבד.",
	"Unable to write read-only property.": "‏‏אין אפשרות לכתוב מאפיין לקריאה בלבד.",
	"Unable to load mail system support.": "‏‏אין אפשרות לטעון תמיכה במערכת דואר.",
	"Mail system DLL is invalid.": "‏‏DLL של מערכת דואר אינו חוקי.",
	"Send Mail failed to send message.": "‏‏שליחת הודעה באמצעות Send Mail נכשלה.",
	"No error occurred.": "‏‏לא אירעה שגיאה.",
	"An unknown error occurred while accessing %1.": "‏‏אירעה שגיאה לא מוכרת בעת גישה ל- %1.",
	"%1 was not found.": "‏‏%1 לא נמצא.",
	"%1 contains an invalid path.": "‏‏%1 מכיל נתיב לא חוקי.",
	"%1 could not be opened because there are too many open files.": "‏‏פתיחת %1 לא הצליחה משום שקבצים רבים מדי פתוחים.",
	"Access to %1 was denied.": "‏‏הגישה ל- %1 נדחתה.",
	"An invalid file handle was associated with %1.": "‏‏מזהה ייחודי (handle) לא חוקי של קובץ שוייך אל %1.",
	"%1 could not be removed because it is the current directory.": "‏‏הסרת %1 לא הצליחה משום שזו הספריה הנוכחית.",
	"%1 could not be created because the directory is full.": "‏‏יצירת %1 לא הצליחה משום שהספריה מלאה.",
	"Seek failed on %1": "‏‏פעולת Seek נכשלה ב- %1",
	"A hardware I/O error was reported while accessing %1.": "‏‏דווח על שגיאת קלט/פלט בחומרה בעת גישה ל- %1.",
	"A sharing violation occurred while accessing %1.": "‏‏אירעה הפרת זכויות גישה בעת גישה ל- %1.",
	"A locking violation occurred while accessing %1.": "‏‏אירעה הפרת נעילה בעת גישה ל- %1.",
	"Disk full while accessing %1.": "‏‏דיסק מלא בעת גישה ל- %1.",
	"An attempt was made to access %1 past its end.": "‏‏בוצע נסיון גישה ל- %1 מעבר לקצהו.",
	"An attempt was made to write to the reading %1.": "‏‏בוצע ניסיון לכתוב אל %1 המוגדר לקריאה.",
	"An attempt was made to read from the writing %1.": "‏‏בוצע ניסיון לקרוא מתוך %1 המוגדר לכתיבה.",
	"%1 has a bad format.": "‏‏ל- %1 תבנית שגויה.",
	"%1 contained an unexpected object.": "‏‏%1 הכיל אובייקט לא צפוי.",
	"%1 contains an incorrect schema.": "‏‏%1 מכיל סכימה שגויה.",
	"Selects a rectangular part of the picture to move, copy, or edit.": "בחירת קטע מלבני מהתמונה לשם הזזה, העתקה או עריכה.",
	"Select": "בחירה",
	"Selects a free-form part of the picture to move, copy, or edit.": "בחירת קטע בעל צורה חופשית מהתמונה לשם הזזה, העתקה או עריכה.",
	"Free-Form Select": "בחירה חופשית",
	"Inserts text into the picture.": "הוספת טקסט לתוך התמונה.",
	"Fills an area with the current drawing color.": "מילוי אזור בצבע הציור הנוכחי.",
	"Fill With Color": "מילוי בצבע",
	"Draws a straight line with the selected line width.": "ציור קו ישר בעובי הקו הנבחר.",
	"Line": "קו",
	"Draws using an airbrush of the selected size.": "ציור באמצעות מברשת אוויר בגודל הנבחר.",
	"Airbrush": "מברשת אוויר",
	"Draws a curved line with the selected line width.": "ציור קו מעוקל בעובי הקו הנבחר.",
	"Curve": "עיקול",
	"Draws a polygon with the selected fill style.": "ציור מצולע בסגנון המילוי הנבחר.",
	"Polygon": "מצולע",
	"Draws a rounded rectangle with the selected fill style.": "ציור מלבן מעוגל בסגנון המילוי הנבחר.",
	"Rounded Rectangle": "מלבן מעוגל",
	"Draws a free-form line one pixel wide.": "ציור קו בעל צורה חופשית בעובי פיקסל אחד.",
	"Pencil": "עיפרון",
	"Erases a portion of the picture, using the selected eraser shape.": "מחיקת קטע מהתמונה באמצעות צורת המחק הנבחרת.",
	"Eraser/Color Eraser": "מחק/מחק צבעוני",
	"Changes the magnification.": "שינוי המרחק מהתצוגה.",
	"Magnifier": "זכוכית מגדלת",
	"Picks up a color from the picture for drawing.": "בחירת צבע מהתמונה לשם ציור.",
	"Pick Color": "בחירת צבע",
	"Draws using a brush with the selected shape and size.": "ציור באמצעות מברשת בצורה ובגודל הנבחרים.",
	"Brush": "מברשת",
	"Draws a rectangle with the selected fill style.": "ציור מלבן בסגנון המילוי הנבחר.",
	"Rectangle": "מלבן",
	"Draws a filled rectangle.": "ציור מלבן עם מילוי.",
	"Draws an ellipse with the selected fill style.": "ציור אליפסה בסגנון המילוי הנבחר.",
	"Ellipse": "אליפסה",
	"Draws a filled ellipse.": "ציור אליפסה עם מילוי.",
	"Makes the current selection either opaque or transparent.": "‏‏הפיכת הקטע הנבחר הנוכחי לאטום או שקוף.",
	"Creates a new color.": "יצירת צבע חדש.",
	"Uses a previously saved palette of colors.": "שימוש בלוח צבעים שנשמר קודם.",
	"Saves the current palette of colors to a file.": "שמירת לוח הצבעים הנוכחי בקובץ.‏",
	"You must save the file before choosing it as Wallpaper.": "‏‏עליך לשמור את הקובץ לפני בחירתו כטפט.",
	"The selection is now larger than the bitmap.": "‏‏הקטע הנבחר כעת גדול יותר ממפת הסיביות.",
	"Would you like the bitmap enlarged?": "האם ברצונך להגדיל את מפת הסיביות?",
	"The image in the clipboard is larger than the bitmap.": "‏‏התמונה בלוח גדולה יותר ממפת הסיביות.",
	"The file is not in the correct format.": "‏‏הקובץ אינו בתבנית הנכונה.",
	"Not enough room to paste text.": "‏‏אין די מקום להדבקת הטקסט.",
	"Enlarge the text area and try again.": "הגדל את אזור הטקסט ונסה שנית.",
	"Places the text.": "מיקום הטקסט."
});
